### ISSUE TITLE
传入chart.source的数据错误，可能导致浏览器卡死

### ISSUE THREAD

**Issue by hughfenghen** [antvis/f2#10]
以[官方demo](https://antv.alipay.com/g2-mobile/demo/02-line/line-smooth.html)为例。
第十五行改成`var data = []`，再点击执行。当前标签页卡死。
期望绘制图表时，如果从数组中拿不到需要的数据能在控制台打印错误，不会卡死浏览器。

**Comment by dxq613** [comment]
我定位了下，发现是计算坐标点的时候出问题了，由于这个demo的列定义定义了 min,而没定义max，所以出现了这个问题，下个版本修复掉。建议可以 去掉列定义中的 min,或者 同时设置max

**Comment by hughfenghen** [comment]
@dxq613 thx
