### ISSUE TITLE
getPosition在最新版本的F2中，双Y数据根据右侧Y轴数据获取不到位置坐标，在3.4.2版本是正常的

### ISSUE THREAD

**Issue by xiaoming0827** [antvis/F2#1004]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-flower-twjqd?file=/src/index.js)

### Steps to reproduce
1、项目中使用的3.4.2版本，需求是趋势图自动定位到最后天的数据显示图例封层等信息
2、升级到最新版本3.7.4 getPosition 获取右侧Y轴的数据不能获取到坐标，3.4.2版本是可以，但是获取左侧Y轴数据是可以的。项目曲线图是双Y轴
3、再没有改动代码的情况下，切换到3.4.2版本一切正常

| Environment | Info |
|---|---|
| f2 | 3.7.2 |
| System | mac |
| Browser | chrome |

**Comment by zengyue** [comment]
我看了下，好像都有问题，我修一下

**Comment by xiaoming0827** [comment]
> 我看了下，好像都有问题，我修一下

好的，辛苦大佬！
另外我们项目中使用F2还有一个非常影响体验的问题，点击图例区域会导致辅助线移动，是否支持点击图例不影响辅助线移动，只有点击曲线图才会影响辅助线。这个一直不知咋解决，反馈issues也没有反馈，多谢大佬百忙之中回复

**Comment by zengyue** [comment]
> > 我看了下，好像都有问题，我修一下
> 
> 好的，辛苦大佬！
> 另外我们项目中使用F2还有一个非常影响体验的问题，点击图例区域会导致辅助线移动，是否支持点击图例不影响辅助线移动，只有点击曲线图才会影响辅助线。这个一直不知咋解决，反馈issues也没有反馈，多谢大佬百忙之中回复

我看了下不会呀，是哪个issues ?

**Comment by xiaoming0827** [comment]
> > > 我看了下，好像都有问题，我修一下
> > 
> > 
> > 好的，辛苦大佬！
> > 另外我们项目中使用F2还有一个非常影响体验的问题，点击图例区域会导致辅助线移动，是否支持点击图例不影响辅助线移动，只有点击曲线图才会影响辅助线。这个一直不知咋解决，反馈issues也没有反馈，多谢大佬百忙之中回复
> 
> 我看了下不会呀，是哪个issues ?

忘了补充条件了，也是设置了alwaysShow:true  之后，点击图例空白区域也会导致辅助线移动，issues记得是提了，找不到了。另外辛苦更新后发一下新版本，不然还低手动改源码，不方便ci发布上线

**Comment by zengyue** [comment]
https://github.com/antvis/F2/pull/1018

是不是这个，我今天会发个包，迟点你可以再试试

**Comment by xiaoming0827** [comment]
> #1018
> 
> 是不是这个，我今天会发个包，迟点你可以再试试

好的，谢谢。 设置alwaysShow：true 点击图例区域影响辅助线的这个问题也有时间看看，多谢了，正好项目重构可以解决这些问题。
