### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: canvas.getContext is not a function"

### ISSUE THREAD

**Issue by JulesCesar** [antvis/f2#101]
这是为何

**Comment by simaQ** [comment]
F2 图表的容器是 <canvas> 元素，不是 dom，参见 [快速上手](https://antv.alipay.com/zh-cn/f2/3.x/tutorial/index.html#_1.-%E5%88%9B%E5%BB%BA-canvas-%E6%A0%87%E7%AD%BE):

```html
<canvas id="myChart" width="400" height="260"></canvas>
```

**Comment by Yan1513149392** [comment]
我也遇到这个问题了，用都就说canvas标签，但是依然会报这个错误
