### ISSUE TITLE
饼图在数据皆为0的时候没有任何显示，该怎么解决？

### ISSUE THREAD

**Issue by tts-kk** [antvis/F2#1010]
应该需要一个默认值才对，给个浅灰色提示用户这里有图表渲染也好。
如果没有 pieLabel 和 legend，在数据皆为0的时候没人会知道该区域有这么大的一个空白是干什么用的。
那么，可以请问一下大佬们的解决方案是什么吗？
![image](https://user-images.githubusercontent.com/69715752/90712919-b1acec00-e2d6-11ea-9870-34bdaf3a90f9.png)

**Comment by zengyue** [comment]
要自己处理，饼图本身就是表现数据在100%中的占比，你可以前置做一个判断
