### ISSUE TITLE
timeCat属性的数据绘制折线时，点不按时间分布而是均匀分布

### ISSUE THREAD

**Issue by xiguashuiguo** [antvis/F2#1022]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-currying-eq4ci?file=/src/index.js)

### Steps to reproduce
任意的数据均如此，目前可以使用linear配合formatter解决。
![image](https://user-images.githubusercontent.com/15158750/92195642-0e480380-eea0-11ea-9708-276dd8121e86.png)

| Environment | Info |
|---|---|
| f2 | 3.7.6 |
| System | - |
| Browser | - |

**Comment by zengyue** [comment]
是的，如果要按时间分布，可以在数据上保留全部时间，然后在设置`connectNulls: true`

https://f2.antv.vision/zh/examples/line/other#connect-null

**Comment by xiguashuiguo** [comment]
意思是时间属性保留，Y轴值为null嘛，这样的话，感觉不如用linear然后格式化x轴显示。

**Comment by zengyue** [comment]
嗯，用linear也可以
