### ISSUE TITLE
怎么关联两个图表？

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#104]
![image](https://user-images.githubusercontent.com/18193798/39698963-b04a0400-5229-11e8-9b6b-cee7c7212781.png)
像上面的图通过f2怎么实现，能实现坐标系的关联吗？echarts上可以关联两个坐标系，第一次用f2。

**Comment by simaQ** [comment]
像这种关联两个图表的场景，目前 F2 的实现方案是基于两个 canvas 标签绘制两个 chart，然后通过 dom 上的事件监听来完成 tooltip 的交互，在 chart 上提供了 [getSnapRecords()](https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_getSnapRecords) 以获取鼠标位置对应的 chart 信息。
