### ISSUE TITLE
堆叠图如何显示 label ？

### ISSUE THREAD

**Issue by xiecg** [antvis/F2#1043]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以更直观的看到数值

![image](https://user-images.githubusercontent.com/10857932/94241407-3084ec80-ff47-11ea-94b8-a79ae72fb309.png)

### What does the proposed API look like?
{
label: true
}

**Comment by benvirus** [comment]
@xiecg 
F2 遵循图形语法的设计理念，所以，区别于其他图形库的配置。虽然配置提供了更低的使用门槛，但是却大大限制了灵活性。
所以，，label 的实现需要自己使用 F2 的图形语法去实现。
