### ISSUE TITLE
F2 条形图如何根据传入数据量自动撑开高度

### ISSUE THREAD

**Issue by ChenMuzhan** [antvis/F2#1046]
目前使用版本3.7.7，然后条形图不会根据传入的数据量自动撑开高度，默认都是150px，不管是3条数据还是10条数据，请问如何设置自动撑开高度？

**Comment by zengyue** [comment]
没看懂，给下你的demo，然后描述下你期望的效果

**Comment by benvirus** [comment]
@ChenMuzhan 这个高度是根据你的 Chart 所挂载的 dom 节点的高度确定的，如果想要根据数据量动态改变高度，可以在拿到数据之后，初始化 Chart 之前，手动去改一下 dom 的高度。 
从设计原则上看，Chart 是不应该去改变外部容器的大小的，以防对外部造成干涉，影响其他布局。
