### ISSUE TITLE
AntV F2 隐藏分组柱状图的分组标题

### ISSUE THREAD

**Issue by januwA** [antvis/F2#1048]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
隐藏分组柱状图的分组标题

当我使用color函数进行分组，会自动在图标上加上标题，我想要分组，但是不想要分组标题，我该使用哪个函数

参考[分组柱状图](https://f2.antv.vision/zh/examples/column/dodge)

### What does the proposed API look like?
.

**Comment by zengyue** [comment]
chart.legend(false)
