### ISSUE TITLE
F2 坐标轴x轴如何设置position:top

### ISSUE THREAD

**Issue by ChenMuzhan** [antvis/F2#1053]
场景如下：现在有一个需求场景，就是条形图数据是排序的，从大到小，然后业务有展开收起的功能，需要把x轴放到顶部，满足视觉的需要，但是官方文档设置axis里面没有position:top的选项。
![image](https://user-images.githubusercontent.com/13306747/96331374-46418980-108f-11eb-8965-70b1d358a98b.png)
在官网修改设置x轴为position: top之后，运行报错

![image](https://user-images.githubusercontent.com/13306747/96331425-94ef2380-108f-11eb-9ad6-f8a9d3896b8f.png)

**Comment by benvirus** [comment]
先把原始的 y 轴坐标放到 `right`, 然后整个坐标系 `transposed` 一下。
```js
chart.axis('sales', {
  position: 'right'
})

chart.coord({
  transposed: true
});
```

**Comment by benvirus** [comment]
> 场景如下：现在有一个需求场景，就是条形图数据是排序的，从大到小，然后业务有展开收起的功能，需要把x轴放到顶部，满足视觉的需要，但是官方文档设置axis里面没有position:top的选项。
> ![image](https://user-images.githubusercontent.com/13306747/96331374-46418980-108f-11eb-8965-70b1d358a98b.png)
> 在官网修改设置x轴为position: top之后，运行报错
> 
> ![image](https://user-images.githubusercontent.com/13306747/96331425-94ef2380-108f-11eb-9ad6-f8a9d3896b8f.png)

先把原始的 y 轴坐标放到 `right`, 然后整个坐标系 `transposed` 一下。
```js
chart.axis('sales', {
  position: 'right'
})

chart.coord({
  transposed: true
});
```

**Comment by benvirus** [comment]
@ChenMuzhan 
先把原始的 y 轴坐标放到 `right`, 然后整个坐标系 `transposed` 一下。
```js
chart.axis('sales', {
  position: 'right'
})

chart.coord({
  transposed: true
});
```

**Comment by ChenMuzhan** [comment]
已实现，thanks
