### ISSUE TITLE
在使用Interaction后，chart里面超过坐标系部分的文本会消失（在只调用chat.repaint()重新绘制，而不先destroy的情况下）

### ISSUE THREAD

**Issue by Break-2020** [antvis/F2#1058]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/basic](https://f2.antv.vision/zh/examples/basic)

### Steps to reproduce
1.比如在柱状图中new一个Interaction对象；2.用registerShape绘制柱状图的数值和其他一些图形；3.用chart.render()重新渲染一次图表，超出坐标系的文字消失；4.先调用chart.destory()再new一个chart并render()，显示正常。但是按理来说不应该只显示一半文字，想知道是因为什么原因导致的这个问题

| Environment | Info |
|---|---|
| f2 | 3.7.7 |
| System | win10 |
| Browser | mozilla/5.0 (windows nt 10.0; win64; x64) electron/5.0.3 safari/537.36 |
![2222](https://user-images.githubusercontent.com/73464509/97150435-112ce980-17a9-11eb-88cc-1470ea614710.png)
![111111](https://user-images.githubusercontent.com/73464509/97150444-138f4380-17a9-11eb-965c-03a81758fc0d.png)
![2222](https://user-images.githubusercontent.com/73464509/97150505-299d0400-17a9-11eb-8f16-3e09e7b8ba2e.png)
![111111](https://user-images.githubusercontent.com/73464509/97150510-2b66c780-17a9-11eb-8c7a-e043d60d5e16.png)

**Comment by benvirus** [comment]
请使用 [codesandbox](https://codesandbox.io/)、 [codepen](https://codepen.io/) 等 webIDE 提供最小可复现问题的 example。
