### ISSUE TITLE
f2 华为原生浏览器 无法渲染。

### ISSUE THREAD

**Issue by githubgmq** [antvis/f2#106]
华为荣耀9, mate9, mate9pro 原生浏览器 图表示例无法打开。。
其他版本的华为系浏览器没有测试。
测试了vivo，小米系列，没发现大问题。。

**Comment by simaQ** [comment]
谢谢反馈，可能是因为页面 CSS 样式导致的问题，我定位解决下~~~~再次表示感谢

**Comment by githubgmq** [comment]
问题解决了，及时告知一下。谢谢。

**Comment by simaQ** [comment]
恩恩，我找到原因了，demo 中的代码使用了很多 es6 的特性，而华为原生的浏览器对很多 es6 特性不支持，导致绘制不出来。

![image](https://user-images.githubusercontent.com/6628666/39743601-faaaecbc-52d3-11e8-909c-a3d0ce35b4b9.png)

我今天处理下这些代码

**Comment by simaQ** [comment]
你好，我已经更新 demo 上的代码，现在可以正常渲染了~~~ 你看下

**Comment by simaQ** [comment]
不好意思，上周扫码打开的页面代码没有更新成功，今天已经全部更新了部署了，你可以再看下~~~
