### ISSUE TITLE
一个页面多个图表的问题

### ISSUE THREAD

**Issue by wangzhenyuWZY** [antvis/F2#1074]
当一个页面有两个图表的时候，后加载的那个图表会混乱或者不展示，请教下这个是哪里的问题怎么解决

**Comment by AlanKnightly** [comment]
@wangzhenyuWZY 你好 我们现在也遇到这个问题，控制台一直报出Maximum recursive updates exceeded. 的warning，并且页面会非常卡，请问你们后来解决了嘛？
