### ISSUE TITLE
找不到示例代码所用的API

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#108]
![image](https://user-images.githubusercontent.com/18193798/39758566-cc5ffae4-5302-11e8-9e36-a1291839bbaf.png)

![image](https://user-images.githubusercontent.com/18193798/39758598-ddbc30dc-5302-11e8-9a97-215c04db544a.png)
示例代码给出的
```
 const legend = chart.get('legendController').legends.top[0];

```
在chart的get方法里没找到对应的参数。
legendController是什么 top[0]是什么意思？是指多个图例中的第一个图例吗？

**Comment by simaQ** [comment]
恩，是的，是这个意思。
后面我会将 tooltip 和 legend 联动的这类交互进行封装的，在接口上更易用。
