### ISSUE TITLE
分时图数据和展示问题

### ISSUE THREAD

**Issue by PHenryy** [antvis/F2#1117]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-spence-5suph?file=/src/App.vue)

### Steps to reproduce
时间 ticks 设定 "09:30", "11:30", "15:00"， 但数据如果没有设定的 ticks 就不会显示，且折线会扩展至整个canvas大小，无法像股票软件那样，折线只占canvas中的部分区域，然后随x轴实时的更新长度

| Environment | Info |
|---|---|
| f2 | 3.8.1 |
| System | windows7 |
| Browser | 版本 87.0.4280.88（正式版本） （64 位） |

**Comment by PHenryy** [comment]
@zengyue

**Comment by Psilocine** [comment]
目前我也遇到这个问题了，数据不完整时分时图没办法展示完整 x轴。 @PHenryy 哥你最后是怎么解决的

**Comment by PHenryy** [comment]
@Psilocine 太久远了，我只记得那个项目后来换了别的库，这个不适合做复杂图表
