### ISSUE TITLE
放弃了放弃了，真的使用不下去了。。。

### ISSUE THREAD

**Issue by PHenryy** [antvis/F2#1120]
使用经历两周，主要用于移动端K线图，实时报价，从阅读文档到上手开发，遇到种种问题。。

1. 文档中示例版本老旧，运行即报错
2. 数据缺失/平移卡顿 等明显问题竟一直存在
3. 社区无人维护，项目能够近一个月无任何commit, 上百个 issue 无人回复

前几天通过一个在蚂蚁的同学了解了些情况，公司内部的问题确实不少，果真如浏览 issue 时某个人说的 为了KPI开源吗。。

**Comment by yeenjian** [comment]
平移卡顿问题，已弃坑，简单图表还是老老实实自己画算了

**Comment by wozien** [comment]
滚动一堆问题，我是真吐了
