### ISSUE TITLE
图表背景的设置

### ISSUE THREAD

**Issue by JulesCesar** [antvis/f2#115]
![image](https://user-images.githubusercontent.com/19618696/39851326-d25cca2a-5448-11e8-86cf-45f3000015db.png)
这种类型的背景 没找到相关的background配置文件 求方法

**Comment by simaQ** [comment]
1. 整个图表的背景色，可以直接通过 css 设置 canvas 的 background-color 就可以了。
2. 
![image](https://user-images.githubusercontent.com/6628666/39851401-2fdd35b8-5449-11e8-98b0-f7d07ec00921.png)
区域图的背景色设置，参照这个示例： https://antv.alipay.com/zh-cn/f2/3.x/demo/line/gradient.html

**Comment by JulesCesar** [comment]
解决啦 谢谢！！！

**Comment by JulesCesar** [comment]
但是有个新问题！红色框框里的文字颜色我怎么更改？？实在是没在文档里看到这个配置
![image](https://user-images.githubusercontent.com/19618696/39857644-a0b4112c-5466-11e8-9080-20c5b831dc4d.png)

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/39857677-d0d61fe4-5466-11e8-99c2-f44993ce8548.png)
这个是坐标轴的文本，https://antv.alipay.com/zh-cn/f2/3.x/api/axis.html，配置下 label 属性：
 
```js
chart.axis('xxx', {
  label: {
    fill: 'red' // 配置坐标轴文本的颜色
  }
})
```

---

![image](https://user-images.githubusercontent.com/6628666/39857729-0f24ef78-5467-11e8-9ea5-360871378ba8.png)
这个是图例的文本颜色, nameStyle 和 valueStyle 属性， https://antv.alipay.com/zh-cn/f2/3.x/api/legend.html 

```js
  chart.legend({
    nameStyle: {
      fill: 'red' 
    }
  });
```

**Comment by JulesCesar** [comment]
好滴

**Comment by simaQ** [comment]
@hanxu317317 并非不负责任，而是理解的场景不同。如果是整个图表的颜色，用 css 解决是最好的。而你的场景并非是整个图表的背景色。

**Comment by autukill** [comment]
如何添加背景色, 类似 echarts 直接配置:
` "grid": {
    "show": true,
    "backgroundColor": "RGB(0,39,49)"
  }`
