### ISSUE TITLE
如何得到柱状图柱子的宽度？

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#117]
有个需求需要得到柱状图柱子的宽度看文档不知道怎么得到

**Comment by simaQ** [comment]
额，这个目前不好拿到，但是你可以直接调用 .size(10) 自己设置柱状图的宽度，这样就可以控制柱子的宽度了

**Comment by wenkeShi** [comment]
@simaQ 好的谢谢🙏

**Comment by wenkeShi** [comment]
@simaQ 柱状图我通过
```javascript
chart.get('geoms')[0].getSize();
```
能拿到柱子的宽度，不知道这个是不是标准可用的API？

**Comment by simaQ** [comment]
这个只有在 chart.render() 之后才能获取到这个数值。你可以这么拿，不过原则上并不想作为外部 api 去提供给用户的，所以在 api 文档上没有给出~~~~
