### ISSUE TITLE
绘制柱状图时能否让柱子紧靠边界线，与y轴间不留空隙

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#118]
![image](https://user-images.githubusercontent.com/18193798/39870020-63a12096-5492-11e8-9779-cdc706877911.png)
上图x轴设置了range: [0,1] 结果柱子有一半超出y轴和grid的边界线。不设置range又会有间隙

![image](https://user-images.githubusercontent.com/18193798/39870159-daf346b0-5492-11e8-8877-d62b9a56557e.png)

能设置为紧贴轴线的吗？
像下图这样
![image](https://user-images.githubusercontent.com/18193798/39870153-d4a897e2-5492-11e8-8716-5beab1a748ce.png)

**Comment by simaQ** [comment]
这个不太好办到...  😢 
---

对啦，介意能留个名么？我们想了解使用 F2 的用户方们~~~ https://github.com/antvis/f2/issues/111

**Comment by wenkeShi** [comment]
@simaQ 第一次用F2，还在开发中，做好了在上链接哈。

**Comment by dxq613** [comment]
range 可以动态计算一下：

```js
var margin = 1 / data.length
chart.source(data, {
  sales: {
    tickCount: 5,
  },
  year: {
    range: [margin / 4, 1 - margin/4]
  }
});
```

**Comment by dxq613** [comment]
![snip20180511_17](https://user-images.githubusercontent.com/1264678/39904371-09accd38-550a-11e8-8d1a-d4c38bfaab95.png)

**Comment by wenkeShi** [comment]
@dxq613 谢谢🙏，感觉文档range说的不是很清楚，还能这样操作
