### ISSUE TITLE
图例能显示其他信息吗？

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#120]
![image](https://user-images.githubusercontent.com/18193798/39909825-0c9067ae-5527-11e8-8ca3-a6fa815f820c.png)
像上图，我需要在图例右边显示出选中点的x轴信息

**Comment by dxq613** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_getSnapRecords

**Comment by simaQ** [comment]
如果是 x 轴的话，tooltip 的钩子里返回的 items 中每一项记录都会有个 title 属性的，默认是 x 轴的数据，也可以直接从 origin 属性中获取，该属性存储的是原始数据记录。
