### ISSUE TITLE
多条折线图的tooltip ，点击不准确，感觉有延迟

### ISSUE THREAD

**Issue by caojide** [antvis/F2#1209]
点击总是显示之前的点击位置的tooltip
线上案例： 移动端打开 [https://www.gezhiwo.cn/#/holiday](demo链接)

**Comment by bestGao** [comment]
我这边Taro3.x 微信小程序 "@antv/f2": "^3.8.10-beta.1" 在ios真机上也是长按显示上一步点击位置的tooltip，没人解决吗？
