### ISSUE TITLE
如何让y轴的label显示在图形上层？

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#121]
![image](https://user-images.githubusercontent.com/18193798/39914252-070be1c2-5537-11e8-9d36-f3194dbe4c74.png)

**Comment by simaQ** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/api/axis.html  
![image](https://user-images.githubusercontent.com/6628666/39914296-2dc2312c-5537-11e8-9b4d-cd480244f37a.png)

```js
chart.axis('xxx', {
  label: {
   top: true
  }
})
```
