### ISSUE TITLE
请教下 F2 有 Slider 组件么？

### ISSUE THREAD

**Issue by 285858315** [antvis/f2#125]
数据很多的时候折线图需要滑动操作怎么办？

**Comment by simaQ** [comment]
目前 F2 没有提供 slider 组件，主要的原因是：

1. F2 解决的是移动端图表可视化问题，在移动端，多用手指进行交互，使用传统的 slider 组件的话，如下图，手指的触控面积较大，这样的体验不会太好
![image](https://user-images.githubusercontent.com/6628666/40092000-7eb8b9a2-58ed-11e8-97de-bd52c1f8b8ea.png)

2. 在数据很多的折线图上，可以使用 zoom and pan 的交互，即让用户直接用双指进行放大缩小以及平移操作，这个交互我们正在实现，不过得等一段时间。

---

在这里，我提供一个解决方案，你批判性得看哈~~~~

可以按照某个维度对数据进行切分，然后提供 tab 的切换，如常见的基金的业绩走势图就是这样的： 
![img_9691](https://user-images.githubusercontent.com/6628666/40092133-42025e0e-58ee-11e8-8360-476025f90687.PNG)
