### ISSUE TITLE
F2可以实现漏斗图吗？

### ISSUE THREAD

**Issue by xiazhangli** [antvis/f2#127]
请问一下F2有什么方式可以实现漏斗图呢？

**Comment by simaQ** [comment]
目前还不支持漏斗图的绘制，在计划中

**Comment by mrKylinZhou** [comment]
现在看官网仍然没有漏斗图的Demo，我看这个问题已经关闭了，是已经实现了还是不打算支持了。
或者如果支持能给个Demo链接吗
