### ISSUE TITLE
双Y轴辅助线bug

### ISSUE THREAD

**Issue by xiazhangli** [antvis/f2#128]
* **F2 Version**:
* **Platform**: HUAWEI MATE 8；EMUI 5.0.1；Android 7.0；
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

F2的demo小程序中，双Y轴的示例在微信开发者工具中开发时可以看到guide辅助线，但是在手机上就没有显示。

**Comment by simaQ** [comment]
目前我手上还没找到测试机，你看下是不是  guide().line() 那里设置 lineDash 属性导致的，你将它设置为 null 试下看看能不能渲染出来？
![image](https://user-images.githubusercontent.com/6628666/40287444-eee28672-5cdf-11e8-93f4-406fd81c1fe7.png)

**Comment by xiazhangli** [comment]
改成null的话可以渲染出来。
