### ISSUE TITLE
f2 4.0版本计划什么时候发布正式版本

### ISSUE THREAD

**Issue by wangshuqing** [antvis/F2#1298]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
f2 4.0版本计划什么时候发布正式版本

### What does the proposed API look like?
f2 4.0版本计划什么时候发布正式版本

**Comment by El-Chiang** [comment]
年前会发布一个正式版

**Comment by ACERY1** [comment]
已发布正式版，欢迎尝鲜
