### ISSUE TITLE
f2的柱状图和曲线图如果有多个legend能实现单个切换吗?

### ISSUE THREAD

**Issue by alianrock** [antvis/f2#131]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
单个切换指的是？图例单选操作么，类似下面的动图？

![default](https://user-images.githubusercontent.com/6628666/40399274-0b48bb16-5e6f-11e8-8254-db3c7ee10908.gif)

**Comment by alianrock** [comment]
@simaQ 是的哈

**Comment by simaQ** [comment]
目前还没有支持这个功能，这周给你加上

**Comment by alianrock** [comment]
@simaQ 赞👍！

**Comment by simaQ** [comment]
@alianrock  3.1.8 小版本里面支持了。

```js
chart.legend({
  selectedMode: single'
});
```
