### ISSUE TITLE
连续数据的量度的min和max如何设置为数据最小值和最大值

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#135]

**Comment by wenkeShi** [comment]
将nice设置为false之后，在最大值和最小值处无法显示刻度吗

**Comment by simaQ** [comment]
能看下你的代码么？

**Comment by wenkeShi** [comment]
```javascript
          this.headerChart1.source(chart1Data,
          {
            time : {
              range: [0,1],
              type : 'timeCat',
              tickCount : 2,
              mask : 'MM-DD',
            },
            nvt : {
              // range: [0, 1],
              nice: false,
              // tickCount: 3,
            },
          });
```

**Comment by simaQ** [comment]
你可以配置下 min max

**Comment by wenkeShi** [comment]
min,max想设置为数据的最小值和最大值是需要自己计算出来吗

**Comment by wenkeShi** [comment]
![image](https://user-images.githubusercontent.com/18193798/40571868-3e39a6b4-60d3-11e8-87d4-687dc3144c4a.png)
能实现类似这样的刻度吗

**Comment by wenkeShi** [comment]
![image](https://user-images.githubusercontent.com/18193798/40571894-b9625eee-60d3-11e8-8346-5978058a002d.png)
能实现类似这样的刻度吗

**Comment by simaQ** [comment]
默认情况下，我们会根据数据的范围，计算出 min 和 max，然后对 min 和 max 的范围进行优化（即 nice 为 true 的情况），比如你的数据原始的 min 和 max 是 1 和 98，我们为了刻度显示均匀会默认优化为 0 和 100。

这样的效果，你可以尝试使用 tickInterval 属性:

```js
chart.scale('nvt', {
  nice: false, // 以实际的 min 为准
  tickInterval: 10 
});
```

**Comment by wenkeShi** [comment]
nice设为false,绘图区域确实是从数据最大值到数据最小值，但是纵坐标的刻度始终无法标记在最小值和最大值处，手动设置min，max为数据最小值和最大值，在纵坐标的开始和结尾处也没有刻度

**Comment by simaQ** [comment]
那你方便写一个  codePen 给我么，我定位下：

https://codepen.io/Sima/pen/qVgdex

**Comment by wenkeShi** [comment]
https://codepen.io/anon/pen/mLNOXx
设置了nice为false，min和max为数据最值，但是在最值处无刻度

**Comment by wenkeShi** [comment]
@simaQ 请问这算是缺陷吗

**Comment by simaQ** [comment]
恩我看了你的例子，也不算是缺陷，是符合我们的设计预期的。在这里我们需要同时考虑刻度的均匀以及显示上不造成重叠，所以出现了这种情况。

可以的话，你尝试下直接设置 ticks ，这样就可以完全按照你的预期来显示数字了。

```js
chart.source(data, {
  value: {
    min: 68,
    max: 309,
    nice: false,
    //tickCount:3
    ticks: [ 68, 100, 150, 200, 250, 309]
  },
  date: {
    type: 'timeCat',
    range: [0, 1],
    tickCount: 3
  }
});
```

**Comment by wenkeShi** [comment]
哦哦，感谢。那数据切换时，不能只用changeData()了，必须要改配置项然后在repaint吗？

**Comment by simaQ** [comment]
不客气。

数据切换的时候，你只要在 chart.changeData() 之前，调用 chart.scale('value', {}) 重新为 value 字段进行列定义就可以了。

**Comment by wenkeShi** [comment]
![image](https://user-images.githubusercontent.com/18193798/40595011-ddf1886a-6264-11e8-84db-56efe429205b.png)
![image](https://user-images.githubusercontent.com/18193798/40595016-e16c0768-6264-11e8-9a75-d142ef25bc09.png)
![image](https://user-images.githubusercontent.com/18193798/40595021-e4a63b88-6264-11e8-9c5f-9923562db034.png)
我切换数据时，想改变时间轴的刻度文本格式化方式，为日时则时HH:mm 为月时则为MM:DD。但是切换数据时。第一次由日切换到月，时间都显示的00:00，第二次切换回来就正常显示了。
```javascript
this.qrChart.scale('time',
            {
              range: [0,1],
              type : 'timeCat',
              tickCount : 2,
              mask : qrSwitch == 0 ? 'HH-mm' : 'MM-DD',
              // formatter: function(){
              // },
            });
            // this.qrChart.repaint();
            this.qrChart.changeData(this.qrData[qrSwitch]);
```

**Comment by wenkeShi** [comment]
用formatter也时一样的

**Comment by simaQ** [comment]
因为你的数据源里面时间格式是 "2017-06-15"，没有提供到 时 分 秒的精度，所以会这样哦，优化下原始数据吧

**Comment by wenkeShi** [comment]
已经解决啦谢谢🙏
