### ISSUE TITLE
柱状图怎么细化区分度, 让纵坐标底部为最小值

### ISSUE THREAD

**Issue by wenkeShi** [antvis/f2#136]
![image](https://user-images.githubusercontent.com/18193798/40607367-e95b966a-629a-11e8-813f-83fdbab62d5e.png)
```javascript

chart.source(data, {
  sales: {
    min: 37,
    max: 180,
	nice: false,
    ticks: [37, 50, 180]
  }
});
```
上面的是修改的官方实例，
想让柱状图更有区分度一点

**Comment by wenkeShi** [comment]
![image](https://user-images.githubusercontent.com/18193798/40607543-6896a83e-629b-11e8-9f05-73b179853555.png)
```javascript
 volumn: {
              tickCount: 3,
              range: [0,1],
              
              nice: false,
              formatter: function(ivalue){
                return (ivalue/100000000).toFixed(2);
              },
            },
```
上面的图就没有区分度，柱状图怎么让数值很大但是差值很小的数据有区分度

**Comment by simaQ** [comment]
恩，刚定位了，是个 BUG，目前柱状图不支持 min 的设置。。。 我给你修复一下

**Comment by simaQ** [comment]
@antv/f2/v/3.1.9-beta.1 在这个版本里面修复了，你试下~~~

```js
volumn: {
      min: 30,
      nice: false
    }
```
