### ISSUE TITLE
微信小程序气泡图pinch缩放是否支持？

### ISSUE THREAD

**Issue by yuyunzhi** [antvis/F2#1371]
您好，关于微信小程序需要实现一个气泡图，缩放的功能。pinch 是否可以支持对气泡或者整个xy坐标进行放大放小？ 我在https://github.com/antvis/F2/issues/627 看到您们说小程序不支持pinch交互吗？

**Comment by zengyue** [comment]
嗯，气泡图的气泡缩放确实不支持
