### ISSUE TITLE
曲线层叠图Y轴超过100%导致图标上方出现空白区

### ISSUE THREAD

**Issue by zbk6** [antvis/F2#1375]
曲线层叠图Y轴超过100%导致图标上方出现空白区
![image](https://user-images.githubusercontent.com/71298600/155267409-517da907-6527-4ed3-b468-95cb9a428c89.png)

**Comment by zbk6** [comment]
各项数据不超过100%，为什么会出现120%的y轴。可控么

**Comment by zengyue** [comment]
这个是刻度的 nice 算法，为了让刻度间隔更符合阅读，如果要关闭的也可以，但是不建议
```
chart.scale({
[yField]: { nice: false }
})
```

**Comment by zbk6** [comment]
> 这个是如果要阅读的好方法，但是让间隔更适合阅读的也可以，不建议阅读
> 
> ```
> chart.scale({
> [yField]: { nice: false }
> })
> ```
我的意思是 数据总和不超过100%，为什么y轴的上限会超过100% 达到120%

**Comment by zbk6** [comment]
> 数据发一个看看

[{ country: '0', value: 0.64, year: '20201231' },
      { country: '1', value: 0, year: '20201231' },
      { country: '2', value: 0.03, year: '20201231' },
      { country: '3', value: 0, year: '20201231' },
      { country: '4', value: 5.65, year: '20201231' },
      { country: '5', value: 1.22, year: '20201231' },
      { country: '6', value: 0.01, year: '20201231' },
      { country: '7', value: 6.43, year: '20201231' },
      { country: '8', value: 0.02, year: '20201231' },
      { country: '9', value: 16.51, year: '20201231' },
      { country: '10', value: 0, year: '20201231' },
      { country: '11', value: 0.04, year: '20201231' },
      { country: '12', value: 0.01, year: '20201231' },
      { country: '13', value: 1.64, year: '20201231' },
      { country: '14', value: 1.96, year: '20201231' },
      { country: '15', value: 3.67, year: '20201231' },
      { country: '16', value: 0, year: '20201231' },
      { country: '17', value: 0, year: '20201231' },
      { country: '18', value: 0, year: '20201231' },
      { country: '19', value: 0, year: '20201231' },
      { country: '20', value: 0, year: '20201231' },
      { country: '21', value: 13.75, year: '20201231' },
      { country: '22', value: 2.28, year: '20201231' },
      { country: '23', value: 1.08, year: '20201231' },
      { country: '其他', value: 45.06, year: '20201231' },
      { country: '22', value: 1.85, year: '20210331' },
      { country: '2', value: 0.03, year: '20210331' },
      { country: '7', value: 6.22, year: '20210331' },
      { country: '6', value: 0.01, year: '20210331' },
      { country: '16', value: 0, year: '20210331' },
      { country: '23', value: 0.88, year: '20210331' },
      { country: '18', value: 0, year: '20210331' },
      { country: '9', value: 16.91, year: '20210331' },
      { country: '15', value: 1.92, year: '20210331' },
      { country: '21', value: 17.12, year: '20210331' },
      { country: '4', value: 6.5, year: '20210331' },
      { country: '14', value: 1.59, year: '20210331' },
      { country: '11', value: 0.03, year: '20210331' },
      { country: '1', value: 0, year: '20210331' },
      { country: '10', value: 0, year: '20210331' },
      { country: '12', value: 0.01, year: '20210331' },
      { country: '0', value: 0.52, year: '20210331' },
      { country: '5', value: 0.04, year: '20210331' },
      { country: '13', value: 1.34, year: '20210331' },
      { country: '8', value: 0.02, year: '20210331' },
      { country: '其他', value: 45.01, year: '20210331' },
      { country: '24', value: 0, year: '20210630' },
      { country: '13', value: 0.01, year: '20210630' },
      { country: '11', value: 0, year: '20210630' },
      { country: '4', value: 1.85, year: '20210630' },
      { country: '12', value: 0, year: '20210630' },
      { country: '23', value: 3.57, year: '20210630' },
      { country: '22', value: 2.6, year: '20210630' },
      { country: '16', value: 0.01, year: '20210630' },
      { country: '20', value: 0, year: '20210630' },
      { country: '19', value: 0, year: '20210630' },
      { country: '2', value: 0.02, year: '20210630' },
      { country: '25', value: 0.01, year: '20210630' },
      { country: '26', value: 0, year: '20210630' },
      { country: '6', value: 0.02, year: '20210630' },
      { country: '7', value: 6.6, year: '20210630' },
      { country: '10', value: 0.01, year: '20210630' },
      { country: '0', value: 0.61, year: '20210630' },
      { country: '8', value: 0.13, year: '20210630' },
      { country: '21', value: 15.13, year: '20210630' },
      { country: '9', value: 12.9, year: '20210630' },
      { country: '15', value: 11.48, year: '20210630' },
      { country: '27', value: 0, year: '20210630' },
      { country: '3', value: 0, year: '20210630' },
      { country: '其他', value: 45.05, year: '20210630' },
      { country: '9', value: 15.84, year: '20210930' },
      { country: '21', value: 13.72, year: '20210930' },
      { country: '15', value: 12.38, year: '20210930' },
      { country: '23', value: 5.07, year: '20210930' },
      { country: '28', value: 2.8, year: '20210930' },
      { country: '22', value: 2.36, year: '20210930' },
      { country: '7', value: 2.13, year: '20210930' },
      { country: '0', value: 0.56, year: '20210930' },
      { country: '8', value: 0.07, year: '20210930' },
      { country: '6', value: 0.02, year: '20210930' },
      { country: '16', value: 0.01, year: '20210930' },
      { country: '2', value: 0.01, year: '20210930' },
      { country: '13', value: 0.01, year: '20210930' },
      { country: '10', value: 0.01, year: '20210930' },
      { country: '14', value: 0.01, year: '20210930' },
      { country: '18', value: 0, year: '20210930' },
      { country: '12', value: 0, year: '20210930' },
      { country: '17', value: 0, year: '20210930' },
      { country: '25', value: 0, year: '20210930' },
      { country: '19', value: 0, year: '20210930' },
      { country: '27', value: 0, year: '20210930' },
      { country: '26', value: 0, year: '20210930' },
      { country: '4', value: 0, year: '20210930' },
      { country: '24', value: 0, year: '20210930' },
      { country: '其他', value: 45, year: '20210930' }]

**Comment by zbk6** [comment]
> 数据发一个看看

{ country: '01', year: '20200331', value: 38.81 },
        { country: '02', year: '20200331', value: 33.29 },
        { country: '03', year: '20200331', value: 0 },
        { country: '04', year: '20200331', value: 24.6 },
        { country: '05', year: '20200331', value: 3.3 },
        { country: '01', year: '20200630', value: 39.81 },
        { country: '02', year: '20200630', value: 38.24 },
        { country: '03', year: '20200630', value: 0 },
        { country: '04', year: '20200630', value: 20.24 },
        { country: '05', year: '20200630', value: 1.71 },
        { country: '01', year: '20200930', value: 40.36 },
        { country: '02', year: '20200930', value: 34.32 },
        { country: '03', year: '20200930', value: 0 },
        { country: '04', year: '20200930', value: 24.86 },
        { country: '05', year: '20200930', value: 0.46 },
        { country: '01', year: '20201231', value: 39.71 },
        { country: '02', year: '20201231', value: 27.57 },
        { country: '03', year: '20201231', value: 0 },
        { country: '04', year: '20201231', value: 27.89 },
        { country: '05', year: '20201231', value: 4.83 },
        { country: '01', year: '20210331', value: 40.68 },
        { country: '02', year: '20210331', value: 26.85 },
        { country: '03', year: '20210331', value: 0 },
        { country: '04', year: '20210331', value: 25.25 },
        { country: '05', year: '20210331', value: 7.22 },
        { country: '01', year: '20210630', value: 40.25 },
        { country: '02', year: '20210630', value: 28.48 },
        { country: '03', year: '20210630', value: 0 },
        { country: '04', year: '20210630', value: 29.23 },
        { country: '05', year: '20210630', value: 2.04 }


用这个吧 这个数据简单点

**Comment by zengyue** [comment]
![image](https://user-images.githubusercontent.com/1478197/155468456-1da8d1ca-4b4d-4abb-b580-dbf40a43341b.png)


js 的精度问题，可以这样处理下 https://codesandbox.io/s/cool-thunder-whuc2m?file=/index.js

**Comment by zbk6** [comment]
> ![图片](https://user-images.githubusercontent.com/1478197/155468456-1da8d1ca-4b4d-4abb-b580-dbf40a43341b.png)
> 
> js的精确问题，可以这样处理下https://codesandbox.io/s/cool-thunder-whuc2m?file=/index.js

好的，谢谢。数据传进F2之前我就用bignumber解决了精度损失。没想到F2处理时也会有精度损失。这个问题可以的话F2可以优化一下。预祝F2越来越好
