### ISSUE TITLE
支持Weex吗

### ISSUE THREAD

**Issue by cileLV** [antvis/f2#138]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

能在Weex项目中使用吗？想在Weex项目中绘制图表，如何使用？

**Comment by simaQ** [comment]
恩，可以支持的，weex 之前基于旧版的 F2 （那时候叫 g2-mobile） 封装过 [weex-chart](https://github.com/weex-plugins/weex-chart)，目前还没有升级至 F2 。

可以给你支持下

**Comment by cileLV** [comment]
谢谢！

**Comment by KaelInvoker** [comment]
f2版本已经4.0了，请问各位大佬这个封装的方案能使用最新版的f2么
