### ISSUE TITLE
图表类型丰富

### ISSUE THREAD

**Issue by simaQ** [antvis/f2#139]
- [ ] 支持 symmetric （对称）的数据调整方式，增加该方式之后可以支持漏斗图、streamgraph 的图表的绘制

![image](https://user-images.githubusercontent.com/6628666/40818817-9d433ac8-658b-11e8-856e-afbc1ec97428.png)
![image](https://user-images.githubusercontent.com/6628666/40818824-a9225996-658b-11e8-8bfe-088d5caaf883.png)

- [ ] 支持 adjust 的组合调整，以支持如分组层叠柱状图的绘制。

![image](https://user-images.githubusercontent.com/6628666/40818783-77f39e2a-658b-11e8-90c9-9f1d194e8118.png)

**Comment by mrKylinZhou** [comment]
漏斗图这个功能目前有支持吗
