### ISSUE TITLE
无法形成一个完整的闭环

### ISSUE THREAD

**Issue by liangyt** [antvis/f2#14]
这组代码：
`GM.Global.pixelRatio = 6;
      var  data = [
       {a: '1', b: 0.833403, c: '1'},
       {a: '1', b: 0.041649, c: '2'},
       {a: '1', b: 0.041649, c: '3'},
       {a: '1', b: 0.041649, c: '4'},
       {a: '1', b: 0.04165, c: '5'}
      ];
      var chart = new GM.Chart({
        id: 'c1'
      });
      chart.source(data);
      chart.coord('polar', {
        transposed: true,
        inner: 0.6
      });
      chart.axis(false);
      chart.intervalStack().position('a*b').color('c');
      chart.animate().wavec();
      chart.render();`
没法形成一个完整的闭环，如果数据的顺序移动一下则可以，如：

` var  data = [
       {a: '1', b: 0.033403, c: '1'},
       {a: '1', b: 0.841649, c: '2'},
       {a: '1', b: 0.041649, c: '3'},
       {a: '1', b: 0.041649, c: '4'},
       {a: '1', b: 0.04165, c: '5'}
      ];`

**Comment by dxq613** [comment]
在 b 的列定义里面加个 nice: false 即可

chart.source(data, {b: {nice: false}});
