### ISSUE TITLE
为什么在 react 中使用饼图位置发生偏差

### ISSUE THREAD

**Issue by LoeiFy** [antvis/f2#143]
完全照着官方例子渲染到页面上，我试了折线图，柱状图都是正常的，但是饼图会发生错位

饼图使用的例子是这个：https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/pie.html

但我这边显示的效果是这样：

<img width="1139" alt="screen shot 2018-06-05 at 7 40 29 pm" src="https://user-images.githubusercontent.com/2193211/40973953-a5faa7a8-68f8-11e8-8f3d-bf5d156a9550.png">

* **F2 Version**: 3.1.8
* **Platform**: macOS 10.12.6 chrome 66

**Comment by simaQ** [comment]
阿列。。。 能提供可运行的 react demo 么？我排查下~~~ 多谢

**Comment by LoeiFy** [comment]
@simaQ 可以看这里：https://codesandbox.io/s/7z95n6o0k1

**Comment by simaQ** [comment]
恩，应该是你设置了 padding 属性 ，这个默认值可以直接设置成 'auto' 的，F2 默认的也是  'auto' ，我们会根据坐标轴文本、图例大小自动计算的。

![image](https://user-images.githubusercontent.com/6628666/41011751-df24dc9c-6970-11e8-90d9-2be1e0665e37.png)

**Comment by LoeiFy** [comment]
@simaQ thanks.

我尝试了柱状图，折线图，都需要设置 padding，不然坐标会被挡住，所以我以为全部都要加 padding
