### ISSUE TITLE
设置max和min无效

### ISSUE THREAD

**Issue by jilaokang** [antvis/f2#144]
* 很抱歉我的浏览器无法使用提问模板，很抱歉一打开就崩溃。

在使用最新的F2

这个Demo的最大最小值无法设置
https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/basic-column.html

但是如折线图都可以使用，其他的一些图表也可以

**Comment by simaQ** [comment]
嗯哪，这个 bug 已经发现了，在 3.1.9-beta.2 这个版本里试一下，我明天发布正式版

**Comment by jilaokang** [comment]
@simaQ 好的，非常感谢！框架好看好用

**Comment by jilaokang** [comment]
在哪里下载3.1.9？

**Comment by jilaokang** [comment]
框架很好用，但很多api用法没有示例，不知道怎么用，希望能加上示例，就更完美了

**Comment by simaQ** [comment]
非常感谢。demo 还有文档我会尽力补全的~

**Comment by jilaokang** [comment]
看到刚刚更新了，想问一下最新版本如何安装呢？

**Comment by simaQ** [comment]
1. npm 模块安装

```js
npm install @antv/f2 --save
```

2. 浏览器引入

```html
<!-- 引入在线资源 -->
<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.1.9/f2.js"></script>
```

使用教程： https://antv.alipay.com/zh-cn/f2/3.x/tutorial/index.html#_%E5%AE%89%E8%A3%85

**Comment by komagic** [comment]
@simaQ 3.4.1 min设置折线图还是无效啊

**Comment by simaQ** [comment]
> @simaQ 3.4.1 min设置折线图还是无效啊

提 issue，提供可复现的代码
