### ISSUE TITLE
小程序中如何自定义tooltip的显示

### ISSUE THREAD

**Issue by yyq914828jzg** [antvis/F2#1440]
> 有一个需求,小程序中要实现tooltip的自定义显示,

如下图这样的实现
![c24bf97eb2db0b9784755c5f713445a](https://user-images.githubusercontent.com/23169108/162676383-6acb5945-dd5e-4dbc-bf98-06fbef1be746.png)
![1101f59e5189750c73b1ccc43a1d3ad](https://user-images.githubusercontent.com/23169108/162676393-351dd09d-7fb4-4d56-8607-1281ae296f83.png)
这个是可以实现的吗？

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/docs/tutorial/advanced/custom-view  可以参考这个

**Comment by zengyue** [comment]
https://f2-v3.antv.vision/zh/docs/tutorial/require#guide

按需引进来，然后自己手动注册下

**Comment by xiongchenxu** [comment]
> https://f2-v3.antv.vision/zh/docs/tutorial/require#guide
> 
> 按需引进来，然后自己手动注册下

ok，感谢，F2 4.x 能给个F2 3.x 下这样的图例吗？https://f2-v3.antv.vision/zh/examples/component/legend#custom ，同时希望完善下F2 4.x下其他的图例，现在官方提供的F2 4.x的图例和F2 3.x的图例差距较大, 希望能尽快完善F2 4.x，我们研发也好尽快做版本移植. @zengyue

**Comment by zengyue** [comment]
> > https://f2-v3.antv.vision/zh/docs/tutorial/require#guide
> > 按需引进来，然后自己手动注册下
> 
> ok，感谢，F2 4.x 能给个F2 3.x 下这样的图例吗？https://f2-v3.antv.vision/zh/examples/component/legend#custom ，同时希望完善下F2 4.x下其他的图例，现在官方提供的F2 4.x的图例和F2 3.x的图例差距较大, 希望能尽快完善F2 4.x，我们研发也好尽快做版本移植. @zengyue

这个是自定义的。。默认的和3.x 是一样的

**Comment by xiongchenxu** [comment]
> > > https://f2-v3.antv.vision/zh/docs/tutorial/require#guide
> > > 按需引进来，然后自己手动注册下
> > 
> > 
> > ok，感谢，F2 4.x 能给个F2 3.x 下这样的图例吗？https://f2-v3.antv.vision/zh/examples/component/legend#custom ，同时希望完善下F2 4.x下其他的图例，现在官方提供的F2 4.x的图例和F2 3.x的图例差距较大, 希望能尽快完善F2 4.x，我们研发也好尽快做版本移植. @zengyue
> 
> 这个是自定义的。。默认的和3.x 是一样的

好的，感谢，我试着做一下

**Comment by xiongchenxu** [comment]
你发的邮件，我已经收到了！~I have received the mail of you send!
