### ISSUE TITLE
添加 4.0 版本 的 JSX 如何在 vue 项目使用的文档

### ISSUE THREAD

**Issue by Airkro** [antvis/F2#1444]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
添加文档，说明 JSX 怎样在 vue 项目使用，怎样不使用 JSX 等

### What does the proposed API look like?
无

**Comment by missleeee** [comment]
mark~

**Comment by missleeee** [comment]
mark~

**Comment by zehuichan** [comment]
mark~

**Comment by zengyue** [comment]
可以直接补充下 f2-vue，方便 vue 的项目直接使用

**Comment by liangei** [comment]
> 可以直接补充下 f2-vue，方便 vue 的项目直接使用

这个方法是webpack的，vite上用不了吧。。

**Comment by zengyue** [comment]
vite 可以的，印象中有个插件，可以来编译 jsx 文件

**Comment by zengyue** [comment]
https://github.com/antvis/F2/pull/1475

添加了个 vite 的示例工程

**Comment by zengyue** [comment]
文档： https://f2.antv.vision/zh/docs/tutorial/vue
