### ISSUE TITLE
坐标轴位置偏差

### ISSUE THREAD

**Issue by LoeiFy** [antvis/f2#145]
在获取数据后首次展示图表，如果数据太大，这时候坐标轴会偏差，但是 react hot-reload 后就会恢复正常，这是什么原因？

<img width="441" alt="screen shot 2018-06-07 at 4 42 24 pm" src="https://user-images.githubusercontent.com/2193211/41088977-6440e1de-6a73-11e8-9da5-8b1870970e16.png">

F2 Version: 3.1.8
Platform: macOS 10.12.6 chrome 66

**Comment by simaQ** [comment]
能麻烦截个动图看下么？

**Comment by LoeiFy** [comment]
@simaQ 我弄个 demo 吧，比较麻烦，等一下

**Comment by LoeiFy** [comment]
@simaQ 这个：https://codesandbox.io/s/7z95n6o0k1

打开后点 reload，你会看到 y 轴被挡住

**Comment by simaQ** [comment]
好的，我看下~~~

**Comment by LoeiFy** [comment]
@simaQ 再提两个小点

1. 饼图更新数据时候，如果设置了 legend，这时候 legend 不会更新，有什么办法更新这个 legend ？我现在做法是 destory 当前 chart，然后重建，这时候图表就会闪烁

2. 我使用 `parcel-bundler`   这个构建工具，但我发现我不能直接 improt `@antv/f2`，会报错说不存在这个包，但我这样引入是可以的 `import F2 from '../../../node_modules/@antv/f2/build/f2'` 但是别的类似 @ 开头的包却不会报错，例如 `@npm/decorate` 就可以正常引入。后面测试所有 `@antv` 开头的包都会有这个问题

**Comment by simaQ** [comment]
@LoeiFy 好的，感谢反馈~~

不过我建议还是一个问题一个 issue 的方式提交。便于我们后续问题的记录追踪哈~~~

**Comment by simaQ** [comment]
@LoeiFy 饼图图例那个问题，数据变更的时候图例默认是会自动更新的，可能是使用姿势不太对。你可以重新提一个 issue，我帮你看看。

**Comment by leungwensen** [comment]
@LoeiFy 使用 parcel-bundler 的时候，具体报错的信息能不能贴一下？

**Comment by LoeiFy** [comment]
@simaQ https://github.com/antvis/f2/issues/147
@leungwensen  https://github.com/antvis/f2/issues/148

**Comment by LoeiFy** [comment]
fixed
