### ISSUE TITLE
4.0版本怎么在vue中使用呢？

### ISSUE THREAD

**Issue by af199901** [antvis/F2#1453]
4.0版本怎么在vue中使用呢？

**Comment by zengyue** [comment]
目前还是 虚位以待，有没有兴趣贡献一版 😄

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/docs/tutorial/vue

**Comment by Yourhero1** [comment]
https://f2.antv.vision/zh/docs/tutorial/vue 这个链接案例在vue中跑不通吧

**Comment by Yourhero1** [comment]
@zengyue 会提示jsx错误问题
![image](https://user-images.githubusercontent.com/88613466/220515015-7f70ede4-0b51-4b19-a6a6-70b28f33e55d.png)
