### ISSUE TITLE
label 折线图

### ISSUE THREAD

**Issue by moyuderen** [antvis/F2#1456]
- **F2 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodeSandbox Link**:

支线图点击label怎么添加事件

**Comment by zengyue** [comment]
没看懂，写详细点吧

**Comment by moyuderen** [comment]
> 没看懂，写详细点吧
![image](https://user-images.githubusercontent.com/94170639/165008606-fbe9c50a-786b-4b63-ada6-643f23974079.png)
背景：希望点击01月 或者 02，重新重新拉取1月份之前两个月的数据数据，需要有一个点击label的事件

**Comment by zengyue** [comment]
好吧，这个 label 目前是没有点击事件的，如果要做，可以通过 自定义 axis 组件来实现

**Comment by moyuderen** [comment]
> 好吧，这个 label 目前是没有点击事件的，如果要做，可以通过 自定义 axis 组件来实现

在3.x版本，目前有方法自定义axis嘛

**Comment by zengyue** [comment]
有是有，不过会相对麻烦点
