### ISSUE TITLE
仪表盘的蓝色进度条宽度是否可以自定义

### ISSUE THREAD

**Issue by ronghang** [antvis/F2#1460]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义仪表盘蓝色进度条宽度

### What does the proposed API look like?
新增一个 width 属性指定仪表盘进度条的宽度

![image](https://user-images.githubusercontent.com/15646173/165451702-584192a8-4259-43fa-9447-a112f4a26238.png)

**Comment by zengyue** [comment]
https://codesandbox.io/s/eloquent-lamport-kjp7hh?file=/index.jsx

可以看这个，仪表盘的样式灵活性比较高，可以用自定义 view 来实现，可以任意定制

**Comment by XianZhengquan** [comment]
自定义，在Taro中不显示
