### ISSUE TITLE
ScrollBar  横向滚动到最后

### ISSUE THREAD

**Issue by xienas** [antvis/F2#1464]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ScrollBar  横向滚动无法初始化的时候滚动到最后。

### What does the proposed API look like?
boolean  开启是否滚动到最后

**Comment by zengyue** [comment]
可以用 4.x， 设置下 range 就可以了

https://f2.antv.vision/zh/examples/line/line#pan

```jsx
<ScrollBar mode="x" range={[0.8, 1]} />
```

**Comment by xienas** [comment]
感谢，可以啦
