### ISSUE TITLE
饼图 legend 更新问题

### ISSUE THREAD

**Issue by LoeiFy** [antvis/f2#147]
demo 在这里：https://codesandbox.io/s/3x2lxkyx01

点击 reload 后会显示数据 undefined，但是如果 destory 后重建图表是可以展示数据的。

我应该怎么方式更好刷新 legend ？

**Comment by simaQ** [comment]
恩。
1. #145 issue 上的问题已经修复了，最新版本 3.1.9.
2. 饼图这个问题，是这样的，reload 的时候 data 变更了调用了 chart.changeData() 方法。但是这一段代码没有更新：

![image](https://user-images.githubusercontent.com/6628666/41147162-3d28f206-6b38-11e8-9b57-517dffb75bee.png)

这个场景里面 changeData 的时候要重新动态计算下各项的百分比。

![image](https://user-images.githubusercontent.com/6628666/41147265-8848b668-6b38-11e8-9360-9d16b50732dc.png)



> PS: 请问你们这个是什么项目呀? 可以帮忙维护下我们的这个列表么？ https://github.com/antvis/f2/issues/111

**Comment by LoeiFy** [comment]
@simaQ 
我发现我现在用的方式更新 legend 数据很麻烦，所以我最后使用 destory 方式来搞了
做的小项目，迟点弄好看能不能加上那个列表
