### ISSUE TITLE
很抱歉打扰了 我看展示中有这个 就是手指滑动的时候 在上面的文字后面显示数值 这么是用哪个属性做到的万分感谢

### ISSUE THREAD

**Issue by Otomii** [antvis/F2#1522]
![微信图片_20220618114738](https://user-images.githubusercontent.com/4024368/174421698-2e3e437f-4c42-45a2-8853-e2e0e14f55d7.png)
很抱歉打扰了 我看展示中有这个 就是手指滑动的时候 在上面的Legend后面显示数值 这么是用哪个属性做到的万分感谢

顺便想询问下 有木有支持群 万分感谢

**Comment by Otomii** [comment]
顺便想询问下 有木有支持群 万分感谢

**Comment by tangying1027** [comment]
只能通过自定义去实现  https://f2.antv.vision/zh/examples/component/legend#custom
