### ISSUE TITLE
堆叠柱状图最大值显示不对

### ISSUE THREAD

**Issue by zengyue** [antvis/F2#1527]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-keldysh-khk49b)

### Steps to reproduce
https://codesandbox.io/s/thirsty-keldysh-khk49b

| Environment | Info |
|---|---|
| f2 | 4.0.25 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
收到，已修改～
