### ISSUE TITLE
Area 设置渐变颜色太淡

### ISSUE THREAD

**Issue by cxh1991** [antvis/F2#1528]
Area设置渐变 官网还可以  为啥我这样配置很淡  几乎看不到

![image](https://user-images.githubusercontent.com/12569325/175498910-f2137771-7812-4237-8758-a80a27ffe343.png)

渲染效果
![image](https://user-images.githubusercontent.com/12569325/175498483-1f2ff696-0809-4b62-b485-f299b5985434.png)

**Comment by tangying1027** [comment]
官网试了一下正常，看图片填充面积有问题，可以贴一下整个代码复现。
