### ISSUE TITLE
钉钉小程序开发F2自定义view，group如何引入，demo中没有提及

### ISSUE THREAD

**Issue by 710800918** [antvis/F2#1531]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-6o11g4)

### Steps to reproduce
官方文档示例中的Apple Watch图表，那里面使用了group，在移植到钉钉小程序的时候，页面空白，也没有任何报错提示。应该是没有识别到group的问题

| Environment | Info |
|---|---|
| f2 | 4.0.25 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
group的使用不需要引入，可以排查一下其他原因。
