### ISSUE TITLE
官方文档/折线图/基础折线图/无障碍 点击之后 图标报错演 示代码报错，请检查 Cannot read properties of undefined (reading 'Chart')

### ISSUE THREAD

**Issue by LinZhanMing** [antvis/F2#1533]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-f2.gitee.io/zh/examples/line/line#aria](https://antv-f2.gitee.io/zh/examples/line/line#aria)

### Steps to reproduce
1、打开 https://antv-f2.gitee.io/zh/examples/line/line#aria
2、出现 演示代码报错，请检查 Cannot read properties of undefined (reading 'Chart')
3、点击其他图表 报一样的错误 ( 在其他页面再刷新 就可以了）

![image](https://user-images.githubusercontent.com/60056876/177188572-7fdeff09-a44f-43e2-aead-93165d7092a7.png)
<img width="596" alt="image" src="https://user-images.githubusercontent.com/60056876/177188623-d82453b4-33d1-49ca-b547-3dd4b87478d2.png">

| Environment | Info |
|---|---|
| f2 | 4.0.25 |
| System | macos 10.14.5 |
| Browser | Microsoft Edge 103.0.1264.44 |

---
我在firefox下测试，报错变成了 演示代码报错，请检查 _f.default is undefined

**Comment by tangying1027** [comment]
可以看看最新官网地址，应该没有这个问题～
https://f2.antv.vision/zh/examples/line/line#pan
