### ISSUE TITLE
图例过多时能滚动吗？

### ISSUE THREAD

**Issue by ll929** [antvis/f2#154]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问图例过多时能滚动吗？

**Comment by simaQ** [comment]
目前默认的图例是不支持的，但是你可以使用 html 自定义图例。通过 `chart.getLegendItems()` 获取图例的内容，https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_getLegendItems
