### ISSUE TITLE
能否支持用 options 来配置（Support with options）

### ISSUE THREAD

**Issue by Lizhooh** [antvis/F2#1545]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

有这样一个需求：用户可以动态设置图表的配置。

类似 echart 支持 options 配置图表一样。
目前我们自己做了动态 options 转成成 JSX 组件的一层，希望官方可以出支持 options。

---
There is such a requirement: the user can dynamically set the configuration of the chart.

Similar to echart supports options configuration chart.
At present, we have made dynamic options into a layer of JSX components, and hope that the official can support options.

### What does the proposed API look like?
类似这样使用：

Use like this:

```jsx
const options = {
  axis: [{ // 多个时为数组，单个时为对象
    field: 'date',
    tickCount: 3,
    style: {
      label: { align: 'between' },
    },
  }, {
    field: 'date',
    tickCount: 5,
  }],
  line: {
    x: 'date',
    y: 'value'
  },
  tooltip: {}
}

<Canvas context={context} pixelRatio={window.devicePixelRatio} options={options}>
```

**Comment by tangying1027** [comment]
暂不支持
