### ISSUE TITLE
4.0时代g2和f2的融合

### ISSUE THREAD

**Issue by Aaron0502** [antvis/F2#1546]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
移动、pc图表组件两套代码

### What does the proposed API look like?
https://zhuanlan.zhihu.com/p/110989450，文章中所畅想的4.0时代

**Comment by Aaron0502** [comment]
[https://zhuanlan.zhihu.com/p/110989450](https://zhuanlan.zhihu.com/p/110989450%EF%BC%8C%E6%96%87%E7%AB%A0%E4%B8%AD%E6%89%80%E7%95%85%E6%83%B3%E7%9A%844.0%E6%97%B6%E4%BB%A3)

**Comment by tangying1027** [comment]
因为差异过大，暂时还是会两套代码发展～
