### ISSUE TITLE
uni-app中使用antv/f2，雷达图是否有对应label的点击事件

### ISSUE THREAD

**Issue by Leomemory** [antvis/F2#1547]
- **F2 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodeSandbox Link**:

**Comment by tangying1027** [comment]
不知道这边的label具体指什么？
如果是axis上的label的话，暂时没有开口子。
如果是自定义的标注 guide ，5.x版本支持事件，可以关注。

**Comment by Leomemory** [comment]
> 不知道这边的label具体指什么？ 如果是axis上的label的话，暂时没有开口子。 如果是自定义的标注 guide ，5.x版本支持事件，可以关注。

对的，是axis上的label。如果没有它对应的点击事件的话，是否有类似的方法可监听此label的触发事件呢？
