### ISSUE TITLE
分组柱状图 interval-select 只能高亮单个数据？

### ISSUE THREAD

**Issue by lazyXjw** [antvis/F2#1549]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
分组柱状图 一组有两个以上柱状图，选中是只有第一个高亮其余未高亮

### What does the proposed API look like?
是否支持整组高亮

**Comment by lazyXjw** [comment]
selectStyle
类型：Object
默认值：{fillOpacity: 1}
用于设置被选中柱子的显示样式。
分组时只设置了 单个柱子的样式

**Comment by tangying1027** [comment]
我这边试了一下没什么问题，是整组的样式改变，下面是我建的codesandbox的例子。
https://codesandbox.io/s/cranky-goldwasser-8o08do
