### ISSUE TITLE
能否支持多种数据格式

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#155]
* **F2 Version**: 3.1.10
* **Platform**: macOS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1.  能否支持二维数组格式的数据
2. 当有多条曲线时，能否使用以下的数据格式
```
[
{
   date: 1991,
   data10: 1,
   data20:2,
   data30: 3
},
{
   date: 1992,
   data10: 2,
   data20:3,
   data30: 4
}
...
]
```

**Comment by ZiQiangWang** [comment]
二维数据的通过实验，可以支持，只要通过下标访问就行，剩下的问题二，还未解决

**Comment by simaQ** [comment]
当有多条曲线时，你需要将你的数据处理成下面的格式，将 data10, data20, data30 字段展开

```js
[
  { date: 1991, type: 'data10', value: 1 },
  { date: 1991, type: 'data20', value: 2 },
  { date: 1991, type: 'data30', value: 3 },
  { date: 1992, type: 'data10', value: 2 },
  { date: 1992, type: 'data20', value: 3 },
  { date: 1992, type: 'data30', value: 4 }
]
```

展开之后，通过图形语法，将 type 映射至 color 图形属性即可（即用颜色对数据进行分组）；

```js
chart.area().position('date*value').color('type');
```

**Comment by ZiQiangWang** [comment]
@simaQ 这种方式需要做额外的处理，F2能否支持dataset的处理方式。
另外，我尝试使用两个line来绘制，但是出现两个y轴，这种使用方式貌似i不符合当前的场景

**Comment by simaQ** [comment]
1. 目前可以直接使用 dataset 的，只是在传入 chart 的时候，注意传入 dv.rows. 数据处理后的结果存储于 dv.rows，详见 API: https://antv.alipay.com/zh-cn/g2/3.x/api/data-set.html#_dv.rows

```js
chart.source(dv.rows)
```

2. 如果你使用 两个 line 来绘制，如下，因为两条线的 y 轴字段不同，我们默认会分别为两个字段绘制 Y 轴。这个是我们的默认逻辑，这时候你可以将右侧的 Y 轴隐藏，chart.axis('y1', false)

```js
chart.line().position('x*y1');
chart.line().position('x*y2');
```

**Comment by ZiQiangWang** [comment]
明白了，多谢你啦
