### ISSUE TITLE
请问能否支持 TSX？目前在 TypeScript 项目中无法正常使用

### ISSUE THREAD

**Issue by richex-cn** [antvis/F2#1551]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
支持 TypeScript

### What does the proposed API look like?

按照官方提供的示例，改成 tsx 无法通过 ts 检查：

![Snipaste_2022-08-01_09-35-52](https://user-images.githubusercontent.com/25103518/182056262-beab7b9c-567e-4f33-987c-fa91b2477d9a.png)

且安装并配置相关依赖后，项目中原有的 Vue 文件也出现提示：

![Snipaste_2022-08-01_09-38-38](https://user-images.githubusercontent.com/25103518/182056384-29099d61-80af-47e1-a9c0-0e9280ec010c.png)

**Comment by lolarun** [comment]
请参考[和 React 同时使用时，TS 类型报错](https://antv-f2.gitee.io/zh/docs/tutorial/question/with-react-typescript)。
