### ISSUE TITLE
F2支持条形图柱子的最大值和最小值设置吗

### ISSUE THREAD

**Issue by cherrybiu** [antvis/F2#1552]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以自定义条形图的最大最小宽度

### What does the proposed API look like?
可以通过和G2一样设置minColumnWidth 和 maxColumnWidth 属性来控制柱形图的最宽和最窄值

**Comment by tangying1027** [comment]
在 chart 中定义scale的min 和 max
https://f2.antv.vision/zh/docs/tutorial/scale
