### ISSUE TITLE
请在文档中补充<Tooltip/>组件的api属性

### ISSUE THREAD

**Issue by lovesL** [antvis/F2#1561]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我想改提示信息的内容，我在文档中未找到任何关于此组件有哪些API

### What does the proposed API look like?
期望尽快补全

**Comment by tangying1027** [comment]
已补充
https://github.com/antvis/F2/pull/1619
