### ISSUE TITLE
tooltip气泡箭头

### ISSUE THREAD

**Issue by lazyXjw** [antvis/F2#1563]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2-v3.antv.vision/zh/examples/line/line#smooth](https://f2-v3.antv.vision/zh/examples/line/line#smooth)

### Steps to reproduce
chart.tooltip({
  offsetX:100,
  showCrosshairs: true
});

| Environment | Info |
|---|---|
| f2 | 3.4.2 |
| System | - |
| Browser | - |

---
偏移后。气泡箭头位置不对 如何设置气泡箭头 未见文档描述

**Comment by lazyXjw** [comment]
![image](https://user-images.githubusercontent.com/34739183/184275744-3adaea40-3f62-458d-8f4b-3e3118b6016c.png)

另外贴边时若给了tooltip背景圆角， 圆角与箭头处会有缺口

**Comment by lazyXjw** [comment]
![image](https://user-images.githubusercontent.com/34739183/184279807-9dad6ccc-4cfb-405b-8c3f-accbf8f77559.png)

**Comment by tangying1027** [comment]
3.x版本未暴露箭头的修改，因为3.x版本暂不维护,暂时可能只有两种方案。

1.custom
2.在onchage里面拿到箭头的group， 再进行transform 

可以尝试一下
