### ISSUE TITLE
【建议】TooltipView nameStyle valueStyle 能够自定义覆盖 text

### ISSUE THREAD

**Issue by fegg** [antvis/F2#1577]
- **F2 Version**: "4.0.27"
- **Platform**: 微信小程序内嵌 H5
- **Mini Showcase(like screenshots)**:
![20220831-215700](https://user-images.githubusercontent.com/4156879/187696349-aa1eb591-5b2f-4fc9-8b8f-f1e8802118eb.jpeg)

- **CodeSandbox Link**:

源码中目前是 text 属性直接覆盖 `nameStyle` 和 `valueStyle`，但是这样会丢失 text 外部自定义的能力，建议放开，以外部 `nameStyle` 和 `valueStyle` 来覆盖组件内部默认的实现

> 文件地址：packages/f2/src/components/tooltip/tooltipView.tsx

```jsx
 <group
  style={{
    display: 'flex',
    flexDirection: 'row',
  }}
>
  <text
    attrs={{
      ...defaultStyle.nameStyle,
      ...nameStyle,
      text: value ? `${name}${joinString}` : name,
    }}
  />
  <text
    attrs={{
      ...defaultStyle.valueStyle,
      ...valueStyle,
      text: value,
    }}
  />
</group>
```

**Comment by tangying1027** [comment]
最新版本的 f2 添加了  customText  支持自定义 text 了
