### ISSUE TITLE
关于F2中柱状图的交互问题。

### ISSUE THREAD

**Issue by LynnHg** [antvis/F2#1581]
- **F2 Version**: 3.8.11
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodeSandbox Link**:

你好，首先很感谢你们的工作，这是一个很棒的可视化库。

我在使用过程中遇到了一点问题，希望能得到解决：
功能描述：
 1. 柱状图可选中每一根柱子，
 2. 同一珠子选中后再次点击不可取消选中
 3. 当柱子对应的数据为空时不可选中

我的核心实现代码如下：
```
chart.interaction('interval-select', { 
        startEvent: 'tap',
        cancelable: false, // 选中后是否允许取消
        mode: 'shape', 
}
```
这样做能满足上面所有功能1、2和3。
<img width="322" alt="image" src="https://user-images.githubusercontent.com/18587596/188392047-77ca2061-7b7c-4a5c-8e7f-f8ef7d3a8463.png">
但是当我点击空白区域时，问题出现了，所有的柱子都被选中，这不是我期望的。期望的是当点击空白区域，应该什么都不做。
<img width="353" alt="image" src="https://user-images.githubusercontent.com/18587596/188392525-4318cd64-0ae2-4b4b-9749-49d27100b501.png">

于是我修改我的代码，将`mode`设置为`range`：
```
 chart.interaction('interval-select', { 
        startEvent: 'tap',
        cancelable: false, // 选中后是否允许取消
        mode: 'range',
}
```
当我选中一根柱子，再点击空白区域，它不会发生任何事情，这满足了我的需求。但是它不能满足功能3（这也符合预期，因为根据文档说明只要集中点落在该柱子的一定 x 方向范围内都会触发选中交互）：
<img width="320" alt="image" src="https://user-images.githubusercontent.com/18587596/188393095-fdecd031-5a66-450a-988f-f1137fc3d7ea.png">

诉求：当`mode`设置为`shape`时，希望能像`mode`设置为`range`那样，点击空白区域任何事情都不发生。

**Comment by tangying1027** [comment]
shape的模式其实是符合功能的，就是点击空白的处理不同。但这点是这边定义的交互规范。
只能通过自定义interaction来实现 https://f2-v3.antv.vision/zh/docs/api/interaction。
可以参考interaction中shape模式的源码，修改 点击空白部分的逻辑就好。
