### ISSUE TITLE
x轴文字过长，rotate 会使文字被截断

### ISSUE THREAD

**Issue by wenpengfei** [antvis/F2#1583]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-awjd1d?file=index.js](https://stackblitz.com/edit/react-awjd1d?file=index.js)

### Steps to reproduce
https://stackblitz.com/edit/react-awjd1d?file=index.js

| Environment | Info |
|---|---|
| f2 | 4.0.28 |
| System | - |
| Browser | - |

**Comment by wenpengfei** [comment]
![image](https://user-images.githubusercontent.com/2166610/188529868-fc5cf6f8-fd81-4b9c-8950-85a86bab881a.png)

**Comment by tangying1027** [comment]
需要手动调整 padding，这边没办法自动调整哈。

<Canvas context={context} pixelRatio={window.devicePixelRatio} theme={{
        padding: 20
}}>
