### ISSUE TITLE
移动端taro框架开发H5，使用rem模式，字体显示太小

### ISSUE THREAD

**Issue by zhouzyc** [antvis/F2#1586]
请问下这个怎么调整坐标轴字体显示大小，没看见有相关参数
![WX20220908-112928@2x](https://user-images.githubusercontent.com/18420689/189027989-b60d0ac0-7269-47a5-8a9b-a91536f4ecbe.png)

### Steps to reproduce

| Environment | Info |
|---|---|
| f2 | 4.0.29 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
可以传入 theme参数，在里面指定字体大小。
详情可参考源码：
packages/f2/src/theme.ts
packages/f2/src/canvas/index.ts
