### ISSUE TITLE
关闭图表动画导致图表文本不显示问题

### ISSUE THREAD

**Issue by LynnHg** [antvis/F2#1588]
- **F2 Version**: 3.8.11
- **Platform**: mac

- **Mini Showcase(like screenshots)**:
这里提供一个可复现的demo代码：
```js
const yAxis = 'sales';
const xAxis = 'month';

const data = [{
  month: '1月',
  sales: '',
  a:  2,
}, {
  month: '2月',
  sales: 6000,
}, {
  month: '3月',
  sales: 6000,
}, {
  month: '4月',
  sales: 8000,
}, 
{
  month: '5月',
  sales: 3061.43,
}, {
  month: '7月',
  sales: 100000,
}];

const chart = new F2.Chart({
  id: 'bills-chart',
  pixelRatio: window.devicePixelRatio,
  padding: ['auto', 0, 'auto', 0],
});

this.chart = chart;

chart.source(data, {
  [yAxis]: {
    type: 'linear',
  }
});

// 坐标轴配置
chart.axis(yAxis, false);
chart.axis(xAxis, {
  fontSize: 60,
})

chart.tooltip(false);

chart.interval().position([xAxis, yAxis]).size(12)

chart.render();

// 绘制柱状图文本
const canvas = chart.get('canvas');
const group = canvas.addGroup();
data.forEach((obj) => {
  const point = chart.getPosition(obj);
  const textShape = group.addShape('text', {
    attrs: {
      x: point.x,
      y: point.y - 5,
      text: obj[yAxis],
      textAlign: 'center',
      textBaseline: 'bottom',
      fill: '#FA8C16',
      fillOpacity: 0.5,
      fontWeight: 500,
    },
  });;
});
```
正常显示如下：
<img width="365" alt="image" src="https://user-images.githubusercontent.com/18587596/189519535-a3abbec6-9bf5-49af-891d-c36019d84695.png">

但是当我配置: `animate: false`来关闭图表动画，我的图表文本信息没有了：
https://f2-v3.antv.vision/zh/docs/api/chart/chart#animate
<img width="264" alt="image" src="https://user-images.githubusercontent.com/18587596/189519669-96ac849e-e950-43e7-91a1-2ef7e794e73b.png">

```
const chart = new F2.Chart({
    id: 'bills-chart',
    pixelRatio: window.devicePixelRatio,
    padding: ['auto', 0, 'auto', 0],
    animate: false,
});
```
<img width="319" alt="image" src="https://user-images.githubusercontent.com/18587596/189519643-502fc327-bebb-4281-816e-6540b1950483.png">

**Comment by LynnHg** [comment]
> 推荐使用 guide 去添加标注。
好的，非常感谢。
另外有个问题，假若使用 guide 去添加标注话，如是点击交互要去修改选中的柱子对应的标注文本等样式，应该要如何去操作呢。

**Comment by LynnHg** [comment]
> 推荐使用 guide 去添加标注。

感谢大佬，按照guide方法去添加确实可以了

**Comment by tangying1027** [comment]
> > 推荐使用 guide 去添加标注。
> > 好的，非常感谢。
> > 另外有个问题，假若使用 guide 去添加标注话，如是点击交互要去修改选中的柱子对应的标注文本等样式，应该要如何去操作呢。

应该可以根据返回的实例，做样式的修改。

**Comment by LynnHg** [comment]
> > > 推荐使用 guide 去添加标注。
> > > 好的，非常感谢。
> > > 另外有个问题，假若使用 guide 去添加标注话，如是点击交互要去修改选中的柱子对应的标注文本等样式，应该要如何去操作呢。
> 
> 应该可以根据返回的实例，做样式的修改。

确实可以的，感谢
