### ISSUE TITLE
f2 支持 图表x轴内容过多时，左右滑动吗

### ISSUE THREAD

**Issue by LiJingss** [antvis/f2#159]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
是这种么？

![pan](https://user-images.githubusercontent.com/6628666/41697740-ce092bf6-754c-11e8-9fbc-75fc446c9561.gif)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6628666/41697745-d1d49cf2-754c-11e8-863d-4d96fcfae800.gif)


是的话，支持的，可以使用我们新鲜推出的 F2 3.2.0 beta 版本： https://github.com/antvis/f2/issues/165。 更多例子：[交互 demo](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_%E5%9B%BE%E8%A1%A8%E4%BA%A4%E4%BA%92)
