### ISSUE TITLE
Tooltip的background.fillStyle对背景的箭头不生效

### ISSUE THREAD

**Issue by miaowwwww** [antvis/F2#1593]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-forked-o1qim6)

### Steps to reproduce
直接点击柱状图 item

| Environment | Info |
|---|---|
| f2 | 4.0.29 |
| System | - |
| Browser | - |

---
![image](https://user-images.githubusercontent.com/17811091/190104136-e71feec7-b8db-47bd-a4a8-55362d936c22.png)

顺便给tootip加个min-width的属性吧

**Comment by tangying1027** [comment]
属性为background.fill

<Tooltip  background={{fill: 'red'}}/>
