### ISSUE TITLE
3.7.8版本运行npm run build-es 打包出错

### ISSUE THREAD

**Issue by Michael-py001** [antvis/F2#1597]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/F2/tree/3.x](https://github.com/antvis/F2/tree/3.x)

### Steps to reproduce
在3.7.8版本npm install 后，运行npm run build-es出现以下信息：
```
> rm -rf es && BABEL_ENV=esm babel src --out-dir es

'BABEL_ENV' is not recognized as an internal or external command,
operable program or batch file.

```
请问我该如何正常运行打包？

| Environment | Info |
|---|---|
| f2 | 3.7.8 |
| System | win10 |
| Browser | - |

**Comment by tangying1027** [comment]
可能依赖包安装问题，如果你是在最外层跑npm insatll的话，是不是没有跑npm run bootstrap（详见reamde）。
试了一下3.8.11版本，在外层执行yarn，yarn run build 是可以执行的。
