### ISSUE TITLE
Tooltip doesn't seem to work with 3.8.11

### ISSUE THREAD

**Issue by markusand** [antvis/F2#1601]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/vue-qvryw2](https://stackblitz.com/edit/vue-qvryw2)

### Steps to reproduce
Open the demo and see multiple charts where tooltips are not appearing

| Environment | Info |
|---|---|
| f2 | 3.8.11 |
| System | - |
| Browser | - |

---
I'm creating a Vue 3 component that uses F2 v3.8.11 under the hood. There's not way to make tooltips work. I copied many code from documentation examples, current demo contains just one of them. Also legend interactivity seems not to work properly either.

**Comment by tangying1027** [comment]
官网示例示是可以的，https://f2-v3.antv.vision/zh/examples/component/tooltip#show
