### ISSUE TITLE
柱状图坐标系label没有找到旋转属性

### ISSUE THREAD

**Issue by ZhangLinkang** [antvis/F2#1604]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
3.x都有旋转设置，4.x没旋转设置，导致标题过长会出现覆盖显示的情况

### What does the proposed API look like?
加上一个旋转属性，设置角度

**Comment by tangying1027** [comment]
有旋转属性哈。
 label: {
                rotate: -Math.PI / 2,
}

**Comment by wangQingAi** [comment]
加了这个属性就会覆盖原先的样式吗，我加了旋转之后label样式没有了🤔

> 有旋转属性哈。 label: { rotate: -Math.PI / 2, }
