### ISSUE TITLE
多组柱形+折线图，使用不同position渲染，tooltip不居中

### ISSUE THREAD

**Issue by cherrybiu** [antvis/F2#1607]
在使用多组柱形图+折线图的展示的时候，如果线和点的渲染指标和柱形图的不一致，就会导致图形的tooltip不居中，试了官方的demo也是这样，请问是什么原因呢？
现象：
![image](https://user-images.githubusercontent.com/26567876/191536170-f2ebc1b5-439c-408c-bf15-c1b03f2aa9ce.png)

大概是这个样子，tooltip的指示线始终不居中的

**Comment by cherrybiu** [comment]
{
  name: 'London',
  月份: 'Jan.',
  月均降雨量: 18.9,
  lineValue: 12,
}, {
  name: 'London',
  月份: 'Feb.',
  月均降雨量: 28.8,
  lineValue: 2
}, {
  name: 'London',
  月份: 'Mar.',
  月均降雨量: 39.3,
  lineValue: 4
},
{
  name: 'aa',
  月份: 'Jan.',
  月均降雨量: 12.9,
  lineValue: 12
}, {
  name: 'aa',
  月份: 'Feb.',
  月均降雨量: 28.8,
  lineValue: 2
}, {
  name: 'aa',
  月份: 'Mar.',
  月均降雨量: 39.3,
  lineValue: 4
}

具体数据

**Comment by lhiro** [comment]
同样问题，也没有参数可以调整。。。

**Comment by tangying1027** [comment]
多图的tooltip没办法知道是想指柱状还是折线。可以试试把tooltip返回的实例 .translate(x, y)一下

**Comment by lhiro** [comment]
> 多图的tooltip没办法知道是想指柱状还是折线。可以试试把tooltip返回的实例 .translate(x, y)一下

请问vue3 怎么获取tooltip的实例呢
