### ISSUE TITLE
平移柱状图多个渐变报错：error in parsing gradient string, please check if there are any extra whitespaces.

### ISSUE THREAD

**Issue by lhiro** [antvis/F2#1608]
### Reproduction link
[https://vue-ddxicb.stackblitz.io](https://vue-ddxicb.stackblitz.io)

### Steps to reproduce
打开demo，打开console即能看到

| Environment | Info |
|---|---|
| f2 | 3.8.9 |
| System | windows11 |
| Browser | chrome |

---
这里有没有捕获错误的方法，目前是能实现需求，但是开发时报错会导致chrome console直接挂掉，io输出太多

**Comment by tangying1027** [comment]
这个就是捕获了错误，然后console.log出来。我 debug了一下应该是你输入的格式有问题。canvas实例的报错。输入的格式 color
: "l(0) 0:#f7565a 1:#ff999d"，多了个空格

**Comment by lhiro** [comment]
渐变色就是要空格的饿

**Comment by xdmrpgy** [comment]
对啊，就是按文档里面的格式，有空格，报一堆错。。

**Comment by tangying1027** [comment]
> 渐变色就是要空格的饿
是有空格，但是你输入的还多了一个空格。可以帮我上面的输入看看。color
: "l(0) 0:#f7565a 1:#ff999d"

**Comment by tangying1027** [comment]
> 对啊，就是按文档里面的格式，有空格，报一堆错。。

可能文档那边复制出来格式有问题，可以拿我上面的试试

**Comment by xdmrpgy** [comment]
用的3.8.12版本，拿你上面那个试也不行。
```
// 让柱状图的宽度适配不同的屏幕尺寸
const barWidth = 34 * (window.innerWidth / 360)
 // Step 3：创建图形语法，绘制柱状图 date 映射至 x 轴， credit 映射至 y 轴
chart.interval().position('date*credit').color('l(0) 0:#f7565a 1:#ff999d').size(barWidth)
```
![1](https://user-images.githubusercontent.com/11405666/208370505-fb8fe0cc-0a1d-4b55-b513-df2e9b160d14.png)
