### ISSUE TITLE
在vue3使用Shape报错

### ISSUE THREAD

**Issue by lhiro** [antvis/F2#1613]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-vue-forked-y2n8f6?file=/src/App.vue)

### Steps to reproduce
官网例子：https://f2.antv.vision/zh/examples/component/shape#shape
运行报错：Cannot read properties of null (reading 'transformFrom')

| Environment | Info |
|---|---|
| f2 | 4.0.21 |
| System | windows11 |
| Browser | chrome |

**Comment by tangying1027** [comment]
官网的没有报错，不知道vue那边您是怎么写的，可以试试vue-f2 
https://f2.antv.vision/zh/docs/tutorial/vue
