### ISSUE TITLE
PC端scrollbar平移失效

### ISSUE THREAD

**Issue by jiaodingding** [antvis/F2#1616]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ffhz.test.xdf.cn/ydyk/tuesday/mainpage/test](https://ffhz.test.xdf.cn/ydyk/tuesday/mainpage/test)

### Steps to reproduce
在vue2项目中，antv/f2@4.0.31 scrollbar组件平移失效，但是在移动端可以

| Environment | Info |
|---|---|
| f2 | 4.0.31 |
| System | - |
| Browser | - |

**Comment by jiaodingding** [comment]
请不要在意Reproduction link

**Comment by jiaodingding** [comment]
`<template>
  <div class="report">
    <canvas id="mountNode" />
  </div>
</template>

<script>
  import { Canvas, Chart, Line, Point, Axis, ScrollBar, Tooltip } from '@antv/f2/es/index'
  export default {
    name: 'report',
    components: {
      Viewa: Viewa
    },
    mounted() {
      this.testF22()
    },
    methods: {
      testF22() {
        const context = document.getElementById('mountNode').getContext('2d')

        const props =
        fetch('https://gw.alipayobjects.com/os/antfincdn/Jpuku6k%24q%24/linear-pan.json')
          .then((res) => res.json())
          .then((data) => {
            const { props } = (
            <Canvas context={context} animate={false} pixelRatio={window.devicePixelRatio}>
              <Chart data={data}>
              <Tooltip triggerOn={['click']}/>
              <Axis field="release" tickCount={5} nice={false} />
            <Axis field="count" />
              <Line x="release" y="count" />
              <Point x="release" y="count" />
              <ScrollBar mode="x" visible={true} pan={true} range={[0.1, 0.3]}/>
            </Chart>
            </Canvas>
          );
            const chart = new Canvas(props);
            chart.render();
          });
      }
    }
  }
</script>

<style lang="scss" scoped>
  #mountNode {
    width: 600px;
    height: 400px;
  }
</style>
`

**Comment by tangying1027** [comment]
vue项目需要引入 f2-vue中的Canvas，可参考文档 https://f2.antv.vision/zh/docs/tutorial/vue
