### ISSUE TITLE
微信小程序按照官方文档无法正常使用。

### ISSUE THREAD

**Issue by liubaiwu** [antvis/F2#1618]
F2  4.x 版本  根据官网提供的文档地址 https://antv-f2.gitee.io/zh/docs/tutorial/miniprogram进行了配置。无法正常显示。下图是两个主要的配置文件。
![image](https://user-images.githubusercontent.com/7700249/196029143-d4d262ba-d280-45c2-8c2e-8f268b2059be.png)
下面的文件是根据官网的内容复制进去的。
![image](https://user-images.githubusercontent.com/7700249/196029231-52cd21e2-fff7-4030-8ec2-829410874c67.png)
page.js  是没有添加任何内容。

下面是报错的内容
错误提示 TypeError: _this.data.onRender is not a function
![image](https://user-images.githubusercontent.com/7700249/196029431-a24ad87c-86c7-4630-a8f3-31dfb6bc8478.png)

要想必须要配置chart.js  然后在 page.js 里面添加对应的内容才能正常使用。否则 就不行。

因为文档里面说  如果不想在入口文件写 jsx 语法，可以使用在page.js里面添加内容的方式。  目前就是想直接只用jsx的方式。但是一直不行。

**Comment by liubaiwu** [comment]
另外官方提供的demo 里面 去修改 jsx 里面的内容 好像也不起作用。必须是修改 js 里面的代码才能生效。而且官方提供的语法都是
![image](https://user-images.githubusercontent.com/7700249/196029681-c00d4d27-54db-422e-ad58-8b199e998a90.png)
这种语法，如果小程序里面不能支持，开发起来就很费劲

**Comment by tangying1027** [comment]
需要在 pagejs那边 定义  onReady() {}, 去 renderchart。
  onRenderChart() {
      return createElement(Chart, {
        data: data,
      });
    },
可以参考demo  https://github.com/antvis/F2/tree/master/packages/wx/examples

**Comment by tangying1027** [comment]
> 另外官方提供的demo 里面 去修改 jsx 里面的内容 好像也不起作用。必须是修改 js 里面的代码才能生效。而且官方提供的语法都是 ![image](https://user-images.githubusercontent.com/7700249/196029681-c00d4d27-54db-422e-ad58-8b199e998a90.png) 这种语法，如果小程序里面不能支持，开发起来就很费劲


jsx根据文档配置是可以支持的。

**Comment by liubaiwu** [comment]
如何将 案例里面的jsx 的语法转换为js 好像也没有提供相关说明。很费劲啊
