### ISSUE TITLE
能不能填充部分圆？

### ISSUE THREAD

**Issue by icemanpro** [antvis/f2#162]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

能不能做成如下所示？

![-1](https://user-images.githubusercontent.com/1924688/41651302-d52ca024-74b2-11e8-8284-2a5f5b1e631b.png)

**Comment by simaQ** [comment]
可以的，晚上熬夜给你写了个 demo:  [园内占比](https://antv.alipay.com/zh-cn/f2/3.x/demo/other/circle-percent.html)。

原理就是使用自定义 shape，基于柱状图，给柱状图的柱子加一个剪切圆。
