### ISSUE TITLE
legend整体设置居中时，每个子legendItem并没有居中

### ISSUE THREAD

**Issue by Oliver-zg** [antvis/F2#1627]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://render.prefromoffice.alipay.net/p/u/fddh7uM5HX0orGutAQ2Mo](https://render.prefromoffice.alipay.net/p/u/fddh7uM5HX0orGutAQ2Mo)

### Steps to reproduce
legend整体设置居中时，每个子legend并没有完全居中，当canvas很小时，特别明显。原因是子legend是flex-start布局的，并且不可自定义设置，建议透出配置。

| Environment | Info |
|---|---|
| f2 | 4.0.35 |
| System | - |
| Browser | - |

<img width="173" alt="image" src="https://user-images.githubusercontent.com/53323729/197719789-5acc2c42-0930-447b-8075-c15b752737f9.png">

**Comment by tangying1027** [comment]
已修复
