### ISSUE TITLE
【feature】支持 react native 吗

### ISSUE THREAD

**Issue by youngjuning** [antvis/f2#163]

**Comment by dxq613** [comment]
之前有人用 react native 写过，你可以参考使用 node 的方案：https://antv.alipay.com/zh-cn/f2/3.x/tutorial/node-env.html

**Comment by chenshuai2144** [comment]
https://github.com/chenshuai2144/f2-demo
看这里，用的 expo

**Comment by youngjuning** [comment]
谢谢大家的帮助

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/41695270-ef846c52-7540-11e8-82bf-14339469dffb.png)
真的没有办法支持下面三个特性吗

**Comment by simaQ** [comment]
node 是在服务端渲染的，最后以图片方式输出，所以不支持。 react native 的环境我不太清楚，办法或许也有，你可以看下我对小程序适配的思路: https://zhuanlan.zhihu.com/p/35685093，tooltip 组件关键在于事件的触发，动画的关键在于有没有 requestAnimationFrame 或者 setInterval 接口。

**Comment by youngjuning** [comment]
@simaQ 你们团队是vue 栈的吗？有没有小哥哥有兴趣帮你适配一下 rn 呢？我这边rn 水平有限呢

**Comment by simaQ** [comment]
动画应该就支持的吧

**Comment by chenshuai2144** [comment]
代码要自己写哇 大兄弟
我们是开源社区 不是外包社区

**Comment by simaQ** [comment]
我们团队不基于任何栈。RN 如果要支持 F2 全部功能的话，估计的话应该也就是事件这一块，这块我评估下。 vue 的话，目前已经有封装了: https://vux.li/demos/v2/?x-page=github#/components/v-chart/home

**Comment by zhaozhiming** [comment]
所以F2什么时候可以支持RN的事件？有没有计划？谢谢

**Comment by simaQ** [comment]
目前这一块还没有计划，不过欢迎共建

**Comment by luweiCN** [comment]
我看了react-native的那个小demo，他是使用了react-native-canvas，是不是因为这个所以他是node渲染出来的canvas然后直接输出了图片，所以无法支持事件？我看了native-echarts，它们是封装了echarts，我看他们底层是用了WebView来做的，所以很好的支持了事件。我觉得这应该是一个解决方案，我是想做这个feature的支持，但是不知道从哪里入手，希望你们能给点建议

**Comment by youngjuning** [comment]
@simaQ Please ReOpen this feaure issue.

**Comment by youngjuning** [comment]
Thanks Little sister！！

**Comment by fanlide** [comment]
@youngjuning [react-native-f2](https://github.com/fanlide/react-native-f2)已支持其它三项，但有触摸闪动问题

**Comment by luweiCN** [comment]
@fanlide 这个也是用 react-native-canvas 实现的，应该也不支持动画和事件吧

**Comment by simaQ** [comment]
与 #406  重复

**Comment by chj-damon** [comment]
> [chenshuai2144/f2-demo](https://github.com/chenshuai2144/f2-demo)
> 看这里，用的 expo

demo在最新的expo36跑不起来
