### ISSUE TITLE
vue动态数据不更新

### ISSUE THREAD

**Issue by transtone** [antvis/F2#1631]
- **F2 Version**: 4.0.36
- **F2-vue Version** 4.0.17
- **Platform**: windows
- **Mini Showcase(like screenshots)**:
- **CodeSandbox Link**: https://codesandbox.io/s/f2-vue-forked-iso9d7?file=/src/App.vue

vue 下数据更新了，图不更新。

而类似的 react 示例是可以更新的：
https://codesandbox.io/s/fervent-resonance-29rmeb?file=/src/App.tsx:787-802

**Comment by tangying1027** [comment]
我链接点进去是更新的哈

**Comment by transtone** [comment]
> 我链接点进去是更新的哈

呃…… 您仔细看了吗，当数字变化的时候，对应的图没变呀。
