### ISSUE TITLE
4.0版本后，多几何对象的图表，只能展示第一个几何对象的图例，后面的几何对象图例都显示不了，怎么解决有人知道么？

### ISSUE THREAD

**Issue by LrCao** [antvis/F2#1636]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis](https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis)

### Steps to reproduce
双Y轴柱线图，只有第一个几何对象生成了图例，后面的几个对象都没有图例，这个怎么解决？

| Environment | Info |
|---|---|
| f2 | 4.0.37 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
没有做多几何对象自动兼容。
可以尝试 再写一个 legend 组件 传入 marker ，items 等参数去绘制，参考 legend 文档
