### ISSUE TITLE
F2的4.x版本如何实现3.x版本的showTitle和layout为vertical功能

### ISSUE THREAD

**Issue by white-Hang** [antvis/F2#1637]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2-v3.antv.vision/zh/examples/component/tooltip#layout](https://f2-v3.antv.vision/zh/examples/component/tooltip#layout)

### Steps to reproduce
柱形图tooltip如何展示title

| Environment | Info |
|---|---|
| f2 | 4.0.37 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
layout为vertical 可以通过传入style，设置 flex 相关布局就可以实现

**Comment by tangying1027** [comment]
showTitle 已废除，只能通过 showXTip 代替，或者使用 withTooltip函数完全自定义tooltip

**Comment by joker-yjc** [comment]
> layout为vertical 可以通过传入style，设置 flex 相关布局就可以实现
这个怎么设置啊 style设置在tooltip上没有吧

**Comment by joker-yjc** [comment]
toolitip的内容太长了 显示效果不行不能vertical

**Comment by LiuJing1014** [comment]
> toolitip的内容太长了 显示效果不行不能vertical

请问一下，你设置出竖向排列了嘛
