### ISSUE TITLE
Legend过多会把图形挤没，怎么解决

### ISSUE THREAD

**Issue by white-Hang** [antvis/F2#1641]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/basic#base](https://f2.antv.vision/zh/examples/basic#base)

### Steps to reproduce
将legend设置特别多，会导致图形被挤没

| Environment | Info |
|---|---|
| f2 | 4.0.37 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/54161396/200975485-02d97854-432b-4e2f-b2ac-e8b5239c413d.png)

**Comment by tangying1027** [comment]
首先legend过多不太合理。
其次如果真的是需要展示这么多legend的话只能把canvas变大，不然图形绘制不下
