### ISSUE TITLE
分组柱状图，怎么设置每一个柱子的label都在对应柱子上，不然都挤在一起

### ISSUE THREAD

**Issue by white-Hang** [antvis/F2#1643]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/column/dodge#dodge](https://f2.antv.vision/zh/examples/column/dodge#dodge)

### Steps to reproduce
如下图所示
![image](https://user-images.githubusercontent.com/54161396/201272245-831981c9-37b8-4372-b85a-d4bb9e81d4b9.png)

| Environment | Info |
|---|---|
| f2 | 4.0.37 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
可以放一下实现的代码，不然不知道为什么这边是挤在一起的。
另外可以参考 https://f2-v4.antv.vision/zh/examples/component/guide#text 去给label
