### ISSUE TITLE
📣F2 3.2.0 beta 版本试用邀请

### ISSUE THREAD

**Issue by simaQ** [antvis/f2#165]
> 最新 beta 版本： '3.2.0-beta.5'

非常感谢选择 F2 的朋友们，F2 一直在『为**移动端**提供**更生动**、**高交互**图表』的目标上前进着，在  F2 3.2.0 版本中，我们新增加了如下功能，现预向社区试发出试用邀请，如果您有图表交互的需求，欢迎试用 F2 3.2.0 版本~~~ 

## 新增功能点

F2 发布 3.2.0 beta 版本，新增如下功能：

1. 自定义交互机制，支持通用交互行为的封装。详见：[自定义交互](https://antv.alipay.com/zh-cn/f2/3.x/api/custom-interaction.html)
2. 基于交互机制，默认提供以下交互：
    * [饼图选中](https://antv.alipay.com/zh-cn/f2/3.x/api/interaction.html#_%E9%A5%BC%E5%9B%BE%E9%80%89%E4%B8%AD)
![pie-select](https://user-images.githubusercontent.com/6628666/41697452-6d0dcae2-754b-11e8-921c-227ece54c7e0.gif)

    * [柱状图选中交互](https://antv.alipay.com/zh-cn/f2/3.x/api/interaction.html#_%E6%9F%B1%E7%8A%B6%E5%9B%BE%E9%80%89%E4%B8%AD)
![interval-click](https://user-images.githubusercontent.com/6628666/41697454-72ab9b3c-754b-11e8-8669-b1a6a641cd42.gif)

    * [图表平移操作](https://antv.alipay.com/zh-cn/f2/3.x/api/interaction.html#_%E5%B9%B3%E7%A7%BB)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6628666/41697466-82f3a8e0-754b-11e8-8682-6eba142e2191.gif)

    * [图表缩放操作](https://antv.alipay.com/zh-cn/f2/3.x/api/interaction.html#_%E7%BC%A9%E6%94%BE)
![fund](https://user-images.githubusercontent.com/6628666/41697475-904ee022-754b-11e8-885d-fdfd89b77896.gif)

3. 新添加 [Guide.RegionFilter](https://antv.alipay.com/zh-cn/f2/3.x/api/guide.html#_RegionFilter)，图形过滤辅助元素
![undefined](https://cdn.yuque.com/lark/0/2018/png/514/1529037851064-a0ee1806-c3cc-476f-a717-e34533ba0a57.png) 

4. 新增 demo
    * [交互类 demo](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_%E5%9B%BE%E8%A1%A8%E4%BA%A4%E4%BA%92)
    * [健康类图表](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_%E5%81%A5%E5%BA%B7%E7%B1%BB%E5%9B%BE%E8%A1%A8)
    * [Guide 使用](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_Guide-%E4%BD%BF%E7%94%A8)
    * [Legend 使用](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_Legend-%E4%BD%BF%E7%94%A8)
    * [Tooltip 使用](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_Tooltip-%E4%BD%BF%E7%94%A8) 
    * [Axis 使用](https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html#_%E5%9D%90%E6%A0%87%E8%BD%B4-%E4%BD%BF%E7%94%A8) 

## 安装

```bash
npm i @antv/f2@3.2.0-beta.5
```

## 升级说明

* 没有不兼容性变更！
* 没有不兼容性变更！！
* 没有不兼容性变更！！！

## 最后

试用过程中有任何问题以及建议欢迎踊跃提 issue(但是请按照模板提交)，让我们一起将移动端的图表交互做到极致！~~~  谢谢大家!!!!

> PS: 不知道会有多少人看到这个 issue 哈哈哈哈... 尴尬

**Comment by webHello** [comment]
@simaQ 能帮我看一下这个问题吗https://github.com/antvis/f2/issues/166

**Comment by luffyzhao** [comment]
vue.js 引入了交互没有效果呀

**Comment by simaQ** [comment]
如果你是直接 import '@antv/f2' 是不行的，因为处于代码体量的考虑，我默认没有打包进去，你需要自己手动引入。

```js
// 请使用 ^3.2.0-beta.5 版本
import F2 from '@antv/f2';
require('@antv/f2/lib/interaction/');
```

在网站上的文档有详细说明：https://antv.alipay.com/zh-cn/f2/3.x/api/interaction.html#_%E4%BA%A4%E4%BA%92%E8%A1%8C%E4%B8%BA
