### ISSUE TITLE
vue template中使用TextGuide组件报错

### ISSUE THREAD

**Issue by wowsummer** [antvis/F2#1652]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/F2](https://github.com/antvis/F2)

### Steps to reproduce
```base
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'children')
```
```vue
<template>
    <Canvas :pixelRatio="devicePixelRatio">
          <Chart :data="toRaw(chartData)">
              <Axis field="title" />
              <Interval x="title" y="value" />
              <TextGuide
                 v-for="(item, index) in data"
                 :key="index"
                 :records="[item]"
                 content="testtest"
              />
          </Chart>
     </Canvas>
</template>
```

| Environment | Info |
|---|---|
| f2 | 4.0.37 |
| System | mac |
| Browser | google |

**Comment by tangying1027** [comment]
TextGuide的参数不对。不能用 vue 的语法 比如：以及 v-for。
