### ISSUE TITLE
vue根据官方提供的文档，只有第一次更新数据会刷新

### ISSUE THREAD

**Issue by Benjamin369** [antvis/F2#1654]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-vue-forked-vd26ty?file=/src/App.vue)

### Steps to reproduce
运行后，初始化的时候可以根据预设的data1数据进行渲染。

第一次触发定时函数后，数据变更，页面图表根据变化后的数据发生变化。

第二次触发定时函数后，数据变更，页面图表未能根据变更后的数据进行重新渲染。

第三次及后续触发定时函数后，数据变更，页面图表未能根据变更后的数据进行重新渲染。

| Environment | Info |
|---|---|
| f2 | 4.0.38 |
| System | - |
| Browser | - |

**Comment by xiaoai7904** [comment]
同样的问题也遇到了

**Comment by tangying1027** [comment]
感谢提出问题
https://github.com/antvis/F2/pull/1707
已修改，关注一下发版～

**Comment by transtone** [comment]
https://github.com/antvis/F2/issues/1458

https://github.com/antvis/F2/issues/1631
