### ISSUE TITLE
f2+vue+lodash,数据更新后，v2上图型更新了，lodash没更新

### ISSUE THREAD

**Issue by webHello** [antvis/f2#166]
我用npm 安装了lodash，然后引用后。后台获取数据。能画出ring图，但是我动态更新数据后，通过chart.changeData(data)，ring图重绘了，但是lodash并没有，请问这个怎么弄
![image](https://user-images.githubusercontent.com/31120327/41807271-210fb424-76ff-11e8-89ec-b24cec86f8f9.png)
![image](https://user-images.githubusercontent.com/31120327/41807275-310b4eba-76ff-11e8-8f92-f6b93c334b1f.png)
![image](https://user-images.githubusercontent.com/31120327/41807277-39761c7e-76ff-11e8-95d5-7e19ed5c25f8.png)

**Comment by webHello** [comment]
为什么不回我这个问题呀

**Comment by simaQ** [comment]
我看不懂你的问题。

lodash 只是工具类，我们只是用来辅助绘制 demo。。。什么叫 lodash 没有更新...

**Comment by simaQ** [comment]
我想你的意思是 饼图的那些文本为什么没有更新。

如果要更新文本的话，你需要在 chart.changeData() 的时候，重新绘制文本。

**Comment by webHello** [comment]
谢谢你的回答，我的意思是这样的，我chart.changeData()重绘后，图是重绘了，但是文本没有。

**Comment by simaQ** [comment]
demo 已更新，可参考 demo 上是如何更新数据的：https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/labelline-pie.html
