### ISSUE TITLE
F2 支持 GCanvas 么？

### ISSUE THREAD

**Issue by morelearn1990** [antvis/F2#167]
有人说F2支持GCanvas上下文对象的，我试着集成了一下，报错提示 GCanvas not supported yet 。现阶段是不支持 GCanvas 么？

**Comment by morelearn1990** [comment]
像F2 的支付宝小程序版本一样 mock 一个measureText api 。然后直接把 gcanvasjs 里面 enable 生成的 canvas 对象传给 el 就可以了，但是渲染没有网页流畅,且没有手势交互。估计需要做一些处理

**Comment by morelearn1990** [comment]
我再研究一下

**Comment by cileLV** [comment]
创建chart传入context没有成功绘制图表，关键代码如下：
  <gcanvas ref="canvas_holder" id="mychar" ></gcanvas>

var GCanvas = require('weex-gcanvas')
const F2 = require('@antv/f2')

 var ref = this.$refs.canvas_holder
    ref = GCanvas.start(ref)
    let context = ref.getContext('2d')
 const chart = new F2.Chart({
      context: context,
      id: 'myChart'
    })

测试绘制一个矩形框，在Android端能正常显示，但是绘制的图表不能显示

**Comment by cileLV** [comment]
你好，可以详细说一下是如何实现的吗？gcanvas.js中只看到有start(el)会返回一个canvas，我尝试把start()返回的canvas传给el，没能成功绘制图表
  var ref = this.$refs.canvas_holder
    ref = GCanvas.start(ref)

  const chart = new F2.Chart({
      el: ref
    })

**Comment by morelearn1990** [comment]
import { enable, WeexBridge, Image as GImage } from "gcanvas.js";

var ref = this.$refs.canvas_holder
let gcanvasRef = enable(ref, {bridge: WeexBridge });
let chart = new F2.Chart({
    el: gcanvasRef
});

**Comment by cileLV** [comment]
请问你的"gcanvas.js"文件是从哪儿来的，我这边是根据https://github.com/alibaba/GCanvas#examples这个例子，将GCanvas/GCanvas/js/src/的所有文件拷到项目下，使用其中的index.js文件
import { enable, WeexBridge, Image as GImage } from '../src/index.js'
其他都跟你给的示例代码一样，还是不能渲染图表，
new F2.Chart({
el: gcanvasRef
});
这块代码报错，查看f2.js源码，是 _initCanvas() 中new Canvas()抛异常

**Comment by morelearn1990** [comment]
https://jsplayground.taobao.org/album?name=Graphics  这儿有示例."gcanvas.js"使用 npm install gcanvas.js

**Comment by morelearn1990** [comment]
基于之前的一些讨论，做了个简单的封装，水平有限，有些问题还没有解决。
https://github.com/morelearn1990/F2-gcanvas-wrapper

**Comment by simaQ** [comment]
恩，好的，这个问题我会跟进的

**Comment by lyle-luan** [comment]
在 weex 中集成 F2仍然是`GCanvas not supported yet`

安装 gcanvas：`npm install gcanvas.js`
安装 f2：`npm install @antv/f2`

代码：
```
<template>
  <div class="wrapper">
    <text>it is ok</text>
    <gcanvas ref="canvas_holder" style="width:750px;height:400px;"></gcanvas>
  </div>
</template>
<script>
import F2 from '@antv/f2'
import {enable, WeexBridge} from 'gcanvas.js'

export default {
  name: 'App',
  data () {
    return {
      data: [{
        time: '2016-08-08 00:00:00',
        tem: 10
      }, {
        time: '2016-08-08 00:10:00',
        tem: 22
      }]
    }
  },
  methods: {
    renderNativeF2 () {
      let ref = this.$refs.canvas_holder
      let gcanvasRef = enable(ref, {bridge: WeexBridge})
      const chart = new F2.Chart({
        el: gcanvasRef,
        width:750,
        height:400
      })

      chart.source(this.data)
      chart.interval().position('time*tem').color('genre')
      chart.render()
    }
  },
  mounted: function () {
    this.renderNativeF2()
  }
}
</script>
```

**Comment by chenzefeng09** [comment]
> 在 weex 中集成 F2仍然是`GCanvas not supported yet`
> 
> 安装 gcanvas：`npm install gcanvas.js`
> 安装 f2：`npm install @antv/f2`
> 
> 代码：
> 
> ```
> <template>
>   <div class="wrapper">
>     <text>it is ok</text>
>     <gcanvas ref="canvas_holder" style="width:750px;height:400px;"></gcanvas>
>   </div>
> </template>
> <script>
> import F2 from '@antv/f2'
> import {enable, WeexBridge} from 'gcanvas.js'
> 
> export default {
>   name: 'App',
>   data () {
>     return {
>       data: [{
>         time: '2016-08-08 00:00:00',
>         tem: 10
>       }, {
>         time: '2016-08-08 00:10:00',
>         tem: 22
>       }]
>     }
>   },
>   methods: {
>     renderNativeF2 () {
>       let ref = this.$refs.canvas_holder
>       let gcanvasRef = enable(ref, {bridge: WeexBridge})
>       const chart = new F2.Chart({
>         el: gcanvasRef,
>         width:750,
>         height:400
>       })
> 
>       chart.source(this.data)
>       chart.interval().position('time*tem').color('genre')
>       chart.render()
>     }
>   },
>   mounted: function () {
>     this.renderNativeF2()
>   }
> }
> </script>
> ```

看下这个例子有没有帮助https://github.com/or0fun/weex-gcanvas

**Comment by lyle-luan** [comment]
[or0fun/weex-gcanvas](https://github.com/or0fun/weex-gcanvas)
移植了这个库的代码，现在能显示出来图表。
沿着这个路线按照我们的需求定制化图表，看有没有问题。

**Comment by lyle-luan** [comment]
[参考这篇文章](https://segmentfault.com/a/1190000015418640)和or0fun/weex-gcanvas基本是一样的。
参照两位大神的做法，可以成功画出图形，但是在iOS 中要使用 0.18.* 的 WeexSDK，不然图表分辨率会不正常。我使用的0.18.0.3。完美。

**Comment by LiXinLeLe** [comment]
> [or0fun/weex-gcanvas](https://github.com/or0fun/weex-gcanvas)
> 移植了这个库的代码，现在能显示出来图表。
> 沿着这个路线按照我们的需求定制化图表，看有没有问题。

你好, 请问一下你的 f2 是什么版本的 , 我按这个试发现 F2.Util.measureText 这个是 只读属性, 修改不了..

**Comment by KaelInvoker** [comment]
您好，参考上面的方案支持f2最新版本么? f2最新版本已经4.0了
