### ISSUE TITLE
我要画一个双y轴的柱形图，我要怎么做呢？两条柱子会覆盖在一起啊

### ISSUE THREAD

**Issue by chenfengjuan** [antvis/f2#169]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
是什么场景下需要双 Y 轴柱状图？个人是不建议双 Y 轴的，尤其是两条 Y 轴的数据范围不同的情况下。

分组柱状图不能解决问题么？

![image](https://user-images.githubusercontent.com/6628666/41832764-0408d612-7880-11e8-8232-37c1e201f6c9.png)

**Comment by chenfengjuan** [comment]
比如说左侧y轴数据的比例尺很大，如果分组显示，数量级小的系列的数据就看不到了，所以我需要把数据较小的列映射到右边的y轴，这样数量级小的这个系列也可以很好的展示啦。
目前F2有办法做到吗

**Comment by simaQ** [comment]
恩，明白你的意思。要做也是可以的，使用自定义 shape，将柱子分别往左或者往右偏移下。

Demo：https://codepen.io/Sima/pen/gKjMZo
