### ISSUE TITLE
饼图 getPosition 获取的坐标有问题

### ISSUE THREAD

**Issue by yjj5855** [antvis/f2#17]
获取的坐标 都相对起始角度的坐标 这个应该是bug吧？还是说要开发者自己去算？

http://runjs.cn/code/p7fbxymn

**Comment by iNahooNya** [comment]
您好，

因为目前的环(饼)图并不是直接通过柱状图( interval )，而是通过层叠柱状图 ` .adjust('stack') `来实现的。
举例来说

如果数据是` [ 3 , 5 , 7 , 9 ] `
因此如果要获取对应区域在圆弧上终点的正确位置，
需要以 `[ 3 , 3+5 , 3+5+7 , 3+5+7+9 ]` 来调用 `getPosition()` 才能得到。

相应的，如果需要各段中点位置，则需要 `[ 3/2 , 3 + 5/2 , 3+5+7/2 , 3+5+7+9/2  ]` 来获取

这方面体验确实不够好。

**Comment by yjj5855** [comment]
好的 了解了
