### ISSUE TITLE
【F2】The jump link of the two buttons on the home page is incorrect

### ISSUE THREAD

**Issue by lorcannn** [antvis/F2#1702]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh](https://f2.antv.vision/zh)

### Steps to reproduce
see this screenshot
![1673317474808-20230110_101222](https://user-images.githubusercontent.com/56643497/211447756-521e88de-696b-4e07-a837-fb0cfaae8850.gif)

| Environment | Info |
|---|---|
| f2 | 5.0.14 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
感谢提意见！这两天会修复～

**Comment by tangying1027** [comment]
感谢提意见！这两天会修复～

**Comment by tangying1027** [comment]
https://github.com/antvis/F2/pull/1704/files
