### ISSUE TITLE
折线图怎么连接空数据

### ISSUE THREAD

**Issue by hyelimwu** [antvis/f2#171]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![1529913097 1](https://user-images.githubusercontent.com/23385561/41837317-b565697a-788f-11e8-88d2-cdbcc0ada676.jpg)
```
var data = [{
  day: '周一',
  value: 300
}, {
  day: '周二',
  value: 400
}, {
  day: '周三',
  value: null
}, {
  day: '周四',
  value: 500
}, {
  day: '周五',
  value: 490
}, {
  day: '周六',
  value: 600
}, {
  day: '周日',
  value: 900
}];
```

**Comment by simaQ** [comment]
这个需要开放配置参数。我给你加下

**Comment by hyelimwu** [comment]
赞！
