### ISSUE TITLE
Shape标签的animation的iterations的infinity无效

### ISSUE THREAD

**Issue by cdx111** [antvis/F2#1716]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/purple-sound-08e0fh?file=/index.jsx:368-378)

### Steps to reproduce
animation的iterations属性设置infinity无效，期望可以无限循环执行动画

| Environment | Info |
|---|---|
| f2 | 5.0.14 |
| System | - |
| Browser | - |

**Comment by tangying1027** [comment]
iterations: Infinity
I 为大写

**Comment by cdx111** [comment]
> iterations: Infinity I 为大写

可以看看我demo，里面是大写

**Comment by tangying1027** [comment]
> > iterations: Infinity I 为大写
> 
> 可以看看我demo，里面是大写

不是字符串 Infinity。可以贴到f2 官网里面试试，codesandbox确实好像有问题。本地也是没问题的

**Comment by cdx111** [comment]
> 

thank you, Set Infinity constant able to work.
