### ISSUE TITLE
微信小程序使用f2-wx时环形图中间文字不显示

### ISSUE THREAD

**Issue by SoySauceJYZ** [antvis/F2#1740]
我参考图表示例 https://f2.antv.antgroup.com/zh/examples/pie/donut/#donut 在小程序端实现
jsx代码如下：

import { Chart, Interval, Legend } from '@antv/f2';
const Text = (props, context) => {
  const { coord } = props;
  const { center } = coord;
  return (
    <group
      style={{
        display: 'flex',
        left: center.x,
        top: center.y - context.px2hd('30px'),
        width: '100px',
      }}
    >
      <text
        style={{
          text: '总资产',
          fill: '#000',
          textAlign: 'center',
        }}
      />
      <text
        style={{
          marginTop: '10px',
          text: '100.33亿元',
          fill: '#000',
          textAlign: 'center',
        }}
      />
    </group>
  );
};

export default (props) => {
  const {
    // 环形图数据 列表 { 'name': 环形图分类名, percent: 百分比 }
    data
  } = props;

  data.forEach(element => {
    element.ica = 'ica'
  });

  return (
    <Chart
      data={data}
      coord={{
        type: 'polar',
        transposed: true,
        innerRadius: 0.6,
        radius: 1,
      }}
    >
      <Interval
        x="ica"
        y="percent"
        adjust="stack"
        color={{
          field: 'name',
        }}
        selection={{
          triggerOn: 'touchstart',
          selectedStyle: (record) => {
            const { yMax, yMin } = record;
            return {
              r: yMax + yMax * 0.1,
              r0: yMin + yMax * 0.1,
            };
          },
        }}
      />
      <Legend
        position="right"
        itemFormatter={(val, name) => {
          return name;
        }}
      />
      <Text />
    </Chart>
  );
};

编译后的js代码
import { Chart, Interval, Legend } from '@antv/f2';
import { jsx as _jsx } from "@antv/f2/jsx-runtime";
import { jsxs as _jsxs } from "@antv/f2/jsx-runtime";
const Text = (props, context) => {
  const {
    coord
  } = props;
  const {
    center
  } = coord;
  return _jsxs("group", {
    style: {
      display: 'flex',
      left: center.x,
      top: center.y - context.px2hd('30px'),
      width: '100px'
    },
    children: [_jsx("text", {
      style: {
        text: '总资产',
        fill: '#000',
        textAlign: 'center'
      }
    }), _jsx("text", {
      style: {
        marginTop: '10px',
        text: '100.33亿元',
        fill: '#000',
        textAlign: 'center'
      }
    })]
  });
};
export default (props => {
  const {
    // 环形图数据 列表 { 'name': 环形图分类名, percent: 百分比 }
    data,
    // 长按环形图中部分数据时的事件触发的函数
    selectedFunction
  } = props;
  data.forEach(element => {
    element.ica = 'ica';
  });
  return _jsxs(Chart, {
    data: data,
    coord: {
      type: 'polar',
      transposed: true,
      innerRadius: 0.6,
      radius: 1
    },
    children: [_jsx(Interval, {
      x: "ica",
      y: "percent",
      adjust: "stack",
      color: {
        field: 'name'
      },
      selection: {
        triggerOn: 'touchstart',
        selectedStyle: record => {
          const {
            yMax,
            yMin
          } = record;
          selectedFunction(record);
          return {
            r: yMax + yMax * 0.1,
            r0: yMin + yMax * 0.1
          };
        }
      }
    }), _jsx(Legend, {
      position: "right",
      itemFormatter: (val, name) => {
        return name;
      }
    }), _jsx(Text, {})]
  });
});

环形图和图例正常展示，但Text的内容（group和text标签未展示出来）
同时我发现文档中  Interval 的 selection 的 triggerOn 配置  click 时点击事件没有触发，但配置未touchstart触发了点击事件，文档中只有 click | touch 两个枚举

**Comment by zengyue** [comment]
用的是哪个版本？

**Comment by SoySauceJYZ** [comment]
用的以下版本  
"dependencies": {
    "@antv/f2": "^4.0.41",
    "@antv/f2-wx": "^4.0.41",
  },
