### ISSUE TITLE
区间面积图+折线图

### ISSUE THREAD

**Issue by hyelimwu** [antvis/f2#175]
* **F2 Version**: 3.1.13
* **Platform**:
* **Mini Showcase(like screenshots)**:  ![picture](https://user-images.githubusercontent.com/23385561/42074636-aa21c618-7b9f-11e8-895b-7ca9cbe462a5.png)
* **CodePen Link**: https://codepen.io/Hyelim/pen/gKZbMw

```
chart.area({
    connectNulls: true
}).position('time*temperature');

chart.line({
    connectNulls: true
}).position('time*value');
```
出现双Y轴之后，通过设置source最小值最大值，可以强行让两Y轴的显示区间相同，
但是如果出现一些特殊值的时候，就会出现超过规定区域的情况。
请问有没有更好的解决方法？

**Comment by simaQ** [comment]
emmmmmmmmmmmmmm...

这个问题的话，可以在绘制图表前，先求出 temperature 和 value 各自的最大最小值，然后取这四个值最大的区间作为 temperature 和 value 的 min 和 max

```js
let temperatureMax; // temperature 最大值
let temperatureMin; // temperature 最小值
let valueMax; // value 最大值
let valueMin; // value 最小值

chart.scale({
  temperature: {
    min: Math.min(valueMin, temperatureMin),
    max: Math.max(valueMax, temperatureMax)
  },
  value: {
    min: Math.min(valueMin, temperatureMin),
    max: Math.max(valueMax, temperatureMax)
  }
});


```

**Comment by hyelimwu** [comment]
哦吼，原来如此。
![2e2bb44543a982263b7826a08682b9014890ebe8](https://user-images.githubusercontent.com/23385561/42075665-8e7ea53e-7ba4-11e8-9eab-72d4f33587cf.jpg)
