### ISSUE TITLE
API文档访问不了

### ISSUE THREAD

**Issue by GeSnowBoy** [antvis/F2#1750]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/](https://f2.antv.vision/)

### Steps to reproduce
https://f2.antv.vision/

| Environment | Info |
|---|---|
| f2 | 5.0.16 |
| System | v1 |
| Browser | 所有 |

---
官方 https://f2.antv.vision/  访问不了
![image](https://user-images.githubusercontent.com/17561864/223945381-788d774a-8012-4ccf-98d3-f2eae4abaccf.png)

**Comment by tangying1027** [comment]
最新的官网地址是  https://f2.antv.antgroup.com/
