### ISSUE TITLE
Many document links cannot be opened

### ISSUE THREAD

**Issue by noyobo** [antvis/F2#1755]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/1292082/224923412-5927eb49-151c-4c11-b194-9745ea08be21.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1292082/224923627-0a62cdd0-ff52-4bb4-a219-5695573553b0.png">

**Comment by tangying1027** [comment]
latest website： https://f2.antv.antgroup.com/
