### ISSUE TITLE
tooltip如何隐藏主体，然后显示xtip和ytip？

### ISSUE THREAD

**Issue by cdx111** [antvis/F2#1764]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
f2教程不一致

### What does the proposed API look like?
希望实现xtip和ytip
![image](https://user-images.githubusercontent.com/39432333/227171761-82477521-6d3e-4e4a-ae71-c45d448cec46.png)

**Comment by cdx111** [comment]
我找不到相关的文档，但是我找到了showXtip和showYtip，关于主体我要如何隐藏？

**Comment by tangying1027** [comment]
目前没有主体隐藏，只显示xtip和ytip的api

可以自定义 withTooltip 或者试试把主体里面的样式透明度置0

**Comment by cdx111** [comment]
后面我使用空custom，可以隐藏主体
