### ISSUE TITLE
f2分组柱状图 文本显示堆叠

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#178]
用f2做小程序分组柱状图，要求文本显示在柱状图顶部，但是文本重叠。代码如下

datas.map(function (obj) {
          chart.guide().text({
            position: [obj.yAxis, obj.xAxis],
            content: obj.xAxis,
            offsetX: 8
          });
        });

**Comment by simaQ** [comment]
在分组柱状图中使用 guide 绘制文本的话，确实会出现这种问题。 文本标注插件已经在我们的开发计划中了哦。

现在你可以采用自定义 shape 来解决这个问题，这里是 demo: https://codepen.io/Sima/pen/JvpQeG?editors=1010

**Comment by luowei1991** [comment]
利用自定义的shape可以显示顶部文本，但是柱状图没有渲染出来，￣□￣｜｜

**Comment by luowei1991** [comment]
文本可以渲染出来，但是柱状图不显示了。代码如下：  opts: {
      onInit: function initChart(canvas, width, height, datas) { // 使用 F2 绘制图表
        let chart = new F2.Chart({
          el: canvas,
          width,
          height
        });
      
        chart.source(datas.reverse(), {
          xAxis:{
            formatter: params => {
              var newParamsName = ""; // 最终拼接成的字符串
              var paramsNameNumber = params.length; // 实际标签的字数
              var provideNumber = 4; // 每行能显示的字的个数
              var rowNumber = Math.ceil(paramsNameNumber / provideNumber); // 换行的话，需要显示几行，向上取整
              /**
               * 判断标签的个数是否大于规定的个数， 如果大于，则进行换行处理 如果不大于，即等于或小于，就返回原标签
               */
              // 条件等同于rowNumber>1
              if (paramsNameNumber > provideNumber) {
                /** 循环每一行,p表示行 */
                for (var p = 0; p < rowNumber; p++) {
                  var tempStr = ""; // 表示每一次截取的字符串
                  var start = p * provideNumber; // 开始截取的位置
                  var end = start + provideNumber; // 结束截取的位置
                  // 此处特殊处理最后一行的索引值
                  if (p == rowNumber - 1) {
                    // 最后一次不换行
                    tempStr = params.substring(start, paramsNameNumber);
                  } else {
                    // 每一次拼接字符串并换行
                    tempStr = params.substring(start, end) + "\n";
                  }
                  newParamsName += tempStr; // 最终拼成的字符串
                }
              } else {
                // 将旧标签的值赋给新标签
                newParamsName = params;
              }
              //将最终的字符串返回
              return newParamsName;
            }
          },
          value: {
            tickInterval: 750
          }
        });
        chart.coord({
          transposed: true
        });
        // chart.tooltip({
        //   showItemMarker: false
        // });
        chart.legend(false); //所有的图例都不显示
        chart.axis('yAxis', {
          line: F2.Global._defaultAxis.line,
          grid: null
        });
        chart.axis('xAxis', {
          line: null,
          grid: F2.Global._defaultAxis.grid,
          label: function label(text, index, total) {
            var textCfg = {};
            if (index === 0) {
              textCfg.textAlign = 'left';
            } else if (index === total - 1) {
              textCfg.textAlign = 'right';
            }
            return textCfg;
          }
        });
    
 
        chart.legend(false); //所有的图例都不显示
     //   绘制文本

        // datas.map(function (obj) {
        //   chart.guide().text({
        //     position: [obj.yAxis, obj.xAxis],
        //     content: obj.xAxis,
        //     offsetX: 8,
        //     textAlign: 'center',
        //     textBaseline: 'middle'
        //   });
        // });
        
        let Shape = F2.Shape;
        let Util = F2.Util;
        Shape.registerShape('interval', 'text', {
          draw: function draw(cfg, container) {
            var points = this.parsePoints(cfg.points);
            // points 顶点的顺序
            // 1 ---- 2
            // |      |
            // 0 ---- 3
            var style = {
              fill: cfg.color,
              z: true // 需要闭合
            };
            const intervalShape = container.addShape('rect', {
              attrs: Util.mix({
                x: points[1].x,
                y: points[1].y,
                width: points[2].x - points[1].x,
                height: points[0].y - points[1].y
              }, style)
            });

            var origin = cfg.origin._origin; // 获取对应的原始数据记录
            var textShape = container.addShape('text', {
              zIndex: 1,
              attrs: {
                x: (points[1].x + points[2].x) / 2,
                y: points[1].y - 5, // 往上偏移 5 像素
                text: origin['xAxis'],
                fill: '#808080',
                textAlign: 'center',
                textBaseline: 'bottom'
              }
            });
            container.sort();
            return [intervalShape, textShape];
          }
        });
        chart.interval().position('yAxis*xAxis').color('name', ['#4C84FF', '#00CC98']).shape('text').adjust({
          type: 'dodge',
          marginRatio: 1 / 32
        }).size(10);
   
        chart.render();
        return chart;
      }
    }

**Comment by luowei1991** [comment]
你看看是哪里的问题

**Comment by simaQ** [comment]
恩，我知道了，是因为你的是分组条形图，而不是分组柱状图，我改了下自定义 shape 的方法（用更通用的方法绘制矩形）：https://codepen.io/Sima/pen/JvpQeG?editors=1010  你看下吧

**Comment by luowei1991** [comment]
非常感谢，可以啦。Thanks♪(･ω･)ﾉ

**Comment by luowei1991** [comment]
还有个问题，顶部文本可以自适应居中吗？代码如下：
      var textShape = container.addShape('text', {
              zIndex: 1,
              attrs: {
                x: (points[1].x + points[2].x) / 2 - 7 ,
                y: points[1].y - 5, // 往上偏移 5 像素
                text: origin['yAxis'],
                fill: '#808080',
                textAlign: 'start',
                textBaseline: 'middle'

              }
            });

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/42554505-bdbc3268-8517-11e8-94ed-af6a2c28c9d8.png)
你看我圈的顶部值是不居中的

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/42554553-e5d93b92-8517-11e8-81cf-cbf09183b979.png)
我的意思就是想让这个值自动居中在柱状图的顶部

**Comment by simaQ** [comment]
这个不能自适应，需要自己配置。你在添加文本图形的时候，这之下 textAlign: 'center' 属性即可： 

![image](https://user-images.githubusercontent.com/6628666/42554581-08f219e6-8518-11e8-9e50-b733a5c3b6d7.png)

**Comment by luowei1991** [comment]
嗯嗯，可以了，谢谢啦！
