### ISSUE TITLE
f2, 是不是没有提供 tooltip。

### ISSUE THREAD

**Issue by Cccccl** [antvis/f2#18]
在移动端引入f2,想要实现点击图表某个点位，出现对应的提示框要怎么实现。

**Comment by iNahooNya** [comment]
你好~

F2 没有内置 tooltip 模块，如果想在图表上显示，需要自己实现。
在官方文档中提供了一个简单的实践，可以参考下面的链接。

[常见问题 - 如何显示tooltips](https://antv.alipay.com/zh-cn/f2/3.x/tutorial/faq.html#_4.-如何显示-tooltip)
