### ISSUE TITLE
【雷达图】部分文字区域难以触发tooltip的事件

### ISSUE THREAD

**Issue by LLawlight** [antvis/f2#182]
* **F2 Version**: 3.1.13
* **Platform**: web/h5
* **Mini Showcase**:
用官方的[雷达面积图](http://antv.alipay.com/zh-cn/f2/3.x/demo/radar/area.html)的例子：
![image](https://user-images.githubusercontent.com/17525377/42440174-84a3279c-8397-11e8-80ee-80fa91548ef9.png)
在点击Design和Test两个文字的时候出发不了tooltip的onChange事件，在点击左右两边的文字是很容易触发的（虽然也不是整个文字区域都能触发），可能跟点击区域有关。正上方和正下方的文字需要非常靠近图表顶点才能触发。

测试如下：
正上方和正下方的文字触发面积最小，然后是正左和正右，右上、右下、左上、左下的触发范围最大。

**Comment by simaQ** [comment]
在内部我做了判断，如果触发区域不在绘图区域内就不会展示 tooltip。在 3.1.14-beta.1 版本里面加了 alwaysShow 属性，你设置下应该就可以了。

```js
chart.tooltip({
  alwaysShow: true
})
```

**Comment by LLawlight** [comment]
@simaQ 设置之后，文字区域确实都可以触发事件了。

还有一个问题，当我关闭tooltip之后，点击文字区域有没有什么事件可以抛出呢。

比如有个需求，不需要展示详细的信息，只需要点击x轴上不同的值(对应的整个文字区域)去触发相应的动作(页面跳转、提示之类的)。

目前有方法可以实现吗？

**Comment by simaQ** [comment]
如果是这样的话，可以直接监听 canvas 的事件，可以参考 faq 上的这个问题 ： [怎么跟图表交互
](https://antv.alipay.com/zh-cn/f2/3.x/tutorial/faq.html#_3.-%E6%80%8E%E4%B9%88%E8%B7%9F%E5%9B%BE%E8%A1%A8%E4%BA%A4%E4%BA%92)

**Comment by LLawlight** [comment]
好的，一直以来都是这样去实现的，所以问问有没有更便捷的方法。

其他暂时没问题了，这个issue的问题也测试成功，可以关闭了。

辛苦啦～
