### ISSUE TITLE
官方文档里环形进度条中间文字位置不对

### ISSUE THREAD

**Issue by hurricane1998** [antvis/F2#1828]
v4版本的文档，饼图->环形图->环形进度条
官方文档地址：https://f2-v4.antv.vision/zh/examples/pie/donut#progress-bar
修改TextGuide标签里的x并不能把文字设置在中间（或许是我设置的值不对）

![image](https://github.com/antvis/F2/assets/56187561/9df365a5-3bf1-49fb-be2d-ed30c4fecd87)

**Comment by zengyue** [comment]
record 是数据点的位置，通过 style 来设置
