### ISSUE TITLE
React ts Bar 简单柱图报错

### ISSUE THREAD

**Issue by mshmyw** [antvis/F2#1833]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/happy-moore-6vkhsw?file=/src/App.tsx:15,37-15,44)

### Steps to reproduce
运行上述例子即可看到tsx报错
不知是否不支持 react ts
![image](https://github.com/antvis/F2/assets/6376429/6db95696-8416-44f8-b2dc-12682c6d291d)

| Environment | Info |
|---|---|
| f2 | 5.0.30 |
| System | macos |
| Browser | chrome |

**Comment by mshmyw** [comment]
是官网文档错了吗？
安装@antv/f2-react 才能跑通。
话说 @antv/f-react 与 @antv/f2-react 二者什么区别？
![image](https://github.com/antvis/F2/assets/6376429/d9b62d33-702d-4e14-b8f1-4dc08d8be848)

**Comment by zengyue** [comment]
确认下使用的版本，是否是一致的

**Comment by zengyue** [comment]
> 话说 @antv/f-react 与 @antv/f2-react 二者什么区别？

没有区分
