### ISSUE TITLE
非jsx/tsx环境下如何使用group、circle、text 等图形标签

### ISSUE THREAD

**Issue by zhuddan** [antvis/F2#1841]
- [ x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些特殊环境下，我不得不放弃jsx/tsx的方式使用F2，但是我无法从 @antv/f2 中引入 group、circle、text 等图形标签 我该怎么做
```ts

   const element = createElement(Chart, {
        data,
        children: [

          createElement('group'), // 我该怎么做？

          createElement(Axis, { field: 'time' }),
          createElement(Axis, { field: 'val' }),
          createElement(Interval, {
            x: 'time',
            y: 'val',
            color: COLOR_GREEN,
            selection: {
              selectedStyle: {
                fillOpacity: 1,
              },
              unSelectedStyle: {
                fillOpacity: 0.4,
              },
            },
            size: 10,
            style: {
              radius() {
                return [40, 40, 40, 40];
              },
            },
          }),
          createElement(Legend, {}),
          createElement(Tooltip, {}),
        ],
      });

```

### What does the proposed API look like?
虽然在jsx/tsx的环境下不用导入，但是我当前的环境限制期望可以导出显式地从 @antv/F2 中导出  Group、Circle、Text  等标签，或者提供其他解决方案
```ts

import { Group } from '@antv/f2';

 const element = createElement(Chart, {
        data,
        children: [

          createElement(Group,{

         }), 

          createElement(Axis, { field: 'time' }),
          createElement(Axis, { field: 'val' }),
          createElement(Interval, {
            x: 'time',
            y: 'val',
            color: COLOR_GREEN,
            selection: {
              selectedStyle: {
                fillOpacity: 1,
              },
              unSelectedStyle: {
                fillOpacity: 0.4,
              },
            },
            size: 10,
            style: {
              radius() {
                return [40, 40, 40, 40];
              },
            },
          }),
          createElement(Legend, {}),
          createElement(Tooltip, {}),
        ],
      });

```

**Comment by zengyue** [comment]
是没法编译吗? babel 和 ts 都可以独立编译的，建议使用编译工具，否则写起来还是有点痛苦的

**Comment by zhuddan** [comment]
@zengyue 谢谢你的回复！

 现在的项目是uni-app 的vue3 的 ts 的 alpha 版本，然后这个项目又是很久之前创建的....不知为何tsx编译不了（@dcloudio/uni-app 内部报错），现在就是Group、Circle、Text 等标签这类标签用不了，其他都ok。现在写起来痛苦已经不重要了，就求一个解决方案。

如果不能解决就算了。

ps 尝试过@antv/f2-graphic导入依然无效

```ts
import { Shape } from '@antv/f2-graphic';
createElement(Shape.Text)
```

**Comment by zengyue** [comment]
https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3AG8kEAacAYQAsBDY8AX3ADMC8twBySBgDsiAN2DsATLwDcaNAB56TEgBMGRBgF5SAbQC6LAHxpw4eQElhAUwIiGAG3D5YGIhjyDNAInggAnl7gwMbywErEhkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.15&externalPlugins=&assumptions=%7B%7D


![image](https://github.com/antvis/F2/assets/1478197/bc8fee10-4174-4c33-acf7-5b6317e8c2cb)

**Comment by zhuddan** [comment]
@zengyue  谢谢，虽然最终尝试过各种方式都没有解决，之后换taro算了

ps, 使用 babeljs 转成jsx函数渲染 group 和 text 等元素都不会报错，但是小程序页面上不会渲染。
官网中的一些demo包含了text等元素的情况，在沙盒（stackblitz/codesandbox）中也不会渲染，我尝试过切换版本（5.x和4.x）都不会正常工作，我怀疑原因沙盒是否和我当前的小程序环境，导致的不会渲染。

下面是官网demo, 在官方沙盒上的一些不显示的例子

 1. [图形标签](https://f2.antv.antgroup.com/zh/examples/component/shape/#shape)/[codesandbox](https://codesandbox.io/s/lwuu4p)
 
![image](https://github.com/antvis/F2/assets/32126992/67693f26-12ab-42c4-9563-6dfc35f25fd5)
![image](https://github.com/antvis/F2/assets/32126992/30b7ea25-b424-4201-871e-3601861a25f8)

2. [折线图动态排序](https://f2.antv.antgroup.com/zh/examples/creative/case/#line-race)/[codesandbox](https://codesandbox.io/s/nzfpmk)
这个例子中出来了折线图末端的文字不显示其他都正常

![image](https://github.com/antvis/F2/assets/32126992/0a9fd8c7-b00e-46ee-9e20-e07373dc02c9)
![image](https://github.com/antvis/F2/assets/32126992/76cf12d2-d327-4ed3-ab58-198d35b8c12a)

**Comment by zhuddan** [comment]
好的谢谢
