### ISSUE TITLE
f2饼状图 指标比例相近时 文本绘制不出来

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#185]
截图如下：
![image](https://user-images.githubusercontent.com/19301689/42552408-afaf6112-850e-11e8-8e59-2920cef77c4b.png)
   
代码如下：var text = new F2.G.Shape.Text({
          attrs: {
            x: _side === 'left' ? APPEND_OFFSET : canvasWidth - APPEND_OFFSET,
            y: y,
            fontSize: 12, // 字体大小
            fill: '#808080',
            text: _data.name + '\n' + _data.percent.toFixed(2)+"%",
            textBaseline: 'middle',
            textAlign: _side === 'left' ? 'left' : 'right',
            lineHeight: 16
          },
          origin: _data // [存储原始数据](url)
        });

**Comment by luowei1991** [comment]
求回复啊！ლ(′◉❥◉｀ლ)

**Comment by luowei1991** [comment]
第二个demo是可以绘制出来的，但是样式方面有些挑战极限了。

**Comment by simaQ** [comment]
如果你允许部分重叠，那么可以在判断是否文本重叠的方法适当放松些。其实对于大部分用户来说，是不会察觉到文本是否完全显示的。

**Comment by luowei1991** [comment]
嗯，两个demo我都试下，然后给产品经理看看吧！谢谢啦！你的效率真高哈！

**Comment by simaQ** [comment]
so~~~ 赏个 star 或者留个名，帮助我们维护这个合作项目的列表吧：https://github.com/antvis/f2/issues/111  感谢

**Comment by luowei1991** [comment]
给了，给了，哈哈
