### ISSUE TITLE
钉钉小程序中jsx模版中新增<Legend>报错

### ISSUE THREAD

**Issue by laoxiaokang** [antvis/F2#1853]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-forked-x6dq96?file=/src/index.js)

### Steps to reproduce
可见截图

| Environment | Info |
|---|---|
| f2 | 4.0.48 |
| System | - |
| Browser | - |

**Comment by laoxiaokang** [comment]
![image](https://github.com/antvis/F2/assets/45983816/bacf842d-3dac-4687-ad3f-6060a34b0507)
![image](https://github.com/antvis/F2/assets/45983816/195f7cd4-3b91-4fd7-97ac-15b8c43f5107)
 去掉Legend标签就正常了

**Comment by laoxiaokang** [comment]
另外 使用Tooltip时 会报错
![image](https://github.com/antvis/F2/assets/45983816/261dd4b8-2102-4fb7-bedd-e3afbd77cafa)

**Comment by laoxiaokang** [comment]
版本信息
![image](https://github.com/antvis/F2/assets/45983816/2091e3b2-3df9-40a6-a8f0-d98c4560bc60)

**Comment by zengyue** [comment]
钉钉啊。。钉钉确实没调过

**Comment by zengyue** [comment]
能大致定位到具体的报错位置吗？
