### ISSUE TITLE
多条曲线的图表中Tooltip内容显示异常

### ISSUE THREAD

**Issue by 152056212** [antvis/F2#1864]
- **F2 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodeSandbox Link**:

- F2 Version: 4.0.48
- Platform: 微信小程序
- Mini Showcase(like screenshots):
![image](https://github.com/antvis/F2/assets/27007064/880b2591-7f84-44bd-b673-1ac899c03e1b)

问题总结：Tooltip内容显示异常
具体描述：如图所示，共显示3条曲线，每条曲线分别表示了数据中的systolicValue(收缩压)、relaxationValue(舒张压)、heartRate(心率)，点击tooltip显示出来的内容只有“09 19:34:22:148”

- CodeSandbox Link: https://codesandbox.io/s/f2-reproduction-template-forked-qhtlpf

**Comment by 152056212** [comment]
![image](https://github.com/antvis/F2/assets/27007064/bc7d0f04-9fba-457f-bba6-c6158aa5ed71)

**Comment by tangying1027** [comment]
https://f2.antv.antgroup.com/examples/line/multiple/#series
参考多条折线demo
