### ISSUE TITLE
能否横向铺满，不留边距，改变坐标轴文字位置

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#191]
* **F2 Version**:3.1.13
* **Platform**:mac os
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问能不能把整个图表横向铺满，不留边距，
然后坐标轴的文字显示在内部

**Comment by simaQ** [comment]
来，赏个图，让我更好地明白你想要的效果~~

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/42682629-be82b580-86bd-11e8-9f5f-fff48d558342.png)


这样吗？ demo 地址： https://codepen.io/Sima/pen/jpbWLm

方法是：
1. new Chart 时，将 appendPadding 和 padding 配置为 0 （例子里面我保留了 X 轴的文本空间，只让 Y 轴坐标显示在内部）

```js
const chart = new F2.Chart({
  id: 'mountNode',
  appendPadding: 0, // 不留空隙
  padding: [ 0, 0, 'auto', 0],
  pixelRatio: window.devicePixelRatio
});
```

2. 在 chart.axis 接口中将 Y 轴对应的坐标轴文本的 labelOffset 设置为 0，并且将 textAlign 设置为 start 就可以了。

```js
chart.axis('tem', {
  label: (text, index, total) => {
    const cfg = {
      textAlign: 'start'
    };
    if (index === 0) {
      cfg.textBaseline = 'botom';
    } else if (index === total - 1) {
      cfg.textBaseline = 'top';
    }
    return cfg;
  },
  labelOffset: 0
});
```

**Comment by ZiQiangWang** [comment]
![image](https://user-images.githubusercontent.com/11312811/42682966-93768dac-86be-11e8-83e8-5d578dc11846.png)
非常感谢，我想要的是这个样子的

**Comment by ZiQiangWang** [comment]
没有仔细看文档，真是打扰了
