### ISSUE TITLE
饼图一下变成了方图。

### ISSUE THREAD

**Issue by luffyzhao** [antvis/f2#193]
参数用示例的也是这样。我之前用的3.1.x 升级到3.2.0_bate5后出现了这问题。。

![image](https://user-images.githubusercontent.com/4166371/42811238-a38814f0-89ec-11e8-9d37-3284f408a6ba.png)

**Comment by simaQ** [comment]
请提供下：
1.  环境
2. 可运行代码

我好排查哈~~~

**Comment by simaQ** [comment]
1. 在升级的时候，建议先将原先在 node_modules 安装的 @antv/f2 删除，然后再重新安装。
2. 检查下  

```js
chart.coord('polar', {
  transposed: true
});
```

**Comment by luffyzhao** [comment]
找原因了。我没有 import coord/polar ，不知道 为什么也没报错。。

**Comment by simaQ** [comment]
恩，好的~
