### ISSUE TITLE
折线图横坐标时间数据较多时如何处理

### ISSUE THREAD

**Issue by zzwar2009** [antvis/f2#197]
* **F2 Version**:3.1.14
* **Platform**:ios  iPhone4等
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/zzwar2009/pen/jprQRX

首先谢谢f2团队的图表支持！，我做的是比特币的价格折线图，数据比较大而且（大概120组数据）一天在不同时间有好几组数据如下
![image](https://user-images.githubusercontent.com/2322990/42866790-23d83546-8aa0-11e8-857e-7d253cd43724.png)
然后x轴代码糊在一起，看了文档也没太懂怎么配置，想请教一下

![image](https://user-images.githubusercontent.com/2322990/42867545-7ec35330-8aa2-11e8-87d0-882d177616af.png)

代码如下：
![image](https://user-images.githubusercontent.com/2322990/42866802-2e00f2b0-8aa0-11e8-93dd-ca9566827fc3.png)

**Comment by simaQ** [comment]
谢谢。

这个问题是这样的，你直接将变量名作为 key 值了，应该是将变量名对应的数值作为 key 值，另外 range 只能设置为 0 ~ 1 的数据。你把 chart.source() 那里的代码改成下面的即可：

```js
  chart.source(data, {
    [`${y_label}`]: {
      tickCount: 5,
      min: 0
    },
    [`${x_label}`]: {
      type: 'timeCat',
      mask:"YYYY-MM-DD HH:MM",
      nice:true,
      range: [0, 1], 
      tickCount: 3 // 如果你要根据以上 mask 的根式显示四件，建议使用 3 个就好
    }
  });
```

**Comment by zzwar2009** [comment]
哇 万分感谢 ，相应速度好快啊 ，好幸福的感觉！！！希望你们越做越强大

**Comment by simaQ** [comment]
谢谢
