### ISSUE TITLE
AntV f2必须要给canvas指定画布么，当数据多的时候支持左右滚动么？

### ISSUE THREAD

**Issue by Cui-y** [antvis/f2#198]
My Info：
  F2 Version: v3.1.14
  Platform: 移动端web

My Question：
  当我的数据过多的时候，无法指定给f2 canvas固定宽度，这样就显示不完全，另外如果动态指定canvas宽度，那么虽然能够左右滑动但是纵坐标轴随着滚动就不见了，能不能当数据过多时，坐标轴内的数据可以滚动，而坐标轴固定的。

场景截图
![wechatimg6839](https://user-images.githubusercontent.com/21211512/42920956-f3de81e0-8b4b-11e8-8a10-cad78f5e2a04.png)

**Comment by adow** [comment]
同问这个问题，大数据量的时候，柱状图可以支持滚动吗？
