### ISSUE TITLE
AntV f2 使用交互行为引入相应的行为依旧报错

### ISSUE THREAD

**Issue by Cui-y** [antvis/f2#200]
* **F2 Version**:
![image](https://user-images.githubusercontent.com/21211512/42932901-18aa5506-8b76-11e8-9289-87152c6198e1.png)

* **Platform**: 移动端 Vue

![image](https://user-images.githubusercontent.com/21211512/42932869-037c530a-8b76-11e8-8deb-08cdcc33ebcb.png)

**Comment by Cui-y** [comment]
错误信息如下：
![image](https://user-images.githubusercontent.com/21211512/42932954-355f3eaa-8b76-11e8-9166-f50d60702019.png)

**Comment by simaQ** [comment]
恩，这个问题我们同学也遇到了。你尝试下如下解决方案：

1. 删除 node_modules, 重新安装最新版 beta 版本 F2 3.2.0-beta.8
2. 按需引入的话，全部引用 @antv/f2/lib 下的代码模块，如下：

```js
import F2 from '@antv/f2/lib/index';
require('@antv/f2/lib/interaction/pan');
```

**Comment by Cui-y** [comment]
![image](https://user-images.githubusercontent.com/21211512/42933191-c4c2b5c2-8b76-11e8-95fa-07b99c6c7e59.png)

**Comment by Cui-y** [comment]
@simaQ 好的 ，我试一下 . 我试着输出chart对象，没有行为这个属性方法

**Comment by Cui-y** [comment]
@simaQ  谢谢，昨天已经解决。

**Comment by lt1067066026** [comment]
你好，我在vue里面使用使用
import F2 from '@antv/f2/lib/index';
require('@antv/f2/lib/interaction/pan');
这样引入，解决了'interaction' is not a function这个报错，但是又出来一个新的报错：Ctor is not a constructor"。
你是怎么解决的呀？请教一下
