### ISSUE TITLE
F2 平移交互

### ISSUE THREAD

**Issue by Cui-y** [antvis/f2#201]
F2平移目前只是支持x轴是数字的么，比如人员姓名呢？ 不可以平移么？

**Comment by simaQ** [comment]
应该也是支持的，不过目前貌似在线图上有问题 ... 你稍等下，我跟进下。

**Comment by simaQ** [comment]
可以的，参考这个 demo，需要配合列定义，写了个简单的 demo: 

https://codepen.io/Sima/pen/vayQgo

目前如果是折线图或者区域图的话，需要加一个加一个 sortable: false：

```js
chart.line({
  sortable: false
})
```

**Comment by Cui-y** [comment]
我这边是柱状图，还好，但是视图左右边界的两项柱状图并没有显示完全，而是显示一半，这个文档里有解决方案么？

**Comment by simaQ** [comment]
把 range: [0, 1] 配置删除。

![image](https://user-images.githubusercontent.com/6628666/43003246-6f2581f6-8c5e-11e8-97e0-907e987bc93a.png)

**Comment by Cui-y** [comment]
@simaQ  感谢 ~
