### ISSUE TITLE
x 轴数据过多导致重叠,即使设置字体旋转也没用!可以做成x 轴间隔显示数据吗?或者有其他的办法吗?

### ISSUE THREAD

**Issue by LiangAndJing** [antvis/f2#209]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
可以通过设置 tickCount 的。

```js
chart.source(data, {
  {你的坐标轴对应的字段名}: {
    tickCount: 5
  }
});
```

**Comment by ire-solas** [comment]
尝试了在axis中，设置文本的rotate属性，但文字并没有旋转

**Comment by LiangAndJing** [comment]
me.chart.axis('c', {
        label: {
          rotate: Math.PI / 2,
          textAlign: 'start',
          textBaseline: 'middle',
        }
      });
这个是我的代码,希望对你有帮助!

**Comment by LiangAndJing** [comment]
chart.axis(' date', {
        label: {
          rotate: Math.PI / 3,
          textAlign: 'start',
          textBaseline: 'middle',
        }
      });
这是我的代码,希望对你有帮助

**Comment by ire-solas** [comment]
感谢！参考了你的代码，试了一下，还是不行，可能问题出在其他地方。

**Comment by simaQ** [comment]
建议按照我们的 issue 模板，提供可运行的代码，方便快速帮助你定位到问题哦

**Comment by ire-solas** [comment]
更新库文件之后，rotate属性生效了
