### ISSUE TITLE
F2平移交互中，滑动图表时，手指松开tooltip就消失了

### ISSUE THREAD

**Issue by gg343917542** [antvis/f2#220]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

F2平移交互中，不加上平移交互就没有问题，请问怎么解决？

**Comment by simaQ** [comment]
只这样的，平移交互中 tooltip 的触发手势是 press 长按，长按出现 tooltip，然后来回滑动，手指松开 tooltip 是会消失。

**Comment by gg343917542** [comment]
@simaQ 
我需要的功能是tap时候展示tooltip，这个功能我已经实现了，但还有一个问题是pan时候tooltip又被移除了。如何做到pan的时候tooltip不被移除？

**Comment by simaQ** [comment]
恩，这块我得重新设计下，我将 tooltip 的触发和 pan 耦合了，稍等~~~~

**Comment by simaQ** [comment]
> 如何做到pan的时候tooltip不被移除？

这个问题，可以直接在 onProcess 的这个钩子里面定义：

```js
 onProcess(e) {
      const center = e.center; // 获取当前的坐标
      const position = F2.Util.getRelativePosition(center, chart.get('canvas')); // 转换为画布坐标
      chart.showTooltip(position); // 调用显示 tooltip 的接口
 },
```

**Comment by alianggitok** [comment]
> @simaQ
> 我需要的功能是tap时候展示tooltip，这个功能我已经实现了，但还有一个问题是pan时候tooltip又被移除了。如何做到pan的时候tooltip不被移除？

请问tap的时候如何立即显示tooltip？

**Comment by yleson** [comment]
> @simaQ
> 我需要的功能是tap时候展示tooltip，这个功能我已经实现了，但还有一个问题是pan时候tooltip又被删除了。如何做到pan的时候tooltip不被删除？

求解这个怎么做，pan手势下能做到tap时候展示tooltip
