### ISSUE TITLE
F2平移交互中，拖到最右动态加载数据

### ISSUE THREAD

**Issue by lizhencheng** [antvis/f2#223]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

F2平移交互中，可以实现拖到最右动态加载数据吗，类似滚动加载

**Comment by GuoQichen** [comment]
我也遇到这个需求，但是文档上没有找到对应的api，请问你是如何解决的？

**Comment by simaQ** [comment]
@GuoQichen 参考 https://github.com/antvis/f2/issues/413
