### ISSUE TITLE
使用官方提供的饼图选中交互,选中后调用changeData,交互样式并没有清除

### ISSUE THREAD

**Issue by gg343917542** [antvis/f2#227]
* **F2 Version**:
3.2.0-beta.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

http://jsrun.net/m7gKp/edit

**Comment by simaQ** [comment]
非常感谢反馈！绝对无疑是个 BUG

**Comment by simaQ** [comment]
你好，在 @antv/f2@3.2.0-beta.13  这个版本修复了。
