### ISSUE TITLE
在数据长度为0时，存在脚本错

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#238]
* **F2 Version**: 3.1.19
* **Platform**: mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

提供的data长度为0时，脚本错，是否考虑处理边界情况
![image](https://user-images.githubusercontent.com/11312811/44009913-b0089fec-9ee1-11e8-83fe-9c3103a6c96c.png)

**Comment by simaQ** [comment]
emmmmmm, 是个 bug，这个我在 3.2.0-beta 版本中已经修复了... 哈哈，我先修复下（建议使用 3.2.0-beta.x 版本，这几天我就会发布稳定版的）

**Comment by ZiQiangWang** [comment]
嗯嗯，这个影响不大，我可以规避下
