### ISSUE TITLE
beta版本的tickCount问题

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#240]
* **F2 Version**: 3.2.0-beta.21
* **Platform**: mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在版本3.2.0-beta.21中，设置tickCount=3，但是只显示两个label
![image](https://user-images.githubusercontent.com/11312811/44021790-40b3ff42-9f18-11e8-9164-484e6b711ae2.png)
下图是版本3.1.20的样子
![image](https://user-images.githubusercontent.com/11312811/44021627-dbeb12ee-9f17-11e8-952f-892eb01d9644.png)

**Comment by simaQ** [comment]
恩，这个是因为在 3.2.0 版本里面我们统一了 G2 和 F2 的  [scale](https://github.com/antvis/scale)(负责计算 tickCount 这个模块)，这个我们这两天优化下。

**Comment by ZiQiangWang** [comment]
大佬辛苦

**Comment by simaQ** [comment]
@antv/f2@3.2.0-beta.22
