### ISSUE TITLE
饼图是否有方式设定最小角度

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#242]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

对于有些占很小比例的项，期望有一个最小角度可点击。
除了在外部手动计算的方式，还有其他方法吗

**Comment by simaQ** [comment]
你的意思是想要让占比很小的扇形部分也能够被点击到？

![image](https://user-images.githubusercontent.com/6628666/44066889-66e8e67c-9fa5-11e8-8ccd-aacfedf6be90.png)

**Comment by ZiQiangWang** [comment]
是滴是滴

**Comment by simaQ** [comment]
(⊙o⊙)… 

> 苹果iPhone人机界面指南推荐的最小目标大小为44px宽，44px高。微软的Windows手机用户界面设计和交互设计指南建议一个最低目标尺寸是26px乘以34px。诺基亚的开发者指南建议，目标尺寸应不小于1cm×1cm平方或28×28像素。

这个可触目标的范围太小了... 我的建议是通过设计解决，像这种占比很小的，可以通过绘制一个带线的文本来解决。
![image](https://user-images.githubusercontent.com/6628666/44067064-23aa1538-9fa6-11e8-9638-941030213eae.png)

**Comment by ZiQiangWang** [comment]
因为之前用的echarts，提供了一个minAngle属性，当某一项占比很小时，将其角度设为最小角度，其他项的比例在剩余角度基础上重新分配
![image](https://user-images.githubusercontent.com/11312811/44067126-74cc4e72-9fa6-11e8-9230-29f8a9d7926c.png)

**Comment by simaQ** [comment]
啊咧咧，涨见识了，多谢~~~ 我考虑下 👍

**Comment by ZiQiangWang** [comment]
辛苦大大

**Comment by simaQ** [comment]
经过讨论以及深思熟虑，我们认为 minAngle 这个方案在对于数据的解读上会存在误解，而且在**移动端**，这么小的范围对于点触操作来说基本没有多大意义，可以通过设计的方案解决的（就像我👆说的）。

**Comment by ZiQiangWang** [comment]
试着说服产品和ui。。。

**Comment by dxq613** [comment]
其实你可以伪造占比数据，只是同时要调小所有其他的数据。显示文本的时候再用真实数据展示就可以了。但是这种方式跟可视化的理论冲突很大，不利于用户理解。

**Comment by ZiQiangWang** [comment]
@dxq613 这种方式我也想过，我在支付宝的记账页面看到这种情形，每个扇形区域包含一个图标，并且可点击，这要求了最小角度，所以想着这种方式有没有比较方便的实现方式

**Comment by dxq613** [comment]
可视化解决方案，第一要点是不要引起歧义，特别是在手机的屏幕上，像素太小肯定没法点击到，稍微大点，就会造成歧义。
