### ISSUE TITLE
能否在F2中实现G2类似的渐变填充功能

### ISSUE THREAD

**Issue by dwhdrbdhs** [antvis/f2#243]
* **F2 Version**:3.1.17 
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

F2中若使用canvas生成的线性渐变进行填充，无法满足对每一个值的柱状图内部覆盖全部渐进范围的需求，只可在canvas区域内进行全区域渐变

G2中利用
chart.interval().position('year*sales').style({
    fill: 'l(90) 0:#000000 0.5:#7ec2f3 1:#ff0000'
  });
的方式即可轻松实现。

求靠谱的解决方式 或功能实现

**Comment by simaQ** [comment]
恩，非常理解，这个问题之前 我也考虑到了，目前的渐变方案是对整个画布生效的。这个功能我这周支持一下，稍等哦

**Comment by dwhdrbdhs** [comment]
非常感谢！

**Comment by simaQ** [comment]
3.2.1-beta.1 版本已经支持。使用范式同 G2，但是注意除去颜色之间的空格，其余不要留有任何空格。

```js
fill: 'l(90) 0:#000000 0.5:#7ec2f3 1:#ff0000'
```

**Comment by chaunceym** [comment]
> 恩，非常理解，这个问题之前 我也考虑到了，目前的渐变方案是对整个画布生效的。这个功能我这周支持一下，稍等哦

您好, 渐变色对整个画布生效现在还支持么,  有需求想用到这个
