### ISSUE TITLE
时间类型的平移设置初始范围

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#244]
* **F2 Version**: 3.2.0-beta.21
* **Platform**: mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

这个例子中初始显示全部的数据
http://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/timecat-pinch-pan.html

我想要下面的例子中，初始定位到一个范围的效果
http://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/x-pan.html

但是，timeCat类型没有max和min属性，不知道怎么设置

**Comment by simaQ** [comment]
timeCat 类型本质属于分类类型，需要通过设置 values 来达到初始定位一个范围的效果，可以参考这个例子： https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/steps-pan.html
