### ISSUE TITLE
画柱形图的时候，最左侧和最右侧的数据宽度会突变 ，版本"@antv/f2": "^3.1.16",

### ISSUE THREAD

**Issue by liuyang1106** [antvis/f2#247]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
你好，能提供一个可复现的 demo 么？

**Comment by liuyang1106** [comment]
谢谢你，现在已经解决了，是x轴数据需要String的原因，我填的Number

**Comment by simaQ** [comment]
赞
