### ISSUE TITLE
平移交互中，折线图滑动过程中如果点消失了，连接线也一起消失了，有没有办法让连接线保持？

### ISSUE THREAD

**Issue by justiceti** [antvis/f2#252]
数据点较少时特别明显，导致折线看起来不连续，现在我临时的解决办法是在数据中插入多个点尽量让消失的部分变短，请问有没有更好的解决办法？另外，我看文档有个generatePoints属性，设置过后没有效果，请问这个属性是什么作用？

**Comment by simaQ** [comment]
`generatePoints` 属性是用于计算构成每个图形的关键点的，比如矩形的四个顶点，而线图是不需要的，默认为 false，因为本身每条数据就代表一个点，不需要再设置这个来消耗计算性能。

你的这个问题，可以先提供下使用的版本号，我看下是不是我预想的问题导致的，可是试着升级到 3.2.0 稳定版看看还有么有

**Comment by justiceti** [comment]
解决了，谢谢
