### ISSUE TITLE
pie-select的defaultSelected设置无效

### ISSUE THREAD

**Issue by gg343917542** [antvis/f2#263]
* **F2 Version**:3.2.1-beta.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[https://github.com/antvis/f2/issues/248#issuecomment-414200740](url)
首先非常感谢提供这个feature，但设置后发现无效，后调试代码时发现 selectedShape 返回为null
const selectedShape = self._getSelectedShapeByData(defaultSelected);

**Comment by gg343917542** [comment]
我已经是在chart.render() 后调用的，但发现Util.isObjectValueEqual(shapeData, data)不相等，应该是原始数据跟vue数据不相等的原因，但我传入的defaultSelected也是vue数据，怎么会不相等呢

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/44323998-b3910a00-a486-11e8-9066-aaad9580861a.png)



减少沟通成本

**Comment by gg343917542** [comment]
不好意思，等下我给下demo哈

**Comment by gg343917542** [comment]
https://codepen.io/gg343917542/pen/GXKeQO
@simaQ

**Comment by simaQ** [comment]
啊咧咧，我知道原因了， vue 给每一个记录存放了一个  __ob__ 属性..... 原始数据被修改了... ，稍等下，我纠正下比对策略

**Comment by gg343917542** [comment]
我觉得defaultSelected同时支持索引会比较好吧。。。

**Comment by gg343917542** [comment]
同时发现一个问题，changeData后应该需要一个api来重新设置defaultSelected，不应只在init时候设置

**Comment by simaQ** [comment]
索引值不太靠谱。3.2.1-beta.2 版本修复了，你试一下。

> 同时发现一个问题，changeData后应该需要一个api来重新设置defaultSelected，不应只在init时候设置

这个重新在声明chart.interaction('pie-select') 即可，我们会销毁上一个 interaction 对象，重新创建的

**Comment by gg343917542** [comment]
@simaQ 
好的，非常感谢
