### ISSUE TITLE
请问可以实现柱状图柱体背景透明度设置么?

### ISSUE THREAD

**Issue by ZhangCheng-zh** [antvis/f2#266]
请问有可能实现下图的样式么?
![image](https://user-images.githubusercontent.com/6847409/44389471-86635b00-a55d-11e8-85b2-0f1cf5caf9c3.png)

**Comment by simaQ** [comment]
可以的，参考一些这个 demo: https://codepen.io/Sima/pen/aabXMP

也可以通过自定义 shape 的方法实现
