### ISSUE TITLE
为什么发布了 v3.2.0 又发布 v3.1.21

### ISSUE THREAD

**Issue by yangmingshan** [antvis/f2#267]
看 CHANGELOG v3.2.0 也没有破坏性变更，新的 bug fix 为什么不发布 v3.2.1 呢？

这让我有些混乱，还是 v3.2.0 有破坏性变更？

**Comment by simaQ** [comment]
不好意思 ，因为内部有业务是在 3.1.x 版本使用，由于一些原因还未升级至 3.2，又急着上线，所以先发了 3.1.21。后面肯定是有 3.2 为准的。抱歉！！！

**Comment by yangmingshan** [comment]
@simaQ 所以我是可以安全升级至 3.2 的吧

**Comment by simaQ** [comment]
恩，是的。
