### ISSUE TITLE
小程序端能否实现线条颜色渐变

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#268]
![image](https://user-images.githubusercontent.com/19301689/44437641-a3e00580-a5ed-11e8-84cf-68df9c7e5235.png)
如上图所示，是否可以实现啊

**Comment by simaQ** [comment]
恩，可以的。在 3.2.1-beta.2 版本中内嵌了渐变色的支持。可以直接通过 `.color('l(90) 0:#000 1#333')` 这样的方式传入。

参见小程序 demo: https://github.com/antvis/wx-f2/blob/master/pages/charts/gradient-column/index.js#L31

<img src="https://gw.alipayobjects.com/zos/rmsportal/ElBYXdsTZKFflacOBNtp.png" style="width: 50%;">


> 说明：`l` 表示使用线性渐变，绿色的字体为可变量，由用户自己填写，由一个空格进行间隔。

```js
// example
// 使用渐变色描边，渐变角度为 0，渐变的起始点颜色 #ffffff，中点的渐变色为 #7ec2f3，结束的渐变色为 #1890ff
stroke: 'l(0) 0:#ffffff 0.5:#7ec2f3 1:#1890ff'
```

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/44438777-43ec5d80-a5f3-11e8-85f3-492947e7897b.png)
如上图所示，tooltip显示不对。
代码如下：
  chart.interval().position('xAxis*yAxis').color('l(90) 0:#4C84FF 1:#00CC98').shape('text').adjust({
          type: 'dodge',
          marginRatio: 0 // 设置分组间柱子的间距
        }).size(10);

**Comment by luowei1991** [comment]
还有个问题，怎么将柱状图设置成圆角啊

**Comment by simaQ** [comment]
恩，是用法错误了。你想要绘制的是分组数据，所以 color() 这个方法需要对应具体的字段名。参照这个例子：
https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/dodge-column.html

![image](https://user-images.githubusercontent.com/6628666/44438972-3a172a00-a5f4-11e8-8386-25f9ecde4223.png)


```js
chart.interval().position('xAxis*yAxis')
.color('参与分组的字段名',  [ 颜色数组])
.shape('text')
.adjust({
  type: 'dodge',
  marginRatio: 0 // 设置分组间柱子的间距
})
.size(10);
```

**Comment by simaQ** [comment]
圆角设置方法参照这个例子：https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negetive-dodge-column.html  

![image](https://user-images.githubusercontent.com/6628666/44439015-6a5ec880-a5f4-11e8-9d17-b7b8323106d9.png)


或者直接 

```js
.style({
 radius: 5
})
```

**Comment by luowei1991** [comment]
嗯呢，圆角出来了，但是柱状图上面的数字不见了
以前显示柱状图数字代码：
        chart.interval().position('xAxis*yAxis').color('name', ['#4C84FF', '#00CC98']).shape('text').adjust({
          type: 'dodge',
          marginRatio: 0 // 设置分组间柱子的间距
        }).size(10);
现在设置圆角后不显示柱状图数字代码：
     chart.interval().position('xAxis*yAxis').color('name', ['l(90) 0:#4C84FF 1:#00CC98']).style({
          radius: 5
        }).adjust({
          type: 'dodge',
          marginRatio: 0 // 设置分组间柱子的间距
          }).size(10);
好像style与shape不能兼容啊

**Comment by simaQ** [comment]
如果你参考的是这个例子 https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/dodge-column-with-label.html，在自定义 shape 的时候需要将 style 参数也传入(demo 里面没有传入)，你先参考下这个 demo:
https://codepen.io/Sima/pen/eLmMrx.  官网demo 我这周更新下

```js
Shape.registerShape('interval', 'text', {
  draw: function draw(cfg, container) {
    var points = this.parsePoints(cfg.points);
    // points 顶点的顺序
    // 1 ---- 2
    // |      |
    // 0 ---- 3
    var style = Util.mix({
      fill: cfg.color,
      z: true // 需要闭合
    }, cfg.style); // 传入 style
    var intervalShape = container.addShape('rect', {
      attrs: Util.mix({
        x: points[1].x,
        y: points[1].y,
        width: points[2].x - points[1].x,
        height: points[0].y - points[1].y
      }, style)
    });

    var origin = cfg.origin._origin; // 获取对应的原始数据记录
    var textShape = container.addShape('text', {
      zIndex: 1,
      attrs: {
        x: (points[1].x + points[2].x) / 2,
        y: points[1].y - 5, // 往上偏移 5 像素
        text: origin['月均降雨量'],
        fill: '#808080',
        textAlign: 'center',
        textBaseline: 'bottom',
        fontSize: 10 // 字体大小
      }
    });
    container.sort();
    return [intervalShape, textShape];
  }
});
```

**Comment by luowei1991** [comment]
嗯嗯，好的，搞定了，谢谢啦
