### ISSUE TITLE
单页面内多个实例的情况

### ISSUE THREAD

**Issue by ZhangCheng-zh** [antvis/f2#270]
![wechatworkscreenshot_258478d2-c461-4040-be31-f54292a9aea2](https://user-images.githubusercontent.com/6847409/44449759-9ba1bd80-a621-11e8-84da-4c47f67b22bd.png)
这个页面初始化了两个chart实例,为什么刚载入的时候都正常显示,刷新的时候会不显示?
如果在也页面中打断点,两个实例会分批显示.

**Comment by simaQ** [comment]
你好，能提供简单的可复现 demo 吗？

**Comment by ZhangCheng-zh** [comment]
`    // 渲染图表
    setTimeout(_ => chart.render(), 0)`
加个异步,可以保证多个实例都能展示了
