### ISSUE TITLE
微信小程序 饼图能否可以实现如下图圆角展示

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#272]
![image](https://user-images.githubusercontent.com/19301689/44499261-b1f95900-a6b5-11e8-81d7-ba0f6c76f773.png)
如上图所示，饼图是否可以实现如上图的样式呀

**Comment by simaQ** [comment]
可以通过自定义 shape 自己绘制，但是这种形式的饼图从可视化准确性表达的角度不太推荐。

**Comment by luowei1991** [comment]
具体怎么实现呢，能否附上代码啊

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/44500496-53cf7480-a6bb-11e8-86f4-f36780a1cb60.png)
怎么把这个饼图变成圆角的形式

**Comment by luowei1991** [comment]
好的，三克油！！！
