### ISSUE TITLE
npm @antv/f2雷达图报错

### ISSUE THREAD

**Issue by fffyang** [antvis/F2#275]
我在vue项目中使用F2的雷达图时，_clone和_.values均报错，点击雷达图上的点时触发错发。
<img width="500" alt="image" src="https://user-images.githubusercontent.com/37098927/44513518-2355fd80-a6f0-11e8-88e4-ac13a03a8f7f.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/37098927/44513543-2f41bf80-a6f0-11e8-850f-28e3cb504160.png">

**Comment by fffyang** [comment]
我可能找到原因了，可能是因为我没有引jquery的缘故。我把这两个方法换成js原生的方法就可以了

**Comment by simaQ** [comment]
这个是 [lodash](https://lodash.com/) 的命名空间，你用 JS 原生的方法替换即可。
