### ISSUE TITLE
移动端webview中图表显示模糊,这个是个例么?

### ISSUE THREAD

**Issue by ZhangCheng-zh** [antvis/f2#277]
![image](https://user-images.githubusercontent.com/6847409/44564098-ddeb0c00-a793-11e8-8f69-d4786b6591b8.png)

**Comment by simaQ** [comment]
你设置 pixelRatio 了吗？

**Comment by hy-pillow** [comment]
@simaQ hi，UI 组件封装里（如：React，Vue） 里貌似默认设置成了 1，这个有什么特殊的吗

![Uploading image.png…]()
