### ISSUE TITLE
有没有计划加入time类型呢？

### ISSUE THREAD

**Issue by OPY-bbt** [antvis/f2#278]
time类型也是很常见的类型啊， 为什么在移动端不支持呢

**Comment by simaQ** [comment]
目前没有这个计划呢，虽然理论上说目前应该也是支持的，因为 F2 和 G2 是公用 `@antv/scale` 模块的，但是 F2 内部还需要做一些调整适配一下

**Comment by OPY-bbt** [comment]
ok~ 谢谢
