### ISSUE TITLE
层叠柱状图和折线图一起渲染，怎么破

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#280]
![image](https://user-images.githubusercontent.com/19301689/44635595-3bbc6580-a9d9-11e8-838f-6946b87e0e63.png)
demo中只是实现了柱状图和折线图一起渲染，现在想实现层叠柱状图和折线图一起渲染，有案例吗

**Comment by simaQ** [comment]
demo: https://codepen.io/Sima/pen/djEzME 

具体解释，参见该 issue：https://github.com/antvis/f2/issues/205#issuecomment-413456452

**Comment by luowei1991** [comment]
width, height也是需要手动传入的吧

**Comment by simaQ** [comment]
恩，是的

**Comment by luowei1991** [comment]
这就尴尬了

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/44644095-763bf780-aa05-11e8-974b-4a0a087d6465.png)
真是数据量可能很大，这种情况怎么破呢

**Comment by simaQ** [comment]
恩，这个情况，可以让图表平移，毕竟移动设备的尺寸也就那么大...
