### ISSUE TITLE
请问有办法让X轴线显示在柱状图上面么?

### ISSUE THREAD

**Issue by ZhangCheng-zh** [antvis/f2#284]
![image](https://user-images.githubusercontent.com/6847409/44712354-259acc00-aae3-11e8-940d-a852be82f000.png)

**Comment by simaQ** [comment]
有的

```js
 chart.axis('x 轴对应字段名称', {
     line: {
       top: true 
     }
    });
```

**Comment by ZhangCheng-zh** [comment]
谢谢 为什么api文档里面没找到这个配置项

**Comment by simaQ** [comment]
有的，在 axis 章节中，就是层级描述不清，我的锅。。。 每一个 axis 的属性都支持 top 的配置，我更新下
![image](https://user-images.githubusercontent.com/6628666/44713076-e79ea780-aae4-11e8-882b-48b500b02011.png)
