### ISSUE TITLE
如何定义柱状图的每一根柱子的宽度，我想动态的设置多个项，但是这样每一次获取数据，每一条的宽度都不一致

### ISSUE THREAD

**Issue by xingyuefa** [antvis/f2#289]
如何定义柱状图的每一根柱子的宽度，我想动态的设置多个项，但是这样每一次获取数据，每一条的宽度都不一致，怎么做

**Comment by xingyuefa** [comment]
chart.interval().position('name*ration').size(10);，我这样拿到了柱子的宽度了，但是我没有设置图的height，默认150高，一旦我size设置大了，所有柱子都挤在一起了，怎么办？？？/

**Comment by simaQ** [comment]
.size(10) 的意思是将柱状图的宽度设定为 10 像素，无论图表什么尺寸，都会按照 10 像素渲染。你可以：

1. 不设置 size，我们会根据图表的宽度以及数据的个数自动计算
2. 或者根据你设置 10 时的这个图表当前的宽度计算下比例 ratio = 10 / currentCanvaWidth, 然后根据就可以 .size(ratio*canvasWidth)

**Comment by xingyuefa** [comment]
![image](https://user-images.githubusercontent.com/26361352/44781506-269d2d80-abb7-11e8-82bb-d34d973a620b.png)

举个图吧，我现在的图表是从上往下排列的，高度是动态的，我是想，当行数不一致的情况下保持每条宽度一直，每条之间的上下间距一致，看起来，只是图表的高度变化了，其他没有变化，我该怎么实现这样的效果

**Comment by xingyuefa** [comment]
![image](https://user-images.githubusercontent.com/26361352/44781629-7e3b9900-abb7-11e8-8556-aa1a4445fc76.png)
tiao'shu条数多了的时候是这样的，对比起来，确实行间距不一样，看上去很不舒服，像是两张图

**Comment by simaQ** [comment]
你设置下  `F2.Global.widthRatio.column` 这个参数试试，这是用于设置柱子之间的间距的，默认是 0.5，你加到一写看看，另外 .size() 可不设置。

比如：  `F2.Global.widthRatio.column = 0.75;`

**Comment by xingyuefa** [comment]
那图表的高度可以不设置吗？不设置高度的话好像默认是150高，不知道在我fetch完之后数据多了之后图表会实时检测数据而动态的增加图表的高度吗？因为可能图表高度不变的话，条数多了也会压在里面挤成一坨的，还是说我得把图表的高度也设置为动态的，根据返回数据的length设置动态高度
