### ISSUE TITLE
坐标轴上的label如何换行？

### ISSUE THREAD

**Issue by LLawlight** [antvis/f2#29]
![image](https://user-images.githubusercontent.com/17525377/33718225-a00dcbac-db97-11e7-94b8-df6da11d3a68.png)
如图，一个项目的文字过长就会出现这种现象，请问如何才能换行显示

**Comment by dxq613** [comment]
这个地方会支持 '\n' 的写法，遇到 '\n' 会自动换行，后面的迭代中增加。

**Comment by simaQ** [comment]
3.1 版本支持

**Comment by ye1641893401** [comment]
在微信小程序 \n 失效
