### ISSUE TITLE
我限制了x轴文字每行展示四个数字，为什么tooltip中的title也会换行？？

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#292]
![image](https://user-images.githubusercontent.com/19301689/44825229-3d399800-ac3c-11e8-92cf-d3dfb4cbe275.png)
如图所示问题。

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/44825288-8ab60500-ac3c-11e8-83c7-04b3322062ac.png)
想实现这个堆叠图圆角无缝连接，怎么玩呀

**Comment by simaQ** [comment]
换行这个，你检查下原始诗句中是否含有： '\n'

**Comment by luowei1991** [comment]
是加了‘\n’，如果不加'\n'的话，x轴就不会换行的

**Comment by dxq613** [comment]
建议你不要在原始数据里面加 "\n"，在坐标轴的 label 回调函数里面格式化下文本，这样 tooltip 上就不会换行了。可以参考这个：
https://antv.alipay.com/zh-cn/f2/3.x/demo/component/axis-iconfont.html

**Comment by luowei1991** [comment]
现在发现数据量太大了，想做平移，但是发现没有效果。
参考demo中，平移功能是由这个控制的  chart.interaction('pan');但是没有效果啊
![image](https://user-images.githubusercontent.com/19301689/44833923-25750a80-ac62-11e8-9c82-20f93a117872.png)
