### ISSUE TITLE
贴一个demo的代码，你们试试看嘛，看看问题在哪

### ISSUE THREAD

**Issue by xingyuefa** [antvis/f2#296]
var data = [{
  key: '0%',
  sales: 38
}, {
  key: '10%',
  sales: 52
}, {
  key: '20%',
  sales: 61
}, {
  key: '30%',
  sales: 145
}, {
  key: '40%',
  sales: 48
}, {
  key: '50%',
  sales: 38
}, {
  key: '60%',
  sales: 38
}, {
  key: '70%',
  sales: 38
}];
var chart = new F2.Chart({
  id: 'mountNode',
  pixelRatio: window.devicePixelRatio
});

chart.source(data, {
  sales: {
    tickCount: 5
  }
});
chart.axis('sales', false);
chart.tooltip({
  showItemMarker: false,
  onShow: function onShow(ev) {
    var items = ev.items;
    items[0].name = null;
    items[0].name = items[0].title;
    items[0].value = '¥ ' + items[0].value;
  }
});
// draw the Guide.Text
data.map(function(obj) {
  chart.guide().text({
    position: [obj.key, obj.sales],
    content: obj.sales,
    style: {
      textAlign: 'start'
    },
    offsetY: 0
  });
});

chart.interval().position('key*sales');
chart.render();

试试看guide 的位置还对不对

**Comment by simaQ** [comment]
#### 原因
这是因为我们的 Guide 有一种定位方式： 使用百分比，比如： [ '80%', '100%' ]，而你的原始数据里面恰恰好就是百分比形式，所以我们就将 x 和 y 都按照百分比解析了。

---

#### 解决
这里你先通过索引值解决吧，分类类型的数据也可以直接传入索引值的：

```js
// draw the Guide.Text
  data.map(function (obj, index) {
    chart.guide().text({
      position: [index, obj.sales],
      content: obj.sales,
      style: {
        textAlign: 'center',
        textBaseline: 'bottom'
      },
      offsetY: 0
    });
  });
```
