### ISSUE TITLE
Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by zhaozhiming** [antvis/f2#300]
* **F2 Version**: 3.2.1
* **Platform**: React native, Mac
* **Mini Showcase(like screenshots)**:  https://snack.expo.io/@tik-zhaozhiming/f2_demo
* **CodePen Link**: 

When I npm start I got this error:
```
/xxxxx/node_modules/@antv/f2/lib/geom/adjust/index.js: Couldn't find preset "env" relative to directory "/xxxxx/node_modules/@antv/f2"
```
I have install the `transform-remove-strict-mode` and config in my babel setting.

```json
{
  "presets": ["babel-preset-expo"],
  "plugins": [["import", { "libraryName": "antd-mobile-rn" }]],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source", "transform-remove-strict-mode"]
    }
  }
}
```

**Comment by simaQ** [comment]
It may be caused by import from  '@antv/f2/src' directly or packaged the code without masking the node_modules folder for babel.

You should import from '@antv/f2/lib' or configure babel to block node_modules

**Comment by zhaozhiming** [comment]
It's OK now. Thanks
