### ISSUE TITLE
微信小程序，tooltip被遮住。点击各种图像发现tootip的高度位置始终固定，能否自适应位置

### ISSUE THREAD

**Issue by luowei1991** [antvis/f2#305]
如图所示：
![image](https://user-images.githubusercontent.com/19301689/44979592-1c58a600-afa0-11e8-8902-64e01f522795.png)

代码如下：   chart.tooltip({
          showTitle: true,
          offsetY: 80 
        });
tooltip的显示位置可否紧跟点击处？？？

**Comment by simaQ** [comment]
F2 的 Tooltip 交互是专为移动端设计的，在固定处显示会解决各种手指遮挡问题。

> tooltip的显示位置可否紧跟点击处

这个可以通过自定义 Tooltip 实现

**Comment by luowei1991** [comment]
可否提供下代码呀！

**Comment by luowei1991** [comment]
自定义tooltip的代码能否提供下，我借鉴下

**Comment by simaQ** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/demo/component/tooltip-custom.html  DEMO 中都有的。小程序环境的思路相同，你把 html 改成小程序中的元素即可。

**Comment by luowei1991** [comment]
这。。。完全不符合需求嘛，没法借鉴使用啊

**Comment by luowei1991** [comment]
![image](https://user-images.githubusercontent.com/19301689/44981045-0cdb5c00-afa4-11e8-8bc6-f355895aa7d6.png)
元素的顶部高度。我真不知道如何去计算，如果说按照dom换成小程序的方法。

**Comment by simaQ** [comment]
我们并不提倡在移动端使用同 PC 端一样的 tooltip 交互方式，因为这个在我们的设计原则中并不合适。而且在实现 tooltip 跟随手势时需要考虑 tooltip 遮挡等问题，并没有那么简单。

**Comment by lishaoshi** [comment]
小程序自定义tooltip安卓点击对应的柱状图没反应是怎么回事呢
