### ISSUE TITLE
曲线超出坐标轴范围

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#306]
* **F2 Version**:3.2.1
* **Platform**:macos
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在下面例子中，删除interaction设置部分，曲线超出了坐标轴范围
https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-line-chart.html
![image](https://user-images.githubusercontent.com/11312811/44989091-571e0680-afbf-11e8-9fa2-ddc2866c44b5.png)

**Comment by simaQ** [comment]
恩，这是因为设置了横轴数据的范围，如果不需要平移操作的话，这个范围设定就可以移除了，或者直接在 new Chart 处声明 `limitInPlot: true` 即可，就不会超出了。

```js
  var chart = new F2.Chart({
    id: 'mountNode',
    limitInPlot: true, // 限定范围
    pixelRatio: window.devicePixelRatio
  });
// 限定横轴数据的范围
chart.source(data, {
    release: {
      min: 1990,
      max: 2010
    }
  });
```

**Comment by ZiQiangWang** [comment]
哈哈，谢了，我最近封装了一个vue版本的，在写各种demo加文档，弄好了给你看哈

**Comment by simaQ** [comment]
嗯哪，非常给力
