### ISSUE TITLE
问个小小的问题，图表的数据是动态的，想要图表在数据为[]的时候，表现出没有数据的样子而不是空白一片怎么做，图表现在有这个接口吗？？

### ISSUE THREAD

**Issue by xingyuefa** [antvis/f2#309]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
可以这么做，在列定义中声明横轴的数据的类型，这样在数据为空数组时，会将横轴的坐标轴线绘制出来。

目前 Y 轴的轴线默认是不绘制的，如果也想将 Y 轴显示出来，可以在 chart.axis() 中配置下，参见这个 demo: https://codepen.io/Sima/pen/JayjGv
