### ISSUE TITLE
如何实现点击文字标隐藏曲线

### ISSUE THREAD

**Issue by miewx** [antvis/f2#310]
如何实现点击文字标隐藏曲线

![image](https://user-images.githubusercontent.com/26247733/45206223-140dad00-b2b7-11e8-9fd0-a65588501177.png)

我在使用过程中发现2件奇怪的事情

triggerOn必须手写上mousemove才会有提示，而不是默认有，这个影响到不大。

但是，在官网的演示中，点文字标可以隐藏曲线，但是自己开发的页面点击后就没反应。

请问如何实现：如何实现点击文字标隐藏曲线？

代码如下
![image](https://user-images.githubusercontent.com/26247733/45206263-2daef480-b2b7-11e8-9944-42aa6a7732c4.png)

**Comment by simaQ** [comment]
tooltip 那个，你在自己的项目下运行应该是生效的，如果是在 PC 端浏览器下开发，建议打开设备模拟器，以 chrome 为例，这样就会触发了

![image](https://user-images.githubusercontent.com/6628666/45208389-0a874380-b2bd-11e8-8817-faaf249332fa.png)

**Comment by miewx** [comment]
我测试了，用手机模式浏览的确是可以切换隐藏显示的。

但是，设置
chart.legend({
  triggerOn: 'click',
  itemWidth:90
});
用pc浏览器还依然是无效的。

有什么好的解决方案吗？

**Comment by simaQ** [comment]
生效的，看下我的这个例子： https://codepen.io/Sima/pen/WgXNzb

**Comment by miewx** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/api/legend.html
我搞明白了，文档上写的参数签名是 chart.legend(field, config)
我调用的时候写的是 chart.legend("xxx", config)
但是应该写 chart.legend(config)
现在搞定了，多谢。

**Comment by miewx** [comment]
可以考虑修正下文档

**Comment by simaQ** [comment]
@miewx 恩，是的，非常感谢指正，我纠正下
