### ISSUE TITLE
F2的interaction的事件触发可以支持点击事件吗？

### ISSUE THREAD

**Issue by LInonems** [antvis/f2#312]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/26306218/45216798-63aea180-b2d4-11e8-848d-807e7fd6e955.png)

**Comment by simaQ** [comment]
F2 的交互是特为移动端设计的，目前不支持点击事件。
