### ISSUE TITLE
饼图、环形图能否逆时针显示

### ISSUE THREAD

**Issue by joeyczz** [antvis/f2#314]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如果没有逆时针展示，是否有什么解决方案
![image](https://user-images.githubusercontent.com/15942257/45266654-fd22b280-b490-11e8-8631-bdc59198a828.png)

**Comment by simaQ** [comment]
emmm，是可以的。用饼图的绘制逻辑，调整下显示数据的顺序即可，这样可以实现你截图的效果。

详见 demo: https://codepen.io/Sima/pen/JaMmyg
