### ISSUE TITLE
想请教下f2可以多表联动的吗？

### ISSUE THREAD

**Issue by devin-yuan** [antvis/f2#315]
想请教下f2有没有多表联动的功能，想股票分时图那样，上面是个折线图，下面是柱状图，然后看行情时可以联动

**Comment by simaQ** [comment]
恩，这个目前是有方法做到的，可以通过监听 canvas 的事件同时配合 F2 提供的一个 api 实现。

**Comment by devin-yuan** [comment]
@simaQ 感谢，我去找一下
