### ISSUE TITLE
能否支持一下双Y轴

### ISSUE THREAD

**Issue by why-git** [antvis/f2#321]
如题

**Comment by simaQ** [comment]
天然支持的，只要你声明的两个图形语法语句的 y 字段不同即会生成双 Y 轴。

```js
chart.line().position('x*y').color('red')
chart.line().position('x*z').color('blue')
```

具体的 demo： https://antv.alipay.com/zh-cn/f2/3.x/demo/component/legend-custom.html

**Comment by ZiQiangWang** [comment]
这个demo里面，点击legend的时候，显示有问题

**Comment by simaQ** [comment]
我看下，记得这个问题已经修复了的。

**Comment by simaQ** [comment]
是 demo 编写有误，已经更正：https://github.com/antvis/site/blob/master/site/zh-cn/f2/3.x/demo/component/legend-custom.html#L95

我们会尽快发布上线的，非常感谢。
