### ISSUE TITLE
使用曲线平移，滑动平移过程中会报错

### ISSUE THREAD

**Issue by lanjinli** [antvis/f2#324]
error in parsing gradient string, please check if there are any extra whitespaces.

TypeError: Failed to execute 'createLinearGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.

![qq 20180911155349](https://user-images.githubusercontent.com/42225063/45346221-2b140e00-b5db-11e8-95c2-96f2b1a9744b.png)

**Comment by simaQ** [comment]
请尽量按照 issue 模板提问：

![image](https://user-images.githubusercontent.com/6628666/45346337-847c3d00-b5db-11e8-8160-9cfa972eaeb9.png)

**Comment by simaQ** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/api/canvas.html#_%E6%B8%90%E5%8F%98%E8%89%B2 渐变色的说明:
![image](https://user-images.githubusercontent.com/6628666/45346439-c4dbbb00-b5db-11e8-92f4-4ff257725bd6.png)

**Comment by simaQ** [comment]
升级到 F2 3.2.2 版本就不会有这个问题了

**Comment by simaQ** [comment]
https://gw.alipayobjects.com/os/antv/assets/f2/3.2.2/f2-all.min.js
