### ISSUE TITLE
scale的range默认值失效

### ISSUE THREAD

**Issue by padma0** [antvis/f2#325]
* **F2 Version**: 3.2.2
* **Platform**: ALL
* **Mini Showcase(like screenshots)**:
不设range：
![image](https://user-images.githubusercontent.com/29781322/45352778-dd53d180-b5eb-11e8-8b82-36f823b4a3de.png)
设置range为[0,1]：
![image](https://user-images.githubusercontent.com/29781322/45352804-f066a180-b5eb-11e8-9a8b-bd341eeafbda.png)

* **CodePen Link**:
https://codepen.io/padma0/pen/EeoBRg

根据[文档](https://antv.alipay.com/zh-cn/g2/3.x/api/scale.html#_range)，range的默认值是[0,1]，但与实际填入效果不一致。

**Comment by simaQ** [comment]
抱歉，文档有误，对于数值类型，默认值是 [ 0, 1 ]，而对于分类类型的数据，我们会对 range 进行处理，默认值不是 [ 0, 1 ]
