### ISSUE TITLE
x轴为cat类型 数据有重复时会在一列显示

### ISSUE THREAD

**Issue by iamllitog** [antvis/f2#327]
* **F2 Version**: 3.2.2
* **Platform**: PC
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/6738756/45406196-45f88800-b698-11e8-882d-6021b2546ff7.png)

* **CodePen Link**:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="chart-name" content="基础面积图">
    <title>F2 图表组件库 - AntV</title>
    <link rel="stylesheet" href="https://gw.alipayobjects.com/os/rmsportal/YmDAMEQVbLJpVbKiRQVX.css" />
    
</head>
<body>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>

<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.2.2/f2.min.js"></script>

<script src="https://gw.alipayobjects.com/os/antv/assets/lib/jquery-3.2.1.min.js"></script>

<script src="https://gw.alipayobjects.com/os/rmsportal/NjNldKHIVQRozfbAOJUW.js"></script>

  <div class="chart-wrapper">
    <canvas id="mountNode"></canvas>
  </div>
  <script>
var data = [{"yaxi":"9020.46","xaxi":"120.67","type":"xaxi_0+yaxi_0"},{"yaxi":"38855.20","xaxi":"120.67","type":"xaxi_0+yaxi_1"},{"yaxi":"3051.13","xaxi":"117.16","type":"xaxi_0+yaxi_0"},{"yaxi":"9138.69","xaxi":"117.16","type":"xaxi_0+yaxi_1"},{"yaxi":"1797.24","xaxi":"116.42","type":"xaxi_0+yaxi_0"},{"yaxi":"5238.98","xaxi":"116.42","type":"xaxi_0+yaxi_1"},{"yaxi":"1629.67","xaxi":"123.41","type":"xaxi_0+yaxi_0"},{"yaxi":"4813.16","xaxi":"123.41","type":"xaxi_0+yaxi_1"},{"yaxi":"1616.08","xaxi":"102.12","type":"xaxi_0+yaxi_0"},{"yaxi":"5922.84","xaxi":"102.12","type":"xaxi_0+yaxi_1"},{"yaxi":"1224.25","xaxi":"104.12","type":"xaxi_0+yaxi_0"},{"yaxi":"4164.97","xaxi":"104.12","type":"xaxi_0+yaxi_1"},{"yaxi":"1064.16","xaxi":"111.79","type":"xaxi_0+yaxi_0"},{"yaxi":"2906.57","xaxi":"111.79","type":"xaxi_0+yaxi_1"},{"yaxi":"899.24","xaxi":"117.13","type":"xaxi_0+yaxi_0"},{"yaxi":"2693.95","xaxi":"117.13","type":"xaxi_0+yaxi_1"},{"yaxi":"856.79","xaxi":"108.99","type":"xaxi_0+yaxi_0"},{"yaxi":"2724.79","xaxi":"108.99","type":"xaxi_0+yaxi_1"},{"yaxi":"821.62","xaxi":"117.20","type":"xaxi_0+yaxi_0"},{"yaxi":"2461.26","xaxi":"117.20","type":"xaxi_0+yaxi_1"},{"yaxi":"773.14","xaxi":"118.08","type":"xaxi_0+yaxi_0"},{"yaxi":"2479.62","xaxi":"118.08","type":"xaxi_0+yaxi_1"},{"yaxi":"655.98","xaxi":"125.42","type":"xaxi_0+yaxi_0"},{"yaxi":"1881.29","xaxi":"125.42","type":"xaxi_0+yaxi_1"},{"yaxi":"652.62","xaxi":"111.88","type":"xaxi_0+yaxi_0"},{"yaxi":"1790.02","xaxi":"111.88","type":"xaxi_0+yaxi_1"},{"yaxi":"639.34","xaxi":"116.52","type":"xaxi_0+yaxi_0"},{"yaxi":"1864.35","xaxi":"116.52","type":"xaxi_0+yaxi_1"},{"yaxi":"611.22","xaxi":"122.29","type":"xaxi_0+yaxi_0"},{"yaxi":"1712.08","xaxi":"122.29","type":"xaxi_0+yaxi_1"},{"yaxi":"600.50","xaxi":"116.24","type":"xaxi_0+yaxi_0"},{"yaxi":"1743.60","xaxi":"116.24","type":"xaxi_0+yaxi_1"},{"yaxi":"593.92","xaxi":"126.37","type":"xaxi_0+yaxi_0"},{"yaxi":"1642.79","xaxi":"126.37","type":"xaxi_0+yaxi_1"},{"yaxi":"591.56","xaxi":"113.71","type":"xaxi_0+yaxi_0"},{"yaxi":"1933.04","xaxi":"113.71","type":"xaxi_0+yaxi_1"},{"yaxi":"585.53","xaxi":"117.13","type":"xaxi_0+yaxi_0"},{"yaxi":"1756.89","xaxi":"117.13","type":"xaxi_0+yaxi_1"},{"yaxi":"521.69","xaxi":"113.56","type":"xaxi_0+yaxi_0"},{"yaxi":"1703.36","xaxi":"113.56","type":"xaxi_0+yaxi_1"},{"yaxi":"511.03","xaxi":"104.21","type":"xaxi_0+yaxi_0"},{"yaxi":"1458.88","xaxi":"104.21","type":"xaxi_0+yaxi_1"},{"yaxi":"489.81","xaxi":"104.04","type":"xaxi_0+yaxi_0"},{"yaxi":"1664.66","xaxi":"104.04","type":"xaxi_0+yaxi_1"},{"yaxi":"468.13","xaxi":"100.52","type":"xaxi_0+yaxi_0"},{"yaxi":"1206.26","xaxi":"100.52","type":"xaxi_0+yaxi_1"},{"yaxi":"437.18","xaxi":"121.50","type":"xaxi_0+yaxi_0"},{"yaxi":"1700.95","xaxi":"121.50","type":"xaxi_0+yaxi_1"},{"yaxi":"429.09","xaxi":"117.65","type":"xaxi_0+yaxi_0"},{"yaxi":"1294.14","xaxi":"117.65","type":"xaxi_0+yaxi_1"},{"yaxi":"422.86","xaxi":"119.00","type":"xaxi_0+yaxi_0"},{"yaxi":"1189.98","xaxi":"119.00","type":"xaxi_0+yaxi_1"},{"yaxi":"417.08","xaxi":"113.65","type":"xaxi_0+yaxi_0"},{"yaxi":"1363.80","xaxi":"113.65","type":"xaxi_0+yaxi_1"},{"yaxi":"406.00","xaxi":"121.64","type":"xaxi_0+yaxi_0"},{"yaxi":"1581.30","xaxi":"121.64","type":"xaxi_0+yaxi_1"},{"yaxi":"397.10","xaxi":"120.38","type":"xaxi_0+yaxi_0"},{"yaxi":"1324.16","xaxi":"120.38","type":"xaxi_0+yaxi_1"},{"yaxi":"396.94","xaxi":"120.37","type":"xaxi_0+yaxi_0"},{"yaxi":"1324.05","xaxi":"120.37","type":"xaxi_0+yaxi_1"}];
var chart = new F2.Chart({
  id: 'mountNode',
  pixelRatio: window.devicePixelRatio
});

chart.source(data);
chart.tooltip({
  showCrosshairs: true
});
chart.scale({
  yaxi: {
          type: 'linear'
        },
        xaxi: {
          type: 'cat',
          tickCount: 6
        }
});
chart.area({ sortable: false }).position('xaxi*yaxi').color('type');
chart.line({ sortable: false }).position('xaxi*yaxi').color('type');
chart.render();
</script>

</body>
</html>
`

在xaxi中有重复的117.13数据，重复排在一列，而使用echart则会分开排列

![image](https://user-images.githubusercontent.com/6738756/45406258-80622500-b698-11e8-9c9c-8c0fbec7a2c9.png)

麻烦问下是有特殊的类型吗？像这种情况应如何处理

**Comment by simaQ** [comment]
这种情况下，对于 F2 来说，你可以对 x 轴的数据进行排列处理，这里你只要将 sortable: false 配置删除即可。

```js
chart.area().position('xaxiyaxi').color('type');
chart.line().position('xaxiyaxi').color('type');
```
