### ISSUE TITLE
guide().regionFilter 实现不了 guide其它的可以

### ISSUE THREAD

**Issue by Wu-JunFeng** [antvis/f2#329]
chart.guide().regionFilter({
      start: ['min', 30],
      end: ['max', 'max'],
      color: '#FF4D4F'
    });
![image](https://user-images.githubusercontent.com/24196742/45603058-a9006b00-ba5a-11e8-8465-68a755b49bd2.png)

**Comment by simaQ** [comment]
'@antv/f2' 默认没有打包 Guide.RegionFilter，你需要自己引入。详见次 issue: https://github.com/antvis/f2/issues/311#issuecomment-419776034

**Comment by Wu-JunFeng** [comment]
是需要从lib下引入F2: import F2 from '@antv/f2/lib/index'
问题已解决谢谢
