### ISSUE TITLE
grid用函数的形式来写 return {type: 'arc'}, 报错

### ISSUE THREAD

**Issue by 1126341821** [antvis/f2#331]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://riddle.alibaba-inc.com/riddles/1e4d5a94?amdType=common&mode=jsx

**Comment by simaQ** [comment]
@antv/f2@3.2.3-beta.2  这个版本修复了
