### ISSUE TITLE
能否设置图和左右边界的距离

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#333]
* **F2 Version**:3.2.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我通过设置padding和appendPadding，实现了整个图的平铺
![image](https://user-images.githubusercontent.com/11312811/45669265-193de800-bb52-11e8-9e78-3db86fb30a9e.png)
但是柱状图会遮住左侧的坐标轴文字。设置scale的range为[0.2,0.9]的话，在marginRatio为0时，出现重叠。请问怎么解决这个问题呢
![image](https://user-images.githubusercontent.com/11312811/45669360-7a65bb80-bb52-11e8-8d62-e664167d6adb.png)

**Comment by simaQ** [comment]
有办法，不需要你这么设置，直接调整下坐标轴文本的显示层级即可：

```js
chart.axis('Y 轴坐标轴字段名', {
  label: {
    top: true // 展示在最上层图层
  }
});
```

**Comment by ZiQiangWang** [comment]
这个设置解决的是什么问题吗？我尝试了下，没有起作用。还是有柱状图重叠的问题

**Comment by simaQ** [comment]
柱状图会遮住左侧的坐标轴文字的问题。柱状图层叠那个问题，你把一些没必要的配置去掉就好了。

**Comment by ZiQiangWang** [comment]
我觉得，你可能误会我的意思了，我不是很在意柱状图遮住了文字，而是希望把柱状图往右挤一挤，留一点空间专门用来显示坐标轴文字

**Comment by simaQ** [comment]
恩，我误解了，`marginRatio` 为 0 导致重叠的问题我跟进下，看看是什么原因导致的，稍等

**Comment by simaQ** [comment]
暂无解决办法。
