### ISSUE TITLE
X轴为时间序列时，数据源中若缺少某个时间点时，绘制出的X轴不连贯

### ISSUE THREAD

**Issue by miaojiuchen** [antvis/f2#335]
场景：
后端返回 t1, <del>t2,</del> t3, <del>t4,</del> t5......tn 的不连续时间点的数据，
期望直接传入chart.source()绘制出来的图的X轴为连续的 t1, t2, t3......tn，不存在的点为空值，期望表现行为与 { time: tn, value: null }一致

<b>有什么便捷的方式吗？</b>

**Comment by miaojiuchen** [comment]
请问 f2 啥时候支持G2里的 time linear 类型？

**Comment by miaojiuchen** [comment]
@simaQ

**Comment by simaQ** [comment]
目前 F2 不支持 time 类型，是否。这里即使使用 time 类型，不存在的点还是会被线连接起来，而不是一个空值的表现。你可以手动将缺失的时间段补充上，将对应的 value 设置为 null。

**Comment by miaojiuchen** [comment]
OK    -______-!     只有这样了
