### ISSUE TITLE
折线图支持平移时，如果数据为0，点显示不全

### ISSUE THREAD

**Issue by crazyliuxp** [antvis/f2#336]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

折线图支持平移时，添加上`  chart.interaction('pan');`后，如果数据为0，则画出的点只能显示一半，能完全显示吗？
如果不支持平移则显示的是完整的点。

下面是我修改官方demo的图例

![image](https://user-images.githubusercontent.com/8414495/45730361-c45aaa00-bc03-11e8-8651-95440d55b6f8.png)

**Comment by simaQ** [comment]
恩，我们在平移的时候会将图形限制在绘图区域内，所以会造成点部分被遮挡，这个可以优化一下

**Comment by crazyliuxp** [comment]
要等后边的版本了吧？

**Comment by simaQ** [comment]
@antv/f2@3.2.3-beta.3
