### ISSUE TITLE
饼图能否支持贴边？或者背景层能否设置透明呢？

### ISSUE THREAD

**Issue by Sapphire2k** [antvis/f2#337]
* **F2 Version**:  3.2.2
* **Platform**: Chrome 69
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/17328005/45735882-fed04100-bc1b-11e8-943b-fd55c80a7326.png)

设置了padding、appendPadding为0，仍然无法贴边哦~

**Comment by simaQ** [comment]
是不是在 `chart.coord('polar')` 坐标系中配置了 `radius`  属性？将其去除或者设置为 1 即可，当然 `padding` 和 `autoPadding` 仍然要设置为 0。

```js
chart.coord('polar', {
  transposed: true,
  //radius: 0.85
});
```

另外背景色的设置，你直接设置 canvas 标签的 css 样式即可。

**Comment by Sapphire2k** [comment]
@simaQ 确实是配置了radius，感谢。
