### ISSUE TITLE
环形图数据过多时会看不到环形图

### ISSUE THREAD

**Issue by 15390940742** [antvis/f2#339]
详细情况：环形图数据比较小时，图例无论放在左边还是有便或者底部都是没问题的，但是数据多的时候就会把环形图挤小，甚至会完全看不到，请问有什么办法解决吗，或者可以修改拓展吗

**Comment by simaQ** [comment]
这种情况，建议使用 html 自己实现图例，通过这个接口可以获取图例项的具体内容:https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_getLegendItems

**Comment by 15390940742** [comment]
这个获取到的只有相关的样式配置啊，如何操作HTML
![image](https://user-images.githubusercontent.com/36804510/45791725-74d8b480-bcbd-11e8-8aa1-776ef360588a.png)

**Comment by simaQ** [comment]
通过这些信息将 legend 使用 html 渲染出来，然后通过监听 dom 事件来操作 html, 至于图例同 chart 的联动，你可以参考源码中 canvas 的实现逻辑：https://github.com/antvis/f2/blob/master/src/plugin/legend.js#L332。

个人的建议是，在手机端，如果图例数量比较大的时候，其实用户点触的面积也会相对比较小了，这时候加上点击操作反而体验不好，另外，对于环图或者饼图，原则上一张饼图不可多于 9 个分类

**Comment by 15390940742** [comment]
非常感谢

**Comment by ShowJoy** [comment]
我写了个[插件](https://github.com/ShowJoy/f2shim)，里面根据legend的高度来调整canvas高度，不知道是否符合需求

**Comment by 15390940742** [comment]
应该可以，有效果图吗



------------------ 原始邮件 ------------------
发件人: "ShowJoy"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 上午9:26
收件人: "antvis/f2"<f2@noreply.github.com>; 
抄送: "没估计回顾减"<1483805662@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [antvis/f2] 环形图数据过多时会看不到环形图 (#339)




我写了个插件，里面根据legend的高度来调整canvas高度，不知道是否符合需求

**Comment by ShowJoy** [comment]
![f2shim](https://user-images.githubusercontent.com/1659577/65492419-7a299a00-dee3-11e9-8a2c-ebc01e8b8930.gif)
