### ISSUE TITLE
guide的渲染依赖于异步数据

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#341]
* **F2 Version**:3.2.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我在下面的例子基础上做修改，但是使用的异步数据。
https://antv.alipay.com/zh-cn/f2/3.x/demo/component/guide-text.html
在异步数据加载完成后，此时已经执行了render函数。
使用changeData修改了数据，但是guide的渲染明显无法起作用，repaint函数应该是只能对现有的已定义的guide进行刷新。
不得已，我只能使用destroy然后再重新render。是否有其他的方式来处理？
或者repaint函数，能否考虑到这种新增元素的情况

**Comment by simaQ** [comment]
https://github.com/antvis/f2/issues/241

**Comment by simaQ** [comment]
对于新增的辅助元素，如果你声明了，调用 repain() 是会绘制的。

**Comment by ZiQiangWang** [comment]
嗯嗯，是我写错了逻辑

**Comment by zim-lee** [comment]
遇到同样的问题，请教如何解决的 @ZiQiangWang

**Comment by ZiQiangWang** [comment]
@zim-lee [#241](https://github.com/antvis/f2/issues/241)，guide有一个repaint函数，异步加载数据后，调用即可
