### ISSUE TITLE
交互pan在初始显示的数据项较少时，移动过快

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#343]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/ziqiangwang/pen/QVXEpv

类型为timeCat，初始显示5条数据，滑动时，平移太快了，有没有配置调整灵敏度的参数

在现有的例子中做了测试，
[折线图平移](https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-line-chart.html)中，将
数据范围改为2010~2015，交互正常。
```
release: {
    min: 2010,
    max: 2015
}
```
[柱状图平移](https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-bar-chart.html)中，将日期范围从`2018-05-01` 改为`2018-05-17`，平移速度太快。
![image](https://user-images.githubusercontent.com/11312811/46005222-5c1a3580-c0e7-11e8-9638-46c2b0ee2227.png)

**Comment by simaQ** [comment]
恩，这个问题同 #342 是一样的，对于分类的交互优化还是需要优化一下
