### ISSUE TITLE
多y轴图表  折线图 平移的时候 线的颜色会变掉 

### ISSUE THREAD

**Issue by caizhendi** [antvis/f2#346]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/caizhendi/pen/GXVpOR

**Comment by simaQ** [comment]
恩，这个问题已经在 3.2.3-beta 版本修复了，你先将 F2 升级到 3.2.3-beta.3 版本，本周会发布稳定版。

线上地址：
- https://gw.alipayobjects.com/os/antv/assets/f2/3.2.3-beta.3/f2-all.min.js
- https://gw.alipayobjects.com/os/antv/assets/f2/3.2.3-beta.3/f2.min.js

**Comment by caizhendi** [comment]
> 恩，这个问题已经在 3.2.3-beta 版本修复了，你先将 F2 升级到 3.2.3-beta.3 版本，本周会发布稳定版。
> 
> 线上地址：
> 
> * https://gw.alipayobjects.com/os/antv/assets/f2/3.2.3-beta.3/f2-all.min.js
> * https://gw.alipayobjects.com/os/antv/assets/f2/3.2.3-beta.3/f2.min.js

我是小程序的话 该怎么整

**Comment by simaQ** [comment]
https://github.com/antvis/wx-f2#%E4%B8%8B%E8%BD%BD

**Comment by caizhendi** [comment]
> https://github.com/antvis/wx-f2#%E4%B8%8B%E8%BD%BD

网页上的是没问题了 小程序上 你平移的时候 其实内容没展示完全 你单击图表内容才完全展示
