### ISSUE TITLE
圆饼图guide().text报错

### ISSUE THREAD

**Issue by huangchaofei** [antvis/f2#348]
环境:angular/cli": "~6.0.8,
报错 IndexComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property '0' of null
    at e.parsePoint (f2-all.min.js:1)
    at e.n.render (f2-all.min.js:1)
    at f2-all.min.js:1
    at Object.t.exports [as each] (f2-all.min.js:1)
    at t.e.paint (f2-all.min.js:1)
    at Object.afterGeomDraw (f2-all.min.js:1)
    at Object.notify (f2-all.min.js:1)
    at e.n.render (f2-all.min.js:1)
    at IndexComponent.push../src/app/components/index/index.component.ts.IndexComponent.ngAfterViewInit (index.component.ts:652)
    at callProviderLifecycles (core.js:9567)
代码:// 故障夹层圆饼图
            this.faultChart = new F2.Chart({
              id: 'faultChart',
              pixelRatio: window.devicePixelRatio
            });
            this.faultChart.source(this.fault_data);
            this.faultChart.legend(false);
            this.faultChart.tooltip(false);
            this.faultChart.coord('polar', {
              transposed: true,
              radius: 1
            });
            this.faultChart.axis(false);
            this.faultChart.interval().position('a*percent').color('name', ['#FFB33B', '#EF4545']).adjust('stack');
            let sum = 0
            this.fault_data.map((item,index)=>{
                const value = sum + item.percent / 2;
                this.faultChart.guide().text([0, value], index);
                sum += item.percent;
            })

            this.faultChart.render();
有没有别的方式在圆饼图上对应区域的中心位置添加自定义文字

**Comment by simaQ** [comment]
你是自己封装过 guide().text() 吗？F2 的 guide().text() 不是像你代码中这么使用的：

```js
this.faultChart.guide().text([0, value], index); // 不是这么用的
```

具体参考： https://antv.alipay.com/zh-cn/f2/3.x/api/guide.html#_Text

**Comment by huangchaofei** [comment]
没有 我是看圆饼图示例guide().text() 这样用的

**Comment by simaQ** [comment]
> 没有 我是看圆饼图示例guide().text() 这样用的

你看的是老版本的 F2 吧，上线上 demo 或者 api 文档看下就知道不是这么用了。。。你改下写法就好了。。。

https://codepen.io/Sima/pen/ddNEGE

![image](https://user-images.githubusercontent.com/6628666/46189763-d682c980-c322-11e8-9549-9d7d64aecacc.png)

**Comment by huangchaofei** [comment]
谢谢  可以了 
https://antv.alipay.com/zh-cn/f2/3.x/demo/index.html 我是在这上面查看demo和API用法的
