### ISSUE TITLE
坐标重复数据合并了

### ISSUE THREAD

**Issue by yellowYiFeng** [antvis/f2#350]
如果其中一条数据的横坐标的值和其他数据重合了，这两条数据会合并成一条，
例如
var data = [{
  name: '张三',
  value: 47
}, {
  name: '李四',
  value: 61
}, {
  name: '王五',
  value: 174
}, {
  name: '张三',
  value: 339
}];
这样的话，第一条张三的数据会和最后一条合并成一条，但是现实情况是名字就是可能会重复的，我想要的是 这两条分开展示，怎么做呢

**Comment by yellowYiFeng** [comment]
横向柱状图 已经解决了

**Comment by amazinglisa** [comment]
> 横向柱状图 已经解决了

请问是如何解决的呢？
