### ISSUE TITLE
使用interval-select的交互，点击元素触发顺序问题

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#355]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/ziqiangwang/pen/BqBmZX

在例子中，我希望interval遮住line，即柱状图处在上层，因此如下定义，先绘制line再绘制interval。
```
chart.line().position('year*sales').color('black');
chart.interval().position('year*sales');
```
但是这种情况下，interval-select点击，点到了line上。必须调换两者的顺序，才能正确触发。
```
chart.interval().position('year*sales');
chart.line().position('year*sales').color('black');
```

这种情况是否违反直觉，因为通常情况下，会觉得处在上面的元素被点到

**Comment by simaQ** [comment]
升级到 3.2.4-beta.1
