### ISSUE TITLE
interval-select和pan，交互冲突

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#356]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

当柱状图选中时，进行平移操作，选中状态丢失

**Comment by simaQ** [comment]
目前还不支持该功能哦。

**Comment by ZiQiangWang** [comment]
是不允许同时存在多种交互吗

**Comment by ZiQiangWang** [comment]
和我想象的不太一样，还以为平移这种操作是使用类似translate的方式，不会影响到已选中的状态
