### ISSUE TITLE
放大图表超出坐标系后，辅助 `guide().tag` 依然存在

### ISSUE THREAD

**Issue by ReconcileMySelf** [antvis/f2#358]
我往图表上添加了一些 `line` 和 `tag`  辅助，但是当我对图表进行缩放的时候，`line` 和 `tag` 超出坐标轴了过后还显示，这就导致会超出和页面的其它部分重叠。
* **F2 Version**: 3.2.3
* **Platform**: android
* **Mini Showcase(like screenshots)**:
![1538119829 1](https://user-images.githubusercontent.com/10515836/46194272-852f0600-c333-11e8-9fdb-e72f3403488e.png)
![632419545220246863](https://user-images.githubusercontent.com/10515836/46194323-b27bb400-c333-11e8-876f-7a0648ed8e17.jpg)
![529320434794696148](https://user-images.githubusercontent.com/10515836/46194334-b9a2c200-c333-11e8-865e-219f19045115.jpg)
有没有办法，当超出坐标系过后，就不显示这些 `line` 和 `tag` 吗？

**Comment by simaQ** [comment]
在 chart.guide() 那里加一个参数： `limitInPlot: true` 试试

**Comment by ReconcileMySelf** [comment]
嗯，对的，加上后，就对了，建议把这个参数更新到文档上。

**Comment by ReconcileMySelf** [comment]
谢谢，指正！
