### ISSUE TITLE
可否配置初始的缩放等级

### ISSUE THREAD

**Issue by ReconcileMySelf** [antvis/f2#360]
* **F2 Version**: 3.2.3

1. 数据量多的时候，出现缩放抖动的情况
2. 能否配置初始的缩放等级
3. 能否实现类似于 G2 那样，缩放和平移的时候，显示在坐标轴上的刻度标签始终显示那么多个

**Comment by simaQ** [comment]
1. 抖动的情况目前正在完善中
2. 目前是支持配置初始缩放等级的，只是针对不同的数据类型配置不同，数值类型，你可以直接配置 min 和  max 来确定缩放等级，分类（cat, 字符串类型）或者时间（timeCat）可以直接通过 values 进行配置
3. 目前没有开放这个功能
