### ISSUE TITLE
[Legend] onClick event prevents chart repaint

### ISSUE THREAD

**Issue by disoul** [antvis/f2#362]
* **F2 Version**: 3.2.3
* **Platform**: Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

I added label and legend to my pie chart based on this [document](https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/labelline-pie.html)
![image](https://user-images.githubusercontent.com/8756894/46334014-1adcd500-c655-11e8-8123-bef5d60ea087.png)
Now i want to handle legend click event to update label position, so i used `onClick` event in my legend options.But once I set this option, the chart will not be repainted.    
I think the problem code is [here](https://github.com/antvis/f2/blob/master/src/plugin/legend.js#L328). I can't understand why F2 uses conditional statements here. So if i just want to listen to click events, what should I do?

**Comment by simaQ** [comment]
`onClick` is used to help developers customize the interactive behavior of the legend. If you just want to listen to `click` event,  you can set `triggerOn` as 'click'. But in this situation, as the labels are rendered after the rendering of chart, the labels will not update after chart repaint(when you click the legend, the chart will be repainted), so you still has to define `onClick` and call `addPieLabel` method in your `onClick` method. 

This demo gives the solution: https://codepen.io/Sima/pen/BqQpON

The key code：

```js
chart.legend({
  triggerOn: 'click',
  onClick(ev) {
    const clickedItem = ev.clickedItem;
    const checked = clickedItem.get('checked');
    const value = clickedItem.get('dataValue');
    const { filterVals, field, selectedMode } = this;
    const isSingeSelected = selectedMode === 'single';

    if (isSingeSelected) {
      chart.filter(field, val => {
        return val === value;
      });
    } else {
      if (!checked) {
        filterVals.push(value);
      } else {
        Util.Array.remove(filterVals, value);
      }

      chart.filter(field, val => {
        return filterVals.indexOf(val) !== -1;
      });
    }

    chart.repaint();
    setTimeout(function() {
      addPieLabel(chart);
    }, 320); // 必须在更新动画结束之后再绘制，默认的更新时间是 300
  }
});
```

**Comment by disoul** [comment]
thanks
