### ISSUE TITLE
timecat类型 设置了缩放平移 缩放后会有一个阴影

### ISSUE THREAD

**Issue by mdj11j** [antvis/f2#363]
* **F2 Version**:3.2.1
* **Platform**:mobile web,
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题如图：
![webwxgetmsgimg](https://user-images.githubusercontent.com/27773969/46579646-81446780-ca48-11e8-874b-98f4fcdcc236.jpeg)

相关代码只有这些
this.chart.source(data.itemlist, {
                createOn: {
                    type: "timeCat",
                    range: [0, 1],
                    tickCount: 4
                },
            });

this.chart.interaction('pan').interaction('pinch');

**Comment by simaQ** [comment]
恩，你升级下 F2 的版本，使用最新的 @antv/f2@3.2.3 版本。

**Comment by mdj11j** [comment]
@simaQ 升级后问题仍然存在，
缩放后 在最左边没有问题，往右移就会出现

**Comment by simaQ** [comment]
恩，能提供复现这个问题的源码和数据吗？ 我还具体排查下问题在哪里

**Comment by mdj11j** [comment]
@simaQ https://codepen.io/mdj11j/pen/NObgVR

**Comment by simaQ** [comment]
升级到 3.2.4-beta.1
