### ISSUE TITLE
Geometry  的position 方法 支持传入坐标或者回调函数吗

### ISSUE THREAD

**Issue by johnsky123** [antvis/f2#364]
chart.line().point('x*y')  只支持映射全部的x,y 点嘛    现在需要只映射部分点  应该怎么操作

**Comment by simaQ** [comment]
目前 position 是不支持回调的，如果只是想要映射部分点的话，可以借助 `.size()` 方法：


```js
chart.line().point('x*y').size('x', val => {
  if (val === 'xxxx') {  // 符合这个条件的，不展示，通过将点的大小设置为 0 
    return 0;
  } 
  return 5;
})
```

**Comment by johnsky123** [comment]
@simaQ   
![image](https://user-images.githubusercontent.com/11240977/46597804-342dc780-cb14-11e8-91fe-3ed1f5ae8161.png)
类似这样的图  只需 后三个点   实现 chart.point().position('x*y').adjust('stack').style('medalType', {lineWidth: 1, fill: '#fff', stroke: '#4468DA'})     这样的样式  并且后三个点所在的曲线  为虚线  这样的需求 f2 怎么实现
