### ISSUE TITLE
interval在直角坐标系和极坐标下，动画表现不一致

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#366]
* **F2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在直角坐标系中，2s后高度从90减小到20，柱状图从高到低
https://codepen.io/ziqiangwang/pen/NObyKM

在极坐标系中，2s后大小从90减小到20，圆弧表现很奇怪，绕了一大圈从90到20
https://codepen.io/ziqiangwang/pen/ZqBvdP

希望圆弧角度从90回退到20，需要怎么做呢

**Comment by ZiQiangWang** [comment]
startAngle: -Math.PI,
endAngle: 0

完整的圆形，动画是正确的，但是设置了开始和结束角度后，就异常了

**Comment by simaQ** [comment]
这里需要重新定义下入场和更新动画，改变了起始和结束角度之后，有可能会导致圆弧的结束弧度小于起始弧度，所以会很奇怪。因为我们极坐标的起始弧度是 -Math.PI / 2，结束弧度为 Math.PI * 1.5，所以会存在结束弧度小于起始弧度的情况。 参考这个 demo 就可以了： https://codepen.io/Sima/pen/RqbVeX

doAnimation 方法：

```js
// 自定义圆弧动画
   function doAnimation(shape, animateCfg) {
      const startAngle = shape.attr('startAngle');
      let endAngle = shape.attr('endAngle');
      if (startAngle > endAngle) {
        endAngle += Math.PI * 2;
      }
          
      shape.attr('endAngle', startAngle);
      shape.animate().to(F2.Util.mix({
        attrs: {
          endAngle
        }
      }, animateCfg));
   }
```
