### ISSUE TITLE
饼图 。数据项都为为0的时候 ，饼图不显示，只显示图例

### ISSUE THREAD

**Issue by shen-lan** [antvis/f2#371]
是因为我使用姿势不对吗？
把官网的demo饼图数据改为0  饼图也是不显示。。。。
[官网demo链接](https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/pie.html)

**Comment by simaQ** [comment]
数据项都为 0 时，饼图怎么展示呢？ 在饼图中，是通过每个扇形的角度来映射真实数据的大小的，当数据为 0 角度为 0，当然显示不出来。

这样的场景，我的建议是你在外部判断一下，当所有数据项为 0 时，在图表区域显示『数据为空』的提示信息

**Comment by shen-lan** [comment]
> 数据项都为 0 时，饼图怎么展示呢？ 在饼图中，是通过每个扇形的角度来映射真实数据的大小的，当数据为 0 角度为 0，当然显示不出来。
> 
> 这样的场景，我的建议是你在外部判断一下，当所有数据项为 0 时，在图表区域显示『数据为空』的提示信息

sorry  ，echarts用习惯了.......
我试着按您的建议做下，谢谢热心解答。
