### ISSUE TITLE
doc 404

### ISSUE THREAD

**Issue by jason19659** [antvis/f2#372]
https://antv.alipay.com/zh-cn/f2/3.x/api/custom-interaction.html
更多可参考 pie-select 交互行为类的实现。

网址404

**Comment by simaQ** [comment]
非常感谢反馈，这个链接是：https://github.com/antvis/f2/blob/master/src/interaction/pie-select.js

我会马上更新官网的网址的

**Comment by jason19659** [comment]
> 非常感谢反馈，这个链接是：https://github.com/antvis/f2/blob/master/src/interaction/pie-select.js
> 
> 我会马上更新官网的网址的

https://antv.alipay.com/zh-cn/f2/3.x/api/interaction.html

对于开发者来说，可以基于此机制封装自己的交互行为，详见 自定义交互行为 教程，非常欢迎一起建设。 链接404

**Comment by simaQ** [comment]
尴尬了... 真实非常抱歉，为你带来困扰了，我马上修正。
