### ISSUE TITLE
自定义interaction时，对于自定义shape，如何获取到该shape中的所有元素

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#379]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我定义了一个shape，point-text，由一个circle和一个text组成

在interaction中，通过container.get('children')获取到的，是一个数组，里面由circle和text组成，但是自定义选中的事件时，参考了interval-select的实现方式，selectedShape只能确保一个shape选中状态，并且不能获取到circle对应的text

我在自己实现时，采用如下的方案，不知道是否合理：
自定义shape中，定义circle的className为point，text的className为point-text
在_selectShapesByData中，child.get('className').indexOf('point')) !== -1来过滤，同时使用将
selectedShape定义为数组，以保存选中的多个shape

**Comment by simaQ** [comment]
因为你定义的这个 point-text 是一个 group，所以自然拿到的就是一个 group 对象，它是 circle 和 text 两个 shape 的容器，选中状态的话，有很多方法可以判断，给 group 赋值一个 className 做标识就可以了啊，或者在自定义 shape 那里给 group 添加一个 data 的属性存储原始数据，做下判断也是可以的。
