### ISSUE TITLE
一个特殊的需求——留空

### ISSUE THREAD

**Issue by NicholasNC** [antvis/f2#380]
![image](https://user-images.githubusercontent.com/10840542/47330948-a7a30d80-d6ac-11e8-9db6-060a33c499d7.png)

如上图：
1. 日期要显示
2. 同时柱形那块区域加上相关元素标注“数据未出”
3. 实际上最后两个是没有数据，而不是数据为0

下图的实现是错误的：
![image](https://user-images.githubusercontent.com/10840542/47330931-92c67a00-d6ac-11e8-895e-0cdba72686d9.png)

这个需求的本意是想给用户知道还会有数据在未来两天内产出，不知道是否支持这么特殊的需求实现

**Comment by simaQ** [comment]
要留空的话，直接将数值变成 null 即可，不要使用 0

**Comment by simaQ** [comment]
> 同时柱形那块区域加上相关元素标注“数据未出”

这个直接使用 chart.guide().html() 绘制即可。
