### ISSUE TITLE
在使用pinch进行缩放时，坐标轴的label没有重新计算，最终挤在一起

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#382]
* **F2 Version**:3.2.4-beta.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
pan and pinch 交互会在 3.3 版本重新优化一波

**Comment by ZiQiangWang** [comment]
请问3.3是什么时候呀？

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/47469882-d26c9d80-d835-11e8-9a93-1a204d8e775a.png)
