### ISSUE TITLE
折线图可以自定义点击事件进行滑动吗？

### ISSUE THREAD

**Issue by NicholasNC** [antvis/f2#384]
![image](https://user-images.githubusercontent.com/10840542/47422916-5c752180-d7b6-11e8-9dc0-2dd275bd9e1d.png)

请问能否如上图所示，自定义点击事件，点击上图两个按钮实现数据的移动？

**Comment by simaQ** [comment]
这个可以直接通过操作 canvas 这个 dom，类似于 web 上面实现图片滑块的原理
