### ISSUE TITLE
平移  折线图绘制错误

### ISSUE THREAD

**Issue by xiao-xiansheng** [antvis/f2#391]
![z1 v2xwhi npz pyl p8](https://user-images.githubusercontent.com/22864419/47635094-c44cb300-db8e-11e8-8bed-bb5cdbead698.png)
![7fe9 nc2 senp0dlr1ux 2](https://user-images.githubusercontent.com/22864419/47635102-c9a9fd80-db8e-11e8-93f1-a87a8b8267eb.png)

数据格式 [{amount: 10,yrMonth:"14.01"},{amount: 10,yrMonth:"14.02"}]

**Comment by simaQ** [comment]
请提供 F2 版本号以及可复现问题、可运行的代码。

**Comment by simaQ** [comment]
时间过长未提供可运行的代码，即将此 issue 关闭，建议升级至 F2 最新版本。
