### ISSUE TITLE
图表再次渲染，会有上一次数据的bug

### ISSUE THREAD

**Issue by ChazLun** [antvis/f2#399]
代码参考例子：https://antv.alipay.com/zh-cn/f2/3.x/demo/line/basic.html
1.数据一开始初始化的时候，按在图表上面快速移动。图表正常；
2.重新初始化了数据源，按在图表上面快速移动，会频繁出现上一次的图表；
3.在new F2.Chart之前，尝试用了clear，repaint还是changeData。都会出现该bug。
4.代码跟官网提供的例子一样，只是更改了数据源进来。

![12](https://user-images.githubusercontent.com/22490984/48053854-a9a9b800-e1e6-11e8-920f-e1f0a3697405.gif)

**Comment by simaQ** [comment]
你好，我按照你的描述尝试复现，没有什么问题。

麻烦提供下可以复现问题的代码，并提供 F2 的版本。

**Comment by ChazLun** [comment]
代码：
var chart = new F2.Chart({
        id: name,
        pixelRatio: window.devicePixelRatio
      })
chart.source(data, {
        date: {
          type: 'timeCat',
          range: [0, 1],
          tickCount: 3
        }
      })

        chart.scale('value', {
          min: -19.5,
          max: -3
        })

      chart.axis('date', {
        label: function label(text, index, total) {
          var cfg = {
            textAlign: 'center'
          }
          if (index === 0) {
            cfg.textAlign = 'start'
          }
          if (index > 0 && index === total - 1) {
            cfg.textAlign = 'end'
          }
          return cfg
        }
      })
chart.tooltip({
        showCrosshairs: true,
        onShow: function onShow(ev) {
          var items = ev.items
          items[0].name = items[0].title
          items[0].value = `${items[0].value} dB`
        }
      })
chart.line().position(coord).shape('smooth').color('l(0) 0:#36f4ca 0.5:#36c7f4 1:#0a7ff3')
chart.render()
版本号：
![image](https://user-images.githubusercontent.com/22490984/48183816-fae2b480-e36a-11e8-8138-1ece7a278227.png)

**Comment by ChazLun** [comment]
代码：
```
var chart = new F2.Chart({
  id: name,
  pixelRatio: window.devicePixelRatio
})
chart.source(data, {
  date: {
    type: 'timeCat',
    range: [0, 1],
    tickCount: 3
  }
})

chart.scale('value', {
  min: -19.5,
  max: -3
})

chart.axis('date', {
  label: function label(text, index, total) {
    var cfg = {
      textAlign: 'center'
    }
    if (index === 0) {
      cfg.textAlign = 'start'
    }
    if (index > 0 && index === total - 1) {
      cfg.textAlign = 'end'
    }
    return cfg
  }
})
chart.tooltip({
  showCrosshairs: true,
  onShow: function onShow(ev) {
    var items = ev.items
    items[0].name = items[0].title
    items[0].value = ${items[0].value} dB
  }
})
chart.line().position(coord).shape('smooth').color('l(0) 0:#36f4ca 0.5:#36c7f4 1:#0a7ff3')
chart.render()
```
版本号：
![image](https://user-images.githubusercontent.com/22490984/48183930-6167d280-e36b-11e8-824c-e7a1425060d1.png)

**Comment by simaQ** [comment]
@ChazLun 久等了，关于你的问题，我并没有复现，调用 chart.changeData() 重新更新数据源并不会出现你描述的情况。

如果你使用的是 react 技术栈，请检查下组件的生命周期。

![343](https://user-images.githubusercontent.com/6628666/48525316-ab4a3e80-e8be-11e8-8467-1ef94fbab643.gif)


```js
const data = [
      { "date": "2018-11-06 13:59:14", "value": -8 },
      { "date": "2018-11-05 21:18:18", "value": -5 },
      { "date": "2018-11-05 18:28:21", "value": -6 },
      { "date": "2018-11-05 18:08:18", "value": -11 },
      { "date": "2018-11-05 13:51:59", "value": -8 },
      { "date": "2018-11-05 13:50:16", "value": -12 },
      { "date": "2018-11-05 13:40:40", "value": -6 },
      { "date": "2018-11-05 13:08:39", "value": -5 },
      { "date": "2018-11-05 13:06:32", "value": -8 },
      { "date": "2018-11-05 12:55:20", "value": -9 }
    ];
    var chart = new F2.Chart({
      id: 'mountNode',
      pixelRatio: window.devicePixelRatio
    })
    chart.source(data, {
      date: {
        type: 'timeCat',
        range: [0, 1],
        tickCount: 3
      }
    })

    chart.scale('value', {
      min: -19.5,
      max: -3
    })

    chart.axis('date', {
      label: function label(text, index, total) {
        var cfg = {
          textAlign: 'center'
        }
        if (index === 0) {
          cfg.textAlign = 'start'
        }
        if (index > 0 && index === total - 1) {
          cfg.textAlign = 'end'
        }
        return cfg
      }
    });
    chart.tooltip({
        showCrosshairs: true,
        onShow: function onShow(ev) {
          var items = ev.items
          items[0].name = items[0].title
          items[0].value = items[0].value
        }
      })
    chart.line().position('date*value').shape('smooth').color('l(0) 0:#36f4ca 0.5:#36c7f4 1:#0a7ff3')
    chart.render();

    setTimeout(() => {
      chart.changeData(data.slice(3, -1));
    }, 2000);
```
