### ISSUE TITLE
在将tooltip绑定到legend同时，自定义tooltip样式

### ISSUE THREAD

**Issue by ZiQiangWang** [antvis/f2#400]
* **F2 Version**: 3.2.4-beta.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
遇到以下的需求，需要保持legend后显示数据的同时，显示当前的横坐标值。

![image](https://user-images.githubusercontent.com/11312811/48113915-dcf84f80-e297-11e8-838f-eecec0d15038.png)

我在这个[例子](https://antv.alipay.com/zh-cn/f2/3.x/demo/line/series.html)基础上做了修改，通过配置tooltip如下，
```
    showTitle: true,
    showItemMarker: false,
    nameStyle: {
    	fontSize: 0,
    },
    valueStyle: {
    	fontSize: 0,
    },
    itemMarkerStyle: {
      fontSize: 0,
    },
```
达到了如下效果，但是和我预期还是有差距，不知道有没有更好的方法实现
![image](https://user-images.githubusercontent.com/11312811/48114190-04035100-e299-11e8-8d22-d11e9d07b624.png)

**Comment by simaQ** [comment]
参考这个 demo: https://antv.alipay.com/zh-cn/f2/3.x/demo/area/stacked.html

![image](https://user-images.githubusercontent.com/6628666/48124253-d3321480-e2b6-11e8-9654-845977ff8c17.png)


另外在将要发布的 3.3 版本中将会在框架内直接支持这个功能， 11.22 敬请期待~~~~

**Comment by ZiQiangWang** [comment]
哈哈，多谢多谢
