### ISSUE TITLE
我该如何在下面代码的基础上实现这样的效果呢？

### ISSUE THREAD

**Issue by newBird01** [antvis/f2#401]
![_20181103180533](https://user-images.githubusercontent.com/25924193/48109447-7583d500-e282-11e8-9e30-2a4664a3e103.png)
[这是我写的， 但是不是我想要的效果--项目地址](https://github.com/newBird01/f2canvas)

**Comment by simaQ** [comment]
你好，首先提 issue 时请遵照模板，将运行平台这些注明。
针对你的问题：

#### 1. 图例不换行的原因

```js
chart.legend('name', {
  itemWidth: null // 按照每个图例项实际的文本宽度渲染
});
```

请阅读 API  文档，itemWidth 并不支持 `true`。

#### 2. 双侧坐标轴的问题

如果需要能够绘制双侧坐标轴，你需要改变你的数据结构，按照你目前的数据结构以及图形图法，是不会生成双坐标轴的，但是这样你就要自定义图例。总之你如果要根据现在的数据结构实现这个图的效果，在我看来非常麻烦，基本就是走弯路。

Anyway，按照你的要求帮你实现了，demo 地址： https://codepen.io/Sima/pen/aQvXXN。需要说明的是，你需要自己计算 Y 轴的坐标轴刻度值。

PS：
1. 其实在你这个例子中，并不一定要使用双 Y 轴我认为。
2. 不要乱给我们 F2 的属性赋值，我们的 API 里面没有写明可以这么随便赋值的 ...

**Comment by newBird01** [comment]
@simaQ 谢谢您的回复，我是新手，我再仔细看看api,麻烦您了哦！
