### ISSUE TITLE
regionFilter y轴数值为0 时 无法绘制虚线

### ISSUE THREAD

**Issue by johnsky123** [antvis/f2#404]
chart.guide().regionFilter({
        start: [points[3].x,points[3].y],
        end: [points[4].x, points[4].y],
        color: '#fff',
        style: {
          lineDash: [ 2, 6 ]
        }
      })
当  y 轴 数值为0 的时候  无法绘制出虚线

**Comment by simaQ** [comment]
请提供完整可复现的代码
