### ISSUE TITLE
f2 在React Native上的支持

### ISSUE THREAD

**Issue by wanshijie3** [antvis/f2#406]
请问f2 在React Native上是否支持呢,之前尝试运行过 https://github.com/chenshuai2144/f2-demo这个项目,所有者声称这个是f2在RN上的实现,但是实在无法运行,请问对于支持ReactNative是否有具体实例呢

**Comment by paddingC** [comment]
我也遇到了这个问题，按照demo写无法渲染出来

**Comment by wanshijie3** [comment]
多端异构：在完美支持 H5 环境的同时，同时兼容 Node.js，支付宝小程序、微信小程序、React Native以及 Weex 端的渲染，一份代码，多设备多环境渲染。

f2的官方文档里面不是声明支持React Native了吗,而且也给出了链接,但是现在demo无法运行,询问具体支持的程度无人回应,之前相关的issues也没说清楚,这是一个共同促进的问题吧,为什么避而不谈呢?

**Comment by simaQ** [comment]
对于这个问题不能及时响应表示非常抱歉。

之前不能运行的原因初步推测是由于打包问题造成的，但是具体的原因处于各种原因就没有继续跟进，当然我们很欢迎共建，也请给我们一些时间去解决。

**Comment by paddingC** [comment]
自己写的canvas打包之后是可以显示的，但是引入你们的组件之后就会一片空白呢，官方给的demo跑不起来也不给说明一下，然后自己在找问题？会白白浪费很多时间呢

**Comment by wanshijie3** [comment]
> 对于这个问题不能及时响应表示非常抱歉。
> 
> 之前不能运行的原因初步推测是由于打包问题造成的，但是具体的原因处于各种原因就没有继续跟进，当然我们很欢迎共建，也请给我们一些时间去解决。

好的,谢谢

**Comment by simaQ** [comment]
@paddingC 我们开源寻求的是共建互赢，并不是作为一个服务者，当然对于这个问题迟迟不回复也是有不对之处，如果对您的时间造成可极大的浪费我们表示非常抱歉，对于 react native 的支持，在第一个可运行 demo 出来之后我们确实没有花特别多的时间在这个平台的支持上，至于为什么不能运行，我们需要花时间去解决，毕竟作为一个可视化工程师，我们更多专注于可视化上，不是对所有的平台都非常熟悉。

**Comment by paddingC** [comment]
嗯，谢谢

**Comment by fanlide** [comment]
自己写的一个可用的[react-native-f2](https://github.com/fanlide/react-native-f2)。根据wx-f2完成的，暂时只能说可用

**Comment by wanshijie3** [comment]
> 自己写的一个可用的[react-native-f2](https://github.com/fanlide/react-native-f2)。根据wx-f2完成的，暂时只能说可用

可以运行,第一遍运行失败,后来发现和babel有关,修改版本后可以了,目前存在点击闪动问题

**Comment by fanlide** [comment]
@wanshijie3 嗯，闪动问题跟使用的canvas插件有关。react-native-canvas是用webview封装的。其它没找到好的插件，暂解决不了

**Comment by fanlide** [comment]
@wanshijie3 上周发现了gcanvas，研究了下，用它重构解决了闪动问题。现在还剩两个问题

1. Interaction的交互行为不能用
2. 大数据时存在性能问题

**Comment by httol** [comment]
动画引入GroupAnimation，好生硬的动画

**Comment by simaQ** [comment]
GroupAnimation 只提供了图表第一次初始化绘制的时候的动画。

**Comment by wangyeming** [comment]
我可以跑起来https://github.com/chenshuai2144/f2-demo 这个项目，但是画饼状图的文本时，直接就挂了。referenceError:cannot find variable：document

看起来在rn上，问题还是非常多阿

**Comment by zenggang97** [comment]
> 我可以跑起来https://github.com/chenshuai2144/f2-demo这个项目，但是画饼状图的文本时，直接就挂了.referenceError：找不到变量：document
> 
> 看起来在RN上，问题还是非常多阿

目前是可以在rn上运行，但是不支持交互，事件，只支持图表绘制能力

**Comment by zenggang97** [comment]
在ios上图表显示没有问题，在android上图表大部分时候会不显示（第一次运行的时候会显示，但之后就再也没显示出来过），可能和gcanvas有关

**Comment by simaQ** [comment]
@mmorcc F2 是可以在 native-react 上渲染的，并不是不支持... 另外 F2 并不支持水波图的绘制。

**Comment by aloneszjl** [comment]
借鉴native-echarts ，自己搞了个 https://github.com/aloneszjl/react-native-f2chart ，目前没发现有什么问题

**Comment by L-x-C** [comment]
> 借鉴native-echarts ，自己搞了个 https://github.com/aloneszjl/react-native-f2chart ，目前没发现有什么问题

如果使用react-native-webview好像就不能使用tooltip了

**Comment by aloneszjl** [comment]
@L-x-C 可以的，把
```
onChange: function(obj) {
        window.postMessage(stringify(obj))
    },
```
改成
```
onChange: function(obj) {
      window.ReactNativeWebView.postMessage(stringify(obj))
    },
```

**Comment by GospelHW** [comment]
大佬们啊，那这到底是能用还是不能用啊...

**Comment by wangyeming** [comment]
各位大佬们，经过我们项目组的实践，f2+webview+rn/weex/native 去实现图表库是最好的方案，支付宝似乎也是这么做的！

**Comment by aloneszjl** [comment]
@GospelHW https://github.com/aloneszjl/react-native-f2chart

**Comment by httol** [comment]
其实rn可以使用html5去承载f2，借助webview嵌入rn，效果很好
