### ISSUE TITLE
按需引入时的打包问题

### ISSUE THREAD

**Issue by leungwensen** [antvis/f2#41]
* **F2 Version**: all
* **Platform**: all

目前只提供了 ES6 的源码，当用户在项目里配置了 babel-loader 忽略 node_modules 文件夹时，最终打包出来的文件有问题。

解决方案：

1. 在 webpack 配置里，把 f2 加到 babel 的打包列表中；
2. 提供一个 ES5 版本的源码 lib 文件夹

**Comment by simaQ** [comment]
大湿兄，这两种方案有具体的区别吗？

**Comment by leungwensen** [comment]
方案一是目前用户碰到按需引入问题的解决方法，用户在用的时候配置 webpack、babel
方案二是我们发布前打包好 lib 文件夹，让用户直接引用 require('@antv/f2/lib/xxx.js'), 不需要再配置 babel。

标准的 npm 包应该都要提供方案二的解法，下周过去几个包我统一做一下构建

**Comment by simaQ** [comment]
恩，点赞！~
