### ISSUE TITLE
支付宝小程序 IOS 不兼容 changeData

### ISSUE THREAD

**Issue by newBird01** [antvis/f2#411]
支付宝小程序 IOS 不兼容 changeData;
安卓和编辑器工具正常，IOS不能通过changeData改变视图；
这是我的代码地址[BUG复现](https://github.com/newBird01/f2canvas)

**Comment by simaQ** [comment]
@newBird01 你好，这个应该不是 F2 changeData() 接口的问题，因为我在你的 drawOldhouseChart() 方法里面调用 chart.changeData() 接口是正常运行的，可能是按钮交互、异步请求等的问题，你先定位下。

**Comment by newBird01** [comment]
谢谢你哦，这个问题，我换了一种方式解决了。
