### ISSUE TITLE
饼图中，手动指定每一个扇区的color时，希望legend的color和扇区color保持一致

### ISSUE THREAD

**Issue by miaojiuchen** [antvis/f2#412]
代码大概是这样：
```javascript
chart
    .interval()
    .position('a*percent')
    .color('name*color', (type, color) => color);
```
扇区的颜色起作用了，但是legend的圆点没有变色，有什么方法吗？

**Comment by simaQ** [comment]
默认会对应上的，你是不是自己定义了图例，如果是的话，自己在自定义图例那里把颜色更新下。

如果不是自己定义了图例，提供可运行的代码

**Comment by miaojiuchen** [comment]
@simaQ  https://codepen.io/anon/pen/VVmwpv  

qiqi一个人维护这个项目吗好厉害_(:зゝ∠)_

**Comment by simaQ** [comment]
是一个 BUG，我修复下

**Comment by simaQ** [comment]
@miaojiuchen 久等了，是这样的，目前我们 color 内部机制还不支持这种由多字段共同映射确定色值，所以这个解决办法只能是自己手动写一个 colorMap 对象来解决了。

```js
const colorMap = {
  '芳华': 'red',
  '妖猫传': 'orange',
  '机器之血': 'pink'
};
.color('name', r => colorMap[r])
```

**Comment by miaojiuchen** [comment]
@simaQ 好的，我瞅瞅
