### ISSUE TITLE
能否支持svg渲染

### ISSUE THREAD

**Issue by kang558** [antvis/f2#415]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

### [echarts svg渲染](http://echarts.baidu.com/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93)

**Comment by dxq613** [comment]
考虑到 F2 主要是面向 C 端的用户场景，兼容性、多端适配是最重要的因素，所以 SVG 的版本不考虑。

**Comment by kang558** [comment]
> 考虑到 F2 主要是面向 C 端的用户场景，兼容性、多端适配是最重要的因素，所以 SVG 的版本不考虑。

好吧
