### ISSUE TITLE
vue中在别的路由页面触发了tooltip 的 onHide 事件， 请问怎么解决

### ISSUE THREAD

**Issue by wangzhiiang** [antvis/f2#417]
this.chartLinePro.tooltip({
        custom: true, // 自定义 tooltip 内容框
        onChange: function onChange (obj) {
          console.log(_this)
          var legend = _this.chartLinePro.get('legendController').legends.top[0]
          var tooltipItems = obj.items
          var legendItems = legend.items
          var map = {}
          legendItems.map(function (item) {
            map[item.name] = _.clone(item)
          })
          tooltipItems.map(function (item) {
            var name = item.name
            var value = item.value
            if (map[name]) {
              map[name].value = value
            }
          })
          legend.setItems(_.values(map))
        },
        onHide: function onHide () {
          console.log(_this.chartLinePro.get('legendController'))
          var legend = _this.chartLinePro.get('legendController').legends.top[0]
          legend.setItems(_this.chartLinePro.getLegendItems().country)
        }
      })

**Comment by wangzhiiang** [comment]
触发显示tipsShow之后点击页面任何位置就会触发onHide事件，我在beforeDistory之前对已经对chart做了distory()处理

**Comment by simaQ** [comment]
为什么别的路由页面会影响当前呈现的页面？我不是很明白 vue 的这个机制。至于 

> 触发显示tipsShow之后点击页面任何位置就会触发onHide事件

这个确实是这么设计的，不过我们同时还开放了一个参数 `alwaysShow` 参数，用于控制手指移出触发区域，是否仍显示提示框内容。

**Comment by wangzhiiang** [comment]
这个其实也没有太大问题只是在其他页面点击会报错， 可能是我在页面跳转的时候没有把chart置空， 置空之后就好了 chart = ''
