### ISSUE TITLE
一个页面有多个图表，真机调试的时候只能显示一个

### ISSUE THREAD

**Issue by newBird01** [antvis/f2#418]
一个页面有多个图表，数据是异步获取，真机调试的时候值图表能显示一个，
小程序编辑器调试工具可以显示多个：如下图是支付宝小程序的编辑器可以显示多个图标
![image](https://user-images.githubusercontent.com/25924193/48552013-2a1c9700-e912-11e8-9e83-f73cab1d6d65.png)
[BUG复现地址](https://github.com/newBird01/f2canvas)

**Comment by simaQ** [comment]
@newBird01 这个问题是你自己写法的问题，你的代码里面把所有返回的 chart 对象都存储到 self.oldchart 中，以至于前面几个创建的 chart 对象被后面创建的覆盖了，自然就绘制不出来了，你把这句注释掉就好了。

![image](https://user-images.githubusercontent.com/6628666/48593273-0c3d4980-e987-11e8-9d6f-f6dbb9170587.png)

建议后面请先自己多调试代码解决问题。
