### ISSUE TITLE
代码是否可以精简？

### ISSUE THREAD

**Issue by hustcc** [antvis/f2#420]
https://github.com/antvis/f2/blob/6e1870147d420a1438384921afb9b34ac864c3a4/src/graphic/container.js#L54-L66

上面的代码应该等效于：

```js
sort() {
    const children = this.get('children');
    children.sort(function(left, right) {
      return left.get('zIndex') - right.get('zIndex')
    });

    return this;
  },
```

原代码的意思是：
 - 先按照 zindex 排序
 - 如果 zindex 相同，然后根据元素所在的索引排序

但是元素的索引 idx 本身就是排序好的，所以第二层排序应该没有意义的，反而可能因为排序不稳定而造成非期望的结果！

**Comment by simaQ** [comment]
这是 shape 以及 group 对象的图层排序，需要保证排序前后的稳定性。而不同的浏览器内核，他们对于 Array.sort() 的实现是不同的，有的是稳定排序而有的是非稳定排序（比如  chrome 的 v8 使用的就是快速排序），这样就会导致我们的 shape 在排序之后顺序同排序前不一致，影响到一些拾取相关的交互。

所以目前采用这种方法，排序的稳定性。

更多的可以参考这篇文章：http://efe.baidu.com/blog/talk-about-sort-in-front-end/

当然如果有更好更精简的方法，欢迎一起交流，给我们提 PR 👍

**Comment by hustcc** [comment]
首先直觉上，zindex 排序后再根据 index 排序一次就能保证稳定性，这个不一定正确😂，这个待调研和测试。

另外，为了稳定而在 obj 上增加冗余数据，并且把一次排序变成两次，感觉不划算。

v8 在最近的版本，把 sort 改成了稳定的实现。

**Comment by simaQ** [comment]
@hustcc 这主要涉及到图表层面的图形拾取交互问题，比如散点图的 hover 高亮。如果能够保证所有浏览器引擎的排序都是稳定排序，当然两次很不划算。最开始我们就是直接使用 Array.sort() 对图层按照 zIndex 进行排序，因为遇到了我说的这个问题，才增加一层的排序。当然还是那句话有更好更精简的方法能够解决这个问题，当然更好。
