### ISSUE TITLE
请问折线图是否支持双纵轴呢？

### ISSUE THREAD

**Issue by xiaoming0827** [antvis/f2#422]
在官网的文档上只看到柱状图支持双Y轴
折线图没有找到实现双Y轴的方法，请问咱们的是否支持呢？谢谢

**Comment by simaQ** [comment]
F2 生成双 Y 轴的机制是：只要你绘制两种 geometry 时，映射到 position() 通道的 Y 不同就会对应生成两条 Y 轴。

参考这个 demo: https://codepen.io/Sima/pen/bQLzzp

**Comment by curry-wxj** [comment]
如何能 取消这种默认机制呢？  比我就想要一个y轴 @simaQ
