### ISSUE TITLE
点击api为什么跳到语雀 网站有更改吗？

### ISSUE THREAD

**Issue by huangchaofei** [antvis/f2#423]

**Comment by simaQ** [comment]
@huangchaofei 后续我们的教程、API 文档都会托管在语雀上，无论是我们文档的阅读体验还是后续的快速更新迭代、反馈都很有帮助，请知晓~

**Comment by huangchaofei** [comment]
只是今天使用的时候 突然发现很多链接都跳转到语雀上  感觉搜索没有之前的好用

**Comment by simaQ** [comment]
可以这么操作；

![image](https://user-images.githubusercontent.com/6628666/48895675-9fdbb200-ee80-11e8-9c55-633d83cfa9f3.png)
