### ISSUE TITLE
关于axis 横轴线宽度的bug？

### ISSUE THREAD

**Issue by komagic** [antvis/f2#424]
* **F2 Version**: 3.2.2
* **Platform**: mac os
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我设置了
```
chart.axis('time',{ line:{lineWidth:0.1 })
```
 用mac屏幕下打开，显示如下图，正常
![2018-11-23 2 07 20](https://user-images.githubusercontent.com/13415767/48930172-abcf7e80-ef29-11e8-8baa-f472077f845d.png)，
然后我把窗口放到普通显示器下，然后打开该chart，下面的线就变这么粗了。如下图：
![2018-11-23 2 13 51](https://user-images.githubusercontent.com/13415767/48930217-0963cb00-ef2a-11e8-801f-68d63d765edb.png)

奇怪的是在mac pro下打开的内容移动到普通显示器下是正常的，但是如果再普通显示器下打开的就不正常？

**Comment by simaQ** [comment]
这个不是 BUG，是浏览器渲染的问题。 具体请参考：https://stackoverflow.com/questions/24669578/canvas-line-behaviour-when-0-linewidth-1
