### ISSUE TITLE
uglifyjs-webpack-plugin  1.3.0版本 压缩   ecma参数配置6及以上，ios8.1报错： Unexpected token ','. Expected a ':' following the property name 'x'.

### ISSUE THREAD

**Issue by zaoyu63** [antvis/f2#425]
* **F2 Version**: 3.3.0
* **Platform**: 饼图
ios版本： 8.1
uglifyjs-webpack-plugin 配置信息
new UglifyJsPlugin({
uglifyOptions: {
ie8: false,
ecma: 6,
mangle: true,
output: { comments: false },
compress: { warnings: false }
},
sourceMap: false,
cache: false,
parallel: os.cpus().length * 2
}),
错误信息
Unexpected token ','. Expected a ':' following the property name 'x'.

* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/30930585/48930603-a0ca1d80-ef2c-11e8-8c23-6426b991ddf6.png)

* **CodePen Link**:

**Comment by zaoyu63** [comment]
ios版本： 8.1
uglifyjs-webpack-plugin 配置信息
new UglifyJsPlugin({
        uglifyOptions: {
          ie8: false,
          ecma: 6,
          mangle: true,
          output: { comments: false },
          compress: { warnings: false }
        },
        sourceMap: false,
        cache: false,
        parallel: os.cpus().length * 2
      }),
错误信息
 Unexpected token ','. Expected a ':' following the property name 'x'.

**Comment by simaQ** [comment]
你这么描述让我无从下手...

**Comment by zaoyu63** [comment]
vue项目， 使用webpack构建工具,  uglifyjs-webpack-plugin 1.3.0版本压缩代码， f2版本3.3.0

这是使用方式
![image](https://user-images.githubusercontent.com/30930585/48940324-1c8a9100-ef52-11e8-8d43-50d5c9752132.png)
这是压缩配置方式
![image](https://user-images.githubusercontent.com/30930585/48940385-522f7a00-ef52-11e8-91f4-0494bd7cf8cd.png)
报错信息
![image](https://user-images.githubusercontent.com/30930585/48940457-97ec4280-ef52-11e8-9376-e39a50b57b82.png)

**Comment by zaoyu63** [comment]
uglifyjs-webpack-plugin 升级到2.0.1, 问题解决
