### ISSUE TITLE
每次展示数据量多会挤压到一块。为何不是超出隐藏显示滚动条呢？

### ISSUE THREAD

**Issue by huangjieqiu** [antvis/f2#426]
如题：

**Comment by huangjieqiu** [comment]
<img width="362" alt="wechat773fc8eea68f421d1c7426da47ca5892" src="https://user-images.githubusercontent.com/22678921/48992090-145c6c80-f171-11e8-96ad-6af881aa83f2.png">

**Comment by adow** [comment]
请问关闭是因为这个问题解决了吗？在大数据量的时候，怎么样出现滚动条呢？

**Comment by yangfandashuaige** [comment]
这也是我想问的，
