### ISSUE TITLE
圆饼图legend positon为right时设置itemWidth无效吗

### ISSUE THREAD

**Issue by huangchaofei** [antvis/f2#427]
![image](https://user-images.githubusercontent.com/25143078/49055840-15a29d80-f234-11e8-8e59-2005f0ed3a44.png)
这是想要的效果
![image](https://user-images.githubusercontent.com/25143078/49055847-205d3280-f234-11e8-8eb1-e4eea5ed002d.png)
这是实际的效果 0 0 
代码：
this.chargeSourceChart = new F2.Chart({
        id: 'charge-source',
        pixelRatio: window.devicePixelRatio,
        padding: [0,'auto'],
        height:163
      });
      this.chargeSourceChart.source(this.chargeSourceData, {
        percent: {
          formatter: function formatter(val) {
            return val + '%';
          }
        }
      });
      this.chargeSourceChart.tooltip(false);
      this.chargeSourceChart.legend({
        position: 'right',
        nameStyle:{
            fontSize: '13', // 文本大小
        },
        marker:{
            symbol:'square'
        },
      });
      this.chargeSourceChart.legend('source',{
          itemWidth:150
      })
      // this.chargeEleChart.legend(false);
      this.chargeSourceChart.coord('polar', {
        transposed: true,
        innerRadius: 0.8,
        radius: 1
      });
      this.chargeSourceChart.axis(false);
      this.chargeSourceChart.interval().position('a*value').color('source', (source)=>{
          if(source === '移动端'){
              return '#FFA84F'
          }
          if(source === '充电卡'){
              return '#8F83FF'
          }
      }).adjust('stack');
      this.chargeSourceChart.guide().html({
        position: ['50%', '56%'],
        html: '<div style="width: 100px;height: 40px;text-align: center;">' + '<div style="font-size: 11px">充电消费来源</div>'  + '</div>'
      });
      this.chargeSourceChart.render();
可以把这四个legend设置成一样的吗 这样图表大小才能一样

**Comment by simaQ** [comment]
这个你在初始化 chart 的地方设置下 padding 就可以调整了，你只要让右侧的 padding 都是同一个值就可以了。

```js
new F2.Chart({
  id: 'charge-source',
  pixelRatio: window.devicePixelRatio,
  padding: [ 0, 100, 0, 0 ]
  height:163
});
```

**Comment by huangchaofei** [comment]
嗯 可以的 谢谢 自己没想到 @simaQ
