### ISSUE TITLE
请问咱们F2如何做手机横屏？

### ISSUE THREAD

**Issue by xiaoming0827** [antvis/f2#428]
目前想将F2绘制的图表横屏显示在手机上
思路是使用css旋转了F2canvas所在容器90度
但是导致图表滑动touch还是左右方向的，请问如何将解决这个问题呢？谢谢

**Comment by simaQ** [comment]
... 直接调用 chart.changeSize(width, height)

**Comment by simaQ** [comment]
chart.changeSize() 不是改变坐标轴大小，而是改变画布大小。
至于你的方案，旋转之后 touch 事件肯定是有问题的。

至于你说的横屏显示，F2 官网的示例都支持横竖屏切换，你自己扫码看下： https://antv.alipay.com/zh-cn/f2/3.x/demo/line/basic.html，思路是这样的：
1. canvas 元素宽高响应式，即使用 css 分别在横竖屏下定义对应的宽高
2. 监听 window 的 orientationchange 事件，发生横竖屏切换的时候刷新页面

**Comment by xiaoming0827** [comment]
非常感谢细心的解答，但是目前的需求是可能手机锁定了屏幕旋转，但是需求点击一个全屏按钮后横向全屏显示咱们图表，所以才考虑旋转的问题。
请问咱们这个有啥好的解决方案吗？十分感谢您的耐心解答

**Comment by wqzwh** [comment]
@xiaoming0827  我之前也遇到你这样的需求，我是通过点击全屏按钮后，新弹出一个层，然后用rotate做下旋转，并且在这个层上进行做图表渲染操作，就类似一个modal弹窗一样。

**Comment by xiaoming0827** [comment]
@wqzwh 但是旋转过后图表的touch时间还是左右方向的，不能正常的拖动，这个你是如何解决的呢？

**Comment by wqzwh** [comment]
@xiaoming0827  当时只是单纯的图表展示，并没有绑定方法，那还得想想别的办法

**Comment by xiaoming0827** [comment]
解决方案是让客户端webview支持屏幕旋转，这样是最好的方案

**Comment by G1King** [comment]
横屏之后的   想让柱状图 可以 滑动   但是事件 是左右方向的  不能正常滑动啊  大佬们怎么解决的啊

**Comment by leaper1** [comment]
最后解决了吗，就是旋转后手势错误的问题

**Comment by Strongstar** [comment]
我也遇到了 但是并没有解决方案呀

**Comment by Strongstar** [comment]
求大佬给个解决方案

**Comment by aitexiaoy** [comment]
1. 原生webview旋转
2.采用iframe打开图表，转iframe

**Comment by aitexiaoy** [comment]
官方已支持全屏了，直接旋转div然后再设置图表实例 
```
 chart.landscape(true);
```

**Comment by 30stomars** [comment]
> 官方已支持全屏了，直接旋转div然后再设置图表实例
> 
> ```
>  chart.landscape(true);
> ```

我这样试了还是不行，横屏展示后，左右方向还是竖屏状态的左右

**Comment by aitexiaoy** [comment]
> > 官方已支持全屏了，直接旋转div然后再设置图表实例
> > ```
> >  chart.landscape(true);
> > ```
> 
> 我这样试了还是不行，横屏展示后，左右方向还是竖屏状态的左右

版本是3.8.*以上版本吗？
