### ISSUE TITLE
在`type: 'arc'`下fillStyle失效

### ISSUE THREAD

**Issue by cydiacen** [antvis/f2#429]
* **F2 Version**:3.3.0
* **Platform**:web
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://antv.alipay.com/zh-cn/f2/3.x/demo/radar/line.html
具体问题就是上面链接是官方的链接，直接在138行增加一条代码`fillStyle:'#cd0200',`
目的是为了实现按区域显示背景色（代码上可以用rgba但是为了方便 直接没有透明通道的颜色 一样有问题），可是这段代码添加上去是没有效果的，感觉好像跟`type: 'arc'`有冲突，去掉`type: 'arc'`又是有效果的，可是我现在的场景就是需要圆形的雷达图。
望解答！谢谢！

**Comment by simaQ** [comment]
我们的网格线不支持颜色填充，只能设置线的颜色。

**Comment by cydiacen** [comment]
我试过了 如果没有`type: 'arc'`是支持填充的 加了就不支持 ，后期有优化的打算吗 起码应该体验一致嘛 对吧，一种有 一种没有 给人的感觉就是会不会是自己用错了 或者代码有bug

**Comment by simaQ** [comment]
我们对于 fill 填充确实不支持，这个并不是我们预期的。对于表现不一致的问题这个确实需要优化一下。

**Comment by simaQ** [comment]
@cydiacen，`@antv/f2@3.3.1` 版本已经修复，type: 'arc' 与非 `arc` 表现一致，均支持填充。

**Comment by cydiacen** [comment]
@simaQ 那么请问下 my-f2的项目会同步更新吗 因为我用的是钉钉小程序

**Comment by cydiacen** [comment]
@simaQ 我也尝试了在`node_module`里面对应的文件 添加了` this._attrs.canFill = true;` 但是好像 并没有效果。。讲道理用这种方式也是可行的吧 毕竟小程序上传是包含`node_module`的

**Comment by simaQ** [comment]
...  你使用的 my-f2 是什么版本？ 1.1.4 是话你重新安装下会更新到最新版的   https://github.com/antvis/my-f2/blob/1.1/package.json#L94

**Comment by cydiacen** [comment]
@simaQ emmm 在官网demo上 更改了版本号之后进行测试 是可行的 但是在小程序上 却没有效果。。。我去`node_module`里也检查了下 确实是新的代码。。可是弧形还是不能填充。。

**Comment by cydiacen** [comment]
我发现是因为 my-f2的包里的build/my-f2.js 不是最新版导致的 因为在小程序的IDE里面引用的是这个文件
