### ISSUE TITLE
怎么控制y轴和x轴单位

### ISSUE THREAD

**Issue by long20150122** [antvis/f2#431]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
请具体描述需求

**Comment by long20150122** [comment]
就比如降雨量图 x轴表示小时 需要在最右边需要(h) ,y轴表示毫升最上面需要有（ml）。还有可能还气温曲线，这样就需要两个y轴一左一右，而且应该是可以自定义和控制的。

**Comment by simaQ** [comment]
在 F2 中，这些单位可以使用 chart.guide().text() 来绘制，具体参考相关 Api 以及 demo 实例：
https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negative-column-1.html
