### ISSUE TITLE
官网DEMO在手机上打不开

### ISSUE THREAD

**Issue by iamllitog** [antvis/f2#432]
* **F2 Version**:3.3.0/f2-all.min.js
* **Platform**:红米5A
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/6738756/49349465-aa4e4500-f6e5-11e8-8e98-12398df0b055.png)

* **CodePen Link**:
https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pinch-and-pan-for-smooth-line.html

**Comment by simaQ** [comment]
感谢反馈，这个是 AntV 官网统一的问题，已经反馈至相应的 issue: https://github.com/antvis/site/issues/180 ，我们会尽快修复。

**Comment by iamllitog** [comment]
原来的头像好看👀
