### ISSUE TITLE
图表背景设置，根据Y轴区间设置背景颜色

### ISSUE THREAD

**Issue by baiban1994** [antvis/f2#433]
* **F2 Version**: ^3.3.0
* **Platform**: web
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我想根据y轴的值，不同的y轴值区间设置不同的背景颜色。
看过文档，只是设置了line与x轴的背景颜色。
#115 并不符合，还有#115的热心人提供的设置办法我试过出不来

**Comment by baiban1994** [comment]
大概思路能讲下嘛，谢谢了。能做出来都好

**Comment by baiban1994** [comment]
> 你是想要这种效果吧？
> ![image](https://user-images.githubusercontent.com/6628666/49361113-1c3e8280-f716-11e8-9ba4-b38e72427e03.png)
> 
> 目前 F2 不支持这个功能，只能通过调用一些内置的属性来自己绘制，很麻烦。

我不是很熟悉这些，能说个大概思路吗。谢谢了

**Comment by simaQ** [comment]
这个建议你通过 chart.guide().rect() 辅助框来绘制，根据 Y 轴坐标轴的刻度个数，计算出每个矩形框的位置百分比即可。

参考：https://codepen.io/Sima/pen/zMQJNy
