### ISSUE TITLE
tooltip点击提示

### ISSUE THREAD

**Issue by baiban1994** [antvis/f2#434]
* **F2 Version**: v3.3.0
* **Platform**: h5
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

tooltip能实现点击point显示，点击其它区域隐藏吗。
看api了解到的东西很少，还是说就没有这么做的？

**Comment by simaQ** [comment]
目前 Tooltip 的触发区域是整个 canvas 画布，目前默认情况下当在触发区域外时 tooltip 还是会显示，但是可以通过 alwaysShow: false 关闭。

如果你想自己控制 tooltip 的显示隐藏，你可以自己监听 canvas 上的事件，然后通过调用 chart.showTooltip() 和 chart.hideTooltip() 来解决
