### ISSUE TITLE
请问折线图的拐点样式可以改变的吗？

### ISSUE THREAD

**Issue by K-Stella** [antvis/f2#435]
* **F2 Version**: 3.3.1
* **Platform**: 微信小程序

官方给的折线图拐点都是按着折线图的颜色设定，如下图：
https://upload.cc/i1/2018/12/04/yjeS3k.png

想要把折线图的拐点样式改成这样：
https://upload.cc/i1/2018/12/04/9BmYd1.jpeg

看了大半天文档，也没有找到对应修改的接口，想请教大家这个样式有什么办法可以改变的吗？谢谢。

**Comment by simaQ** [comment]
直接在 tooltipMarkerStyle 属性里面定义就可以了，参照：

```
chart.tooltip({
  tooltipMarkerStyle: {
    fill: '#1890ff' ,
    stroke: '#1890ff',
    strokeOpacity: 0.3,
    lineWidth: 10
  }
});
```

**Comment by K-Stella** [comment]
谢谢！问题解决了。

**Comment by huochezaodian** [comment]
> 直接在 tooltipMarkerStyle 属性里面定义就可以了，参照：
> 
> ```js
> chart.tooltip({
>   tooltipMarkerStyle: {
>     fill: '#1890ff' ,
>     stroke: '#1890ff',
>     strokeOpacity: 0.3,
>     lineWidth: 10
>   }
> });
> ```

请教下，多折线的高亮拐点要怎么处理呢，颜色是不一样的
