### ISSUE TITLE
多个geom, 在执行.color(‘type’, [...colors])配置 colors 不同时，  显示的tooltip会重复

### ISSUE THREAD

**Issue by ykx456654** [antvis/f2#440]
* **F2 Version**: 3.3.1
* **Platform**: windows
* **CodePen Link**:  [https://runjs.cn/code/sbp8clzt](url)

**Comment by simaQ** [comment]
这个你在 chart.tooltip 的 onShow 回调函数（参考 https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/basic-column.html 中 onShow 的使用）中过滤下重复数据吧，我们内部的去重策略是考虑到颜色的，至于表示相同数据集的点线，我们建议是使用相同的色值在可视化表达上可能会更好。

**Comment by yu521088** [comment]
@sima
你们的文档迁移到雨雀以后都没了啊 F2的文档链接过去都到首页了
