### ISSUE TITLE
请问如何将不同的形状对应到同一条y轴上

### ISSUE THREAD

**Issue by Pzzul** [antvis/f2#441]
* **F2 Version**: v3.3.1
* **Platform**: 微信小程序
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

以 https://antv.alipay.com/zh-cn/f2/3.x/demo/other/multiple-y.html 这个为例。如果在数据中增加一个纬度变成：
```js
{
  time: '周一',
  tem: 10,
  rain: 6.9,
  wind: 2
}
chart.interval().position('time*tem')
chart.line().position('time*rain')
chart.line().position('time*wind')
```
现在希望tem和rain对应左轴，wind对应右轴。左右轴的取值范围独立自适应。请问要如何做到？

**Comment by simaQ** [comment]
默认如果多条声明的 position 语句中 y （就是 * 号右侧的字段）不同时，就会为每个 y 生成一条坐标轴，按照声明的顺序。第一条坐标轴位于左侧，其他的都位于右侧。所以你只要在chart.axis() 接口中将 rain 对应的坐标轴 position 设置为 'left' 即可，至于左右轴的取值范围独立自适应，你设置下 [syncY](https://www.yuque.com/antv/f2/api-chart#ou7mld) 就可以啦

**Comment by Pzzul** [comment]
希望得到的效果是，在左面的两条轴tem和rain的范围一致了，右轴的取值范围是独立的，现在有这种功能吗？

**Comment by simaQ** [comment]
有的，你在列定义中手动同步下 tem 和 rain 两个字段的 min 和 max 就好
