### ISSUE TITLE
FEATURE: 数据的Group/或者动态data渲染更优雅的处理方案

### ISSUE THREAD

**Issue by afeiship** [antvis/f2#444]
现在我有这种需要：
我有三个数据源：data1/data2/data3
```js
var data1 = [
    { x: '2018-12-01', y: 1.2 },
    { x: '2018-12-02', y: 2.2 },
    { x: '2018-12-03', y: 4.3 }
];

var data2 = [
    { x: '2018-12-01', y: 2.2 },
    { x: '2018-12-02', y: 3.2 },
    { x: '2018-12-03', y: 2.9 }
];

var data3 = [
    { x: '2018-12-01', y: 10.2 },
    { x: '2018-12-02', y: 13.2 },
    { x: '2018-12-03', y: 12.9 }
];
```
**我实际的业务需求如下：**
1. 我期望 data1/data2 数据源是堆叠的关系 - 产生group1
2. 我期望 group1 与 data3 是分组的关系

**现在这个是我的实现思路：**
![Alt text](https://ws3.sinaimg.cn/large/006tNbRwgy1fxzmcwdufjj30u0191tc0.jpg)

1. 将data1/data2/data3数组处理，分别添加 type_1/type_2/type3
2. 上图：将三个data渲染成堆叠，并将 data3 数据部分的 style 设置为 opacity:0;
3. 下图：将三个data渲染成分组，将将 data2 的 size 设置为0

**存在的问题:**
1. 上图中的透明的部分，有个最大值，导致整个数据轴会有很大的空间是空白
2. 下图，需要设置 marginRatio为 -0.5 才可以达到只有两根柱形图的效果
3. 目前的做法，也只是个hack的做法
4. 点击区域不太正常

@各位大佬，求合适的解决方案 😃

这个是我期望的结果图（黄柱应该与坐标系显示正常的空间关系）：
![Alt text](https://ws2.sinaimg.cn/large/006tNbRwgy1fxzmqhiralj30km0ek3z5.jpg)

**Comment by simaQ** [comment]
目前 F2 还不支持分组层叠柱状图的绘制。你使用的方法确实蛮 hack 的。

目前对于这种需求，我们推荐的是使用自定义 shape 的方法：
1. 先绘制一个层叠柱状图，让它偏左
2. 再绘制一个柱状图，让它偏右

```js
chart.interval().position('x*y1').color('type').adjust('stack').shape('left'); // 层叠柱状图
chart.interval().position('x*y2').shape('right'); // 柱状图
```

你可以按照这个思路试一下，当然你需要将这三份数据合并一下。

**Comment by afeiship** [comment]
> 目前 F2 还不支持分组层叠柱状图的绘制。你使用的方法确实蛮 hack 的。
> 
> 目前对于这种需求，我们推荐的是使用自定义 shape 的方法：
> 
> 1. 先绘制一个层叠柱状图，让它偏左
> 2. 再绘制一个柱状图，让它偏右
> 
> ```js
> chart.interval().position('x*y1').color('type').adjust('stack').shape('left'); // 层叠柱状图
> chart.interval().position('x*y2').shape('right'); // 柱状图
> ```
> 
> 你可以按照这个思路试一下，当然你需要将这三份数据合并一下。

好的，感谢回复，我的场景应该是多条数据(可能有只两条)分组，我换个思路试一下吧。
