### ISSUE TITLE
请问node端怎么使用drawImage方法绘制图片呢？以及怎么绘制字体图标？

### ISSUE THREAD

**Issue by GDC6203** [antvis/f2#447]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
参考这篇文档中的示例代码: https://www.yuque.com/antv/f2/node-env

`canvas.createPNGStream().pipe(fs.createWriteStream(path.join(__dirname, 'pie.png'))) // 导出图片
`

字体图表的绘制，你 google 下 node-canvas 是否支持吧
