### ISSUE TITLE
辅助文本显示不全

### ISSUE THREAD

**Issue by weifengmomo** [antvis/f2#450]
使用F2时有一个这样的现象，辅助文本显示不全，直接在官网图标事例修改试了一下，https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/bar-with-label.html
如图：
![image](https://user-images.githubusercontent.com/45845859/49930612-f2e4da00-feff-11e8-923f-04a7228afd09.png)

**Comment by weifengmomo** [comment]
@simaQ 根据你的建议我做了一下调整
这个是加padding的情况：
![image](https://user-images.githubusercontent.com/45845859/49979832-c8d8f980-ff8b-11e8-935a-bfa1ec623f5a.png)
这个是end的情况：
![image](https://user-images.githubusercontent.com/45845859/49979871-f6be3e00-ff8b-11e8-96b3-ad375c0b202d.png)
加了padding，会把整体缩小，文字和条形图的位置还是保持原样，有没有办法是只调整一下条形图的长度？

**Comment by simaQ** [comment]
........ 我说的 padding 是这个 https://www.yuque.com/antv/f2/api-chart#92uqpt，哎，请阅读下 API
