### ISSUE TITLE
F2-柱状图平移，平移后的x轴部分数据不显示

### ISSUE THREAD

**Issue by l328958741** [antvis/f2#451]
【问题】：按照官网demo，[https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-bar-chart.html](https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-bar-chart.html)给出的示例，完成一个demo发现向左平移后x轴有部分对应的日期没有显示，查看文档和多次尝试未解决该问题。

* **F2 Version**: 3.3.1
* **Platform**: windows 10
* **Mini Showcase(like screenshots)**: 
【向左平移后，有部分日期未显示】
![image](https://user-images.githubusercontent.com/21151878/49953086-4b37ce00-ff38-11e8-86ad-39124e52b5ce.png)

* **CodePen Link**:  [https://codepen.io/Liuzc/pen/roxeKy](https://codepen.io/Liuzc/pen/roxeKy)

**Comment by simaQ** [comment]
这个是因为刻度计算的问题，你把 tickCount 配置删除

**Comment by l328958741** [comment]
感谢！
