### ISSUE TITLE
官网的“时间类型的平移缩放”图拖拽时console报错

### ISSUE THREAD

**Issue by fudanfuhua** [antvis/f2#457]
[官网的“时间类型的平移缩放”图拖拽时console报错](https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pinch-and-pan-for-line-chart.html)

**Comment by simaQ** [comment]
感谢反馈，但是这个建议在手机端操作观看，因为 PC 端是不支持 pinch 和 pan 的。
