### ISSUE TITLE
折线图X轴边距的一个问题

### ISSUE THREAD

**Issue by xiaoming0827** [antvis/f2#463]
如果x轴的数据是日期类型或者数字类型，然后设置：
if (index === 0) {
                        textCfg.textAlign = 'start';
                    } else if (index === total - 1) {
                        textCfg.textAlign = 'end';
                    }
                    return textCfg;
可以得到正确的效果，即第一个左对齐最后一个右对齐，
而数据为2018Q1这样的string类型时，这样就不生效了，效果是都是居中对齐，左右各留一块空白，非常的不美观，不知道是设置的问题，还是咱们对于非数字类型处理的不好

**Comment by simaQ** [comment]
应该是设置的问题，但是请按照模板，提供可复现的代码以供定位

**Comment by xiaoming0827** [comment]
以下为可以直接运行的代码，x轴坐标第一个和最后一个距离两边都有空白，不知道为何？

<!DOCTYPE html><html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="chart-name" content="&#x5546;&#x54C1;&#x4EF7;&#x683C; 7 &#x5E74;&#x8D70;&#x52BF;&#x5BF9;&#x6BD4;">
    <title>F2 &#x56FE;&#x8868;&#x7EC4;&#x4EF6;&#x5E93; - AntV</title>
    <link rel="stylesheet" href="https://gw.alipayobjects.com/os/rmsportal/YmDAMEQVbLJpVbKiRQVX.css">
    
</head>
<body>
<script>
/*Fixing iframe window.innerHeight 0 issue in Safari*/
document.body.clientHeight;
</script>

<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.3.0/f2.min.js"></script>

<script src="https://gw.alipayobjects.com/os/antv/assets/lib/lodash-4.17.4.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/lib/jquery-3.2.1.min.js"></script>

<script src="https://gw.alipayobjects.com/os/rmsportal/NjNldKHIVQRozfbAOJUW.js"></script>

  <div class="chart-wrapper">
    <canvas id="mountNode"></canvas>
  </div>
  <script>
var data = [{
  "date": "2010-01-10",
  "type": "能源",
  "value": 99.9
}, {
  "date": "2010-01-11",
  "type": "能源",
  "value": 96.6
}, {
  "date": "2010-01-12",
  "type": "能源",
  "value": 96.2
}, {
  "date": "2010-02-13",
  "type": "能源",
  "value": 96.7
},{
  "date": "2010-01-10",
  "type": "金属",
  "value": 20.9
}, {
  "date": "2010-01-11",
  "type": "金属",
  "value": 49.6
}, {
  "date": "2010-01-12",
  "type": "金属",
  "value": 60.2
}, {
  "date": "2010-02-13",
  "type": "金属",
  "value": 90
}];

  var chart = new F2.Chart({
    id: 'mountNode',
    pixelRatio: window.devicePixelRatio
  });
  chart.source(data);
  chart.scale('date', {
    type: 'timeCat',
    tickCount: 3
  });
  chart.scale('value', {
    tickCount: 5
  });
  chart.axis('date', {
    label: function label(text, index, total) {
      // 只显示每一年的第一天
      var textCfg = {};
      if (index === 0) {
        textCfg.textAlign = 'left';
      } else if (index === total - 1) {
        textCfg.textAlign = 'right';
      }
      return textCfg;
    }
  });
  chart.tooltip({
    custom: true, // 自定义 tooltip 内容框
    onChange: function onChange(obj) {
      var legend = chart.get('legendController').legends.top[0];
      var tooltipItems = obj.items;
      var legendItems = legend.items;
      var map = {};
      legendItems.map(function(item) {
        map[item.name] = _.clone(item);
      });
      tooltipItems.map(function(item) {
        var name = item.name;
        var value = item.value;
        if (map[name]) {
          map[name].value = value;
        }
      });
      legend.setItems(_.values(map));
    },
    onHide: function onHide() {
      var legend = chart.get('legendController').legends.top[0];
      legend.setItems(chart.getLegendItems().country);
    }
  });
  chart.line().position('date*value').color('type');
  chart.render();

</script>





</body></html>

**Comment by simaQ** [comment]
下次建议直接使用 codepen，尽量不要直接贴代码，谢谢。

你的坐标轴对齐方式已经是生效的，之所以会留空白是因为默认分类数据我们会在横轴左右留下空白的，你只要在下面的设置中添加  range: [ 0, 1  ] 即可，可以在 scale 的 API 文档下看到说明。

```js
chart.scale('date', {
  type: 'timeCat',
  tickCount: 3,
  range: [ 0, 1 ] // 添加 range
});
```
