### ISSUE TITLE
多图表放在一起没有办法触发Tooltip的onShow事件

### ISSUE THREAD

**Issue by luoyali** [antvis/F2#464]
工程师,你好:
    我的项目中有一个需求要使用到F2,参照官方网站提供的[双y轴案例](https://antv.alipay.com/zh-cn/f2/3.x/demo/other/multiple-y.html),根据项目需求改版成现在的样子,[代码](https://jsfiddle.net/Luoyal/h7mxrp1z/10/)在JSFiddle中

- 问题: 参考双y轴的数据格式,在此基础上多加了一个字段,没有办法触发Tooltip的onShow事件

- 环境:  第三方Js均引用的官方网站中的

- 希望展示的效果:
   - 鼠标在 柱状叠加图 和 面积图上按下时可以触发图表的Tooltip的onShow()事件.
  
不知道是否是data的格式有问题,导致没有触发onShow事件

麻烦了,这边我也会fork源码查看,具体什么原因导致.

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/50516019-41d76580-0ae3-11e9-9d12-e656a71752cb.png)

month 是数值类型，不是字符串。

另外带 'pan' 交互的 tooltip 是长按触发的，你把 values 中的值改为字符串就可以了，但是会有问题，因为数据的问题（2006 ~ 2029 年线图和区域图对应两份一样的数据），tooltip 查找会有问题。
