### ISSUE TITLE
timeCat类型X轴平移后部分数据不显示，类似#451但尚未能解决

### ISSUE THREAD

**Issue by darkxinyu** [antvis/f2#465]
F2 Version: 3.3.0

Platform: OSX, iOS, Android 

Mini Showcase(like screenshots):

![bc1fe116-2cc7-40a6-83c4-71e6818b3a05](https://user-images.githubusercontent.com/688257/50439600-9b962f00-092d-11e9-9f16-7e05384991ec.png)

<img width="424" alt="9b5d31df-9ea1-4d26-8258-240001fd5c62" src="https://user-images.githubusercontent.com/688257/50440358-d5b50000-0930-11e9-9fd8-577086d31942.png">

<img width="427" alt="38438919-ddf0-4c98-8865-b48e18e87ab1" src="https://user-images.githubusercontent.com/688257/50440365-e36a8580-0930-11e9-80d0-303e38cdb2ae.png">

CodePen Link: https://codepen.io/darkxinyu/pen/REgeEO

问题描述：

此问题现象与[#451](https://github.com/antvis/f2/issues/451)相同；

如第一张图所示，该图基本完全使用的官方”折线图平移“教程中的代码，仅仅修改了数据，且没有指定tickCount属性，仍然存在部分X轴文字无法显示的问题；

~~此外，类似的图表如果指定日期为cat类型，在React-Native的WebView下，安卓机（手头的两台华为+mumu模拟器）会出现了后二张图所示的连线错误的情况，同样的代码和数据iOS正常；~~
该问题已通过设置 `chart.line({sortable: false})`解决

还是希望timeCat类型能够正常显示，尝试了多种方法无果，只能到此求助，谢谢！

**Comment by simaQ** [comment]
timeCat 类型，如果没有指定 tickCount 的话，我们默认会展示 5 个坐标轴文本的。所以如果需要将数据全部展示的话，可以直接设置 ticks，就会按照 ticks 的个数和文本来显示 ，详见 api : https://www.yuque.com/antv/f2/api-scale#653vce

**Comment by darkxinyu** [comment]
可能我没有把我想要的效果说清楚，可以参考我的codepen代码，我希望达到的效果是比如我有12个月的数据，我希望最多只显示最后7个月，其他月份通过平移查看，现在如果使用values的方式，就会出现我提出的部分坐标轴文本不显示的问题，而且并不是像文档里说的只显示5个，实际情况是2（平移后可看到）、6、7、8、9、10、11、12月的文本都出来了，1、3、4、5月份的文本没有显示出来；如果按文档所说使用ticks或tickCount，就是显示全部月份，达不到只显示7个月份的效果。

![165dced6-a118-419f-b3f2-5f0a9f406a86](https://user-images.githubusercontent.com/688257/50531415-6152aa80-0b44-11e9-9ac9-9019eefb56fb.png)

![d85d4d80-adb2-44bb-be6b-982fb00cb404](https://user-images.githubusercontent.com/688257/50531419-73344d80-0b44-11e9-9ff1-db68a6ba2818.png)

**Comment by simaQ** [comment]
恩，我明白你的意思，是可以通过设置 `ticks` 属性解决的，将 ticks 设置为全量的时间。

> 我希望达到的效果是比如我有12个月的数据，我希望最多只显示最后7个月，其他月份通过平移查看

你已经通过 `values` 初始化展示最后七个月的数据了，`ticks`虽然设置为全量，但是在展示的时候只展示显示范围的刻度。

参考我的 codepen: https://codepen.io/Sima/pen/zyERMN?editors=1000

```js
chart.source(data, {
    date: {
      type: 'timeCat',
      values: initialDates,
      ticks: [ 
        '2018-01', 
        '2018-02', 
        '2018-03', 
        '2018-04', 
        '2018-05', 
        '2018-06',
        '2018-07', 
        '2018-08', 
        '2018-09', 
        '2018-10', 
        '2018-11', 
        '2018-12'
      ],
      mask: 'YY-MM'
    }
  });
```

**Comment by darkxinyu** [comment]
> 恩，我明白你的意思，是可以通过设置 `ticks` 属性解决的，将 ticks 设置为全量的时间。
> 
> > 我希望达到的效果是比如我有12个月的数据，我希望最多只显示最后7个月，其他月份通过平移查看
> 
> 你已经通过 `values` 初始化展示最后七个月的数据了，`ticks`虽然设置为全量，但是在展示的时候只展示显示范围的刻度。
> 
> 参考我的 codepen: https://codepen.io/Sima/pen/zyERMN?editors=1000
> 
> ```js
> chart.source(data, {
>     date: {
>       type: 'timeCat',
>       values: initialDates,
>       ticks: [ 
>         '2018-01', 
>         '2018-02', 
>         '2018-03', 
>         '2018-04', 
>         '2018-05', 
>         '2018-06',
>         '2018-07', 
>         '2018-08', 
>         '2018-09', 
>         '2018-10', 
>         '2018-11', 
>         '2018-12'
>       ],
>       mask: 'YY-MM'
>     }
>   });
> ```

确实通过您这种方式可以完全显示出坐标轴文本了，但是`mask`属性貌似会失效？如果需要格式化成一些非标准时间格式比如`18-01、18-02`这种，目前好像只能通过
```javascript
chart.axis('date', 
  label: (text) => {
    return {
      text: /* 格式化 */
      ...
    };
  },
  ...
);
```
这样的方式来实现了。

**Comment by leixu2txtek** [comment]
timeCat 如果加 ticks 移动会出现卡住的问题
目前采用 cat 类型，加手动格式化，解决问题
