### ISSUE TITLE
时间类型的平移缩放实例问题

### ISSUE THREAD

**Issue by PerseveranceZ** [antvis/f2#469]
* **F2 Version**: 3.3.0
* **Platform**: mac
* **官方demo**: [地址](https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pinch-and-pan-for-line-chart.html)

复现：无法拖动，打开控制台报错如下。

```
Uncaught TypeError: Cannot read property '0' of undefined
```

**Comment by simaQ** [comment]
因为拖动和缩放是使用的移动端手势: pinch 和 pan，在电脑上是不能模拟的，而且这个 demo 展示的是全部数据，需要缩放之后才能平移，已经在 demo 上注明，使用手机扫码观看

**Comment by PerseveranceZ** [comment]
感谢解答
