### ISSUE TITLE
多Y轴问题

### ISSUE THREAD

**Issue by Naclplus** [antvis/f2#470]
F2 Version: 3.2.1
Platform: All
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/25143160/50510208-ca460e00-0ac3-11e9-8cdc-552a61b872a2.png)
CodePen Link: https://codepen.io/z1259678404/pen/xmXboV

多数据Y轴 在Demo中的'MA20'只有一条数据的时候 会以MA20的数据为Y轴基准(从0开始) 导致出现显示bug 文档中并没有设置以哪个数据来源来设置该轴以哪组数据为主轴

**Comment by simaQ** [comment]
恩，这个问题已经修复了，请使用 F2 的最新版本 3.3.4，就没有问题了。

**Comment by Naclplus** [comment]
> 恩，这个问题已经修复了，请使用 F2 的最新版本 3.3.4，就没有问题了。

![image](https://user-images.githubusercontent.com/25143160/50511351-480c1880-0ac8-11e9-81f6-b094b34a220d.png)
还是有些问题  因为我没有0~2.25区间的数据
