### ISSUE TITLE
wx小程序图表无法平移，数据显示不全

### ISSUE THREAD

**Issue by icyfe** [antvis/f2#471]
F2 Version: 3.X
Platform:wx小程序
CodePen Link:https://codepen.io/icyfe/pen/xmpBep
wx小程序时间类型平移无法显示全部数据只会显示tickcount设置的数据个数，并且会自己折中显示，比如有100个数据 。tickcount设置3 他就会显示头尾两个和中间的一个数值，有点摸不着头脑是怎么回事
![x w wzj k rt f1eb7 z8](https://user-images.githubusercontent.com/44893721/50582812-27650980-0ea0-11e9-8fdd-81ec09c4acea.png)
数据源：
![1d4g14b1cli r wrewcoyq](https://user-images.githubusercontent.com/44893721/50622156-2c7c9400-0f46-11e9-9105-78bd44307a29.png)

设置tick的话会挤在一起：
![b6641 t6d uakgbnvv7jvc](https://user-images.githubusercontent.com/44893721/50582829-5da28900-0ea0-11e9-905d-e3aef15abfc5.png)

**Comment by icyfe** [comment]
求解答呀！！等的好着急。万分感谢

**Comment by simaQ** [comment]
如果初始化想要只显示部分的数据，你要设置 values 而不是 tickCount，好好看下官方例子的写法

**Comment by icyfe** [comment]
> 如果初始化想要只显示部分的数据，你要设置 values 而不是 tickCount，好好看下官方例子的写法

找出原因了，  有设置VALUES ，异步的问题拿到数据后要重新配置下数据源。 感谢回答
