### ISSUE TITLE
antv整体过大，小程序IDE上传失败

### ISSUE THREAD

**Issue by carlos121493** [antvis/f2#472]
<img width="238" alt="screen shot 2019-01-02 at 6 55 36 pm" src="https://user-images.githubusercontent.com/2987495/50589093-30fe6980-0ec0-11e9-8aca-0e70ae0e928f.png">

npm下载的包里含有dist，bundle。src及lib。目前来看非常大。

小程序构建会在云端下载，上传包限制。希望将src等加入.npmignore

**Comment by simaQ** [comment]
目前 @antv/my-f2 包的 main 入口是 build/ 下非压缩的脚本  https://github.com/antvis/my-f2/blob/master/package.json#L6  

将这个入口改为  dist/ 下是否可以解决？

**Comment by carlos121493** [comment]
既然有build，为什么不加个.npmignore将src隐掉？

**Comment by simaQ** [comment]
恩，src 可以隐掉，但是 lib 目前不行，因为 F2 提供了按需引用的功能，这周我会发布个 3.3.5 将 src 隐掉
