### ISSUE TITLE
chart.interaction is not a function

### ISSUE THREAD

**Issue by pzcaaa** [antvis/f2#474]
![image](https://user-images.githubusercontent.com/40380337/50675786-23b1be00-102b-11e9-820a-b5c27373bc15.png)
我已经引入了  require('@antv/f2/lib/interaction/pan');  

F2 Version:  3.1.15
Platform:
Mini Showcase(like screenshots):
CodePen Link: https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-bar-chart.html

**Comment by simaQ** [comment]
https://github.com/antvis/f2/blob/master/CHANGELOG.md#320-2018-08-16  请看下 changelog，3.2.0 才开始支持 interaction，请使用 F2 最新版本 3.3.4

**Comment by a654688383** [comment]
饼图 引入 也会报这个错  antv/f2/lib/index 还有antv/f2，是不是整合一下啊

**Comment by alianggitok** [comment]
> https://github.com/antvis/f2/blob/master/CHANGELOG.md#320-2018-08-16 请看下 changelog，3.2.0 才开始支持 interaction，请使用 F2 最新版本 3.3.4

我都已经3.4.1了

**Comment by akaxiaok** [comment]
有这个问题的 
```js
 import F2 from '@antv/f2/lib/index-all;
```
凑合用吧
