### ISSUE TITLE
guide().html()动态更新的时候  html重绘不了  貌似又新建了一个dom而不是在原来dom的基础上更新数据

### ISSUE THREAD

**Issue by lidongjie123** [antvis/f2#475]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
请提供可复现的代码

**Comment by simaQ** [comment]
时间过长无可复现代码追溯，故关闭
