### ISSUE TITLE
钉钉e应用支持交互行为吗？

### ISSUE THREAD

**Issue by pzcaaa** [antvis/f2#476]
* **F2 Version**:3.1.15
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
钉钉 e 应用使用的是 @antv/my-f2，在 1.1.5 版本上是支持交互的，https://github.com/antvis/my-f2/blob/1.1.5/src/index.js#L31，但是依赖的 @antv/f2 版本是 F2 3.3.x 版本：https://github.com/antvis/my-f2/blob/1.1.5/package.json#L94。

另外，F2 的交互也是在 3.2.0 版本开始才支持的，建议看看 changelog: https://github.com/antvis/f2/blob/master/CHANGELOG.md#320-2018-08-16
