### ISSUE TITLE
求救，柱状图 柱子间距怎么改，实在是没办法了

### ISSUE THREAD

**Issue by tjztj** [antvis/f2#479]
文档我我找了很久，也没有看到柱状图改怎么改，可能是我不够仔细。我是后端开发，前端也不是很懂。
没办法了，求教：柱状图间距怎么改，不是分组里面的每个小柱子的间距
![image](https://user-images.githubusercontent.com/17394651/50893659-551bf680-143c-11e9-80a3-5f38a4d2d2d9.png)
就是这里

**Comment by simaQ** [comment]
F2 并不支持，这个间距是有数据个数以及画布的高度决定的

**Comment by tjztj** [comment]
> F2并不支持，这个间距是有数据个数以及画布的高度决定的，我们只支持调整柱子的宽度以及分组柱子之间的间距

好吧，谢谢
