### ISSUE TITLE
wx小程序柱状图数据更新，视图没有立即渲染

### ISSUE THREAD

**Issue by icyfe** [antvis/f2#481]
* **F2 Version：3.x**:
* **Platform：wx小程序**:

小程序柱状图图表数据更新后， 要点击滑动图表才会显示图表，不然都不会显示

![gif](https://user-images.githubusercontent.com/44893721/50945478-c789e680-14cf-11e9-94d5-200d6b69b86e.gif)

**Comment by simaQ** [comment]
调试下，数据更新的时候有没有调用到 chart.changeData(data)，同时看下 data 是否有传入，如果你的数据加载和逻辑都没有错误，试下 chart.animate(false) 关闭动画后会不会复现。

如果以上两步都不行，请提供可复现的环境和代码方便排查

**Comment by icyfe** [comment]
codeopen: https://codepen.io/icyfe/pen/vvzjPe
demo用的官方的步数例子
![gif](https://user-images.githubusercontent.com/44893721/50959482-03d43b80-14fe-11e9-9ded-eab270611c4c.gif)
我先刷新了下，加载的是初始化的数据，点击刷新后，延迟模拟异步加载网络请求数据。 结果不显示，要拖动才显示而且显示有问题，  麻烦看一下，谢谢了！

**Comment by icyfe** [comment]
> 调试下，数据更新的时候有没有调用到 chart.changeData(data)，同时看下 data 是否有传入，如果你的数据加载和逻辑都没有错误，试下 chart.animate(false) 关闭动画后会不会复现。
> 
> 如果以上两步都不行，请提供可复现的环境和代码方便排查

codeopen: https://codepen.io/icyfe/pen/vvzjPe
demo用的官方的步数例子
加载的是初始化的数据，点击刷新后，延迟模拟异步加载网络请求数据。 结果不显示，要拖动才显示而且显示有问题， 麻烦看一下，谢谢了！
![gif](https://user-images.githubusercontent.com/44893721/50959826-cd4af080-14fe-11e9-9725-c11e12696de4.gif)

**Comment by icyfe** [comment]
问题已解决，因为每次更新前之前保留的数据没有清除掉，导致数据混乱，不好意思麻烦你们看问题了。
