### ISSUE TITLE
虚实线拖动问题

### ISSUE THREAD

**Issue by weizhuangyu** [antvis/f2#487]
* **F2 Version**:最新版
* **Platform**:ios,安卓
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

发现用pan实现拖动后，虚线会发生抖动，有什么解决方案吗？

**Comment by simaQ** [comment]
你指的虚线是什么？坐标轴上的网格线吗？如果是的话，可以尝试将坐标轴上的网格线动画关闭：

```js
chart.animate({
'axis-grid': false
})
```
