### ISSUE TITLE
抱歉，请问有与React Native集成的DEMO吗？

### ISSUE THREAD

**Issue by live106** [antvis/f2#49]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yashwanthm** [comment]
I'm looking for a react-native implementation of F2 like [BizCharts](https://github.com/alibaba/BizCharts)

**Comment by simaQ** [comment]
I'm sorrrrrrrry, this is not available yet...

**Comment by live106** [comment]
@yashwanthm ^_^have you found that now?

**Comment by live106** [comment]
@simaQ Thanks for your response!

**Comment by live106** [comment]
Cause it's not a real issue, just a question.
