### ISSUE TITLE
real time graph

### ISSUE THREAD

**Issue by komagic** [antvis/f2#490]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://www.highcharts.com/demo/dynamic-update

问下f2支持这种动效的realtime 图吗？

**Comment by komagic** [comment]
@simaQ 这个试过，很多数据的时候不可能像他这样一直往内存中加数据，举个例子，data比方说只能保存10个对象，那么要求在第11个对象加入的时候(if(data.length>=10))，第一个对象就要被排出（data.shift()），然后动画就会很奇怪，不信你试下

**Comment by simaQ** [comment]
实时的图表渲染直接通过 chart.changeData() 接口就可以完成。而你如果关注的是实时更新的动画效果，
那么你完全可以使用 F2 提供的自定义动画机制根据实际的数据情况自己写一个动画，官网的这个 demo 就是使用了自定义的动画

**Comment by komagic** [comment]
我就是问有木有现成的嘛

**Comment by komagic** [comment]
易用性和实用性，怎么说就类似妹子你走进一家服装店，从外面看感觉装修大气，衣服种类多，但是进去后没一件合身，店员告诉你裤子需要自己拿去裁10英寸...0 0

**Comment by komagic** [comment]
https://bost.ocks.org/mike/path/
