### ISSUE TITLE
柱状图 changeData 会重复渲染

### ISSUE THREAD

**Issue by ziven27** [antvis/f2#491]
* **F2 Version**: 官方demo
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: [https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negetive-column.html](https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negetive-column.html)

<img width="415" alt="qq20190117-221027 2x" src="https://user-images.githubusercontent.com/7261176/51324075-bbd88a00-1aa4-11e9-8cdc-a4cc1f3ab5a9.png">

在柱状图里chart.changeData(newData)会出现渲染的问题。

在这个 [https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negetive-column.html](https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negetive-column.html)官方示例中，粘贴如下代码，然后点击运行，并多次点击更新数据按钮即可复现。

难道是在柱状图里需要clear一下，可是为啥折线图用这个逻辑不会出现这个问题？

```html
<button id="updateData">更新数据</button>
```

```js
var data2 = [{
  value: 1000,
  season: '第四季'
}, {
  value: 2000,
  season: '第三季'
}, {
  value: -3000,
  season: '第二季'
}, {
  value: -1000,
  season: '第一季'
}];
    $('#updateData').on('click',function(){
      chart.changeData(data2);
    });    
```

**Comment by simaQ** [comment]
你好，是这样的，柱状图上的文本是通过 chart.guide().text() 绘制的，而 chart.guide() 是静态辅助元素，只与当前的数据有关，如果你的数据发生了变更，你需要清空 guide 然后重新绘制。


```js

$('#updateData').on('click',function(){
      chart.guide().clear(); // 清空辅助元素
      // 重新绘制辅助文本
      data2.forEach(function(obj, index) {
        // 文字部分
        var color = obj.value > 0 ? '#FC674D' : '#9AC2AB';
        chart.guide().text({
          position: [obj.season, obj.value > 0 ? obj.value : 0],
          content: numberToMoney(obj.value),
          style: {
            fill: color,
            textBaseline: 'bottom'
          },
          offsetY: -5
        });
        // 背景部分
        var offset = 0.46;
        chart.guide().rect({
          start: [index - offset, 'max'],
          end: [index + offset, 'min'],
          style: {
            fill: '#f8f8f8'
          }
        });
      });
      chart.changeData(data2);
    });    
```
