### ISSUE TITLE
android 内webview的H5页面兼容问题 chart.source(data, ccoldefs)不显示（个别机型）

### ISSUE THREAD

**Issue by allen-ch** [antvis/f2#492]
* **F2 Version**:3.3.4

个别安卓机型上，使用 chart.source(dataccoldefs)，折线图不显示；chart.guide().html()单画的html可以显示。

**Comment by simaQ** [comment]
请提供可复现的代码

**Comment by ovensi** [comment]
> * **F2 Version**:3.3.4
> 
> 个别安卓机型上，使用 chart.source(dataccoldefs)，折线图不显示；chart.guide().html()单画的html可以显示。

我也出现了这种问题，华为Mate30pro上面复现几率非常高。

**Comment by sinduanan** [comment]
我也出现了类似问题，我是列表中加载webview，有一些item不显示图表
