### ISSUE TITLE
多个折线图出现线绘制有问题

### ISSUE THREAD

**Issue by wehnhew** [antvis/f2#493]
* **F2 Version**:3.3.4

多个折线图出现线绘制有问题
![m ui m 4ez55tv evsd_ 30](https://user-images.githubusercontent.com/1829197/51452445-52db6580-1d75-11e9-9f15-7c1abcb27f1a.png)

**Comment by simaQ** [comment]
是什么环境？请提供可复现的代码

**Comment by lisasslisa** [comment]
想问下这个问题解决了吗
