### ISSUE TITLE
怎么取消f2的点击事件

### ISSUE THREAD

**Issue by zust-hh** [antvis/f2#495]
我想要开始的时候就展示一个tooltip，并且不随着点击事件而改变。这要怎么做到。
目前有两种想法：
1. 取消整个f2的点击事件
2. 取消tooltip的改变
请问f2怎么做到哪一点，我看文档并没有提到

**Comment by simaQ** [comment]
恩，你是想要禁止掉 tooltip 的交互行为，然后只在图表展示的时候展示一个 tooltip，这个可以这么做：
1. 首先将 tooltip 关闭: `chart.tooltip(false)`
2. 调用 `chart.showTooltip()` 接口展示你想要的数据点：https://www.yuque.com/antv/f2/api-chart#0v39hh

参考 demo: https://codepen.io/Sima/pen/aXvaOW

**Comment by zust-hh** [comment]
嗯嗯，感谢，但是这样会出现一个问题，怎么改变tooltip item显示的值呢？比如现在是age：20，age这个显示我想改成自定义的字符串
