### ISSUE TITLE
ios有时出现图标是空白的，但是可以在上面进行操作

### ISSUE THREAD

**Issue by hj0503** [antvis/f2#497]
* **F2 Version**: 3.3.1
* **Platform**: ios
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在ios中，有时会出现图标无法显示，一片空白，一旦出现就一直是空白，除非重新进入应用，但是可以在上面进行操作，比如说tooltip的onChange等等

**Comment by snowkeda** [comment]
ios系统本版越高触发几率越大。

**Comment by hj0503** [comment]
> ios系统本版越高触发几率越大。

你也遇到了吗

**Comment by snowkeda** [comment]
> > ios系统本版越高触发几率越大。
> 
> 你也遇到了吗

我也遇到了

**Comment by hj0503** [comment]
> * **F2 Version**: 3.3.1
> * **Platform**: ios
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
> 
> 在ios中，有时会出现图标无法显示，一片空白，一旦出现就一直是空白，除非重新进入应用，但是可以在上面进行操作，比如说tooltip的onChange等等

**Comment by LCF1314** [comment]
怎么解决

**Comment by LCF1314** [comment]
#630
