### ISSUE TITLE
横向柱状图滑动手势求指导

### ISSUE THREAD

**Issue by xxyyyzz** [antvis/f2#499]
* **F2 Version**:3.3.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
我要做一个横向柱状图当数据多的时候要支持上下滑动看数据，但是现在我按官方demo来实现，只能左右滑动图形才会进行上下滚动，当我把手势mode属性设置为y时，发现图形只会横着滚动。具体代码如下：
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="chart-name" content="基础条形图">
    <title>F2 图表组件库 - AntV</title>
    <link rel="stylesheet" href="https://gw.alipayobjects.com/os/rmsportal/YmDAMEQVbLJpVbKiRQVX.css" />
    
</head>
<body>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>

<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.3.0/f2-all.min.js"></script>

<script src="https://gw.alipayobjects.com/os/antv/assets/lib/lodash-4.17.4.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/lib/jquery-3.2.1.min.js"></script>

<script src="https://gw.alipayobjects.com/os/rmsportal/NjNldKHIVQRozfbAOJUW.js"></script>

  <div class="chart-wrapper">
    <canvas id="mountNode"></canvas>
  </div>
  <script>
var Global = F2.Global;
var data = [{
  country: '巴西',
  population: 18203
}, {
  country: '印尼',
  population: 23489
}, {
  country: '美国',
  population: 29034
}, {
  country: '印度',
  population: 104970
}, {
  country: '中国',
  population: 131744
}];
var chart = new F2.Chart({
  id: 'mountNode',
  pixelRatio: window.devicePixelRatio
});

chart.source(data, {
  population: {
    tickCount: 5,
    
  },
  country:{
    values:['巴西','印尼','美国']
  }
});
chart.coord({
  transposed: true
});
chart.axis('country', {
  line: Global._defaultAxis.line,
  grid: null
});
chart.axis('population', {
  line: null,
  grid: Global._defaultAxis.grid,
  label: function label(text, index, total) {
    var textCfg = {};
    if (index === 0) {
      textCfg.textAlign = 'left';
    } else if (index === total - 1) {
      textCfg.textAlign = 'right';
    }
    return textCfg;
  }
});
chart.interval().position('country*population');
    chart.interaction('pan');
chart.render();
</script>

</body>
</html>

**Comment by army8735** [comment]
感觉是transposed时手势没有跟着的缘故
