### ISSUE TITLE
分组柱状图相同数据重新渲染后，顶部Legend会出现重复显示 [bug]

### ISSUE THREAD

**Issue by lordmos** [antvis/f2#501]
* **F2 Version**: latest(3.x)
* **Platform**: web
* **Mini Showcase(like screenshots)**: [官方文档-分组柱状图]( https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/dodge-column.html)

在官方文档的Demo中，在script标签末尾加入
   ` setTimeout(() => chart.render(), 100)`
然后运行，顶部栏会出现`London Berlin London Berlin`

**Comment by lordmos** [comment]
[GitHub-legend.js](https://github.com/antvis/f2/blob/master/src/plugin/legend.js)

`beforeGeomDraw()`方法中是不是需要先清空一下legend再进行添加？

**Comment by simaQ** [comment]
重绘请调用 `chart.repaint()` 不要反复调用  chart.render()

**Comment by lordmos** [comment]
如果数据更新，应该如何重绘？
另外，使用相同数据进行重新render()会发生这样的bug还希望能fix一下。

**Comment by simaQ** [comment]
@lordmos 数据更新了，直接调用 chart.changeData() 接口

> 另外，使用相同数据进行重新render()会发生这样的bug还希望能fix一下。

这个不是 BUG，而是你使用的方式不对，重绘调用 chart.repaint()
