### ISSUE TITLE
Tooltip如何设置多条曲线的tooltipMarkerStyle

### ISSUE THREAD

**Issue by lz311876** [antvis/f2#502]
看文档Tooltip中tooltipMarkerStyle只能设置一种样式，想实现两条折线的tooltipMarker不同样式该怎么写？
`tooltipMarkerStyle: {
                            fill: '#FF3909' ,
                            stroke: '#FF3909',
                            strokeOpacity: 0.3,
                            lineWidth: 5
                        },`
![_a9c7616d-bada-49b8-ad5e-0bbec94733db](https://user-images.githubusercontent.com/12765229/52039229-ed565880-256e-11e9-9f1a-89af1ea97a8c.png)

**Comment by simaQ** [comment]
目前不支持

**Comment by hxlniada** [comment]
@simaQ 请问下回答不支持后把issue关了是什么操作？
