### ISSUE TITLE
【新需求】为 排名类数据 （数值越低 反而在折线图上 显示位置越高）提供更好的支持

### ISSUE THREAD

**Issue by ShenQingchuan** [antvis/f2#504]
* **F2 Version**: **@antv/f2 3.3.4**
* **Platform**: Windows + Chrome 版本 71.0.3578.98（正式版本）（64 位）
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

尊敬的各位 Antv 的维护工作人员你们好！
我想开门见山地说：这个 issue 的目的是： 一个新需求 => 关于坐标轴的数值翻转

### 需求描述
- **关于会在什么场景下提出本需求**：
 当我们需要制作一个与 **名次** 相关的折线图时，因为 29 名 会比 41名 来的高，所以在折线图上，我们当然希望从 41 名 到 25 名的折线是上扬的。

- **关于如何暂时比较别扭地解决我们的需求**：
因为这其实是一个反转数值的逻辑，数值越小反而意味着名次高。
所以目前我们暂时把所有的名次（数据是以整数 Integer 类型出现的）
全部变成了其本身的负数，
这样在折线图上确实能够表现出 刚才提到的：“ 从 41 名 到 25 名的折线是上扬的 ” 这一效果。

- **关于为什么 F2 目前无法实现本需求**：
因为目前，折线图的 纵坐标上的值 是根据 传入的数值的 **数值绝对值大小！！** 来决定的。 
（ 当然我说的是：如果我们只是像本需求这样，只用到了 整数类型，而非其他特殊类型 例如分类类型 ）

所以如果无法让图表本身去支持配置 value 的选项，那么这个逻辑将无法仅仅通过改变数据本身来实现。

### 我们想到的可能的解决思路：
**关于source、scale和colDefs对表数据的配置: **
当然我们查阅了官方F2文档中的一些 API，
我们发现 F2 支持以下三种类型的数据：
- linear: 数值类型
- cat: 分类类型
- timeCat：时间类型

我们阅读到，如果需要定义各个字段的度量配置，
在 chart 的 source 方法中可以多添加一个 配置属性 Object 作为参数。
但是很可惜的是，这个参数虽然能够去定义某一个字段是什么数据类型，但是这三种并不是本需求所需要的。

所以我们在想是否有一种可能，我们专门增加一种类型： 名次类型
因为日常生活中这种排名表实际上非常常见，所以我们很希望 F2 能够更好、更高效地支持本需求。

- **当然最后如何更新该需求，还是要靠各位工程师大大呀！**

衷心祝 Antv 和 F2 越来越好！
希望本需求能早日被实现！
2019 新年快乐！

/ 沈青川

**Comment by komagic** [comment]
感觉妹子就是写字规矩啊~成都妹子会编程很厉害~

虽然我不是antv的，但是感觉这个需求可以通过增加一个转换函数，简单的数字转换就能够达到效果，比方说 100以内，100 - 25 > 100 - 75 就可以简单的实现你的需求了，数字大点可以使用最大值减去你给的数字。不存在新增类型的必要哦。至于显示出来，可以使用formatter 改变你要想要显示的数字样式。

**Comment by simaQ** [comment]
非常感谢您的建议，@ShenQingchuan。

对于你的需求，正如 @komagic  所说，目前 F2 的 scale 是支持自定义 scale 的转换函数的，并不需要再重新定义一个度量类型，scale 的作用就是将原始数据转换为 0 - 1 的范围（即归一化操作），是用户数据到图形数据的转换桥梁，你可以通过自定义 Linear 类型的  scale 方法（作用是将数值进行归一化操作）来实现你的需求。参考如下代码：

* demo: 基金排名  https://antvis.github.io/awesome-f2-charts/fund/rank.html
* 自定义 scale 转换函数：https://github.com/antvis/awesome-f2-charts/blob/master/fund/rank.html#L361

![image](https://user-images.githubusercontent.com/6628666/52543202-abd17300-2de2-11e9-902e-c00dbc07efb3.png)

**Comment by ShenQingchuan** [comment]
### To Antv F2 项目Github维护人员： 

我是该 #504 issue 的发起人

非常感谢 antv 工作人员的回复！
我已经在您给出的方法的指引下成功完成、实现了我的需求！

issue 已解决完毕。

再次感谢各位工程师们的认真回复和帮助！


/沈青川

**Comment by liuhuawen** [comment]
经过上面这种方式反转y轴的数值，势必会导致面积的图形也是反转的

**Comment by liuhuawen** [comment]
![image](https://user-images.githubusercontent.com/19276993/54019264-b73b7280-41c5-11e9-8aa0-878ff4105b76.png)
