### ISSUE TITLE
innerRadius not work

### ISSUE THREAD

**Issue by Ppsj** [antvis/f2#507]
Results
![image](https://user-images.githubusercontent.com/18297094/52696753-c0606780-2faa-11e9-950c-6177e994919c.png)

Code
![image](https://user-images.githubusercontent.com/18297094/52696800-e1c15380-2faa-11e9-9116-984250fe5a3d.png)

Sometimes the property innerRadius doesn't work。
what should I do?

**Comment by Ppsj** [comment]
version:  ^3.2.4

**Comment by simaQ** [comment]
It will be nice to provide a CodePen Link which can reproduce the issue, we provide a CodePen template [f2-github-issue](https://codepen.io/Sima/pen/qVgdex).

**Comment by Ppsj** [comment]
I don't know how to reproduce it.  (template)[https://codepen.io/Carl_su/pen/gqdPOB].
:sweat_smile:

**Comment by simaQ** [comment]
...在 issue 模板里面已经非常清楚得注明了，请按照 issue 模板提供可以复现的完整代码，包括数据、源码以及运行环境，否则无法帮你定位，请了解

**Comment by Ppsj** [comment]
[template](https://codepen.io/Carl_su/pen/gqdPOB)

数据载入后， 会出现中间镂空的问题。

**Comment by simaQ** [comment]
恩，是你的数据有问题，饼图的 `position('x*y')` x 字段需要是字符串类型，你只要把你的 time 字段变成字符串就可以啦！

```js
const data = [
  {
    "type":"出口重柜",
    "value":10.99,
    "time":'2019'
  },
  {
    "type":"进口吉柜",
    "value":2,
    "time":'2019'
  },{
    "type":"进口重柜",
    "value":0.98,
    "time":'2019'
  }];
```

**Comment by Ppsj** [comment]
@simaQ 谢谢
