### ISSUE TITLE
如何让双轴图的0刻度在同一水平线上？

### ISSUE THREAD

**Issue by YueQuanXiaoChe** [antvis/f2#510]
* **F2 Version 3.3.4**:
* **Platform mobil**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/13010474/52924996-1dbd3580-336a-11e9-8347-9de5e44c1106.png)
如何让双轴图的0刻度在同一水平线上，像下面这图一样
![image](https://user-images.githubusercontent.com/13010474/52925042-4e9d6a80-336a-11e9-83d1-2af1c3b62767.png)

* **CodePen Link**:

**Comment by simaQ** [comment]
https://www.yuque.com/antv/f2/api-chart#ou7mld

**Comment by YueQuanXiaoChe** [comment]
由于左轴和右轴的数值范围相差较大，用 syncY 统一 Y 轴的数值范围后，其中一个轴的图就很小很小，甚至看不建了，如下图所示：
![image](https://user-images.githubusercontent.com/13010474/52926921-ec953300-3372-11e9-854b-f25c45668921.png)

期望显示成：
![image](https://user-images.githubusercontent.com/13010474/52926893-bfe11b80-3372-11e9-9282-22bf0f621697.png)

**Comment by simaQ** [comment]
那就自己手动同步下两个 Y 轴的 scale 范围：

```js
chart.scale('y轴对应的字段名', {
  min: 0,
  max: 100,
  nice: false
});
chart.scale('另一条y轴对应的字段名', {
  min: 0,
  max: 100,
  nice: false
})
```
