### ISSUE TITLE
由于我这个双轴图左轴和右轴数值范围相差较大，所以使用 syncY 统一 Y 轴的数值范围后，其中一个轴的图表就显示不出来了，这怎么破？（前提是希望两个轴的0刻度在同一水平线上）

### ISSUE THREAD

**Issue by YueQuanXiaoChe** [antvis/f2#512]
* **F2 Version 3.3.4**:
* **Platform mobile**:
* **Mini Showcase(like screenshots)**:
由于我这个双轴图左轴和右轴数值范围相差较大，所以使用 syncY 统一 Y 轴的数值范围后，其中一个轴的图表就显示不出来了，这怎么破？（前提是希望两个轴的0刻度在同一水平线上）

使用 syncY 前
![image](https://user-images.githubusercontent.com/13010474/52927010-59a8c880-3373-11e9-8952-bef8f15079ce.png)
使用 syncY 后
![image](https://user-images.githubusercontent.com/13010474/52926980-3b42cd00-3373-11e9-8fb1-b890010c9533.png)

* **CodePen Link**:

**Comment by simaQ** [comment]
这样建议用两张图吧
