### ISSUE TITLE
如何调整柱状图宽度

### ISSUE THREAD

**Issue by Ppsj** [antvis/f2#513]
我在工作中， 需要给一个柱状组并且加入字体， 但是发现在高度固定下， 没办法调整柱体的大小
https://codepen.io/Carl_su/pen/omRXKW

想要的效果
- [x]  背景柱体调整大小
- [x]  柱体里面加入字体

于是， 我自定义了一个[Shape](https://codepen.io/Carl_su/pen/WPBQeP?editors=1010)， 但是效果没有达到预期。柱体被覆盖了。

想要的效果
- [x]  背景柱体调整大小
- [x]  柱体里面加入字体

**Comment by Ppsj** [comment]
#289 与这个问题几乎一致。

**Comment by Ppsj** [comment]
更新版本之后还有没有更多方案。 期待 :kissing_smiling_eyes:

**Comment by simaQ** [comment]
？ 我不太理解你的问题...

* 背景柱体调整大小

.size() 就可以

* 柱体里面加入字体

使用自定义 shape 实现的思路没有错。

**Comment by Ppsj** [comment]
抱歉， 问题描述给你带来困扰了。
高度固定的情况下。柱体之间的文本会被覆盖，导致看起来有些别扭。 
想知道有没有除了动态更新高度的方法之外的别的方法。

**Comment by simaQ** [comment]
这个没有别的办法，柱子的宽度是由画布宽高和数据条数决定的，你适当调整下样式来解决吧，就像这样：https://codepen.io/Sima/pen/pGXbOo

**Comment by Ppsj** [comment]
好吧。 谢谢~
