### ISSUE TITLE
我使用了平移图表，可以左右滑动的那种，但是如果想看提示信息需要长按才能显示，不支持点击就显示提示信息吗？如果支持，请问我需要怎么改？

### ISSUE THREAD

**Issue by gaoxinxin520** [antvis/f2#516]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
这个可以直接在 chart.interaction('pan') 提供的钩子回调中使用 chart.showTooltip() 来解决：


```js
chart.interaction('pan', {
  onProcess(e) {
    const center = e.center; // 获取当前的坐标
    const position = F2.Util.getRelativePosition(center, chart.get('canvas')); // 转换为画布坐标
    chart.showTooltip(position); // 调用显示 tooltip 的接口
 },
});
```

**Comment by alianggitok** [comment]
> showTooltip

这只有在拖动的时候才有作用吧？

**Comment by alianggitok** [comment]
> 这个可以直接在 chart.interaction('pan') 提供的钩子回调中使用 chart.showTooltip() 来解决：
> 
> ```js
> chart.interaction('pan', {
>   onProcess(e) {
>     const center = e.center; // 获取当前的坐标
>     const position = F2.Util.getRelativePosition(center, chart.get('canvas')); // 转换为画布坐标
>     chart.showTooltip(position); // 调用显示 tooltip 的接口
>  },
> });
> ```

这只有在拖动的时候才有作用吧？

**Comment by manchang6** [comment]
楼主解决了吗，我也遇到类似的问题
