### ISSUE TITLE
饼图如果我不想显示其中一个块的锚点和线，该怎么做

### ISSUE THREAD

**Issue by dsmelon** [antvis/f2#518]
![image](https://user-images.githubusercontent.com/24835261/53334132-dc60f300-3932-11e9-8d81-8e2ac055e8d2.png)
如果我不想显示其中一个块的锚点和线，该怎么做，建议把配置到全局的锚点和线分发到每一个块的函数中

**Comment by simaQ** [comment]
目前不支持
