### ISSUE TITLE
官网例子有bug

### ISSUE THREAD

**Issue by johnsky123** [antvis/f2#523]
![image](https://user-images.githubusercontent.com/11240977/54005745-87747680-4195-11e9-847d-83bcf804d17c.png)

**Comment by army8735** [comment]
目前padding为auto时，确实没有考虑到tooltip的位置出血，包括g2在内。

**Comment by johnsky123** [comment]
@army8735  请问 tooltip 为自定义html 时  tooltip 位置超出canvas 范围这种情况怎么处理

**Comment by army8735** [comment]
我也不知道……

**Comment by johnsky123** [comment]
@simaQ   请教一下

**Comment by simaQ** [comment]
因为这个是自定义的外部的 tooltip，所以你需要自己判断当前 tooltip 是否超出了画布的范围，超出了你调整下就可以了。tooltip 的当前位置和 canvas 的相对坐标都是可以通过 document 拿到的
