### ISSUE TITLE
如何设置y轴的数字，按照倒序排列呢

### ISSUE THREAD

**Issue by liuhuawen** [antvis/f2#525]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
参考 https://github.com/antvis/f2/issues/504

**Comment by liuhuawen** [comment]
经过#504所说的方法，可以反转数值，但是数值所形成的图形面积也是反转的

**Comment by liuhuawen** [comment]
![image](https://user-images.githubusercontent.com/19276993/54019055-2f556880-41c5-11e9-8e89-b2129854c711.png)

**Comment by simaQ** [comment]
恩，这个确实是的，有解决办法，通过自定义 shape。但是说实话这样的图让我感觉很怪异

**Comment by liuhuawen** [comment]
通过自定义 shape 有相关的demo吗 面积这块的自定义shape
