### ISSUE TITLE
官网例子 图表平移 toolitip 显示不出来

### ISSUE THREAD

**Issue by johnsky123** [antvis/f2#527]
![image](https://user-images.githubusercontent.com/11240977/54095752-cac42480-43e3-11e9-8db7-d317b3a4f2b1.png)

**Comment by simaQ** [comment]
https://www.yuque.com/antv/f2/api-interaction#xgauvx

![image](https://user-images.githubusercontent.com/6628666/54099177-e125ac80-43f2-11e9-9407-f89481ef289d.png)

**Comment by johnsky123** [comment]
请问  是否支持点击直接触发tooltip的方式  (不是通过长按)

**Comment by wangmingxu** [comment]
同问，是否支持点击支持触发tooltip
