### ISSUE TITLE
请问是否支持矩形树图

### ISSUE THREAD

**Issue by sky007z** [antvis/f2#529]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
支持的，但是需要使用 DataSet 将数据进行对应的布局调整，然后使用 chart.polygon() 进行绘制。详见 https://codepen.io/Sima/pen/axOBJa

**Comment by simaQ** [comment]
https://antv.alipay.com/zh-cn/f2/3.x/demo/other/simple-treemap.html
