### ISSUE TITLE
legend中的namestyle里如何设置宽度

### ISSUE THREAD

**Issue by L-x-C** [antvis/f2#530]
想要实现这样的效果
![image](https://user-images.githubusercontent.com/4329120/54260754-d3178d80-45a4-11e9-92e6-afaa35b4e783.png)

但目前只能实现
![image](https://user-images.githubusercontent.com/4329120/54260789-efb3c580-45a4-11e9-8797-422bbea62689.png)
右边的为legendItems中的name和value，如何能实现控制name的宽度？

**Comment by simaQ** [comment]
恩，可以在 nameStyle 属性中设置 width,

```js
nameStyle: {
  width: 30,
}
```

**Comment by L-x-C** [comment]
> 恩，可以在 nameStyle 属性中设置 width,
> 
> ```js
> nameStyle: {
>   width: 30,
> }
> ```

哦！因为文档里没看到貌似，太感谢了
