### ISSUE TITLE
fixed x-axis in cascading histogram chart

### ISSUE THREAD

**Issue by saravanannnallasamy** [antvis/f2#533]
* **F2 Version**: 3.3.5
* **Platform**: ReactJs
* **Mini Showcase(like screenshots)**:
   X-axis is stable here

![image](https://user-images.githubusercontent.com/25293768/54529502-0f345f00-49a6-11e9-9ba5-5a0c4705289d.png)

With higher positive value the x-axis line moves little down. Is there a way to set x-axis line fixed to match the background image.

![image](https://user-images.githubusercontent.com/25293768/54529567-3d19a380-49a6-11e9-8335-58a83efc4402.png)

* **CodePen Link**:

var chart1 = new F2.Chart({
                id: 'mountNode',
                syncY: true,
                width:800,
                height:600
              });
              chart1.source(list1data,{
                value: {
                  min:-60,
                  max:60,
                  tickInterval:1
                }
              });
              chart1.tooltip({
                showCrosshairs: true,
                crosshairsStyle: { stroke: '#1890ff'    },
                background: {  fill: '#1890ff'    },
                typeStyle: {  fill: '#fff'     },
                onShow: function onShow(ev) {
                  ev.items.pop();
                }
              });
              chart1.axis('name', {  label: null,    grid: null   });
              chart1.axis('value', false);
              chart1.interval().position('name*value').color('type').adjust('stack');
              chart1.line().position('name*value2').color('type').adjust('stack');
              chart1.render();

I want make the x-axis fixed in cascading histogram chart.

**Comment by simaQ** [comment]
sorry，there is no solution.
