### ISSUE TITLE
请问 有把canvas 内容保存成图片的接口

### ISSUE THREAD

**Issue by P-Mz** [antvis/f2#534]

**Comment by simaQ** [comment]
目前默认没有提供这个接口，但是  F2 是基于 canvas 元素进行绘制的，你可以直接使用 canvas 的 toDataUrl() 来解决 https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by dongjianghao** [comment]
补充一下 小程序中使用 toDataURL的示例
```
const imgData = this.selectComponent('#chart').canvasEl.context.canvas.toDataURL();
```
