### ISSUE TITLE
[BUG]图表y轴左侧的数字显示很多00000或者很多99999

### ISSUE THREAD

**Issue by caoanlong** [antvis/f2#535]
![image](https://user-images.githubusercontent.com/25009920/54667989-bc36e500-4b28-11e9-9e7b-fd08006199ca.png)
![image](https://user-images.githubusercontent.com/25009920/54668011-c953d400-4b28-11e9-9a7e-dfecc1842d56.png)

**Comment by simaQ** [comment]
这个是浮点数计算的问题，建议在 chart.scale() 接口里面定义下 `formatter` 回调解决下。
