### ISSUE TITLE
在PieLabel中,圆环的文字重叠应该怎么处理

### ISSUE THREAD

**Issue by fangming666** [antvis/f2#537]
![image](https://user-images.githubusercontent.com/27843052/54804005-e31e2400-4cac-11e9-89ac-9581a951347e.png)

**Comment by simaQ** [comment]
尝试调大 `lineHeight` 属性值，默认值是 32，
![image](https://user-images.githubusercontent.com/6628666/54805083-c97edb80-4cb0-11e9-8e28-b4ffab9ff7be.png)

**Comment by fangming666** [comment]
不管用，还是重叠呢
