### ISSUE TITLE
为什么有时候图像会进行自己缩放，但是下一次就来就正常了

### ISSUE THREAD

**Issue by fangming666** [antvis/f2#538]
/*
        * 圆环的设置
        * */
        //整体配置
        let chart = new F2.Chart({
            id: 'gradeLineCanvas',
            plugins: PieLabel,
            pixelRatio: window.devicePixelRatio,
        });

        //数据源
        chart.source(resultGradeLineArr);

        //图例
        chart.legend({
            position: 'bottom',
            titleGap: 22,
            marker: 'square',
            align: 'center',
            itemFormatter: (val: string | number) => {
                return `${val}等`; // val 为每个图例项的文本值
            }
        });

        //圆环大小配置
        chart.coord('polar', {
            transposed: true,
            innerRadius: 0.65,
            radius: 3
        });

        //*坐标轴
        chart.axis(false);

        //工具提示
        chart.tooltip(false);

        //颜色
        chart.interval().position('const*scale').color('grade', ['#3FA1FF', '#3ECBCB', '#50CB74', '#FBD444', '#EF4864']).adjust('stack');

        //圆环中间内容
        chart.guide().html({
            position: ['50%', '50%'],
            html: '<div style="text-align: center;width:150px;height: 50px;">\n      <p style="font-size: 12px;color: #999;margin: 0" id="grade"> </p>\n      <p style="font-size: 18px;color: #343434;margin: 0;font-weight: bold;" id="scale"> </p>\n      </div>',
        });

        // 添加饼图文本
        chart.pieLabel({
            sidePadding: 40,
            inflectionOffset: 10,
            lineHeight: 0,
            textAlign: 'start',
            label1: function label1(data: any) {
                return {
                    text: data.scale + "%",
                    fill: '#919191',
                    fontSize: "14px"
                };
            },
            label2: function label1(data: any) {
                return {
                    text: data.people + "人",
                    marginLeft: 30,
                    fill: '#919191',
                    fontSize: "14px",
                    textAlign: 'start',
                };
            },
            onClick: function onClick(ev: any) {
                var data = ev.data;
                if (data) {
                    //@ts-ignore
                    document.getElementById("grade").innerHTML = `${data.grade}等`;
                    //@ts-ignore
                    document.getElementById("scale").innerHTML = `${data.scale} % `;
                }
            }

**Comment by simaQ** [comment]
看下是不是 canvas dom 的 宽 高样式导致的

**Comment by fangming666** [comment]
那我怎么去修改啊大佬，不固定宽高吗

**Comment by sanshuiwang** [comment]
> 看下是不是 canvas dom 的 宽 高样式导致的

固定了宽高也不行啊
