### ISSUE TITLE
圆环上的文字超出被隐藏了应该怎么办

### ISSUE THREAD

**Issue by fangming666** [antvis/f2#539]
![image](https://user-images.githubusercontent.com/27843052/54804157-7eaf9480-4cad-11e9-8356-f1be9cf6225c.png)

**Comment by simaQ** [comment]
超出了，调整下极坐标的半径。https://www.yuque.com/antv/f2/api-coordinate#0b5vxd

![image](https://user-images.githubusercontent.com/6628666/54805174-195da280-4cb1-11e9-9d0b-6ef177f76c34.png)

**Comment by fangming666** [comment]
这个地方可以了大佬，但是有时候加载进来的时候会进行缩放，有时候不会，一直没找到原因

**Comment by simaQ** [comment]
什么环境？

**Comment by fangming666** [comment]
在create-react-app里面使用的，componentDidMount生命周期里面去渲染了图表
