### ISSUE TITLE
双 Y 轴设置 coord.transposed = true 旋转后，只有一条 Y 轴, 如何实现双 Y 轴？

### ISSUE THREAD

**Issue by yazohu** [antvis/f2#541]
使用
```javascript
 chart.interval().position();
chart.line().position();
```
可实现水平方向的双 Y 轴。效果如图:
![水平双Y轴](https://img.alicdn.com/tfs/TB1jl3ugTZmx1VjSZFGXXax2XXa-396-256.png)
可是设置坐标系
```javascript
chart.coord({
  transposed: true
});
```
后，实现了旋转，只有一条 Y 轴。效果如图：
![单Y轴](https://img.alicdn.com/tfs/TB1OrISNYPpK1RjSZFFXXa5PpXa-399-251.png)
想知道怎么才可以实现旋转后的双 Y 轴。

或者怎么可以最简单的实现双 Y 轴的分组条形图（这是工作中碰到的最初的需求）。效果如下：
![双Y轴条形图](https://img.alicdn.com/tfs/TB1SREYN4TpK1RjSZFKXXa2wXXa-394-344.png)

**Comment by simaQ** [comment]
目前不支持
