### ISSUE TITLE
demo图表在安卓机上除chrome浏览器, 其他点击交互似乎都没有效果?

### ISSUE THREAD

**Issue by webliving** [antvis/f2#544]
* **F2 Version**: 3.3.8
* **Platform**: android

比如demo: 图表交互 > 饼图选中交互 , 不能点击交互
其他此类图表交互似乎都没有效果

**Comment by simaQ** [comment]
是网站的 demo 运行不了是吧，可能是网站 demo 代码编译的问题，你看下在你实际的项目中是否能够运行吧
