### ISSUE TITLE
【需求---层叠柱状图+一条折线+可平移】

### ISSUE THREAD

**Issue by ZYSHINee** [antvis/f2#550]
* **F2 Version**:3.3.8
* **Platform**:chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/zyshinee/pen/bJwzwv

作者你好，由于需求中有三种数据要展示，所以需要用到层叠柱状图和折线图混合使用，按照我的代码，初始化时柱状图每一条柱子宽度很窄，但是移动后柱子的宽度会重新渲染变宽，同时，长按显示tooltip时，会有误差，长按的是A条柱子，却显示了右边一条的tooltip.

请问下我的代码中有什么问题吗？

**Comment by army8735** [comment]
移动变宽发现了，长按误差没有发现。

**Comment by army8735** [comment]
定位这里：https://github.com/antvis/f2/blob/master/src/interaction/mixin/move.js#L122-L132
设置xScale的newValues的长度计算错误，minIndex出现了负值。

**Comment by army8735** [comment]
发现是柱状图重叠了，只有1个的时候没问题，这个例子同一时间有park/combo2种，计算就出错……

**Comment by army8735** [comment]
https://github.com/antvis/scale/blob/master/src/time-cat.js#L107
定位到这里，对于value的length，当重叠的时候，length*2多了一倍，计算错误。

**Comment by ZYSHINee** [comment]
> 宽度定位到这里：https://github.com/antvis/f2/blob/master/src/geom/mixin/size.js#L17
> count多了一倍导致变细。
> 
> 位置定位大概：https://github.com/antvis/scale/blob/master/src/time-cat.js#L107

移动变宽的问题解决了，感谢大佬！

**Comment by yubanxian2014** [comment]
我这里也出现长按会有误差，按A柱子tooltip展现的是B柱子，你解决了么？怎么解决的？
