### ISSUE TITLE
折线图在某些情况下，部分折线不显示

### ISSUE THREAD

**Issue by YueQuanXiaoChe** [antvis/f2#552]
您好，我这边有个折线图，有个显示上的小问题，在不添加缩略轴时显示是正常的；但是添加缩略轴之后，折线图有一部分不显示了，请问这个有办法解决吗？如下图所示：
![image](https://user-images.githubusercontent.com/13010474/55767036-d6217300-5aa9-11e9-9255-7baee17d671f.png)

**Comment by army8735** [comment]
有demo吗

**Comment by army8735** [comment]
只能增加上padding了
