### ISSUE TITLE
分组柱状图如何显示特例数据？比如只显示最大值最小值文本？

### ISSUE THREAD

**Issue by casyalex** [antvis/f2#558]
#113 和demo 用自定义shape的方法显示了每个数据的文本。

现在需求是只显示 每组的最大， 最小值的文本。

有什么实现思路吗？

类似这种效果

![image](https://user-images.githubusercontent.com/5988630/56340863-d3c7c300-61e5-11e9-89e9-dd50417317e7.png)

**Comment by simaQ** [comment]
可以使用自定义 Shape，在自定义 Shape 中可以拿到图形对应的原始数据，然后再对数据进行判断，添加相应标注对应的图形。
