### ISSUE TITLE
数据更新时，滚动条未重新渲染

### ISSUE THREAD

**Issue by ZYSHINee** [antvis/f2#561]
* **F2 Version**:3.3.9
* **Platform**:Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

例：
当前图表展示20条数据，滚动条可以滚动，并且任意滚动图表，切换tab后，数据更新为1条，这是图表没有同步渲染，滚动canvas区域，才会触发图表重新渲染。

**Comment by army8735** [comment]
demo?
