### ISSUE TITLE
折线图点击无数据坐标显示异常

### ISSUE THREAD

**Issue by Wzwttt** [antvis/f2#562]
1，折线图，x坐标是月份 十二个月 y坐标是金额 
2，默认显示19年数据（到本月截至，本月后的金额设置为null），数据从后台查询所得，
3，当切换到18年后显示十二个月，再次切换到19年，显示到本月
4，但是点击后面的无数据（null）坐标会显示18年的折线图，刷新后恢复正常。

**Comment by army8735** [comment]
demo?

**Comment by simaQ** [comment]
提供的信息无法帮助我们复现并定位问题，故关闭
