### ISSUE TITLE
坐标轴翻转，分组柱状图顺序会变，有什么办法可以按正确的顺序来么

### ISSUE THREAD

**Issue by mrsoda00** [antvis/f2#564]
如下图一，为一个分组柱状图
![image](https://user-images.githubusercontent.com/11399718/56668034-7221c000-66e1-11e9-973e-8f307482f464.png)
为了实现水平柱状效果，将cood下transposed设为true，结果如下图
![image](https://user-images.githubusercontent.com/11399718/56668207-b7de8880-66e1-11e9-8971-7a1278f7b225.png)
可以看到翻转过来后原本在左边的series2到了series1下面，可否有方法让反转后顺序与翻转前一样

**Comment by YuMay2009** [comment]
遇到同样的问题，求助

**Comment by YuMay2009** [comment]
请问你后来解决了吗

**Comment by simaQ** [comment]
在列定义中按照想要显示的顺序指定 values
