### ISSUE TITLE
官网日k图示例代码报错，手机扫码没有问题，在哪里可以看到扫码项目的代码

### ISSUE THREAD

**Issue by wsxgs** [antvis/f2#565]
PC:  https://antv.alipay.com/zh-cn/f2/3.x/demo/candlestick/daily.html   报错：Cannot read property '0' of undefined
移动端： https://antv.alipay.com/assets/dist/3.0.0/f2/3.x/candlestick/daily.html?enableWK=YES

**Comment by simaQ** [comment]
与 #586 属于同一问题，故关闭，解决方案请关注 #586
