### ISSUE TITLE
f2-3.3.9&3.3.8 chart.line()和chart.area()的渐变色值不同时，tooltip显示错误

### ISSUE THREAD

**Issue by doddjd** [antvis/f2#566]
* **F2 Version**: 3.3.9及官网demo的3.3.8
* **Platform**: PC Chrome Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
* **Mini Showcase(like screenshots)**:
当 chart.line()和chart.area()的渐变色值不同时，tooltip会出现两个相同的值事例，截图如下，以[官网demo为例](https://antv.alipay.com/zh-cn/f2/3.x/demo/line/gradient.html):

1.色值完全相同时，tooltip展示正常
![image](https://user-images.githubusercontent.com/10265767/56796361-f771b580-6844-11e9-8f8b-49fbc5b3ad2e.png)

2.色值有一处不同，则出现两个值展示
![image](https://user-images.githubusercontent.com/10265767/56796611-7e269280-6845-11e9-8d75-3b482155a6d7.png)

这个逻辑有点奇怪，找了半天才发现是这里的问题，想了下即使f2不支持line和area颜色的分别设置也不应该影响到tooltip，应该是个bug了，辛苦开源开发者们看下是什么问题呀。

**Comment by army8735** [comment]
https://github.com/antvis/f2/blob/master/src/plugin/tooltip.js#L104

这里的去重标准确实包含color，当2种颜色区别较大时区能够同时区分展示，如果去掉就会让人觉得数据丢失。
颜色相近时也会让人觉得多余，所以鱼与熊掌……

**Comment by dxq613** [comment]
是的这个地方纠结过好多次，也改过很多遍最终的结论就是要分辨颜色。如果你想在视觉上表现不一样，给 area 单独加个透明度吧，颜色一定要保持一致。

**Comment by doddjd** [comment]
> https://github.com/antvis/f2/blob/master/src/plugin/tooltip.js#L104
> 
> 这里的去重标准确实包含color，当2种颜色区别较大时区能够同时区分展示，如果去掉就会让人觉得数据丢失。
> 颜色相近时也会让人觉得多余，所以鱼与熊掌……

如果是demo这个例子的话，源数据只有age，area其实只是展示样式的不同，我觉得不应该有两个tooltip的展示。可能在别的图表中会有您说的情况——line和area分别表示两个数据，我只是觉得这里有些歧义。
