### ISSUE TITLE
如何Interaction交互行为引入 + 按需引用

### ISSUE THREAD

**Issue by drizzlezxy** [antvis/f2#567]
* **F2 Version**:3.3.9
* **Platform**:React
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我根据文档的按需引入写，会报错`chart.interval is not a function`：
```
const F2 = require('@antv/f2/lib/core');
require('@antv/f2/lib/interaction/pie-select');
```

似乎官方案例上，引入Interaction交互行为的代码都是：
```
// 首先引入 F2
const F2 = require('@antv/f2/lib/index');

// 引入 pie-select
require('@antv/f2/lib/interaction/pie-select');
```
但是这样不就把不需要的部分都引入了么？

**Comment by army8735** [comment]
core里不包含geom，引入想要的图形即可。

**Comment by drizzlezxy** [comment]
> core里不包含geom，引入想要的图形即可。

是的，我没有引入需要的图形，谢谢！
