### ISSUE TITLE
当我所有的数据全为0时，折线图为什么会计算-1

### ISSUE THREAD

**Issue by yimiZSK** [antvis/f2#569]
![image](https://user-images.githubusercontent.com/24860389/56904481-e6d56f80-6ad0-11e9-8350-1b6f2d585522.png)
如图，我的y坐标轴，数据都为0的时候，计算出-1。有没有什么属性或者办法解决这种情况

**Comment by army8735** [comment]
配置min: 0？

**Comment by yimiZSK** [comment]
@army8735 source的def我有配置min
![image](https://user-images.githubusercontent.com/24860389/56945748-bafecc00-6b5a-11e9-8dcb-27d4daab7884.png)
可以看这个链接：https://codepen.io/yimizsk/pen/gyyVxE

**Comment by simaQ** [comment]
再设置下 nice: false
