### ISSUE TITLE
如何在position中设置柱状图最小高度为1？

### ISSUE THREAD

**Issue by Gaion** [antvis/f2#570]
* **F2 Version**:3.3.9
* **Platform**:全部
* **Mini Showcase(like screenshots)**:无
* **CodePen Link**:无

控制图形显示位置的position属性能支持回调函数之类的么？柱状图想实现最小高度为1，没找到方式实现

**Comment by ytftianwen** [comment]
+1

**Comment by simaQ** [comment]
不支持。。。 如果你想要让柱状图对应 Y 轴数据为 0  的情况下能够显示一像素，那可以通过自定义 Shape 去实现，在绘制的时候根据 data 判断下

**Comment by renyuzh** [comment]
可以通过设置style的height来做
style("value",{
          height: function radius(val) {
            if (Math.abs(val) < MAX_VALUE * 0.01 && val !== 0) {
              if (val > 0) {
                return -1
              } else {
                return 1
              }
            }
          }
        })
