### ISSUE TITLE
3.3.8  版本k线图报错，官网demo都无法显示

### ISSUE THREAD

**Issue by EGsnn** [antvis/f2#574]
![image](https://user-images.githubusercontent.com/22165781/57286551-09c2dd80-70e8-11e9-932d-8bfd2767f07b.png)

**Comment by MinosIE** [comment]
这都一个月了 还没处理 效率低啊

**Comment by MinosIE** [comment]
定位了一下问题 发现是数据问题 
`.color('trend', function(val) {
      return COLOR_MAP[val];
})
`
这行代码，val应该是0或者1，但是数据给了一个0.2 所以获取不到，这个地方做一下兼容就可以了

**Comment by dxq613** [comment]
这个地方有些奇怪，前面的字段是处理后的，怎么会出现 0.2
```
 data.forEach(function(obj) {
      reportDates.push(obj.reportDate);
      obj.range = [obj.start, obj.end, obj.high, obj.low];
      obj.trend = obj.start <= obj.end ? 0 : 1; // 0 表示涨，1 表示跌
    });
```

**Comment by sunxia628** [comment]
https://github.com/antvis/f2/issues/586

**Comment by simaQ** [comment]
与 #586 属于同一问题，故关闭，解决方案请关注 #586
