### ISSUE TITLE
Uncaught TypeError: Cannot read property 'triggerOn' of undefined

### ISSUE THREAD

**Issue by wsf1214** [antvis/f2#575]
* **F2 Version**:"@antv/f2": "3.3.9"
* **Platform**:macOS 10.14
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/23648311/57344747-0462a300-717b-11e9-818a-8829b7a0505a.png)

"@antv/f2": "3.3.9"版本安装后，在调用`chart.clear()`方法时会造成
`Uncaught TypeError: Cannot read property 'triggerOn' of undefined`的错误。截图如上。
已经试验过：
1 把`chart.clear()`方法注释掉之后，报错消失。
2 不注释方法，把`@antv/f2`版本降到`3.3.8`及以下时，报错消失。

**Comment by jayzch** [comment]
同样的问题

**Comment by simaQ** [comment]
根据描述信息未能复现场景，故关闭

**Comment by zhaolixiang** [comment]
同样问题，现在还存在

**Comment by nicemango** [comment]
同样问题

**Comment by zengyue** [comment]
my-f2用最新版本试试

**Comment by jayzch** [comment]
> my-f2用最新版本试试

 不是小程序的应用  怎么办？

**Comment by zengyue** [comment]
> > my-f2用最新版本试试
> 
> 不是小程序的应用 怎么办？

f2用的是什么版本？把复现demo贴下

**Comment by majiang666** [comment]
同问题，怎么破？
