### ISSUE TITLE
雷达图绘制 line 时怎么定制连接处为弧线，非 lineJoin

### ISSUE THREAD

**Issue by lyle-luan** [antvis/f2#576]
* **F2 Version**:3.3.5
* **Platform**:iOS
* **Mini Showcase(like screenshots)**:
![showcase](https://user-images.githubusercontent.com/1920392/57424726-36dbd100-724b-11e9-883e-c9a57ceb4635.png)

如图，请教下如何定制连接处为弧线？

我的目标是实现下面效果：
<img width="601" alt="最终效果" src="https://user-images.githubusercontent.com/1920392/57427132-3b0cec00-7255-11e9-9a09-938704f04906.png">

**Comment by lyle-luan** [comment]
这个问题没人提供思路么？

**Comment by simaQ** [comment]
可以通过自定义 Shape 实现，但是目前 F2 的图形底层不支持 Path，所以目前这个图 F2 实现不了。用 G2 可以的
