### ISSUE TITLE
双环图tooltip触发区域问题

### ISSUE THREAD

**Issue by kuangyanit** [antvis/f2#579]
* **F2 Version**: 3.3.9
* **Platform**: macOS Mojave 10.14.4
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22702771/57522266-cde08000-7354-11e9-85ff-c13e7e4f5a3e.png)
* **CodePen Link**:  无

使用官网例子[https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/ring.html](url)时切换了一个数据源，如下：
```
var data = [
  { name: '50后', percent: 28.79, a: '1' },
  { name: '60后', percent: 21.04, a: '1' },
  { name: '70后', percent: 19.73, a: '1' },
  { name: '80后', percent: 14.83, a: '1' },
  { name: '90后', percent: 7.80, a: '1' },
  { name: '00后', percent: 7.80, a: '1' }
];
```
然后启用tooltip，`chart.tooltip(true);` 观察发现某些圆环相较其他圆环可触发tooltip的区域过小。比如80后对应的这部分圆环，仅边缘部分可触发tooltip。

之后又改变数据源做了几轮测试(比如切换为如下几种)，依然可以发现不同程度的tooltip触发区域小的问题，但不如此前明显。

```
var data= [
  { name: '50后', percent: 28.79, a: '1' },
  { name: '60后', percent: 21.04, a: '1' },
  { name: '70后', percent: 19.73, a: '1' },
  { name: '80后', percent: 14.83, a: '1' },
  { name: '90后', percent: 15.60, a: '1' }
];

var data = [
  { name: '50后', percent: 28.79, a: '1' },
  { name: '60后', percent: 21.04, a: '1' },
  { name: '70后', percent: 19.73, a: '1' }
];

var data= [
  { name: '50后', percent: 28.79, a: '1' },
  { name: '80后', percent: 14.83, a: '1' },
  { name: '90后', percent: 15.60, a: '1' }
];

```

请问该如何处理才可以改善这种情况？

**Comment by simaQ** [comment]
恩，这个是因为添加的 chart.guide().html 将环图的一些区域遮挡导致的，鼠标点击到了 html 上而非 canvas 上导致 canvas 上的事件没有捕获到。你可以将 guide().html() 的宽度调整下。

![image](https://user-images.githubusercontent.com/6628666/63991936-39c14100-cb1c-11e9-909d-93b280fe1bf3.png)
