### ISSUE TITLE
【Tooltip】 value 不展示， 只展示title ,title 下面的距离比较宽， 有配置项可以设置吗？

### ISSUE THREAD

**Issue by Running00** [antvis/f2#584]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/30852766/57750632-950a2780-7715-11e9-9bb9-97b5ef08d250.png)

* **CodePen Link**:

**Comment by simaQ** [comment]
设置 `titleGap: 0`
