### ISSUE TITLE
Legend Appear When click Chart

### ISSUE THREAD

**Issue by RicoLiu** [antvis/f2#585]
* **F2 Version**: "@antv/f2": "^3.3.9",
* **Platform**: Mac OS, node version: 10.15.0, npm version: 6.4.1
* **Mini Showcase(like screenshots)**:
I set `chart.legend(false)`
After click the chart, the legend will appear.
![QQ20190516-092446](https://user-images.githubusercontent.com/12722992/57819812-ac502000-77bc-11e9-9f70-c2db657b4a4f.png)
![111](https://user-images.githubusercontent.com/12722992/57819818-b07c3d80-77bc-11e9-919e-762a2203ff02.png)

* **CodePen Link**:
https://codepen.io/RicoLiu/pen/MdpvpG

**Comment by RicoLiu** [comment]
BTW, How to keep the animation going when fetching data from the server?

**Comment by simaQ** [comment]
It is tooltip, not legend, so you should call:

`chart.tooltip(false)`
