### ISSUE TITLE
蜡烛图示例报错

### ISSUE THREAD

**Issue by DvShu** [antvis/f2#586]
* **F2 Version**: 3.3.9
* **Platform**: windows
* **Mini Showcase(like screenshots)**:  
![1558332952(1)](https://user-images.githubusercontent.com/10515836/58000454-658b5e80-7b0b-11e9-9ae2-a1a254a33de8.png)
  
![1558332974(1)](https://user-images.githubusercontent.com/10515836/58000463-69b77c00-7b0b-11e9-81f8-87259274f600.png)

* **CodePen Link**: [蜡烛图-日K](https://antv.alipay.com/zh-cn/f2/3.x/demo/candlestick/daily.html)

官网给的蜡烛图的示例运行报错。经过排查问题是出在了 `color('trend', function(val) {})` 这个回调函数里面，有时候值会出现小数，不是实际的数据。  
![1558333483(1)](https://user-images.githubusercontent.com/10515836/58000560-b4d18f00-7b0b-11e9-8480-d1a278d4eff3.png)
  
![1558333502(1)](https://user-images.githubusercontent.com/10515836/58000567-b7cc7f80-7b0b-11e9-8017-e36dde347283.png)
  
如果改为 `color('trend', COLOR_MAP)` 就正确了。  
是否是在 `color()` 的回调函数的时候，取值出问题了。

**Comment by sunxia628** [comment]
![image](https://user-images.githubusercontent.com/26341016/59329249-0e029c00-8d21-11e9-9fcf-ff6a72b3d28f.png)
根据日K示例图的报错，我下载了为压缩板的f2-all.js，我排除了数据获取失败问题，这应该是个Bug；虽然定位到了，但是不明白这个功能具体数据来源，因为相关引用过多，我只好return '#ddf';来保证页面渲染，希望开发者能够关注解决或者提供一些帮助

![image](https://user-images.githubusercontent.com/26341016/59329185-e14e8480-8d20-11e9-8059-e4beb5c265c8.png)
