### ISSUE TITLE
K线图加上MA线后整个图形缩小了

### ISSUE THREAD

**Issue by DvShu** [antvis/f2#587]
* **F2 Version**: 3.3.8
* **Platform**: windows、android
* **Mini Showcase(like screenshots)**:
![1558423860(1)](https://user-images.githubusercontent.com/10515836/58076749-9d62d680-7bdd-11e9-9f7e-3c28ce235f64.png)

![1558423840(1)](https://user-images.githubusercontent.com/10515836/58076760-a0f65d80-7bdd-11e9-9be7-fc4c901cf144.png)

* **CodePen Link**:

价上了MA线后，上方出现了很多多余的刻度。

**Comment by simaQ** [comment]
？
