### ISSUE TITLE
图例过多如何控制大小

### ISSUE THREAD

**Issue by lisasslisa** [antvis/f2#593]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lisasslisa** [comment]
![image](https://user-images.githubusercontent.com/22209456/58621518-25db2880-82fc-11e9-9aa0-4167f4eb28fa.png)
![image](https://user-images.githubusercontent.com/22209456/58621532-2c69a000-82fc-11e9-99cf-568f5aface33.png)
![image](https://user-images.githubusercontent.com/22209456/58621542-3095bd80-82fc-11e9-9de5-5e6a8f6cb39a.png)

如上图  这三个tu li图例 有时候 总是大小不一致 折线图也遇到类似问题（偶现） 想问下 怎么控制半径统一

**Comment by wumingkai007** [comment]
我也是遇到这样的问题。图例影响到了图形的大小，然后我把图例单独拿出来做了。但是这样做的话，图例点击是，就切换不了啊，还在研究中。

**Comment by simaQ** [comment]
不使用自动 padding 策略，手动指定 padding
