### ISSUE TITLE
【柱状图】点击柱状图 出现的背景区域 可以调整背景区域的宽度吗？

### ISSUE THREAD

**Issue by Running00** [antvis/f2#598]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: 官网 链接 https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/dodge-column.html

**Comment by army8735** [comment]
marginRatio: 0.05 // 设置分组间柱子的间距

可以更改这个控制宽度
