### ISSUE TITLE
南丁格尔玫瑰图比例不能按照实际大小进行占比排序；

### ISSUE THREAD

**Issue by DuduStyle** [antvis/f2#599]
https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/rose.html
![image](https://user-images.githubusercontent.com/31200868/59342494-7e6ae680-8d3c-11e9-9b1d-da26fe373435.png)

**Comment by simaQ** [comment]
数据为 0 的话正常不就应该这么显示吗？
