### ISSUE TITLE
定制了图例，有矩形和原型，我的onClick触发不了了，然后我想点击图例的数据，触发事件，进行切换，我改怎么做

### ISSUE THREAD

**Issue by wumingkai007** [antvis/f2#603]
![image](https://user-images.githubusercontent.com/50254462/59837572-07f36780-9380-11e9-8f4a-34fb8f29c930.png)

求助。
 https://antv.alipay.com/zh-cn/f2/3.x/demo/component/legend-custom.html
我参考了这个事例，但是 chart.get('geoms'); ，方法，放在我这边都获取不到对象
，

**Comment by wumingkai007** [comment]
求大神告知，我改怎么获取图例的事件，然后进行点击切换显示数据

**Comment by simaQ** [comment]
自己
