### ISSUE TITLE
"TypeError: this.chart.hideTooltip is not a function"

### ISSUE THREAD

**Issue by Ale-cc** [antvis/f2#605]
hideTooltip 不存在，两次打印 chart对象结果不一致，一次包含 hideTooltip()，另一次hideTooltip不存在，多数情况是后者。

![QQ20190628-132238](https://user-images.githubusercontent.com/18302674/60319435-fd9d2300-99a8-11e9-9fc0-24107252b642.png)
![QQ20190628-132306](https://user-images.githubusercontent.com/18302674/60319438-0130aa00-99a9-11e9-8fff-43375f0fd718.png)

* **F2 Version**:  3.3.9
* **Platform**: MacOS mojave， chrome 75
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by army8735** [comment]
CodePen Link: ？
