### ISSUE TITLE
F2 changeData 渲染出的曲线呈阶梯状

### ISSUE THREAD

**Issue by Ale-cc** [antvis/f2#606]
* **F2 Version**: 3.3.9
* **Platform**: MacOs, Chrome 75
* **Mini Showcase(like screenshots)**:
![折线问题](https://user-images.githubusercontent.com/18302674/60476729-355ce100-9caf-11e9-8210-19c73b2d4ade.png)

* **CodePen Link**:
--
我用 webscoket 订阅了一个价格，然后 push 到 this.chartData(已经有 N 条数据)里,然后画出来的折线确实阶梯状的。我看了Demo 是用 changeData 来实现的，那么为什么曲线是这样的呢？
<img width="616" alt="QQ20190702-100311@2x" src="https://user-images.githubusercontent.com/18302674/60477078-920ccb80-9cb0-11e9-8e36-b7d542740c3c.png">

**Comment by Ale-cc** [comment]
如果我用 
`
this.chart.clear();
this.chart.source(this.chartData);
this.chart.repaint()
`
的话就会报错 `Uncaught TypeError: Cannot read property 'getXScale' of undefined`
![QQ20190702-101134](https://user-images.githubusercontent.com/18302674/60477418-b917cd00-9cb1-11e9-939e-8b2ad9b60645.png)

--
所以我现在都不知道怎么去更新图表了，官方 API、demo 跟实际效果有出入，咋办啊？

**Comment by army8735** [comment]
应该是先clear()，然后直接调用changeData()即可。

**Comment by Ale-cc** [comment]
@army8735 没用的
先 clear 再 changeData() 就报错。
![image](https://user-images.githubusercontent.com/18302674/60799424-b6334580-a1a5-11e9-932d-f2ed90694867.png)

![image](https://user-images.githubusercontent.com/18302674/60799424-b6334580-a1a5-11e9-932d-f2ed90694867.png)

**Comment by army8735** [comment]
说错了，直接changeData就可以，clear的话需要重新绘制图形元素。
你代码有link或者贴个示例？

**Comment by alwxkxk** [comment]
可以试试`chart.destroy()`，然后重新初始化图表，临时解决问题。

**Comment by simaQ** [comment]
如果你更新前后的数据源结构没有发生变化，即每条记录的字段都保持一致，直接调用 chart.changeData() 即可。

出现这个问题的原因可能是在数据或者写法上，请提供可复现的代码 demo 以便排查。这里先关闭了
