### ISSUE TITLE
在官网案例中，带文本的层叠柱状图如果只有一组数据时会出现宽度变宽，掩盖左边Y轴的标尺数据

### ISSUE THREAD

**Issue by LZQdingyuan** [antvis/f2#607]
具体代码如下：
出现bug
![image](https://user-images.githubusercontent.com/46004041/60481628-c1c3cf80-9cc0-11e9-83c4-761e545fc2cf.png)

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="chart-name" content="带文本的层叠柱状图">
    <title>F2 图表组件库 - AntV</title>
    <link rel="stylesheet" href="https://gw.alipayobjects.com/os/rmsportal/YmDAMEQVbLJpVbKiRQVX.css" />
    
</head>
<body>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>

<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.3.8/f2.min.js"></script>

<script src="https://gw.alipayobjects.com/os/antv/assets/lib/lodash-4.17.4.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/lib/jquery-3.2.1.min.js"></script>

<script src="https://gw.alipayobjects.com/os/rmsportal/NjNldKHIVQRozfbAOJUW.js"></script>

  <div class="chart-wrapper">
    <canvas id="mountNode"></canvas>
  </div>
  <script>
  var Shape = F2.Shape;
  var Util = F2.Util;
  Shape.registerShape('interval', 'text', {
    draw: function draw(cfg, container) {
      var points = this.parsePoints(cfg.points);
      var style = {
        fill: cfg.color,
        z: true // 需要闭合
      };
      container.addShape('rect', {
        attrs: Util.mix({
          x: points[1].x,
          y: points[1].y,
          width: points[2].x - points[1].x,
          height: points[0].y - points[1].y
        }, style)
      });

      var origin = cfg.origin._origin; // 获取对应的原始数据
      return container.addShape('text', {
        attrs: {
          x: (points[1].x + points[2].x) / 2,
          y: (points[0].y + points[1].y) / 2,
          text: origin.yName,
          fill: '#fff',
          textAlign: 'center',
          textBaseline: 'middle'
        }
      });
    }
  });

  var data = [{
    groupName: 'GroupA',
    xName: '1',
    yName: 100
  }, {
    groupName: 'GroupB',
    xName: '1',
    yName: 300
  }];

  var chart = new F2.Chart({
    id: 'mountNode',
    pixelRatio: window.devicePixelRatio
  });

  var defs = {
    xName: {
      range: [0.15, 0.85],
      type: 'cat'
    }
  };
  chart.source(data, defs);
  chart.axis('yName', {
    grid: null
  });
  chart.axis('xName', {
    grid: null
  });
  chart.tooltip({
    custom: true, // 自定义 tooltip 内容框
    onChange: function onChange(obj) {
      var legend = chart.get('legendController').legends.top[0];
      var tooltipItems = obj.items;
      var legendItems = legend.items;
      var map = {};
      legendItems.map(function(item) {
        map[item.name] = _.clone(item);
      });
      tooltipItems.map(function(item) {
        var name = item.name;
        var value = item.value;
        if (map[name]) {
          map[name].value = value;
        }
      });
      legend.setItems(_.values(map));
    },
    onHide: function onHide() {
      var legend = chart.get('legendController').legends.top[0];
      legend.setItems(chart.getLegendItems().country);
    }
  });
  chart.interval().position('xName*yName').color('groupName').adjust('stack').shape('text');

  chart.render();
</script>

</body>
</html>

**Comment by LZQdingyuan** [comment]
请问可以改下这个bug么？我现在这个版本的app要上线了呀~ @

**Comment by simaQ** [comment]
不是 BUG，是这段配置引起的，将 range 属性移除就好

```js
  var defs = {
    xName: {
      range: [0.15, 0.85],
      type: 'cat'
    }
  };
```
