### ISSUE TITLE
X轴有没有办法显示在顶部

### ISSUE THREAD

**Issue by daqi** [antvis/f2#608]
RT

**Comment by army8735** [comment]
chart.axis({
position: 'top',
})

**Comment by daqi** [comment]
文档里没有这个写法，设置之后报错


Uncaught TypeError: Cannot set property 'position' of undefined

**Comment by army8735** [comment]
呃，翻了下确实不支持top，只有y轴支持左右……

想实现的话只能隐藏坐标轴自己绘制了。

类似：
https://antv.alipay.com/zh-cn/f2/3.x/demo/bar/negative-column-1.html
