### ISSUE TITLE
在支付宝小程序中使用的时候tooltip显示不全。

### ISSUE THREAD

**Issue by newBird01** [antvis/f2#611]
支付宝小程序中使用my-f2会出现tooltip显示不全的问题。附上截图
![2](https://user-images.githubusercontent.com/25924193/61018724-61244900-a3ca-11e9-8149-7bca25edc124.png)

**Comment by army8735** [comment]
未重现，小程序例子里3个tooltip都出现了，有demo吗

**Comment by simaQ** [comment]
试着调整下 padding。增加上边距值 https://www.yuque.com/antv/f2/api-chart#92uqpt
