### ISSUE TITLE
折线图 移动端上 左右 平滑 线条连接错误

### ISSUE THREAD

**Issue by GQxQD** [antvis/f2#612]
* **F2 Version**: ^3.3.9
* **Platform**: xiaomi8 嵌入 APP 的微信浏览器内核 webview
* **Mini Showcase(like screenshots)**:
在vue中使用的，使用了左右平滑的功能，默认显示没问题，向左滑动后，就出现了点线连接错误，web上不会出现此问题
![Screenshot_2019-07-11-17-05-31-433_com accentrix](https://user-images.githubusercontent.com/15622127/61038186-2557a680-a3ff-11e9-8cdd-bb304acf10c6.png)
![Screenshot_2019-07-11-17-06-25-974_com accentrix](https://user-images.githubusercontent.com/15622127/61038193-28eb2d80-a3ff-11e9-899f-992d4797bf80.png)

* **CodePen Link**:

```js
      if (!this.$refs.activeChart) return;
      this.chart && this.chart.destroy();
      this.chart = new F2.Chart({
        id: 'activeChart',
        animate: false,
        width: 694 * 0.5,
        height: 640 * 0.5,
        padding: [50, 0, 'auto', 'auto'],
        pixelRatio: window.devicePixelRatio * 2,
        plugins: [Legend, ScrollBar, Pan],
      });
      const data = this.dataWrapper.length ? this.dataWrapper : generateDataWhenNoData(this.dateRangeTab);
      // 默认显示的日期，去重后取最后7个
      const originDates = [...new Set(data.map(item => item.date))].slice(-7);
      this.chart.source(data, {
        value: {
          min: 0,
        },
      });
      this.chart.scale('date', {
        type: 'cat',
        tickCount: 7,
        values: originDates,
      });
      this.chart.scale('value', {
        tickCount: 5,
        min: 0,
        // nice: false,
        ticks: this.valueTicks,
      });
      this.chart.axis('date', {});
      this.chart.axis('value', {
        label: (text) => {
          return {
            text: /[^\d]/.test(text) ? '' : text,
          };
        },
      });
      this.chart.tooltip({});
      this.chart.legend('type', {
        marker(x, y, r, ctx) {
          ctx.lineWidth = 2;
          ctx.strokeStyle = ctx.fillStyle;
          ctx.moveTo(x - r - 3, y);
          ctx.lineTo(x + r + 3, y);
          ctx.stroke();
        },
        wordSpace: 12,
        itemWidth: null,
      });
      this.chart.line().position('date*value').color('type', ['#7C6AF2', '#5C89FF']);
      this.chart.point().position('date*value').color('type', ['#7C6AF2', '#5C89FF']).style({
        stroke: '#fff',
        lineWidth: 1,
      });
      // 定义进度条
      this.chart.scrollBar({
        mode: 'x',
        xStyle: {
          backgroundColor: '#fff',
          fillerColor: '#fff',
          offsetY: -2,
        },
      });
      this.chart.interaction('pan');
      this.chart.render();
```

**Comment by yleson** [comment]
我也遇到了，求解决啊。android会  iOS不会

**Comment by yleson** [comment]
// 数据结构
            this.chartData.position = this.chartData.rows[0] + '*' + this.chartData.values[0]
            // 判断数据是否多于6条数据，是的话使用先展示6条数据，其他滑动显示
            if (this.chartData.origins.length > 6) {
              // 获取前6个数据
              var rowDatas = []
              this.chartData.origins.forEach(function (obj) {
                rowDatas.push(obj[self.chartData.rows[0]])
              })
              const config = {
                [this.chartData.rows[0]]: {
                  values: rowDatas.slice(0, 6)
                }
              }
              chart.source(this.chartData.origins, config);

              // 定义进度条
              chart.scrollBar({
                mode: 'x',
                xStyle: {
                  backgroundColor: '#F4F7FC',
                  fillerColor: '#DFE7F5',
                  offsetY: -2
                }
              });
              // 滑动手势
              chart.interaction('pan');
            } else {
              chart.source(this.chartData.origins);
            }
            // 配置数据，颜色
            console.log(this.chartData.position)
            chart.line().position(this.chartData.position).shape('smooth').color(this.chartData.themeColors[this.chartData.themeType]);
            chart.point().position(this.chartData.position).shape('smooth').color(this.chartData.themeColors[this.chartData.themeType]).style({
              stroke: '#fff',
              lineWidth: 1
            });
            chart.render();

**Comment by GQxQD** [comment]
@yleson 
我加上这个 `sortable: false` 就好了，你试试是不是
![image](https://user-images.githubusercontent.com/15622127/61283365-9a582100-a7ef-11e9-93b3-fa558e787c66.png)

**Comment by yleson** [comment]
@GQxQD 
确实有用，请问是在哪里文档找到的吗？

**Comment by GQxQD** [comment]
@yleson API 文档能用的配置一个个试出来的[哭笑]
