### ISSUE TITLE
平移柱状图点击图例失效

### ISSUE THREAD

**Issue by wangxianping321** [antvis/f2#613]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by wangxianping321** [comment]
![image](https://user-images.githubusercontent.com/32926615/61192699-00a64c00-a6e9-11e9-959f-9b36cfc4d21c.png)

**Comment by simaQ** [comment]
无可复现定位 demo
