### ISSUE TITLE
平移柱状图中formatter只格式化了最初的几个数据,剩余x轴下标不显示

### ISSUE THREAD

**Issue by mofuliunian** [antvis/f2#614]
chart.source(data, {
        section: {
          type: "timeCat",
          tickCount: 7,
          values: originDates,
          // mask: "MM-DD",
          formatter: function(data) {
            console.log(data)
            const day = new Date(data).getDay();
            const weekday = [
              "周日",
              "周一",
              "周二",
              "周三",
              "周四",
              "周五",
              "周六"
            ];
            return weekday[day]
          },
        },
        duration: {
          tickCount: 7
        }
      });
![image](https://user-images.githubusercontent.com/31590054/61199958-71159300-a712-11e9-8d88-edb6cc055015.png)

**Comment by mofuliunian** [comment]
`chart.source(data, {
        show: {
          type: "timeCat",
          // tickCount: 4,
          values: originDates,
          formatter: function(data) {
            return dateFtt('MM', new Date(data))
            console.log(data, 'data')
            // return data.split('/')[1]
          },
        },
        duration: {
          tickCount: 7
        }
      });`
![image](https://user-images.githubusercontent.com/31590054/61269409-14c57880-a7d1-11e9-8bae-89d67e787eed.png)
![image](https://user-images.githubusercontent.com/31590054/61269428-1f800d80-a7d1-11e9-9ea7-8908f7b89d76.png)

**Comment by mofuliunian** [comment]
`chart.source(data, {
        show: {
          type: "cat",
          // tickCount: 4,
          values: originDates,
          ticks: this.ticks
        },
        duration: {
          tickCount: 7
        }
      });`
类型设定为cat则
![image](https://user-images.githubusercontent.com/31590054/61270786-3c1e4480-a7d5-11e9-897e-4b6da4313973.png)

拖动一次后就
![image](https://user-images.githubusercontent.com/31590054/61270746-23ae2a00-a7d5-11e9-9a28-5b04dbd5849e.png)

**Comment by simaQ** [comment]
无可复现定位 demo
