### ISSUE TITLE
柱状图坐标轴反转之后怎么设置x轴方向

### ISSUE THREAD

**Issue by wangruiStart** [antvis/f2#615]
![image](https://user-images.githubusercontent.com/21194195/61353490-87eaef80-a8a2-11e9-8e33-2951cd4233bf.png)
代码只设置了transposed: true。现在想从1月份开始，但是没地方设置，文档里Coordinate直角坐标系说有start,end两个属性，但并没有地方说明该怎么用

**Comment by army8735** [comment]
那个start和end是只读返回获取原点坐标的。

可以先对data自定义排好顺序，然后chart.area({ sortable: false})，这样就按照自定义排序了

**Comment by wangruiStart** [comment]
> 那个start和end是只读返回获取原点坐标的。
> 
> 可以先对data自定义排好顺序，然后chart.area({ sortable: false})，这样就按照自定义排序了

interval类型sortable默认就是false的自定义排序

**Comment by simaQ** [comment]
可以在列定义中设置 values 属性，自己定义顺序
