### ISSUE TITLE
柱状图tooltip需要长按才显示

### ISSUE THREAD

**Issue by ytftianwen** [antvis/f2#620]
* **F2 Version**: 3.3.8
* **Platform**:  ios12.1 微信 ios safari
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by manchang6** [comment]
同问，
我用的是折线图，在电脑google调试还是在手机上都是长按才能显示，经常会出现其他文字复制

**Comment by manchang6** [comment]
请问楼主改好了吗，是怎么解决的
