### ISSUE TITLE
F2能支持多View吗，或者可以在同一个图表中加载不同的数据源

### ISSUE THREAD

**Issue by mrKylinZhou** [antvis/f2#622]
需求是这样的，需要绘制多条折线图在同一个图表中，某些指标会有聚合然后做adjust('stack')调整，剩下的指标正常绘制。如果这样的话数据处理会非常麻烦，用G2多view实现起来会非常方便，但在F2中，并没有找到多view的使用，不知道F2是否有其他类似的替代方案

**Comment by JChehe** [comment]
@mrKylinZhou Hello，我也遇到类似的需求。请问你找到解决方案了吗？

**Comment by dxq613** [comment]
不支持，如果支持了跟 G2 其实没啥差别了。
