### ISSUE TITLE
调用chart.repaint会导致tooltip消失

### ISSUE THREAD

**Issue by wangmingxu** [antvis/f2#624]
* **F2 Version**:3.4.0
* **Platform**:all
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15760369/61921209-e85aea80-af8e-11e9-9970-fa15ab500bd0.png)
![image](https://user-images.githubusercontent.com/15760369/61921228-f872ca00-af8e-11e9-81ba-9aaf543a9215.png)

* **Code Pen**:
https://codepen.io/wangmingxu/pen/YmGVdv

**Comment by wangmingxu** [comment]
这个issue怎么就关闭了...请问有办法解决吗？现在在做一个平移的折线图 希望tooltip一直存在 但是无法实现 @simaQ

**Comment by simaQ** [comment]
不建议在 onShow 里面调用 chart.repaint()...

如果你是因为使用了 pan 交互，并且想要在平移的过程中一直显示 tooltip，可以这么做：https://github.com/antvis/f2/issues/220#issuecomment-410582940

**Comment by wangmingxu** [comment]
上面这个方法这个我也摸索出来了，但是性能太差了,因为showTooltip会导致canvas重新draw,直接拉低了整个canvas的性能...
