### ISSUE TITLE
pan模式滚动x轴隐藏的标记无法再显示

### ISSUE THREAD

**Issue by coldestlin** [antvis/f2#628]
* **F2 Version**:     "@antv/f2-canvas": "~1.0.5",  "@antv/wx-f2": "~1.1.4"
* **Platform**: 微信小程序  2.7.7
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

微信小程序在scroll/pan模式下, x轴隐藏的标记无法显示

初始渲染显示一切正常

![image](https://user-images.githubusercontent.com/19356579/62260966-5f3c2b80-b446-11e9-9caf-bc3e9877be06.png)

但是把图表scroll拖动, 隐藏的x轴坐标无法显示.
![image](https://user-images.githubusercontent.com/19356579/62260973-695e2a00-b446-11e9-8d64-53b4d4157772.png)

拖动到后面就都是空白了

![image](https://user-images.githubusercontent.com/19356579/62261115-c78b0d00-b446-11e9-8fb7-4fb45b2f056c.png)

尝试设置了ticks, min, max都无法解决这个问题
```
chart.source(this.data.flowData, {
        ts: {
          type: "timeCat",
          range: [0, 1],
          mask: "HH:mm:ss",
          values: tsArray.slice(tsArray.length - 80, tsArray.length),
          // min: util.formatTime(new Date(1562569195094), 'TIME') ,
          // max: util.formatTime(new Date(1562569199094), 'TIME') ,
          tickCount: 5,
          // ticks: tsTick, // https://github.com/antvis/f2/issues/468
        }
```

**Comment by simaQ** [comment]
提供的信息无法帮助我们进行问题的定位，故关闭。您可以根据我们的模板重新提一个 issue，谢谢~
