### ISSUE TITLE
在IOS12上，反复切换SPA路由多次后，页面白屏

### ISSUE THREAD

**Issue by shihuacivis** [antvis/F2#630]
* **F2 Version**:  3.4.0
* **Platform**: IOS 12.3
react-router: 5.0.1
react: 16.8.4

F2图表嵌套在React组件中，在组件生命周期componentWillUnmount中调用chart.destroy()方法销毁图表。当SPA反复切换路由时（前进后又后退），一开始表现正常。大约往复10次后，页面上的大部分图表变成空白（部分正常显示）。此时即使刷新页面图表也无法正常显示，必须关闭浏览器窗口重开。
以上问题在IOS12的iPhone上必现。怀疑页面的canvas缓存没有正确释放。
```
  componentWillUnmount() {
    this.chartContainner && this.chartContainner.destroy();
    this.chartContainner = null;
    this.cvs = null;
    this.chartRendered = false;
  }
```

**Comment by thinkey-yang** [comment]
我这边遇到了同样的问题，目前有什么方法解决吗

**Comment by LCF1314** [comment]
这个问题怎么解决

**Comment by LCF1314** [comment]
？？？？？

**Comment by LCF1314** [comment]
？？？

**Comment by LCF1314** [comment]
????????????

**Comment by snowkeda** [comment]
> 这个问题怎么解决

建议先不走spa。后期解决在走spa

**Comment by zengyue** [comment]
https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12

看了下，是因为这个问题导致的，这个需要清理需要自行处理下，这个会改变canvas大小的，destroy的时候没法在f2里面默认处理

```
// 在destory前把canvas宽高都设置成0
const el = this.chart.get('el')
el.width = 0;
el.height = 0;
this.chart.destroy();
```
