### ISSUE TITLE
当我使用双坐标时，设置了tickCount，两个坐标的点个数并没有完全相同，坐标刻度线比较乱，不知是bug还是设计如此

### ISSUE THREAD

**Issue by steady-join** [antvis/f2#631]
使用了ticks属性。能满足我的刻度个数，但是ticks和tickCount都不能满足刻度线重合，不乱。如下图：
<img width="568" alt="屏幕快照 2019-08-01 下午6 09 02" src="https://user-images.githubusercontent.com/29935583/62285073-7a7b5b00-b487-11e9-867c-e51d8dcee656.png">

ps：我应该如何让双坐标的坐标刻度线重合，不错乱。

**Comment by simaQ** [comment]
这是因为两边的数据范围不一致导致的。设置下这个属性即可 [syncY](https://www.yuque.com/antv/f2/api-chart#ou7mld)

**Comment by tanrongjun** [comment]
> 这是因为两边的数据范围不一致导致的。设置下这个属性即可 [syncY](https://www.yuque.com/antv/f2/api-chart#ou7mld)

加了这个属性依然无效

**Comment by tanrongjun** [comment]
![image](https://github.com/antvis/F2/assets/51949327/7eb182b5-a6b2-40d1-8b15-b9dd3c83c3e4)
![image](https://github.com/antvis/F2/assets/51949327/a649b5f5-e207-4817-9d25-1ea74e7a64de)
