### ISSUE TITLE
设置point后导致tooltip展示有问题

### ISSUE THREAD

**Issue by DavidWong9785** [antvis/f2#635]
![微信截图_20190809164523](https://user-images.githubusercontent.com/35354987/62766564-580bc200-bac5-11e9-8598-965016193a03.png)

问题：当设置point之后，tooltip-onShow方法的参数正常情况下应该是返回一个元素，结果返回的是两个，导致tooltip渲染的value变多
还有其他其他参数的设置也有可能会触发这种情况
pan地址：https://codepen.io/davidwong9785/pen/XvBVjK

**Comment by simaQ** [comment]
因为我们对 Tooltip 展示数据的过滤规则会考虑颜色，如果数据相同但是颜色不一样就认为是两条数据，你可以在 `chart.tooltip()` 的 onShow 钩子中将 items 去重下：

```js
chart.tooltip({
  onShow(ev) {
    const items = ev.items;
    // 操作 items 进行去重
  }
})
```

**Comment by shiyuanzheng** [comment]
无效
