### ISSUE TITLE
折线图平移类型图表前后两条数据点显示不全?

### ISSUE THREAD

**Issue by ouyangxiaoai** [antvis/f2#636]
官方例子下折线图平移的前后两个点显示不完整？
Link: https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-line-chart.html

**Comment by ChenYing13** [comment]
坐标轴线加上range，左右留白，如图。可根据图表坐标轴数量调整值。
![image](https://user-images.githubusercontent.com/45352425/62855947-1fb6ee80-bd26-11e9-8421-4984cf154e6a.png)

**Comment by ouyangxiaoai** [comment]
@ChenYing13 坐标轴数量调整值能否详细一下，谢谢！如何知道值设为多少？我现在的方法是直接在两端加一个空值也能显示全
