### ISSUE TITLE
Tooltip如何设置多条曲线的tooltipMarkerStyle

### ISSUE THREAD

**Issue by hxlniada** [antvis/f2#637]
看文档Tooltip中tooltipMarkerStyle只能设置一种样式，想实现两条折线的tooltipMarker不同样式该怎么写？
tooltipMarkerStyle: { fill: '#FF3909' , stroke: '#FF3909', strokeOpacity: 0.3, lineWidth: 5 },
![image](https://user-images.githubusercontent.com/3838586/62947356-f7f28400-be14-11e9-852e-4564fb94b114.png)

**Comment by simaQ** [comment]
不支持

**Comment by blacider** [comment]
@simaQ 是否支持点的大小控制（fill部分）
