### ISSUE TITLE
柱状图绘制文本时 x轴为数组不能显示文本

### ISSUE THREAD

**Issue by ruapapanoob** [antvis/f2#638]
* **F2 Version**: 3.3.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/ruapapanoob/pen/MWgyLrG

柱状图绘制文本时 x轴为数组不能显示文本
[CodePen Link](https://codepen.io/ruapapanoob/pen/MWgyLrG)

**Comment by simaQ** [comment]
我们目前只支持类型为数值的数组结构，而你的数据是字符串类型。建议在使用 guide().text() 绘制的时候，处理下 obj.year，取数组的第一个或者第二个数据
