### ISSUE TITLE
官方demo双Y轴图legend不显示

### ISSUE THREAD

**Issue by yleson** [antvis/f2#639]
https://antv.alipay.com/zh-cn/f2/3.x/demo/other/double-axis-interval.html

Line: 118-120
  chart.legend({
    position: 'bottom'
  });

**Comment by simaQ** [comment]
感谢反馈，是我们编写疏忽，这句代码多余了，因为我们使用的是自定义 Shape 方式生成分组柱状图以支持双 Y 轴，这种映射方式并不会生成图例：

```js
  chart.interval().position('genre*domestic').shape('left').size(15);
  chart.interval().position('genre*international').color('#36B3C3').shape('right').size(15);
``` 

可以了解下我们默认生成图例的逻辑：https://www.yuque.com/antv/f2/api-legend
