### ISSUE TITLE
x轴为时间序列，数据中缺少某个时间的值时，前后的点能否连起来？线中间不要有断点

### ISSUE THREAD

**Issue by suyaqiang04** [antvis/f2#645]
![将断点连起来](https://img-bbs.csdn.net/upload/201401/20/1390178825_207172.jpg)

- 像这张图空掉的值为null，是否可以将前后两个点连起来，tooltip不显示空掉的值

**Comment by suyaqiang04** [comment]
[https://img-bbs.csdn.net/upload/201401/20/1390178825_207172.jpg](url)

**Comment by suyaqiang04** [comment]
@simaQ

**Comment by simaQ** [comment]
可以，https://www.yuque.com/antv/f2/api-geometry#b36krc
