### ISSUE TITLE
怎么给点，线折线图添加点击事件

### ISSUE THREAD

**Issue by shouwangshe** [antvis/f2#647]
* **F2 Version**: 3.4.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://hy-app.oss-cn-shanghai.aliyuncs.com/uploadFiles/newlife-MobilePhoto/525241668828397568/616319667789185024.jpg?Expires=4720583659&OSSAccessKeyId=LTAIPAczvHRBTx5g&Signature=cJeyZdtE06%2BPDewZ4HkCkYmLCqc%3D)
希望点击图上的点进入某一个月份的详情页。。但是点线图，不太清楚怎么实现精确点击，看手册有tooltip，但是范围太大。这个点线图还没有柱状图的点击事件，自己定义事件没看明白，有点复杂。求帮助。。

**Comment by simaQ** [comment]
F2 目前没有提供图表的事件支持，可以通过直接监听 canvas 的 click 事件，然后通过 [`chart.getRecord()`](https://www.yuque.com/antv/f2/api-chart#5va0hu) 这个接口来获取是否击中某个点。
