### ISSUE TITLE
按需加载引入guide无效，真是服了！

### ISSUE THREAD

**Issue by steady-join** [antvis/F2#651]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.yuque.com/antv/f2/api-guide#l09ehi](https://www.yuque.com/antv/f2/api-guide#l09ehi)

### Steps to reproduce

<img width="458" alt="屏幕快照 2019-08-31 下午7 51 29" src="https://user-images.githubusercontent.com/29935583/64063602-da048c00-cc28-11e9-8b82-86a4b0d95d3a.png">

<img width="744" alt="屏幕快照 2019-08-31 下午7 49 35" src="https://user-images.githubusercontent.com/29935583/64063605-e688e480-cc28-11e9-8038-a5a9e97278c3.png">

### What is expected?
引入啊

### What is actually happening?
没引入

| Environment | Info |
|---|---|
| f2 | 3.4.0 |
| System | mac |
| Browser | chrome |

**Comment by cycgit** [comment]
```
import Guide from '@antv/f2/lib/plugin/guide'
```

你引的路径不对
