### ISSUE TITLE
关于pna模式下的两个bug，官网例子（100%复现）

### ISSUE THREAD

**Issue by steady-join** [antvis/F2#652]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-line-chart.html](https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-line-chart.html)

### Steps to reproduce
均在全屏模式下操作，为了方便
第一个bug：
1.在pan模式下，讲滚动条滑动至左侧，然后在图表右侧快速向上滑动，此时滚动条位置发生变化，然后点击屏幕，滚动条回归。
2.如果是type为timeCat，经上述操作后，x轴坐标会缺失。
第二个bug：
type为timeCat时，自定义label，label于图表点参差不齐，即使使用textAlign属性也无法达到预期

### What is expected?
正常渲染

### What is actually happening?
没有正常渲染

| Environment | Info |
|---|---|
| f2 | 3.4.0 |
| System | android 小米6x |
| Browser | 自带浏览器 |

---
官网例子demo可以体现出。

**Comment by chenchen12** [comment]
> https://antv.alipay.com/zh-cn/f2/3.x/demo/interaction/pan-for-line-chart.html

这个问题修复了吗？我也遇到这样的问题

**Comment by steady-join** [comment]
别想咯，我提的几个bug要么没回复，要么直接给我关了

**Comment by benvirus** [comment]
> 别想咯，我提的几个bug要么没回复，要么直接给我关了

难怪被 Fork 了这么多次，估计都去自己维护了。

**Comment by zengyue** [comment]
新版本修复掉了
