### ISSUE TITLE
饼图圆环大小设置

### ISSUE THREAD

**Issue by giantss** [antvis/f2#661]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义设置饼图大小。
```
 chart.coord('polar', {
      transposed: true,
      innerRadius: 0.7,
      radius: 1 //最大只能设置到1 圆环直径大小太小了，手机屏幕宽度到1/5都不到
    });
```
![image](https://user-images.githubusercontent.com/13778798/64771723-06ea6480-d582-11e9-9c5c-5305e7984e6a.png)

### What does the proposed API look like?
可以自定义设置饼图大小。

**Comment by simaQ** [comment]
可以将 `appendPadding` https://www.yuque.com/antv/f2/api-chart#u5skik 值设为 0，如果还太小，就可以手动调整下 padding https://www.yuque.com/antv/f2/api-chart#92uqpt 值。

**Comment by giantss** [comment]
3q
