### ISSUE TITLE
多条折线显示异常，附测试数据

### ISSUE THREAD

**Issue by openpython** [antvis/F2#662]
var data = [{date:'00:00', type:'BTC-USD-190920', value:510342 },{date:'00:00', type:'BTC-USD-190927', value:4549557 },{date:'00:00', type:'BTC-USD-191227', value:1679935 },{date:'00:01', type:'BTC-USD-190920', value:509949 },{date:'00:01', type:'BTC-USD-190927', value:4549966 },{date:'00:01', type:'BTC-USD-191227', value:1678456 },{date:'00:02', type:'BTC-USD-190920', value:510194 },{date:'00:02', type:'BTC-USD-190927', value:4550004 },{date:'00:02', type:'BTC-USD-191227', value:1675363 },{date:'00:03', type:'BTC-USD-190920', value:510000 },{date:'00:03', type:'BTC-USD-190927', value:4550014 },{date:'00:03', type:'BTC-USD-191227', value:1677146 },{date:'00:04', type:'BTC-USD-190920', value:509820 },{date:'00:04', type:'BTC-USD-190927', value:4549354 },{date:'00:04', type:'BTC-USD-191227', value:1673691 },{date:'00:05', type:'BTC-USD-190920', value:509827 },{date:'00:05', type:'BTC-USD-190927', value:4549429 },{date:'00:05', type:'BTC-USD-191227', value:1674433 },{date:'00:06', type:'BTC-USD-190920', value:510059 },{date:'00:06', type:'BTC-USD-190927', value:4549541 },{date:'00:06', type:'BTC-USD-191227', value:1677965 },{date:'00:07', type:'BTC-USD-190920', value:510142 },{date:'00:07', type:'BTC-USD-190927', value:4549172 },{date:'00:07', type:'BTC-USD-191227', value:1679227 },{date:'00:08', type:'BTC-USD-190920', value:509976 },{date:'00:08', type:'BTC-USD-190927', value:4548423 },{date:'00:08', type:'BTC-USD-191227', value:1679251 },{date:'00:09', type:'BTC-USD-190920', value:509982 },{date:'00:09', type:'BTC-USD-190927', value:4548372 },{date:'00:09', type:'BTC-USD-191227', value:1680394 },{date:'00:10', type:'BTC-USD-190920', value:510047 },{date:'00:10', type:'BTC-USD-190927', value:4549334 },{date:'00:10', type:'BTC-USD-191227', value:1680554 },{date:'00:11', type:'BTC-USD-190920', value:510380 },{date:'00:11', type:'BTC-USD-190927', value:4549678 },{date:'00:11', type:'BTC-USD-191227', value:1681379 },{date:'00:12', type:'BTC-USD-190920', value:509804 },{date:'00:12', type:'BTC-USD-190927', value:4549418 },{date:'00:12', type:'BTC-USD-191227', value:1681464 },{date:'00:13', type:'BTC-USD-190920', value:510241 },{date:'00:13', type:'BTC-USD-190927', value:4549119 },{date:'00:13', type:'BTC-USD-191227', value:1682645 },{date:'00:14', type:'BTC-USD-190920', value:510717 },{date:'00:14', type:'BTC-USD-190927', value:4549609 },{date:'00:14', type:'BTC-USD-191227', value:1681320 },{date:'00:15', type:'BTC-USD-190920', value:510693 },{date:'00:15', type:'BTC-USD-190927', value:4549781 },{date:'00:15', type:'BTC-USD-191227', value:1681994 },{date:'00:16', type:'BTC-USD-190920', value:510077 },{date:'00:16', type:'BTC-USD-190927', value:4549621 },{date:'00:16', type:'BTC-USD-191227', value:1682895 },{date:'00:17', type:'BTC-USD-190920', value:510317 },{date:'00:17', type:'BTC-USD-190927', value:4549304 },{date:'00:17', type:'BTC-USD-191227', value:1683725 },{date:'00:18', type:'BTC-USD-190920', value:509846 },{date:'00:18', type:'BTC-USD-190927', value:4549297 },{date:'00:18', type:'BTC-USD-191227', value:1683937 },{date:'00:19', type:'BTC-USD-190920', value:509877 },{date:'00:19', type:'BTC-USD-190927', value:4548955 },{date:'00:19', type:'BTC-USD-191227', value:1684060 },{date:'00:20', type:'BTC-USD-190920', value:509945 },{date:'00:20', type:'BTC-USD-190927', value:4548498 },{date:'00:20', type:'BTC-USD-191227', value:1684245 },{date:'00:21', type:'BTC-USD-190920', value:509973 },{date:'00:21', type:'BTC-USD-190927', value:4548756 },{date:'00:21', type:'BTC-USD-191227', value:1684565 },{date:'00:22', type:'BTC-USD-190920', value:510044 },{date:'00:22', type:'BTC-USD-190927', value:4548499 },{date:'00:22', type:'BTC-USD-191227', value:1685091 },{date:'00:23', type:'BTC-USD-190920', value:510100 },{date:'00:23', type:'BTC-USD-190927', value:4548750 },{date:'00:23', type:'BTC-USD-191227', value:1685642 },{date:'00:24', type:'BTC-USD-190920', value:510300 },{date:'00:24', type:'BTC-USD-190927', value:4547363 },{date:'00:24', type:'BTC-USD-191227', value:1689136 },{date:'00:25', type:'BTC-USD-190920', value:510124 },{date:'00:25', type:'BTC-USD-190927', value:4546640 },{date:'00:25', type:'BTC-USD-191227', value:1689659 },{date:'00:26', type:'BTC-USD-190920', value:510428 },{date:'00:26', type:'BTC-USD-190927', value:4546766 },{date:'00:26', type:'BTC-USD-191227', value:1689727 },{date:'00:27', type:'BTC-USD-190920', value:510817 },{date:'00:27', type:'BTC-USD-190927', value:4546917 },{date:'00:27', type:'BTC-USD-191227', value:1689508 },{date:'00:28', type:'BTC-USD-190920', value:510946 },{date:'00:28', type:'BTC-USD-190927', value:4547557 },{date:'00:28', type:'BTC-USD-191227', value:1689094 },{date:'00:29', type:'BTC-USD-190920', value:510922 },{date:'00:29', type:'BTC-USD-190927', value:4547458 },{date:'00:29', type:'BTC-USD-191227', value:1689341 },{date:'00:30', type:'BTC-USD-190920', value:510769 },{date:'00:30', type:'BTC-USD-190927', value:4547233 },{date:'00:30', type:'BTC-USD-191227', value:1689682 },{date:'00:31', type:'BTC-USD-190920', value:511033 },{date:'00:31', type:'BTC-USD-190927', value:4547023 },{date:'00:31', type:'BTC-USD-191227', value:1689677 },{date:'00:32', type:'BTC-USD-190920', value:511033 },{date:'00:32', type:'BTC-USD-190927', value:4546980 },{date:'00:32', type:'BTC-USD-191227', value:1689614 },{date:'00:33', type:'BTC-USD-190920', value:510980 },{date:'00:33', type:'BTC-USD-190927', value:4547281 },{date:'00:33', type:'BTC-USD-191227', value:1689810 },{date:'00:34', type:'BTC-USD-190920', value:510964 },{date:'00:34', type:'BTC-USD-190927', value:4547355 },{date:'00:34', type:'BTC-USD-191227', value:1689849 },{date:'00:35', type:'BTC-USD-190920', value:511014 },{date:'00:35', type:'BTC-USD-190927', value:4547385 },{date:'00:35', type:'BTC-USD-191227', value:1690039 },{date:'00:36', type:'BTC-USD-190920', value:511428 },{date:'00:36', type:'BTC-USD-190927', value:4546814 },{date:'00:36', type:'BTC-USD-191227', value:1690221 },{date:'00:37', type:'BTC-USD-190920', value:511735 },{date:'00:37', type:'BTC-USD-190927', value:4546923 },{date:'00:37', type:'BTC-USD-191227', value:1690184 },{date:'00:38', type:'BTC-USD-190920', value:511874 },{date:'00:38', type:'BTC-USD-190927', value:4544466 },{date:'00:38', type:'BTC-USD-191227', value:1690491 },{date:'00:39', type:'BTC-USD-190920', value:511631 },{date:'00:39', type:'BTC-USD-190927', value:4543948 },{date:'00:39', type:'BTC-USD-191227', value:1690211 },{date:'00:40', type:'BTC-USD-190920', value:511611 },{date:'00:40', type:'BTC-USD-190927', value:4544116 },{date:'00:40', type:'BTC-USD-191227', value:1690755 },{date:'00:41', type:'BTC-USD-190920', value:511751 },{date:'00:41', type:'BTC-USD-190927', value:4543820 },{date:'00:41', type:'BTC-USD-191227', value:1690626 },{date:'00:42', type:'BTC-USD-190920', value:511885 },{date:'00:42', type:'BTC-USD-190927', value:4543557 },{date:'00:42', type:'BTC-USD-191227', value:1690616 },{date:'00:43', type:'BTC-USD-190920', value:511864 },{date:'00:43', type:'BTC-USD-190927', value:4543548 },{date:'00:43', type:'BTC-USD-191227', value:1690474 },{date:'00:44', type:'BTC-USD-190920', value:511864 },{date:'00:44', type:'BTC-USD-190927', value:4543524 },{date:'00:44', type:'BTC-USD-191227', value:1690596 },{date:'00:45', type:'BTC-USD-190920', value:511797 },{date:'00:45', type:'BTC-USD-190927', value:4543398 },{date:'00:45', type:'BTC-USD-191227', value:1690481 },{date:'00:46', type:'BTC-USD-190920', value:511755 },{date:'00:46', type:'BTC-USD-190927', value:4543374 },{date:'00:46', type:'BTC-USD-191227', value:1690607 },{date:'00:47', type:'BTC-USD-190920', value:511960 },{date:'00:47', type:'BTC-USD-190927', value:4543460 },{date:'00:47', type:'BTC-USD-191227', value:1690919 },{date:'00:48', type:'BTC-USD-190920', value:511583 },{date:'00:48', type:'BTC-USD-190927', value:4543412 },{date:'00:48', type:'BTC-USD-191227', value:1690699 },{date:'00:49', type:'BTC-USD-190920', value:511867 },{date:'00:49', type:'BTC-USD-190927', value:4543284 },{date:'00:49', type:'BTC-USD-191227', value:1690529 },{date:'00:50', type:'BTC-USD-190920', value:511728 },{date:'00:50', type:'BTC-USD-190927', value:4543555 },{date:'00:50', type:'BTC-USD-191227', value:1689432 },{date:'00:51', type:'BTC-USD-190920', value:511369 },{date:'00:51', type:'BTC-USD-190927', value:4543568 },{date:'00:51', type:'BTC-USD-191227', value:1687375 },{date:'00:52', type:'BTC-USD-190920', value:511430 },{date:'00:52', type:'BTC-USD-190927', value:4543530 },{date:'00:52', type:'BTC-USD-191227', value:1688776 },{date:'00:53', type:'BTC-USD-190920', value:511209 },{date:'00:53', type:'BTC-USD-190927', value:4542830 },{date:'00:53', type:'BTC-USD-191227', value:1688824 },{date:'00:54', type:'BTC-USD-190920', value:511413 },{date:'00:54', type:'BTC-USD-190927', value:4542901 },{date:'00:54', type:'BTC-USD-191227', value:1690278 },{date:'00:55', type:'BTC-USD-190920', value:511492 },{date:'00:55', type:'BTC-USD-190927', value:4542406 },{date:'00:55', type:'BTC-USD-191227', value:1691124 },{date:'00:56', type:'BTC-USD-190920', value:511631 },{date:'00:56', type:'BTC-USD-190927', value:4542233 },{date:'00:56', type:'BTC-USD-191227', value:1701044 },{date:'00:57', type:'BTC-USD-190920', value:511591 },{date:'00:57', type:'BTC-USD-190927', value:4542544 },{date:'00:57', type:'BTC-USD-191227', value:1701761 },{date:'00:58', type:'BTC-USD-190920', value:511580 },{date:'00:58', type:'BTC-USD-190927', value:4542482 },{date:'00:58', type:'BTC-USD-191227', value:1702023 },{date:'00:59', type:'BTC-USD-190920', value:511619 },{date:'00:59', type:'BTC-USD-190927', value:4542218 },{date:'00:59', type:'BTC-USD-191227', value:1702745 },{date:'01:00', type:'BTC-USD-190920', value:512035 },{date:'01:00', type:'BTC-USD-190927', value:4542272 },{date:'01:00', type:'BTC-USD-191227', value:1702728 },{date:'01:01', type:'BTC-USD-190920', value:511820 },{date:'01:01', type:'BTC-USD-190927', value:4542538 },{date:'01:01', type:'BTC-USD-191227', value:1702179 },{date:'01:02', type:'BTC-USD-190920', value:511953 },{date:'01:02', type:'BTC-USD-190927', value:4543089 },{date:'01:02', type:'BTC-USD-191227', value:1703959 },{date:'01:03', type:'BTC-USD-190920', value:511322 },{date:'01:03', type:'BTC-USD-190927', value:4542201 },{date:'01:03', type:'BTC-USD-191227', value:1703997 },{date:'01:04', type:'BTC-USD-190920', value:511551 },{date:'01:04', type:'BTC-USD-190927', value:4542522 },{date:'01:04', type:'BTC-USD-191227', value:1704505 },{date:'01:05', type:'BTC-USD-190920', value:511758 },{date:'01:05', type:'BTC-USD-190927', value:4542789 },{date:'01:05', type:'BTC-USD-191227', value:1705143 },{date:'01:06', type:'BTC-USD-190920', value:512086 },{date:'01:06', type:'BTC-USD-190927', value:4542418 },{date:'01:06', type:'BTC-USD-191227', value:1704928 },{date:'01:07', type:'BTC-USD-190920', value:512283 },{date:'01:07', type:'BTC-USD-190927', value:4542637 },{date:'01:07', type:'BTC-USD-191227', value:1704798 },{date:'01:08', type:'BTC-USD-190920', value:512041 },{date:'01:08', type:'BTC-USD-190927', value:4542335 },{date:'01:08', type:'BTC-USD-191227', value:1707311 },{date:'01:09', type:'BTC-USD-190920', value:512069 },{date:'01:09', type:'BTC-USD-190927', value:4540921 },{date:'01:09', type:'BTC-USD-191227', value:1707957 },{date:'01:10', type:'BTC-USD-190920', value:511854 },{date:'01:10', type:'BTC-USD-190927', value:4540158 },{date:'01:10', type:'BTC-USD-191227', value:1710026 },{date:'01:11', type:'BTC-USD-190920', value:511603 },{date:'01:11', type:'BTC-USD-190927', value:4539636 },{date:'01:11', type:'BTC-USD-191227', value:1710043 },{date:'01:12', type:'BTC-USD-190920', value:510949 },{date:'01:12', type:'BTC-USD-190927', value:4538760 },{date:'01:12', type:'BTC-USD-191227', value:1707730 },{date:'01:13', type:'BTC-USD-190920', value:510655 },{date:'01:13', type:'BTC-USD-190927', value:4538751 },{date:'01:13', type:'BTC-USD-191227', value:1704975 },{date:'01:14', type:'BTC-USD-190920', value:510816 },{date:'01:14', type:'BTC-USD-190927', value:4538843 },{date:'01:14', type:'BTC-USD-191227', value:1704088 },{date:'01:15', type:'BTC-USD-190920', value:511349 },{date:'01:15', type:'BTC-USD-190927', value:4537598 },{date:'01:15', type:'BTC-USD-191227', value:1704558 },{date:'01:16', type:'BTC-USD-190920', value:511449 },{date:'01:16', type:'BTC-USD-190927', value:4537921 },{date:'01:16', type:'BTC-USD-191227', value:1703290 },{date:'01:17', type:'BTC-USD-190920', value:511427 },{date:'01:17', type:'BTC-USD-190927', value:4538136 },{date:'01:17', type:'BTC-USD-191227', value:1703520 },{date:'01:18', type:'BTC-USD-190920', value:511356 },{date:'01:18', type:'BTC-USD-190927', value:4537731 },{date:'01:18', type:'BTC-USD-191227', value:1702530 },{date:'01:19', type:'BTC-USD-190920', value:511440 },{date:'01:19', type:'BTC-USD-190927', value:4537314 },{date:'01:19', type:'BTC-USD-191227', value:1702352 },{date:'01:20', type:'BTC-USD-190920', value:511350 },{date:'01:20', type:'BTC-USD-190927', value:4537570 },{date:'01:20', type:'BTC-USD-191227', value:1705432 },{date:'01:21', type:'BTC-USD-190920', value:511204 },{date:'01:21', type:'BTC-USD-190927', value:4537303 },{date:'01:21', type:'BTC-USD-191227', value:1705463 },{date:'01:22', type:'BTC-USD-190920', value:510706 },{date:'01:22', type:'BTC-USD-190927', value:4537763 },{date:'01:22', type:'BTC-USD-191227', value:1706047 },{date:'01:23', type:'BTC-USD-190920', value:510866 },{date:'01:23', type:'BTC-USD-190927', value:4538229 },{date:'01:23', type:'BTC-USD-191227', value:1706779 },{date:'01:24', type:'BTC-USD-190920', value:510895 },{date:'01:24', type:'BTC-USD-190927', value:4539052 },{date:'01:24', type:'BTC-USD-191227', value:1705535 },{date:'01:25', type:'BTC-USD-190920', value:511049 },{date:'01:25', type:'BTC-USD-190927', value:4539265 },{date:'01:25', type:'BTC-USD-191227', value:1706180 },{date:'01:26', type:'BTC-USD-190920', value:510726 },{date:'01:26', type:'BTC-USD-190927', value:4539303 },{date:'01:26', type:'BTC-USD-191227', value:1705947 },{date:'01:27', type:'BTC-USD-190920', value:511664 },{date:'01:27', type:'BTC-USD-190927', value:4540266 },{date:'01:27', type:'BTC-USD-191227', value:1703451 },{date:'01:28', type:'BTC-USD-190920', value:511658 },{date:'01:28', type:'BTC-USD-190927', value:4541581 },{date:'01:28', type:'BTC-USD-191227', value:1703598 },{date:'01:29', type:'BTC-USD-190920', value:512040 },{date:'01:29', type:'BTC-USD-190927', value:4541726 },{date:'01:29', type:'BTC-USD-191227', value:1703818 },{date:'01:30', type:'BTC-USD-190920', value:511898 },{date:'01:30', type:'BTC-USD-190927', value:4541911 },{date:'01:30', type:'BTC-USD-191227', value:1704154 },{date:'01:31', type:'BTC-USD-190920', value:512147 },{date:'01:31', type:'BTC-USD-190927', value:4542033 },{date:'01:31', type:'BTC-USD-191227', value:1705208 },{date:'01:32', type:'BTC-USD-190920', value:511972 },{date:'01:32', type:'BTC-USD-190927', value:4541959 },{date:'01:32', type:'BTC-USD-191227', value:1706575 },{date:'01:33', type:'BTC-USD-190920', value:512187 },{date:'01:33', type:'BTC-USD-190927', value:4541049 },{date:'01:33', type:'BTC-USD-191227', value:1707412 },{date:'01:34', type:'BTC-USD-190920', value:512016 },{date:'01:34', type:'BTC-USD-190927', value:4541313 },{date:'01:34', type:'BTC-USD-191227', value:1707044 },{date:'01:35', type:'BTC-USD-190920', value:511479 },{date:'01:35', type:'BTC-USD-190927', value:4541889 },{date:'01:35', type:'BTC-USD-191227', value:1704266 },{date:'01:36', type:'BTC-USD-190920', value:511377 },{date:'01:36', type:'BTC-USD-190927', value:4542329 },{date:'01:36', type:'BTC-USD-191227', value:1705191 },{date:'01:37', type:'BTC-USD-190920', value:511418 },{date:'01:37', type:'BTC-USD-190927', value:4541995 },{date:'01:37', type:'BTC-USD-191227', value:1706375 },{date:'01:38', type:'BTC-USD-190920', value:511814 },{date:'01:38', type:'BTC-USD-190927', value:4541965 },{date:'01:38', type:'BTC-USD-191227', value:1712282 },{date:'01:39', type:'BTC-USD-190920', value:511430 },{date:'01:39', type:'BTC-USD-190927', value:4542378 },{date:'01:39', type:'BTC-USD-191227', value:1709775 },];

var chart = new F2.Chart({
    id: 'mountNode',
    pixelRatio: window.devicePixelRatio
  });

  chart.source(data, {
   
    date: {
    type: 'cat',
    sortable: false,
     range: [0, 1],
     tickCount: 8
    }
  });
  
  chart.tooltip({
      custom: true, // 自定义 tooltip 内容框
      onChange: function onChange(obj) {
        var legend = chart.get('legendController').legends.top[0];
        var tooltipItems = obj.items;
        var legendItems = legend.items;
        var map = {};
        legendItems.map(function(item) {
          map[item.name] = _.clone(item);
        });
        tooltipItems.map(function(item) {
          var name = item.name;
          var value = item.value;
          if (map[name]) {
            map[name].value = value;
          }
        });
        legend.setItems(_.values(map));
      },
      onHide: function onHide() {
        var legend = chart.get('legendController').legends.top[0];
        legend.setItems(chart.getLegendItems().country);
      }
    });
    
   
  chart.axis('date', {
    label: function label(text, index, total) {
      var textCfg = {};
      if (index === 0) {
        textCfg.textAlign = 'left';
      } else if (index === total - 1) {
        textCfg.textAlign = 'right';
      }
      return textCfg;
    }
  });
  chart.line().position('date*value').color('type');
  chart.render();

**Comment by openpython** [comment]
![2019-09-15_165355](https://user-images.githubusercontent.com/1044542/64919103-98074880-d7d9-11e9-9418-a33de98aa974.jpg)

**Comment by benvirus** [comment]
Y 轴的数值太大，而每条曲线的波动范围不大，所以看起来像直线。图本身没有问题。

**Comment by W0916** [comment]
这问题我也碰到了，想改成默认显示一条折线图，其他折线图通过点击legend显示，但不知道怎么改，纠结啊！！！

**Comment by zengyue** [comment]
用filter就可以了

https://f2.antv.vision/zh/docs/api/chart/chart#filter
