### ISSUE TITLE
chart.guide().tag 真机上被覆盖

### ISSUE THREAD

**Issue by curry-wxj** [antvis/F2#664]
![656ABE20BF2DC7D1551A320427EA0F0F](https://user-images.githubusercontent.com/30777163/64932806-17e1f100-d874-11e9-9224-c6da27cacda0.png)

   chart.guide().tag({
      position: [data[data.length - 1].time, data[data.length - 1].tem],
      content: data[data.length - 1].tem,
      side: 6,
      background: {
        padding: [4, 4],
        radius: 2,
        fill: '#006FFF',
      },
      top: true,
      autoAdjust: false,
      offsetY: -5,
      textStyle: {
        fill: '#fff',
        fontSize: 10,
      },
      // limitInPlot: true,
      direct: 'tl',
    })

**Comment by Yana5417** [comment]
考虑下是不是设置的canvas大小太大了，可以把画布宽度改小一点儿

**Comment by zengyue** [comment]
// limitInPlot: true

把这个打开就可以了
