### ISSUE TITLE
pie饼图支持渐变色嘛？

### ISSUE THREAD

**Issue by Ele-Cat** [antvis/f2#665]
如题，f2支持饼图渐变色嘛？

**Comment by Ele-Cat** [comment]
@simaQ

**Comment by Ele-Cat** [comment]
还有就是node下不支持使用chart.guide().html({})嘛

**Comment by simaQ** [comment]
1. 支持渐变色，https://www.yuque.com/antv/f2/canvas#zrhdmb
2. node 环境下是不支持 html() 的

**Comment by Ele-Cat** [comment]
> 1. 支持渐变色，https://www.yuque.com/antv/f2/canvas#zrhdmb
> 2. node 环境下是不支持 html() 的

谢谢解答，可以关闭啦！

**Comment by Ele-Cat** [comment]
> 1. 支持渐变色，https://www.yuque.com/antv/f2/canvas#zrhdmb
> 2. node 环境下是不支持 html() 的

谢谢解答！
