### ISSUE TITLE
设置syncY: true后双y轴的刻度还是不统一

### ISSUE THREAD

**Issue by Yin-Xie** [antvis/f2#667]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---设置syncY: true后双y轴的刻度还是不统一

<template>
  <div class="LineRectF2">
    <canvas id="mountNodeY" style="width: 100%"></canvas>
  </div>
</template>

<script>
  import F2 from '@antv/f2';
  export default {
    name: "LineRectF2",
    props: {
      sourceData: {
        type: Array,
        default: function () {
          return [];
        }
      }
    },
    data(){
      return {
        chart: null,
        // data: this.sourceData
      }
    },
    watch: {
      sourceData(newValue, oldValue){
        this.chart.changeData(newValue);
      }
    },
    mounted(){
      this.initChart();
    },
    methods: {
      initChart(){
        const chart = new F2.Chart({
          id: 'mountNodeY',
          syncY: true,
          pixelRatio: window.devicePixelRatio
        });

        chart.source(this.sourceData, {
          sales: {
            tickCount: 5
          }
        });
        chart.tooltip({
          showCrosshairs: true,
          crosshairsStyle: {
            stroke: '#1890ff'
          },
          background: {
            fill: '#1890ff'
          },
          nameStyle: {
            fill: '#fff'
          },
          onShow: function onShow(ev) {
            ev.items.pop(); // 将重复的去除
          }
        });
        // chart.axis('netAmount', false);
        chart.interval().position('year*sales');
        chart.line().position('year*netAmount').color('#5ed470').shape('smooth');
        chart.point().position('year*netAmount').style({
          stroke: '#5ed470',
          fill: '#fff',
          lineWidth: 2
        });
        this.chart = chart;
        chart.render();
      }
    }
  }
</script>

<style scoped>

</style>

**Comment by tanrongjun** [comment]
请问博主解决了吗

**Comment by tanrongjun** [comment]
> The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.
> 
> ---设置syncY: true后双y轴的刻度还是不统一
> 
> <script> import F2 from '@antv/f2'; export default { name: "LineRectF2", props: { sourceData: { type: Array, default: function () { return []; } } }, data(){ return { chart: null, // data: this.sourceData } }, watch: { sourceData(newValue, oldValue){ this.chart.changeData(newValue); } }, mounted(){ this.initChart(); }, methods: { initChart(){ const chart = new F2.Chart({ id: 'mountNodeY', syncY: true, pixelRatio: window.devicePixelRatio }); chart.source(this.sourceData, { sales: { tickCount: 5 } }); chart.tooltip({ showCrosshairs: true, crosshairsStyle: { stroke: '#1890ff' }, background: { fill: '#1890ff' }, nameStyle: { fill: '#fff' }, onShow: function onShow(ev) { ev.items.pop(); // 将重复的去除 } }); // chart.axis('netAmount', false); chart.interval().position('year*sales'); chart.line().position('year*netAmount').color('#5ed470').shape('smooth'); chart.point().position('year*netAmount').style({ stroke: '#5ed470', fill: '#fff', lineWidth: 2 }); this.chart = chart; chart.render(); } } } </script> <style scoped> </style>

哈喽，请问大佬解决了吗，方便提供下解决方案吗

**Comment by tanrongjun** [comment]
> The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.
> 
> ---设置syncY: true后双y轴的刻度还是不统一
> 
> <script> import F2 from '@antv/f2'; export default { name: "LineRectF2", props: { sourceData: { type: Array, default: function () { return []; } } }, data(){ return { chart: null, // data: this.sourceData } }, watch: { sourceData(newValue, oldValue){ this.chart.changeData(newValue); } }, mounted(){ this.initChart(); }, methods: { initChart(){ const chart = new F2.Chart({ id: 'mountNodeY', syncY: true, pixelRatio: window.devicePixelRatio }); chart.source(this.sourceData, { sales: { tickCount: 5 } }); chart.tooltip({ showCrosshairs: true, crosshairsStyle: { stroke: '#1890ff' }, background: { fill: '#1890ff' }, nameStyle: { fill: '#fff' }, onShow: function onShow(ev) { ev.items.pop(); // 将重复的去除 } }); // chart.axis('netAmount', false); chart.interval().position('year*sales'); chart.line().position('year*netAmount').color('#5ed470').shape('smooth'); chart.point().position('year*netAmount').style({ stroke: '#5ed470', fill: '#fff', lineWidth: 2 }); this.chart = chart; chart.render(); } } } </script> <style scoped> </style>

哈喽，请问大佬解决了吗
