### ISSUE TITLE
在小程序中，出现多个tolltip的情况下，可以对tolltip的内容进行筛选进行展示吗？

### ISSUE THREAD

**Issue by jacob-zch** [antvis/f2#674]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决tolltip不全部显示，只希望根据具体情况进行显示。

### What does the proposed API look like?
在tooltip的文档中有特定的API对tooltip进行筛选并生效。我在测试过程中，对tooltip的onshow进行数据筛选，疑惑的是对ev.items.splice(1)进行处理时会达到筛选的效果，但是如果我对ev.items的进行filter，并把filter之后的数组赋值给ev.items并没有出现理想的效果。请问该怎么解决这种需求？谢谢

**Comment by jacob-zch** [comment]
resolved

**Comment by cao1034** [comment]
你好 所以解决方案是啥。我也跟你做了类似的操作。
point 与 tooltip 同时存在的时候会因为 有两个点导致 ev.items 有两个元素。我同样尝试了，ev.items.splice（1）无效果。
<img width="634" alt="WeChat902f16397b2b7ac2ae7552e733ad1937" src="https://user-images.githubusercontent.com/11959771/86346313-532c9f80-bc8f-11ea-8050-ac07e6c969e8.png">
