### ISSUE TITLE
面积图如何设置Y轴值为整数？

### ISSUE THREAD

**Issue by zoux** [antvis/f2#676]
面积图如何设置Y轴值为整数？

目前我的图表中值为0-1区间时，y轴为0/0.2/0.4/0.6/0.8/1。期望值为0/1。

The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by zoux** [comment]
https://www.yuque.com/antv/f2/api-scale#sq97qr

**Comment by dayney** [comment]
> https://www.yuque.com/antv/f2/api-scale#sq97qr

使用values，只是自定义Y轴上的刻度值，此时真实的值并没有按照Y轴上的刻度值显示
