### ISSUE TITLE
如何同时画分组柱状图和折线图？

### ISSUE THREAD

**Issue by johnninja** [antvis/F2#679]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
以官网提供的分组柱状图示例为例，我现在可以实现伦敦和柏林的降水量对比柱状图，但如果我还想加一条两者的平均降水量折线图该如何实现？

### What does the proposed API look like?
没想好

**Comment by simaQ** [comment]
受限于 F2 对于分组柱状图数据的格式要求，目前分组柱状图和线图的混合场景不支持
