### ISSUE TITLE
图像中多条线条存在，后面的线条会覆盖前面的线条，希望图像展示可以自定义层级覆盖逻辑

### ISSUE THREAD

**Issue by fudanfuhua** [antvis/f2#681]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
图像展示可以自定义层级覆盖逻辑

### What does the proposed API look like?
可以使用类似z-index的属性标识图像的层级

**Comment by looserLiu** [comment]
我也遇到了同样的问题 请问是咋解决的呢
