### ISSUE TITLE
color 方法不支持 class get

### ISSUE THREAD

**Issue by ken1987** [antvis/F2#684]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-154nz)

### Steps to reproduce
1.  创建数据源，每个子项是一个 class 实例，且包含 get 属性 isNegativeNumber。
2. color 方法中配置属性名 isNegativeNumber

### What is expected?
负数显示红色，非负数显示蓝色

### What is actually happening?
全都显示蓝色

| Environment | Info |
|---|---|
| f2 | 3.4.2 |
| System | window 7 |
| Browser | chrome |

**Comment by zengyue** [comment]
用简单对象
