### ISSUE TITLE
第一次 render 之前调用 repaint 或者 clear 方法，导致 tooltips 报错

### ISSUE THREAD

**Issue by ken1987** [antvis/F2#685]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-8h9qq?fontsize=14)

### Steps to reproduce
如题

### What is expected?
不报错

### What is actually happening?
导致 tooltips 报错：`Uncaught TypeError: Cannot read property 'triggerOn' of undefined`

| Environment | Info |
|---|---|
| f2 | 3.4.2 |
| System | window 7 |
| Browser | chrome |

---
tooltips.js 源码中，未做空值判断

```js
_proto.unBindEvents = function unBindEvents() {
    var cfg = this._tooltipCfg;         // 可能是空值
    var triggerOn = cfg.triggerOn  // 引发报错
   // ...
}
```

**Comment by zengyue** [comment]
最新版已修复
