### ISSUE TITLE
能否设置分组柱状图居中

### ISSUE THREAD

**Issue by Izayawww** [antvis/f2#688]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Lucas_1220/pen/NWWawMN](https://codepen.io/Lucas_1220/pen/NWWawMN)

### Steps to reproduce
设置size以后，分组柱状图间距很大，设置marginRatio: 0 也没用

### What is expected?
分组柱状图居中

### What is actually happening?
分组柱状图不居中

| Environment | Info |
|---|---|
| f2 | 3.4.2 |
| System | win7 |
| Browser | chrome |

**Comment by zengyue** [comment]
可以通过rang来设置

```
chart.scale('月份',  {
    range: [0.3, 0.7],
  });
```
