### ISSUE TITLE
能否自定义axis样式

### ISSUE THREAD

**Issue by Izayawww** [antvis/F2#689]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义axis样式，能同时设置tickLine和非tickLine的样式，目前也没有设置axis radius的配置

### What does the proposed API look like?
可以用户自定义配置axis样式

**Comment by Izayawww** [comment]
![image](https://user-images.githubusercontent.com/16361564/67916825-f9407b00-fbd1-11e9-8eea-2d584c5ddc94.png)
类似这样的样式

**Comment by zengyue** [comment]
目前不支持
