### ISSUE TITLE
提供 esm 版本

### ISSUE THREAD

**Issue by yesmeck** [antvis/F2#690]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ES modules 在构建时能获得更小的产物体积。

目前 package.json 上指定的 module 目录并不存在 https://unpkg.com/browse/@antv/f2@3.4.2/package.json

另外，现在所有模块都是用的 CommonJS，能够迁移到 ES modules 呢？

### What does the proposed API look like?
不需要 API

**Comment by zengyue** [comment]
@3.7.0 已经有了
