### ISSUE TITLE
微信canvas支持2d啦，官方f2计划啥时候适配一波？

### ISSUE THREAD

**Issue by JeKing** [antvis/F2#691]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
微信canvas支持2d啦，官方f2计划啥时候适配一波？

**Comment by rsnzh** [comment]
F2.Util.isWx = false; 这样就能用微信新的canvas API了

**Comment by zengyue** [comment]
这么hack。。

**Comment by zengyue** [comment]
最新版已经适配 微信canvas 2d了
