### ISSUE TITLE
【BUG】设置 tickCount，引起 Y 轴坐标轴文本计算错误

### ISSUE THREAD

**Issue by mice33** [antvis/f2#694]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-0dwc1?fontsize=14)

### Steps to reproduce
打开链接即可复现

### What is expected?
Y轴坐标轴文本，数字计算正确

### What is actually happening?
Y轴坐标轴文本，数字计算错误

| Environment | Info |
|---|---|
| f2 | 3.4.2 |
| System | win10 |
| Browser | Chrome |

**Comment by zengyue** [comment]
这个是js的精度问题导致的，在sales上做一个formatter就可以了

```
chart.source(data, {
  sales: {
    tickCount: 4,
    formatter: (val) => { return Number(val).toFixed(2) }
  }
});

```
