### ISSUE TITLE
小程序上图形设置了padding:'auto'也不适配宽度这是为什么

### ISSUE THREAD

**Issue by lin5164** [antvis/F2#696]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---
![image](https://user-images.githubusercontent.com/43064442/68532633-d2651000-035a-11ea-920a-1dadc363601f.png)

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by lin5164** [comment]
DAUChart = new F2.Chart({
                el: canvas,
                width,
                height,
                padding: 'auto',
                pixelRatio: 2
            })
这里padding设置数值可以,,可是auto就如图所示,,希望大佬解答,

**Comment by zengyue** [comment]
auto会默认设置成0， 你期望的表现是什么？

**Comment by lin5164** [comment]
> auto会默认设置成0，你期望的表现是什么？

情况是图表会超出边框,,期望表现是图表不要超出边框,并且根据盒子大小自适应,

**Comment by zengyue** [comment]
目前没有这种适应逻辑
