### ISSUE TITLE
双柱状图平移问题

### ISSUE THREAD

**Issue by gntina** [antvis/F2#697]
这边双柱状图使用时出现了下图问题，第一个柱和最后一个柱不见了。烦请查看一下
	代码地址如下：
	https://codesandbox.io/s/static-k9gx3?fontsize=14

**Comment by gntina** [comment]
![PastedGraphic-1](https://user-images.githubusercontent.com/23253248/68670469-fb1e1d00-0587-11ea-9eaf-ddeb087a318e.png)
![PastedGraphic-2](https://user-images.githubusercontent.com/23253248/68670470-fbb6b380-0587-11ea-80ff-96a19df6d38b.png)

**Comment by Maconzhang** [comment]
这个问题修复了吗？
