### ISSUE TITLE
能否提供只有X轴的类似标尺的图？

### ISSUE THREAD

**Issue by uliian** [antvis/F2#707]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一些对页面容量要求较高的场景下这种图是很重要的。

### What does the proposed API look like?
和半圆进度图一样

![image](https://user-images.githubusercontent.com/3947701/69302258-fde9d380-0c53-11ea-85f8-50c671685a9b.png)

**Comment by zengyue** [comment]
定义ticks不能搞定吗？

**Comment by uliian** [comment]
> 定义ticks不能搞定吗？

不好意思，能够说得详细一点点么？在调研产品中，不是很熟悉~

**Comment by zengyue** [comment]
https://antv-f2.gitee.io/zh/docs/api/chart/axis
