### ISSUE TITLE
guide-Arc 需要一个 pieLabel的文本效果 应该如何解决？没有思路

### ISSUE THREAD

**Issue by shouwangshe** [antvis/f2#709]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost/statistics/statisticsProduct](http://localhost/statistics/statisticsProduct)

### Steps to reproduce
guide-Arc 需要一个 pieLabel的文本效果 应该如何解决？没有思路

### What is expected?
这个demo 'https://antv.alipay.com/zh-cn/f2/3.x/demo/component/guide-arc.html' 是一个柱状图，是不是不支持pieLabel 这个效果。现在就是差在这里，希望大大给个思路。谢谢

### What is actually happening?
![效果图](https://hy-app.oss-cn-shanghai.aliyuncs.com/uploadFiles/newlife-MobilePhoto/525241668828397568/647097023923306496.jpg?Expires=4727921553&OSSAccessKeyId=LTAIPAczvHRBTx5g&Signature=mzg79prlW0JA1xFjxljbzFtLWzo%3D)

| Environment | Info |
|---|---|
| f2 | 3.4.3 |
| System | 浏览器 |
| Browser | chrome |

**Comment by benvirus** [comment]
没看明白你想要的是什么

**Comment by shouwangshe** [comment]
@benvirus  demo 地址‘https://f2.antv.vision/zh/examples/component/guide’ 是圆环， 我的需求现在差右上角的  那个点和线 的指示。。

**Comment by benvirus** [comment]
首先要把数据分类，所以要调用 color 方法，然后再使用 pieLabel。
如果你使用的是 CDN 资源，pieLabel 在 f2.min.js 里面是没有的，要使用  f2-all.min.js。
```js
xxxxxx.shape('tick').color('x');
// 然后使用  pieLabel
chart.pieLable({
  label1: function(data) {
    return { text: data.y } // 具体的显示自己搞。
  }
})
```
我简单的实现如下图：
![image](https://user-images.githubusercontent.com/13535932/69706455-b6bb8100-1132-11ea-8a15-63fd2a4d153d.png)

希望能够帮到你。

**Comment by shouwangshe** [comment]
@benvirus 感谢。。。但我试了试 没整出来呢 我在弄弄。。。我记得我也写过这个 pieLable，那时候没好使。我在试试。。

**Comment by shouwangshe** [comment]
@benvirus 感谢~~ 添了 chart.pieLabel 就出来了，只是位置不对，在看看。。记得那时候不行呢。。。

**Comment by benvirus** [comment]
@shouwangshe  关键要 color('x')。 如果问题解决了，请 Close issue。
