### ISSUE TITLE
Is there any @types library for @antv/f2?

### ISSUE THREAD

**Issue by sinitsa** [antvis/F2#711]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am currently using typescript and looking around for types definition support for this beautiful library. I was wondering if there is any declaration of it? Thanks in advance)

### What does the proposed API look like?
d.ts

**Comment by DeyiXu** [comment]
mark
