### ISSUE TITLE
[Bug] x轴只有一条数据时, 无法显示tooltip

### ISSUE THREAD

**Issue by ShuBuShao** [antvis/F2#712]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/shubushao/pen/mddYqXO](https://codepen.io/shubushao/pen/mddYqXO)

### Steps to reproduce
data只有一条数据的时候, 点击图表 tooltip 无法出现

### What is expected?
tooltip正常显示

### What is actually happening?
tooltip hide

| Environment | Info |
|---|---|
| f2 | 3.4.3 |
| System | win10 |
| Browser | chrome78.0 |

---
我跟随调试到了 
@antv\f2\lib\geom\base.js getSnapRecords方法 731-733行

@antv\f2\lib\geom\base.js _getSnap方法 中, 因为values只有一个, 但是for循环的时候, i变成了1, 导致result取不到值

**Comment by zengyue** [comment]
试一下最新版本，这个已经修掉了
https://github.com/antvis/F2/pull/703
