### ISSUE TITLE
f2能否实现 G2类似的层叠条形图，其中x轴是时间段，如下图

### ISSUE THREAD

**Issue by jiyihui** [antvis/f2#719]
![image](https://user-images.githubusercontent.com/26476858/69699770-b8317d00-1123-11ea-8ab9-b17dc5cc0c90.png)
就是在某个时间段是同一个状态，即同一个颜色

**Comment by benvirus** [comment]
[简单示例](https://codepen.io/benvirus/pen/VwwJRwR?editors=0010#0)
一个简单版的例子，经过进一步的处理应该可以实现。希望能帮到你。

**Comment by jiyihui** [comment]
> [简单示例](https://codepen.io/benvirus/pen/VwwJRwR?editors=0010#0)
> 一个简单版的例子，经过进一步的处理应该可以实现。希望能帮到你。

谢谢大佬，解决了
