### ISSUE TITLE
问个如果x轴是Date类型的值，我的tooltip会报   Invalid Date in fecha.format

### ISSUE THREAD

**Issue by jiyihui** [antvis/F2#720]
目前图是绘制出来了
![image](https://user-images.githubusercontent.com/26476858/69770342-9daee080-11c3-11ea-9690-f43206f5f63c.png)
但是点击想要显示tooltip会报这个错
![image](https://user-images.githubusercontent.com/26476858/69770509-42312280-11c4-11ea-8b8d-c91d5a2c5227.png)
我的数据格式是这样的 
![image](https://user-images.githubusercontent.com/26476858/69770595-95a37080-11c4-11ea-9ae5-48784365b87f.png)
range是Date类型的数组
然后设置mask
![image](https://user-images.githubusercontent.com/26476858/69770620-ad7af480-11c4-11ea-8e21-ed6ffac0f16e.png)是这样的，能否有人看下是哪里不对，感谢！

**Comment by benvirus** [comment]
怎么又是你。。。别使用 mask，使用 formatter 试试。
@jiyihui

**Comment by jiyihui** [comment]
> 怎么又是你。。。别使用 mask，使用 formatter 试试。
> @jiyihui

我试了下用formatter还是不行。还是这个错，我还试了把range的类型改成时间戳 数组，也不行，大佬还有啥建议不

**Comment by benvirus** [comment]
你搞一个 codepen 来重现你的问题，这样子描述很难帮到你。

**Comment by benvirus** [comment]
> > 怎么又是你。。。别使用 mask，使用 formatter 试试。
> > @jiyihui
> 
> 我试了下用formatter还是不行。还是这个错，我还试了把range的类型改成时间戳 数组，也不行，大佬还有啥建议不

你搞一个 codepen 用你的真实数据来重新问题，不然很难帮到你。

**Comment by jiyihui** [comment]
> > > 怎么又是你。。。别使用 mask，使用 formatter 试试。
> > > @jiyihui
> > 
> > 
> > 我试了下用formatter还是不行。还是这个错，我还试了把range的类型改成时间戳 数组，也不行，大佬还有啥建议不
> 
> 你搞一个 codepen 用你的真实数据来重新问题，不然很难帮到你。

[代码示例](https://codepen.io/jiyihui/pen/ExxqwJb?editors=1111)， 这个在codepen上面点击图形。没有报错，也没有显示tooltip  但我在f2的官网示例上同样的代码是报错的
![image](https://user-images.githubusercontent.com/26476858/69792545-ce156f80-1201-11ea-9e6d-914bd43ec37d.png) 麻烦了。。

**Comment by benvirus** [comment]
```js
    tooltipItems.forEach(function(item) {
      const name = item.name;
      const value = item.origin.sales.map(res => dayjs(res).format('HH:mm' )).join('-');
      if (map[name]) {
        map[name].value = value;
      }
    });
```
@jiyihui

**Comment by jiyihui** [comment]
@benvirus  换成了你的代码 还是报这个错。。

**Comment by benvirus** [comment]
> @benvirus 换成了你的代码 还是报这个错。。

老哥你自己 Debug 一下吧，我这边在 demo 上换成这个是没有问题的。如果使用 formatter,要把 type 和 mask 去掉。

**Comment by benvirus** [comment]
[ 测试代码 ](https://codepen.io/benvirus/pen/LYEYaaJ?editors=0010)

![image](https://user-images.githubusercontent.com/13535932/70030042-52416b80-15e3-11ea-880a-d421c2382e55.png)

如果还不行，我也帮不了你了

**Comment by jiyihui** [comment]
@benvirus 谢谢老哥了，感谢感谢
