### ISSUE TITLE
浏览器 如何 引入pieLabel

### ISSUE THREAD

**Issue by moxuanluo** [antvis/F2#721]
现在是浏览器 直接 引入的 f2.js ,在创建饼图的时候 使用pieLabel 会报 pieLabel is not a function ,看了看官网api 上 没有写如何在浏览器 引入pieLabel,
想咨询一下，浏览器 该 如何使用 pieLabel

**Comment by benvirus** [comment]
使用 f2-all.min.js

**Comment by moxuanluo** [comment]
> 使用 f2-all.min.js

谢谢，已解决问题

**Comment by benvirus** [comment]
@moxuanluo  已解决请 Close issue.

**Comment by arlbok1** [comment]
> > 使用 f2-all.min.js
> 
> 谢谢，已解决问题

我安装不了依赖能否发一份f2..all.min.js来

**Comment by benvirus** [comment]
> 我安装不了依赖能否发一份f2..all.min.js来
你是通过什么方式使用 F2 的 ？
