### ISSUE TITLE
如何实现类似微信指数中的 tooltip 样式？

### ISSUE THREAD

**Issue by luckymore** [antvis/F2#726]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/5390013/70020906-b5be9f80-15c9-11ea-8aca-1973982cd129.png)

### What problem does this feature solve?
tooltip 样式的深度定制
- 辅助线底部的 `xTip` 位置可以自定义形状

### What does the proposed API look like?
tooltip 完全自定义
```js
chart.tooltip({
  customTooltip: {
    bottom: {},  // 底部块的样式
  }
})
```

**Comment by zengyue** [comment]
是指这个竖线吗?

**Comment by luckymore** [comment]
@zengyue 底下的那个黑圈

**Comment by benvirus** [comment]
去了解一下 addShape api。

**Comment by luckymore** [comment]
@benvirus `addShape` 是定制图表的图形，这个黑点是属于 `tooltip` 的，还是没办法定制呦

**Comment by zengyue** [comment]
这个目前不能配置
