### ISSUE TITLE
问个甘特图（层叠条形图）的问题

### ISSUE THREAD

**Issue by jiyihui** [antvis/F2#731]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。
![image](https://user-images.githubusercontent.com/26476858/70312729-2c200380-184f-11ea-8455-20c766938287.png)
我的数据是Date类型的 问下这里的x轴的时间为啥不是均分的， tickCount和ticks都设置过，ticks是设置的Date类型的数组（设置了ticks之后就不展示x轴的刻度了）type为timeCat

**Comment by zengyue** [comment]
issue请用标准的模板创建，方便我们排查和定位，不然会被我们置为无效

**Comment by jiyihui** [comment]
@zengyue issue已经重新创建了 麻烦关注下，谢谢了
