### ISSUE TITLE
chart.guide().html() 重复绘制

### ISSUE THREAD

**Issue by giantss** [antvis/F2#736]
我切换另一个用户的成绩单,刷新数据时调用 `chart.guide().html()` 上一次绘制的html还在,没有消除,
我尝试使用在 ` chart.guide().html` 之前调用 `clear()` 没有效果 求解...
https://github.com/antvis/F2/issues/475
https://github.com/antvis/F2/issues/554
https://github.com/antvis/F2/issues/241
 @simaQ  与上面遇到的现象很类似
关键代码如下
```
    chart.guide().clear();
    chart.guide().html({
      position: ['50%', '30%'],
      html: '<div style=\"width: 250px;height: 40px;text-align: center;\">' +
      '<p style=\"font-size: 90px; font-weight: bold; color: #333333\">' + sum + '</p>' +
      '<p style="font-size: 14px;color: #666666; margin-duibi: 5px; margin-top: 5px">累计学习单词</p>' +
      '</div>'
    });
    chart.render();
```

![3191575940223_ pic_hd](https://user-images.githubusercontent.com/13778798/70486468-ed2ece00-1b2c-11ea-8445-b09f84baa4f3.jpg)

![3181575940080_ pic](https://user-images.githubusercontent.com/13778798/70486421-bbb60280-1b2c-11ea-8d12-c68eb108dc4f.jpg)

**Comment by giantss** [comment]
这种情况很好复现, 如果使用react的话, 只要setState(); render 重新渲染刷新数据就会出现这个现象. 我看 

https://github.com/antvis/F2/issues/554
https://github.com/antvis/F2/issues/475
https://github.com/antvis/F2/issues/241
这么多人反馈这个问题, 能麻烦解决一下吗?
@simaQ 🙏

**Comment by zengyue** [comment]
我看看

**Comment by zengyue** [comment]
如果还能复现的话，按标准的issue提供个可复现的demo，这样能加快我们的排查和定位

**Comment by giantss** [comment]
有效@zengyue
