### ISSUE TITLE
项目是React项目，数据能展示，但是希望能有交互功能

### ISSUE THREAD

**Issue by johanazhu** [antvis/F2#738]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如题，阅读文档后发现没有交互功能，看隔壁G2就有（鼠标放节点上能显示数据，点击也能展示数据），查看BizGoblin（https://github.com/alibaba/BizGoblin/  ），发现也没有交互

### What does the proposed API look like?
anyway

**Comment by benvirus** [comment]
其实没有太听明白你的需求，F2 是专注 移动端可视化 的项目，tooltip 等很多行为的默认触发条件是 touch。不知道您所谓的没有交互具体是指哪方面 ？请提供进一步的说明。

**Comment by johanazhu** [comment]
可能我表达的不太好，就像你说的，确实是像你说的，touch 能成
https://codesandbox.io/s/elastic-babbage-c0fi3
之前看文档（https://f2.antv.vision/zh/examples/basic ），所以下意识的在网页上点击，奇怪为什么行不通

**Comment by zengyue** [comment]
F2是针对移动端的图表设计，移动端主要是touch事件，会和网页上的鼠标事件不一样，官网上的demo是通过mouse事件模拟的touch事件，所以要点击的
