### ISSUE TITLE
柱状图高度较小时圆角显示异常

### ISSUE THREAD

**Issue by yipf42** [antvis/F2#742]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-dew-5nf55)

### Steps to reproduce
柱状图数据较小时（高度低于圆角radius设置数值）

### What is expected?
柱状图可以设置最小高度或者设置圆角时判断高度，使显示正常

### What is actually happening?
显示异常
![image](https://user-images.githubusercontent.com/7829993/70975034-17abf880-20e4-11ea-8af6-8c352849a0df.png)

| Environment | Info |
|---|---|
| f2 | 3.4.4 |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome 79.0.3945.79 |

**Comment by Izayawww** [comment]
大哥，解决没，遇到同样的问题

**Comment by yipf42** [comment]
> 大哥，解决没，遇到同样的问题

    radius: function radius(val) {
      if (Math.abs(val) < 8) return;
      return val > 0 ? [8, 8, 0, 0] : [0, 0, 8, 8];
    }

我加了个判断，处理了下

**Comment by Izayawww** [comment]
g感谢

**Comment by Izayawww** [comment]
感谢
