### ISSUE TITLE
之前的依赖删除后重新下载依赖运行项目报错

### ISSUE THREAD

**Issue by zx870283980** [antvis/F2#743]
- 

@babel/runtime/helpers/assertThisInitialized in ./node_modules/_@antv_f2@3.5.0-beta.1@@antv/f2/lib/chart/chart.js, ./node_modules/_@antv_f2@3.5.0-beta.1@@antv/f2/lib/geom/interval.js and 2 others
* @babel/runtime/helpers/inheritsLoose in ./node_modules/_@antv_f2@3.5.0-beta.1@@antv/f2/lib/attr/color.js, ./node_modules/_@antv_f2@3.5.0-beta.1@@antv/f2/lib/chart/chart.js and 33 others
* @babel/runtime/helpers/interopRequireDefault in ./node_modules/_@antv_f2@3.5.0-beta.1@@antv/f2/lib/attr/color.js, ./node_modules/_@antv_f2@3.5.0-beta.1@@antv/f2/lib/chart/chart.js and 33 others

**Comment by RicoLiu** [comment]
+1
Same issue
node version: v10.15.0

**Comment by BennyEu** [comment]
我手动安装了`@babel/runtime`后就好了, 不知道有没别的解决方法

**Comment by RicoLiu** [comment]
我是指定了 @antv/f2@3.3.9 版本和 babel-runtime@6.26.0 版本

**Comment by zengyue** [comment]
用最新的3.5，已经把这个依赖加进来了
