### ISSUE TITLE
area的颜色不是实际想要的颜色

### ISSUE THREAD

**Issue by yumengbdw** [antvis/F2#749]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y0bjb)

### Steps to reproduce
官方的demo ,给area 和line都设置颜色后出现效果非想要的颜色
chart.area().position('time*tem').color('#5D7092');
chart.line().position('time*tem').color('#5D7092');

### What is expected?
设置的颜色与展示颜色相同

### What is actually happening?
展示的颜色与设置颜色相差太大

| Environment | Info |
|---|---|
| f2 | 3.4.4 |
| System | 所有 |
| Browser | 所有 |

---
https://antv-issue-helper.surge.sh

![image](https://user-images.githubusercontent.com/11400046/71440890-f7121d00-2739-11ea-993a-21a08ade0436.png)

**Comment by hxdyj** [comment]
同样出现了这个问题

**Comment by a958330481** [comment]
同样出现了这个问题

**Comment by yumengbdw** [comment]
> 同样出现了这个问题

> 同样出现了这个问题

chart.line().position('timetem').color('#5D7092').style({
    fillOpacity: 0.5
  });
解决

**Comment by yumengbdw** [comment]
> > 同样出现了这个问题
> 
> > 同样出现了这个问题
> 
> chart.line().position('timetem').color('#5D7092').style({
> fillOpacity: 0.5
> });
> 解决
