### ISSUE TITLE
自定义带交互的图例demo加上平移之后，点击图例进行交互，点击单个图例第三次的时候，图表渲染位置错误

### ISSUE THREAD

**Issue by Dreamwht** [antvis/F2#751]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by benvirus** [comment]
请提供最小可复现版本的在线实例
