### ISSUE TITLE
环形图支持圆角吗

### ISSUE THREAD

**Issue by Dingo203** [antvis/F2#753]
请问下环形图支持类似这种圆角效果吗？

![image](https://user-images.githubusercontent.com/13451693/71648439-41e5f300-2d3f-11ea-9471-d1062c1172e3.png)

**Comment by benvirus** [comment]
参考如下两个例子：
https://f2.antv.vision/zh/examples/gallery/gauge
https://f2.antv.vision/zh/examples/gallery/fitness-ring

**Comment by Dingo203** [comment]
> 参考如下两个例子：
> https://f2.antv.vision/zh/examples/gallery/gauge
> https://f2.antv.vision/zh/examples/gallery/fitness-ring

搞定了，十分感谢

**Comment by liumengling1973** [comment]
链接打不开

**Comment by MarkRaoAndroid** [comment]
我也遇到同样的问题，但是你提供的链接打不开了，大佬，麻烦更新下链接地址，感谢！！！ @benvirus @zengyue @simaQ @ACERY1

**Comment by ACERY1** [comment]
https://f2.antv.antgroup.com/zh/examples/pie/donut#progress-bar 参考这个例子，给interval加radius的样式
![image](https://github.com/antvis/F2/assets/19555547/6a3b8273-3838-40c0-8928-dff514033e04)

**Comment by ACERY1** [comment]
@MarkRaoAndroid

**Comment by MarkRaoAndroid** [comment]
> @MarkRaoAndroid

好的，我试了下，效果和我预期的不一样，我还是开一个新的问题

**Comment by MarkRaoAndroid** [comment]
我预期的环形图设置圆头，彼此之间是层叠相交的该如何做，谢谢！ @ACERY1

**Comment by MarkRaoAndroid** [comment]
如图所示

**Comment by MarkRaoAndroid** [comment]
如图所示
