### ISSUE TITLE
tooltip显示被截取&& 图例占据canvas高度导致绘图区域被压缩

### ISSUE THREAD

**Issue by qqqqq1y** [antvis/F2#766]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/line/basic#smooth](https://f2.antv.vision/zh/examples/line/basic#smooth)

### Steps to reproduce
const data = [{
day: '周一',
value: 16323,
line:'酒水饮料'
}, {
day: '周二',
value: 13665,
line:'酒水饮料'
}, {
day: '周三',
value: 13485,
line:'酒水饮料'
}, {
day: '周四',
value: 25359,
line:'酒水饮料'
}, {
day: '周五',
value: 27218,
line:'酒水饮料'
}, {
day: '周六',
value: 33586,
line:'酒水饮料'
}, {
day: '周日',
value: 43556,
line:'酒水饮料'
},{
day: '周一',
value: 26348,
line:'五金制品'
}, {
day: '周二',
value: 35316,
line:'五金制品'
}, {
day: '周三',
value: 38649,
line:'五金制品'
}, {
day: '周四',
value: 46721,
line:'五金制品'
}, {
day: '周五',
value: 43576,
line:'五金制品'
}, {
day: '周六',
value: 56736,
line:'五金制品'
}, {
day: '周日',
value: 63412,
line:'五金制品'
},{
day: '周一',
value: 16578,
line:'礼品鲜花'
}, {
day: '周二',
value: 25756,
line:'礼品鲜花'
}, {
day: '周三',
value: 28547,
line:'礼品鲜花'
}, {
day: '周四',
value: 32211,
line:'礼品鲜花'
}, {
day: '周五',
value: 33546,
line:'礼品鲜花'
}, {
day: '周六',
value: 43546,
line:'礼品鲜花'
}, {
day: '周日',
value: 55712,
line:'礼品鲜花'
},{
day: '周一',
value: 14678,
line:'医药保健'
}, {
day: '周二',
value: 23546,
line:'医药保健'
}, {
day: '周三',
value: 25749,
line:'医药保健'
}, {
day: '周四',
value: 25781,
line:'医药保健'
}, {
day: '周五',
value: 29246,
line:'医药保健'
}, {
day: '周六',
value: 32396,
line:'医药保健'
}, {
day: '周日',
value: 43172,
line:'医药保健'
},{
day: '周一',
value: 14548,
line:'汽车用品'
}, {
day: '周二',
value: 23436,
line:'汽车用品'
}, {
day: '周三',
value: 24319,
line:'汽车用品'
}, {
day: '周四',
value: 23481,
line:'汽车用品'
}, {
day: '周五',
value: 29686,
line:'汽车用品'
}, {
day: '周六',
value: 34596,
line:'汽车用品'
}, {
day: '周日',
value: 48472,
line:'汽车用品'
},{
day: '周一',
value: 1748,
line:'个护清洁'
}, {
day: '周二',
value: 2326,
line:'个护清洁'
}, {
day: '周三',
value: 2449,
line:'个护清洁'
}, {
day: '周四',
value: 2681,
line:'个护清洁'
}, {
day: '周五',
value: 2796,
line:'个护清洁'
}, {
day: '周六',
value: 3796,
line:'个护清洁'
}, {
day: '周日',
value: 4752,
line:'个护清洁'
}];

重现连接里数据源修改为 data， 绘制折线图就可复现问题

### What is expected?
1.tootip 显示完整
2.组件传入固定高度, 图例高度不占据绘图区域

### What is actually happening?
1.tooltip中每个item的label   value 过长且item数量超过一定量时，tooltip会被裁剪掉一部分
2.组件传入固定高度，生成的canvas包括图例，坐标系两部分， 图例过多会挤压坐标系高度

| Environment | Info |
|---|---|
| f2 | 3.5.0 |
| System | windows |
| Browser | chrome |

**Comment by qqqqq1y** [comment]
具体图片效果可以看这个连接
[https://github.com/antvis/wx-f2/issues/222](url)

**Comment by zengyue** [comment]
> 2.组件传入固定高度，生成的canvas包括图例，坐标系两部分， 图例过多会挤压坐标系高度 

这个没有办法，空间就这么大，一定会挤压的，可以加大canvas宽高，或者减少legend数量

**Comment by BoleLee** [comment]
图例过多挤压绘图主区域的问题，G2@4.x是做了分页显示处理，还能设置最多显示几行，F2现在也4.x了，图例过多是否支持分页显示呢？ @zengyue
