### ISSUE TITLE
React Native项目里无法使用F2

### ISSUE THREAD

**Issue by chj-damon** [antvis/F2#769]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/chj-damon/F2-expo-reproduce](https://github.com/chj-damon/F2-expo-reproduce)

### Steps to reproduce
yarn
yarn start

### What is expected?
能够正常显示图表

### What is actually happening?
无法正常显示图表

| Environment | Info |
|---|---|
| f2 | 3.5.0 |
| System | MacOS Majave |
| Browser | Expo v36 |

---

**Comment by chj-damon** [comment]
![image](https://user-images.githubusercontent.com/4902684/72972336-32217200-3e06-11ea-9436-170d16904bf1.png)

**Comment by alb90** [comment]
I am also having this issue

**Comment by zengyue** [comment]
pass the context object

```
const chart = new F2.Chart({
  context: canvas.getContext('2d'),
  width: 200,
  height: 200,
  padding: [0, "auto", "auto"]
});
```

**Comment by chj-damon** [comment]
@zengyue 还是不行，现在报另一个错：`undefined is not an object (evaluating 'geoms[0].getXScale')`
- node_modules/@antv/f2/build/f2.js:3647:25 in getXScale
- node_modules/@antv/f2/build/f2.js:3085:16 in _adjustScale

**Comment by zengyue** [comment]
这个错误不是环境的问题，没有设置position

```
...
  chart.source(data, {
        percent: {
          formatter(val) {
            return val * 100 + "%";
          }
        }
      });

  // 少了下面这句
  chart.interval().position('a*percent');

  chart.render();
```

**Comment by chj-damon** [comment]
谢谢，我加上这句之后发现第一次启动应用的时候，图没有出来，但是在随便改了文件里的内容，它reload之后图可以看到。您知道这是为什么吗？

**Comment by zengyue** [comment]
https://github.com/iddan/react-native-canvas#canvasrenderingcontext2d
![image](https://user-images.githubusercontent.com/1478197/73712123-11311900-4744-11ea-9b9a-ffa68cb3c210.png)

额，看起来是因为react-native-canvas 所有的方法都是异步的，可以试试gcanvas https://github.com/alibaba/GCanvas

**Comment by zengyue** [comment]
https://github.com/zengyue/f2-rn-gcanvas-demo

可以参考下这个
