### ISSUE TITLE
柱状图平移，按住选中不准确，每次都是默认选中第一个。官网上的例子也有这个bug

### ISSUE THREAD

**Issue by wumingkai007** [antvis/F2#770]
官网地址：https://antv-f2.gitee.io/zh/examples/column/basic

当我按住选中 5-17号的时候，其实是给我选中的5-22。不准确，这个问题我在开发中也遇到过，然后来官网看，没想到官网上面也有这个问题。
![@N6XY%~3MD)~KG_Q(@)LC69](https://user-images.githubusercontent.com/50254462/73507720-d3b34f80-4414-11ea-88bc-431999fee021.png)

**Comment by benvirus** [comment]
master 分之的最新版本看起来已经修复了，没有复现了

**Comment by zengyue** [comment]
嗯，修复了
