### ISSUE TITLE
柱状图数据如何确定唯一性？

### ISSUE THREAD

**Issue by ACulturedThief** [antvis/F2#773]
[{amount: 2, status: '充值', name: '张三'},{amount: 2, status: '充值', name: '张三'}]，这其实是两条数据，只是重名了，然后f2会这样处理数据：[{amount: 4, status: '充值', name: '张三'}]；在官网文档没找的处理办法，来这里求救

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/examples/column/dodge

是不是要这种效果
