### ISSUE TITLE
tickCount除不尽时，坐标轴刻度值出现精度损失， 0.4000000000013。附测试代码和我的解决方案

### ISSUE THREAD

**Issue by lvguannan888** [antvis/F2#776]
【测试代码】

`import F2 from '@antv/f2';

const data = [{"id":0,"value":0.5},{"id":1,"value":0.6},{"id":2,"value":0.6},{"id":3,"value":0.5},{"id":4,"value":0.5},{"id":5,"value":0.5},{"id":6,"value":0.6},{"id":7,"value":0.6},{"id":8,"value":0.7},{"id":9,"value":0.7},{"id":10,"value":0.6},{"id":11,"value":0.6},{"id":12,"value":0.8},{"id":13,"value":1},{"id":14,"value":1.1},{"id":15,"value":1.1},{"id":16,"value":1.2},{"id":17,"value":1.1},{"id":18,"value":1.1},{"id":19,"value":0.9},{"id":20,"value":0.9},{"id":21,"value":0.8},{"id":22,"value":0.8},{"id":23,"value":1},{"id":24,"value":1},{"id":25,"value":1.1},{"id":26,"value":1.1},{"id":27,"value":1.1},{"id":28,"value":1.1},{"id":29,"value":1.2},{"id":30,"value":1.2},{"id":31,"value":1.5},{"id":32,"value":1.5},{"id":33,"value":1.6},{"id":34,"value":1.6},{"id":35,"value":1.5},{"id":36,"value":1.5},{"id":37,"value":1.3},{"id":38,"value":1.3},{"id":39,"value":1.3},{"id":40,"value":1.3},{"id":41,"value":1.5},{"id":42,"value":1.5},{"id":43,"value":1.6},{"id":44,"value":1.6},{"id":45,"value":1.5},{"id":46,"value":1.5},{"id":47,"value":1.6},{"id":48,"value":1.6},{"id":49,"value":1.8},{"id":50,"value":1.8},{"id":51,"value":1.8},{"id":52,"value":1.8},{"id":53,"value":1.8},{"id":54,"value":1.8},{"id":55,"value":1.6}];

const chart = new F2.Chart({
  id: 'container',
  pixelRatio: window.devicePixelRatio
});

chart.source(data, {
  value: {
    tickCount: 5
  },
  id: {
    tickCount: 2
  }
});
chart.line().position('id*value');
chart.render();
`

【错误效果】
![image](https://user-images.githubusercontent.com/45872165/75084557-c4c74500-555b-11ea-93ba-6eccc4b7863b.png)

【错误定位】（我直接在压缩文件中定位的）：
![image](https://user-images.githubusercontent.com/45872165/75084590-08ba4a00-555c-11ea-82aa-ee04a4dc4aee.png)

【bug修复】
![image](https://user-images.githubusercontent.com/45872165/75084991-6ef49c00-555f-11ea-8d49-71ff0a8d4573.png)

**Comment by zengyue** [comment]
通过formatter自己格式化处理下

https://f2.antv.vision/zh/docs/api/chart/scale
