### ISSUE TITLE
如何正确 resize

### ISSUE THREAD

**Issue by autukill** [antvis/F2#781]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了自适应问题,比如横竖屏切换后手动 resize

### What does the proposed API look like?
echartsInstance. resize
(opts?: {
    width?: number|string,
    height?: number|string,
    silent?: boolean
}) => ECharts

https://www.echartsjs.com/zh/api.html#echartsInstance.resize

改变图表尺寸，在容器大小发生改变时能够手动调用。

**Comment by gongyuying-000** [comment]
`     
// 监听页面缩放，使用antv F2 的 changeSize事件修改大小
   window.addEventListener('resize', () => {
          let width = document.body.clientWidth 
          let height = 200
          chart.changeSize(width, height )
        })
`
