### ISSUE TITLE
Need to draw dashed line on specific yAxis value

### ISSUE THREAD

**Issue by amnan181** [antvis/F2#795]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.yuque.com/antv/f2/api-chart#ou7mld](https://www.yuque.com/antv/f2/api-chart#ou7mld)

### Steps to reproduce
Now i am drawing 2 lines in which one line showing in top and other one is in bottom. But i want to draw line on specific yAxis like between 2 points which is showing on yAxis Ex. 1.00GB -2.00GB i want to draw line between these value mean in 1.5GB

### What is expected?
I want to draw line for threshold on specific yAxis value? How can i achieve this?

### What is actually happening?
Now i am drawing 2 lines in which one line showing in top and other one is in bottom. But i want to draw line on specific yAxis like between 2 points which is showing on yAxis Ex. 1.00GB -2.00GB i want to draw line between these value mean in 1.5GB

| Environment | Info |
|---|---|
| f2 | 3.6.0 |
| System | Mobile |
| Browser | Mobile |

**Comment by amnan181** [comment]
![image](https://user-images.githubusercontent.com/44324439/77226823-066bff80-6b9d-11ea-9f3c-e70ec6a2e388.png)
This is screenshot

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/examples/component/guide#line

Do you expect this ?

**Comment by amnan181** [comment]
Thank you so much sir
