### ISSUE TITLE
测试发现3.5.0版本使用scrollBar+pan拖拽Tooltip时不会跟着滚动，3.5.0之后的版本都会跟着Tooltip和scrollbar会一起移动

### ISSUE THREAD

**Issue by Gallery2000** [antvis/F2#803]
测试发现3.5.0版本使用scrollBar+pan拖拽Tooltip时不会跟着滚动，3.5.0之后的版本都会跟着Tooltip和scrollbar会一起移动

**Comment by baiyidjp** [comment]
你好，你这个是怎么滑动的，我的设置完就没有滑动，或者滑动了就是一个空白页
