### ISSUE TITLE
How to intergrate antv/f2 to React Native

### ISSUE THREAD

**Issue by Rananjaya** [antvis/F2#805]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

Hi, 

Im react native developer, Im going to use antv/f2 chart for my mobile app. is there any guideline to integrate this lib to react-native.

**Comment by zengyue** [comment]
https://github.com/zengyue/f2-rn-gcanvas-demo

This is a simple example with gcanvas

gcanvas: https://github.com/alibaba/GCanvas

**Comment by m4devgeek** [comment]
> https://github.com/zengyue/f2-rn-gcanvas-demo
> 
> This is a simple example with gcanvas
> 
> gcanvas: https://github.com/alibaba/GCanvas

Why GCanvas?

**Comment by m4devgeek** [comment]
> https://github.com/zengyue/f2-rn-gcanvas-demo
> 
> This is a simple example with gcanvas
> 
> gcanvas: https://github.com/alibaba/GCanvas

https://github.com/chenshuai2144/f2-demo/blob/master/App.js#L22 , why this demo is not working?

**Comment by zengyue** [comment]
react-native-canvas need `await` before method, F2 use Standard CanvasRenderingContext2D， not support async method

**Comment by harshitsinghai77** [comment]
@m4devgeek You can try something like

const canvasContext = canvas.getContext('2d');
const chart = new F2.Chart({
      context: canvasContext,
      width: Layout.containerWidth,
      height: 200,
      padding: [20, 0, 20, 40],
    });
