### ISSUE TITLE
饼图数据渲染不能形成完整圆

### ISSUE THREAD

**Issue by chenpeitao** [antvis/F2#807]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---
![image](https://user-images.githubusercontent.com/44704881/77866909-7fd3b400-7267-11ea-9970-50e76a5ddeed.png)

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by zengyue** [comment]
把复现demo贴一下

**Comment by jian263994241** [comment]
> 提供个可复现的demo

这个问题我也遇到了.
不过解决了,   在react下, 移除组件再挂载的就会出现 渲染不完整的情况

去掉 `chart.destroy()` 就好了

```jsx
React.useEffect(()=>{

  const chart =  new F2.Chart({ el, pixelRatio: window.devicePixelRatio});
  ...
  return ()=>{
    chart.destroy()
  }
}, [])
```
