### ISSUE TITLE
pc端折线图柱状图无法点击(移动端可以)

### ISSUE THREAD

**Issue by hzy101552** [antvis/F2#812]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://dev-databoard.hzhengji.cn/#/board/3cdf51d7068d4821b2fbdeea6e1ae283012da443733e4152991b20b00a04b9cc](http://dev-databoard.hzhengji.cn/#/board/3cdf51d7068d4821b2fbdeea6e1ae283012da443733e4152991b20b00a04b9cc)

### Steps to reproduce
F12 ，选择成移动端点击有效果，为pc端时点击无效

### What is expected?
为pc端时点击有效果

### What is actually happening?
点击事件要能正常点击

| Environment | Info |
|---|---|
| f2 | 3.6.3 |
| System | window 10 |
| Browser | Google  80.0.3987.162（正式版本） （64 位） |

---
链接版本为3.2.4，本地的为3.6.3，但是3.6.3也无效

**Comment by zengyue** [comment]
F2 是针对移动端的图表库，默认是不支持pc上的mouse事件的，如果是pc场景的话，建议用g2，如果一定要用的话，需要把mouse事件转换成touch时间，可以用 https://github.com/zengyue/touchemulator
