### ISSUE TITLE
使用浏览器引入F2，使用scrollBar报错

### ISSUE THREAD

**Issue by XiaoWinter** [antvis/F2#816]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://47.103.65.182/bug/demo.html](http://47.103.65.182/bug/demo.html)

### Steps to reproduce
1.打开注释掉的的chart.scrollBar代码
2.运行

### What is expected?
出现滚动条

### What is actually happening?
Uncaught TypeError: chart.scrollBar is not a function at demo.html:53

| Environment | Info |
|---|---|
| f2 | 3.4.4 |
| System | windows10 专业版 |
| Browser | chrome 76.0.3809.132 |

**Comment by XiaoWinter** [comment]
script标签引不行，最后解决方法是用webpack,把所有依赖打个包出来用，

**Comment by baiyidjp** [comment]
我是使用webpack引用的 我这也报这个错 无法解决
