### ISSUE TITLE
ScrollBar is not defined

### ISSUE THREAD

**Issue by MrTager** [antvis/F2#818]
我在浏览器中引入：<script src="js/f2.min.js"></script>
注册： const chart = new F2.Chart({
        id: 'c1',
        pixelRatio: window.devicePixelRatio, 
        plugins: ScrollBar,
      });

使用： chart.scrollBar({
        mode: 'x',
        xStyle: {
          backgroundColor: '#e8e8e8',
          fillerColor: '#808080',
          offsetY: -2
        }
      });

报错：Uncaught ReferenceError: ScrollBar is not defined

**Comment by zengyue** [comment]
<script src="js/f2-all.min.js"></script>
