### ISSUE TITLE
Guide[ClassName] is not a constructor

### ISSUE THREAD

**Issue by junjunsoul** [antvis/F2#819]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xxlkz?file=/index.js)

### Steps to reproduce
加载链接就看到了

### What is expected?
跟图表演示一致
https://antv-f2.gitee.io/zh/examples/gallery/forecast

### What is actually happening?
×
←→1 of 3 errors on the page
TypeError
Guide[ClassName] is not a constructor

| Environment | Info |
|---|---|
| f2 | 3.6.3 |
| System | mac |
| Browser | Chrome |

**Comment by zengyue** [comment]
默认包里是不带这个的，
用 `import F2 from '@antv/f2/lib/index-all';`
