### ISSUE TITLE
3.6.3版本  报错mix is not a function

### ISSUE THREAD

**Issue by tangshuoup** [antvis/F2#821]
![image](https://user-images.githubusercontent.com/25792077/79207883-df3ee000-7e73-11ea-912d-313eea26229a.png)

const data = [{
      const: 'const',
      type: '交通出行',
      money: 51.39
    }, {
      const: 'const',
      type: '饮食',
      money: 356.68
    }, {
      const: 'const',
      type: '生活日用',
      money: 20.00
    }, {
      const: 'const',
      type: '住房缴费',
      money: 116.53
    }]
    const chart = new F2.Chart({
      id: 'rateErrorCanvas',
      width:canvasWidth,
      height: canvasWidth * 2/3,
      pixelRatio: window.devicePixelRatio,
      plugins: PieLabel
    });
    chart.source(data);
    chart.coord('polar', {
      transposed: true,
      innerRadius: 0.8
    });
    chart.axis(false);
    chart.legend(false);
    chart.tooltip(false);
    chart.guide()
      .html({
        position: [ '50%', '50%' ],
        html: '<div style="text-align: center;width:150px;height:50px">\n      <p style="font-size: 12px;color: #999;margin: 0" id="title"></p>\n      <p style="font-size: 18px;color: #343434;margin: 0;font-weight: bold;" id="money"></p>\n      </div>'
      });
    chart.interval()
      .position('const*money')
      .adjust('stack')
      .color('type', [ '#1890FF', '#13C2C2', '#2FC25B', '#FACC14' ]);
    chart.pieLabel({
      // sidePadding: 30,
      activeShape: true,
      label1: function label1(data) {
        return {
          text: '￥' + data.money,
          fill: '#343434',
          fontWeight: 'bold'
        };
      },
      label2: function label2(data) {
        return {
          text: data.type,
          fill: '#999'
        };
      },
      onClick: function onClick(ev) {
        const data = ev.data;
        if (data) {
          document.getElementById('title').innerText = data.type;
          document.getElementById('money').innerText = data.money;
        }
      }
    });
    chart.render();
基本是按照例子的代码

**Comment by jefferyssy** [comment]
我也遇到同样的问题 是在 按需加载以后出现
