### ISSUE TITLE
点击不生效，必须长按才出现提示框？

### ISSUE THREAD

**Issue by nevermore999** [antvis/F2#822]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by hongyu2016** [comment]
chart.tooltip({
triggerOn: 'touchstart'
})

这个官网文档有

**Comment by nevermore999** [comment]
多谢
