### ISSUE TITLE
interval 定义时 颜色的回调好像有bug

### ISSUE THREAD

**Issue by baiyidjp** [antvis/F2#823]
![image](https://user-images.githubusercontent.com/12672573/79541906-400d2900-80bd-11ea-88e3-c31b8a46c563.png)
![image](https://user-images.githubusercontent.com/12672573/79541921-4a2f2780-80bd-11ea-80e2-376fd0baafca.png)
![image](https://user-images.githubusercontent.com/12672573/79541949-57e4ad00-80bd-11ea-9a63-0014888f8427.png)
x 对应的三个值是： 您的 最小 最大，回调中只拿到了最后一个值打印了三次的最大

**Comment by iyanming** [comment]
同问，这个color 应该有bug。

**Comment by iyanming** [comment]
{
          name: '分类 17',
          value: 40,
          percent: '0.9802',
          a: 1
        }, {
          name: '分类 18',
          value: 30,
          percent: '0.9802',
          a: 1
        }
        
        chart.polygon()
        .position('x*y')
        .color('percent', (cValue) => {
          console.log('percent', cValue);
          if (Number(cValue) > 0) {
            return 'red';
          }
          return 'green';
        })
        .shape('labeledPolygon')
        .style({
          lineWidth: 1,
          stroke: '#fff'
        });

**Comment by iyanming** [comment]
这里打印 了三次 percent percent，percent被认为是字符串了，没有识别出是数据源里变量 @zengyue @baiyidjp @lifesinger @army8735

**Comment by iyanming** [comment]
矩形树图
