### ISSUE TITLE
分类柱状图平移后面的全是空白

### ISSUE THREAD

**Issue by myGitHubHuLin** [antvis/F2#824]
chart.source(data, {
        ProjectName: {  
            type:'cat',
            values:originDates
        }
    });
使用官方的这种写法，平移之后，后面的全是空白

**Comment by baiyidjp** [comment]
我也遇见了这种，而且加载出来的柱状图都挤到一起了

**Comment by myGitHubHuLin** [comment]
是antv/f2的问题，同一份代码4，5，6版本，会有不同的效果，我这边是满足不了了放弃使用了，你那边需要你自己试一下。

**Comment by baiyidjp** [comment]
刚开始用的G2，为了实现一个需求换成了F2,不想换了。跟产品商量取消这个功能。。。

**Comment by TheNovemberRain** [comment]
降版本到3.5.0，问题不再出现

**Comment by ukhack** [comment]
真·面向KPI开源，大家散了吧
