### ISSUE TITLE
模拟器显示正常，但到了真机上就有显示问题（以前正常，最近才出这个问题）

### ISSUE THREAD

**Issue by FernAbby** [antvis/F2#825]
### 钉钉小程序图表渲染出问题

- 模拟器效果：
![image](https://user-images.githubusercontent.com/13566690/79633170-6b177b80-8196-11ea-896f-ac618e7165b9.png)
![image](https://user-images.githubusercontent.com/13566690/79633172-6eab0280-8196-11ea-8ec2-a8598b541d9d.png)
- 真机效果：
![image](https://user-images.githubusercontent.com/13566690/79633175-79fe2e00-8196-11ea-87f5-b6b04eb10510.png)
![image](https://user-images.githubusercontent.com/13566690/79633182-7ec2e200-8196-11ea-917e-5b823bdf66f4.png)
渲染位置偏了，以前是好好地，最近升级钉钉后出现这个问题

**Comment by zengyue** [comment]
是最新版钉钉吗？

https://github.com/antvis/f2-context/blob/master/src/context/my.ts#L52
先把这个方法覆盖下试试

**Comment by FernAbby** [comment]
已解决，钉钉升级，V1引擎升级到V2
