### ISSUE TITLE
分组柱状图，添加了pan，但是无法正常使用

### ISSUE THREAD

**Issue by baiyidjp** [antvis/F2#827]
![image](https://user-images.githubusercontent.com/12672573/79720902-1568dd80-8314-11ea-93ae-4d18f2b5d215.png)
![image](https://user-images.githubusercontent.com/12672573/79720915-1bf75500-8314-11ea-83f8-17da1de2a78e.png)

**Comment by baiyidjp** [comment]
import F2 from '@antv/f2/lib/index-all'   
滑动之前是如图所示，滑动一下就变成白板了

**Comment by hongyu2016** [comment]
而且在钉钉自定义组件的插件开发中，也是无法滑动，已经看到滚动条了，宽度也跟官方demo那样显示了，就是无法滑动

**Comment by ashen9** [comment]
> 而且在钉钉自定义组件的插件开发中，也是无法滑动，已经看到滚动条了，宽度也跟官方demo那样显示了，就是无法滑动

结局了吗？

**Comment by ashen9** [comment]
> import F2 from '@antv/f2/lib/index-all'
> 滑动之前是如图所示，滑动一下就变成白板了

解决了吗？
