### ISSUE TITLE
平移柱状图快速滑动时 部分横坐标丢失（官网例子也是）

### ISSUE THREAD

**Issue by youshuo01** [antvis/F2#837]
![image](https://user-images.githubusercontent.com/25683792/80311914-f3d88c00-8814-11ea-8b96-74da58c5e864.png)

**Comment by kuailedechengxuyuan** [comment]
我的直接就是初始可视区域有数据，初始不可见区域都没柱子了

**Comment by hellosanbao** [comment]
我也是，官网的例子就是初始化区域有柱子其他区域没有柱子

**Comment by zengyue** [comment]
已修复
