### ISSUE TITLE
折线图如何设置可平移，官网的例子换上我的数据后，所有的数据显示在一个屏幕上无法平移

### ISSUE THREAD

**Issue by nevermore999** [antvis/F2#838]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by baiyidjp** [comment]
同感 不知道为啥一直不修复

**Comment by nevermore999** [comment]
> 同感 不知道为啥一直不修复

**Comment by baiyidjp** [comment]
你好 这个你找到原因了吗？ 能说下吗

**Comment by nevermore999** [comment]
没有解决，测试貌似只有x轴数据为数字类型时可以使用平移

**Comment by baiyidjp** [comment]
官网的也不都是数字啊 一个是年份的 一个日期的

**Comment by ukhack** [comment]
面向KPI开源，大家散了吧
