### ISSUE TITLE
grid 中 fill 属性 设置无效

### ISSUE THREAD

**Issue by FreeRide-Joe** [antvis/F2#842]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/area/basic](https://f2.antv.vision/zh/examples/area/basic)

### Steps to reproduce
在官网示例右侧，最后一行代码前加入以下代码

```
chart.axis('tem', {
  grid: {
    fill: '#000000'
  }
});
```

![image](https://user-images.githubusercontent.com/16112889/80693662-f2091400-8b05-11ea-8869-f48666a54e87.png)

### What is expected?
图表中颜色被正确设置

### What is actually happening?
图表中颜色和设置不一样

| Environment | Info |
|---|---|
| f2 | 3.6.3 |
| System | Windows |
| Browser | chrome  80.0.3987.132 |

**Comment by zengyue** [comment]
用stroke
