### ISSUE TITLE
折线图更新数据时，之前的线条没有清除掉，滑动线条乱闪

### ISSUE THREAD

**Issue by nevermore999** [antvis/F2#843]
`renderLine(params) {
       this.dataStatus = true;
      let theme = params.slice(0, 5);
      if(theme == 'black') this.src = false
      let data = params.slice(6);
      data = JSON.parse(data);
  
      const chart = new F2.Chart({
        id: "container",
        pixelRatio: window.devicePixelRatio
      });
      chart.source(data, {
        name: {
          type: "timeCat",
          tickCount: 3,
          mask: "HH:mm",
          range: [0,1],
        },}}`

在Android上，不刷新webview，数据改变时重复调用以上方法，造成当前线条和之前线条共存，滑动闪屏的问题，clear(), changedata()方法试过，问题未解决。

请问该问题如何解决？

f2版本：3.6.3

**Comment by zengyue** [comment]
给一个能复现的最小demo吧

**Comment by nevermore999** [comment]
http://antv-2018.alipay.com/zh-cn/f2/3.x/demo/line/customize-tootlip.html 在这个demo上做的扩展，单线改成了双线。
另外1.图表在三星fold上，系统字号调成最大时，点击事件失效。
 2. 饼图的字体大小 在广告机上适配不是太好

**Comment by lubin18** [comment]
朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图  两个分类数据来回闪动，手指离开屏幕又恢复正常

**Comment by nevermore999** [comment]
> 朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图 两个分类数据来回闪动，手指离开屏幕又恢复正常

![image](https://user-images.githubusercontent.com/21188047/85195983-9723ba00-b309-11ea-8918-4ee6dd530bf9.png)
使用clear()

**Comment by nevermore999** [comment]
> 朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图 两个分类数据来回闪动，手指离开屏幕又恢复正常

全局new一个chart，更新数据前先clear

**Comment by lubin18** [comment]
感谢你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nevermore999 <notifications@github.com&gt;
发送时间: 2020年6月20日 15:23
收件人: antvis/F2 <F2@noreply.github.com&gt;
抄送: lubin18 <1341733821@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[antvis/F2] 折线图更新数据时，之前的线条没有清除掉，滑动线条乱闪 (#843)





  
朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图 两个分类数据来回闪动，手指离开屏幕又恢复正常
  
全局new一个chart，更新数据前先clear

**Comment by lubin18** [comment]
报这个错🤦🏻‍♂️


发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nevermore999 <notifications@github.com&gt;
发送时间: 2020年6月20日 15:23
收件人: antvis/F2 <F2@noreply.github.com&gt;
抄送: lubin18 <1341733821@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[antvis/F2] 折线图更新数据时，之前的线条没有清除掉，滑动线条乱闪 (#843)





  
朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图 两个分类数据来回闪动，手指离开屏幕又恢复正常
  
全局new一个chart，更新数据前先clear

**Comment by nevermore999** [comment]
> 报这个错🤦🏻‍♂️ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: nevermore999 <notifications@github.com&gt; 发送时间: 2020年6月20日 15:23 收件人: antvis/F2 <F2@noreply.github.com&gt; 抄送: lubin18 <1341733821@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[antvis/F2] 折线图更新数据时，之前的线条没有清除掉，滑动线条乱闪 (#843) 朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图 两个分类数据来回闪动，手指离开屏幕又恢复正常 全局new一个chart，更新数据前先clear — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> 报这个错🤦🏻‍♂️ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: nevermore999 <notifications@github.com&gt; 发送时间: 2020年6月20日 15:23 收件人: antvis/F2 <F2@noreply.github.com&gt; 抄送: lubin18 <1341733821@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[antvis/F2] 折线图更新数据时，之前的线条没有清除掉，滑动线条乱闪 (#843) 朋友 你这个问题解决了吗 我也是出现 当切换分类是新的图表渲染出的真线图滑动瞬间会出现上一个分类数据的直线图 两个分类数据来回闪动，手指离开屏幕又恢复正常 全局new一个chart，更新数据前先clear — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

什么？
