### ISSUE TITLE
分组柱状图加折线图 tooltip辅助线不准确

### ISSUE THREAD

**Issue by cczhangxin** [antvis/F2#854]
import F2 from '@antv/f2';
import _ from 'lodash';

const data = [{
  name: 'London',
  月份: 'Jan.',
  月均降雨量: 18.9,
  v:10,
}, {
  name: 'London',
  月份: 'Feb.',
  月均降雨量: 28.8,
  v:20,
}, {
  name: 'London',
  月份: 'Mar.',
  月均降雨量: 39.3,
  v:8
},{
  name: 'Berlin',
  月份: 'Jan.',
  月均降雨量: 12.4,
    v:10,
}, {
  name: 'Berlin',
  月份: 'Feb.',
  月均降雨量: 23.2,
    v:20,
}, {
  name: 'Berlin',
  月份: 'Mar.',
  月均降雨量: 34.5,
    v:8,
}];
const chart = new F2.Chart({
  id: 'container',
  pixelRatio: window.devicePixelRatio
});
chart.source(data);
chart.tooltip({
   showCrosshairs: true,
});

chart.interval()
  .position('月份*月均降雨量')
  .color('name')
  .adjust({
    type: 'dodge',
    marginRatio: 0.05 // 设置分组间柱子的间距
  });
chart.line().position('月份*v').color("#000");
chart.render();

**Comment by cczhangxin** [comment]
希望显示的是 柱状图的tooltip背景 而不是一条线

**Comment by zengyue** [comment]
这个是默认自带的，如果要自定义的话，那么通过plugin自己实现一个就可以了

https://f2.antv.vision/zh/docs/api/plugin
