### ISSUE TITLE
使用f2时，用ajax动态获取数据，图表不会立即render出来，只有点击了才渲染出来

### ISSUE THREAD

**Issue by zwqq123456** [antvis/f2#86]
使用f2时，用ajax动态获取数据，图表不会立即render出来，只有点击了才渲染出来

**Comment by simaQ** [comment]
感谢反馈！！！ 我也发现这个问题了，正在积极修复！ 稍等给你反馈~~~

**Comment by simaQ** [comment]
@zwqq123456 试一下 3.1.3-beta.1 版本看下问题解决了没有
