### ISSUE TITLE
Y轴设置为等比数列

### ISSUE THREAD

**Issue by chenxiaobaic** [antvis/F2#868]
图形Y轴能否设置为等比数列，且各刻度间距一致。

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/docs/api/chart/scale#%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7

自己算下显示的ticks就可以了

**Comment by chenxiaobaic** [comment]
![WX20200522-184403](https://user-images.githubusercontent.com/40561372/82660051-3ba7d300-9c5c-11ea-8054-88caadb8e757.png)想要的效果
实际效果
<img width="951" alt="WX20200522-184453@2x" src="https://user-images.githubusercontent.com/40561372/82660130-6003af80-9c5c-11ea-8872-c18a071fd4be.png">
刻度的间距还是根据相邻刻度的差值，没有均匀分布

**Comment by chenxiaobaic** [comment]
最终想实现的效果就是echarts的对数轴类型
