### ISSUE TITLE
今日头条小程序

### ISSUE THREAD

**Issue by gavin99587** [antvis/F2#871]
请问F2是否支持今日头条小程序?

**Comment by zengyue** [comment]
主要是看下今日头条的canvas有哪些差异，只要对齐下这些差异就可以了，上层的绘制都是支持的

**Comment by gavin99587** [comment]
> 主要是看下今日头条的canvas有哪些差异，只要对齐下这些差异就可以了，上层的绘制都是支持的

我测试了下,用F2在头条了画图形,设置颜色不起作用,都是黑色,比如画一个矩形,画个圆,都是黑色,用头条原生代码是正常的
