### ISSUE TITLE
regionFilter 颜色问题

### ISSUE THREAD

**Issue by bedisdover** [antvis/F2#880]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-snowflake-cq9gq?file=/index.js)

### Steps to reproduce
请观察区域的颜色

### What is expected?
区域图的颜色应为红色带0.1透明度

### What is actually happening?
区域图颜色有差异

| Environment | Info |
|---|---|
| f2 | 3.6.3 |
| System | windows |
| Browser | chrome |

**Comment by zengyue** [comment]
这个是区域图本身有颜色和透明度，看到的是叠加后的效果
`chart.area().position("time*tem").style({fillOpacity: 0});` 区域图完全透明后，就是你要的效果了
