### ISSUE TITLE
ios下未完全连接的折线图会丢点

### ISSUE THREAD

**Issue by DearVikki** [antvis/F2#883]
[codesandbox地址](https://codesandbox.io/s/tlr0d)
[预览地址](https://tlr0d.csb.app/)
![image](https://user-images.githubusercontent.com/18145936/82553712-287eff80-9b97-11ea-84d1-5a78e06ec0b7.png)

打开上述预览，pc 和 安卓上正常显示，但在 ios 下中间不连续的点会丢掉。
// 经测试用 point 来画是肯定不存在问题的。

请教下是什么原因，怎样可以避免或者解决，谢谢~

**Comment by zengyue** [comment]
线图是通过moveTo(x, y) -> lineTo(x1, y1) 这2个api来绘制，当中间只有一个点的时候，(x,y) 就会等于(x1, y1)， 所以只有一个点，所以就会画不来

**Comment by DearVikki** [comment]
> 线图是通过moveTo(x, y) -> lineTo(x1, y1) 这2个api来绘制，当中间只有一个点的时候，(x,y) 就会等于(x1, y1)， 所以只有一个点，因此就会画不来

那…我有个疑问是为啥 pc 和安卓上可以绘制出单独的点呢？
