### ISSUE TITLE
对数轴

### ISSUE THREAD

**Issue by chenxiaobaic** [antvis/F2#891]
有实现这种eCharts对数轴的方案吗，Y轴指数分布且刻度等距
![image](https://user-images.githubusercontent.com/40561372/82719807-7fdcb700-9ce0-11ea-92b4-7c941174a5fd.png)

**Comment by chenxiaobaic** [comment]
<img width="951" alt="WX20200522-184453@2x" src="https://user-images.githubusercontent.com/40561372/82748473-b8f65380-9dd4-11ea-860c-40d744bf93ad.png">
定义ticks，但是刻度不会均匀分布

**Comment by zengyue** [comment]
这个需要log类型的度量，目前F2还没有支持这个类型的度量
