### ISSUE TITLE
legend的个数很多的时候被遮挡

### ISSUE THREAD

**Issue by Cuihongsen** [antvis/f2#90]
* **F2 Version**:3.1.3-beta.1
* **Platform**:mac os 10.13.4 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20210798/38806392-ab972a70-41ab-11e8-845d-f1086d7e3834.png)

* **CodePen Link**:

**Comment by simaQ** [comment]
你好，是这样的，针对你的这种场景，我的个人意见是：

1. F2 的定位是专门针对移动端的，移动端的设备屏幕尺寸是有限的，在尺寸有限的情况下，需要取舍，一是你可以把直接不展示图例，`chart.legend(false)` ，二是你可以使用 html 来展示该图例，采用水平布局，并设置 overflow-x: scroll 来解决
2. 从可视化角度来说的话，一张折线图进行对比的折现数目不要超过 5 条以上，您的场景展示这么多的线图，很多线都被遮挡了，很多折线基本已经看不出来，或许可以考虑优化下方案
3. 如果您的使用场景是 PC，推荐直接使用 G2: https://antv.alipay.com/zh-cn/g2/3.x/index.html
