### ISSUE TITLE
折线图，平移之后，空值会连接在一起来，而且折线图会有重绘现象

### ISSUE THREAD

**Issue by yongheng798** [antvis/F2#908]
使用了平移事件之后，折线图在使用自定义的
`
chart.tooltip({
  alwaysShow: false, // 当移出触发区域，是否仍显示提示框内容，默认为 false，移出触发区域 tooltip 消失，设置为 true 可以保证一直显示提示框内容
  offsetX: 0, // x 方向的偏移
  offsetY: 0, // y 方向的偏移
  triggerOn: [ 'touchstart', 'touchmove' ], // tooltip 出现的触发行为，可自定义，用法同 legend 的 triggerOn
  triggerOff: 'touchend', // 消失的触发行为，可自定义
custom:true   自定义
`

chart.line().position('release*count');  //折线图
chart.interaction('pan');  //平移

一旦使用了triggerOn和triggerOff，那么平移之后，折线图会重绘

**Comment by zengyue** [comment]
用标准模板重新创建吧

**Comment by yongheng798** [comment]
是用标准模板创建的，我的demo地址，目前问题已经解决了，分享给官方，希望以后官方注意点。
主要是因为官方的默认排序引起的，同时需要设置时间为timeCat格式，我的demo地址是：https://github.com/yongheng798/vant-demo3/
