### ISSUE TITLE
折线图平移后，折线图数据重绘出错

### ISSUE THREAD

**Issue by yongheng798** [antvis/F2#910]
官网的小伙伴们，最近使用F2  平移后，折线图重绘渲染错误

渲染不正常

- [ ] 

The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by zengyue** [comment]
试试 @antv/f2@3.6.4-beta.8 这个版本，刚修掉
