### ISSUE TITLE
一个折线加柱状图的图形，加上平移功能之后点击会影响折线图功能

### ISSUE THREAD

**Issue by shmilyvidian** [antvis/F2#913]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-reproduction-template-un2dz)

### Steps to reproduce
一个折线加柱状图的图形，加上平移功能之后点击会影响折线图功能，折线图会有段加粗

### What is expected?
一个折线加柱状图的图形，加上平移功能之后点击会不影响折线图功能

### What is actually happening?
一个折线加柱状图的图形，加上平移功能之后点击会影响折线图功能，折线图会有段加粗

| Environment | Info |
|---|---|
| f2 | 3.6.3 |
| System | 安卓手机均有 |
| Browser | windows电脑均有 |

**Comment by yongheng798** [comment]
用平移，要自己将数据排序好，禁用官方的排序，sortable: false，比如柱形图的
chart.interval({sortable: false}).position('date*steps').style({
      radius: [ 2, 2, 0, 0 ]
    });
