### ISSUE TITLE
chart.changeData(newData)图表数据源，chart.clear()后重新渲染图表，显示tooltip的时候图表会切换成旧数据

### ISSUE THREAD

**Issue by chenxiaobaic** [antvis/F2#914]
chart.changeData(newData)图表数据源，chart.clear()后重新渲染图表，显示tooltip的时候图表会切换成旧数据

**Comment by chenxiaobaic** [comment]
chart.changeData(newData)图表数据源，chart.clear()后重新渲染图表，显示tooltip的时候图表会切换成旧数据

**Comment by chenxiaobaic** [comment]
切换多个数据源的时候即使clear()后再使用changeData(new data)加载新的数据源，图表内滑动的时候会来回切换数据

**Comment by zengyue** [comment]
贴下复现demo

**Comment by yongheng798** [comment]
这里有个demo，目前我也遇到这个问题，不过我线上的问题是通过初始化数据，画布ID再次强制更改才能解决的。
demo地址：https://github.com/yongheng798/vant-demo3/blob/dev_demo/src/components/antv/f2/BarColumnPanChart.vue

**Comment by yongheng798** [comment]
tooltip要使用自定义才行的，不然是没法解决的

**Comment by youngjuning** [comment]
我的解决办法是切换的时候先置空，然后判断长度

```ts
data.length > 0 && chart.render();
```
