### ISSUE TITLE
我可以为 F2 提交 TypeScript 的类型定义 PR 吗

### ISSUE THREAD

**Issue by fjc0k** [antvis/F2#923]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这几天才在 Taro 3 中尝试使用的 F2，小程序下表现良好，不得不说，这是个很优质的图表库，但就是缺少了类型定义，少了一点写代码的快感。

因此，我就在本地对一些用着的 API 添加了类型定义，如果可以，我想直接为本仓库提交一个添加 TypeScript 的类型定义的 PR，并将持续完善，之所以不去 https://github.com/DefinitelyTyped/DefinitelyTyped 提一个单独的 @types/* 包，一是因为那个仓库实在太大，二是在这里添加也能开箱即用。

### What does the proposed API look like?
- 在根目录新建 types 文件夹存放类型定义文件
- 通过 types/index.d.ts 导出所有类型定义
- 在 package.json 添加 types 字段指向 types/index.d.ts
- 在文档做适当说明

**Comment by simaQ** [comment]
非常欢迎！

**Comment by fjc0k** [comment]
@simaQ 🤝
