### ISSUE TITLE
带文本的分组柱状图坐标轴翻转transposed: true无法显示

### ISSUE THREAD

**Issue by 1055241046** [antvis/F2#930]
![image](https://user-images.githubusercontent.com/32891535/85943837-30d01480-b965-11ea-964a-d7f88d975556.png)

**Comment by 1055241046** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="chart-name" content="带文本的分组柱状图">
    <title>F2 图表组件库 - AntV</title>
    <link rel="stylesheet" href="https://gw.alipayobjects.com/os/rmsportal/YmDAMEQVbLJpVbKiRQVX.css" />
    
</head>
<body>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>

<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.4.2/f2.min.js"></script>

<script src="https://gw.alipayobjects.com/os/antv/assets/lib/jquery-3.2.1.min.js"></script>

<script src="https://gw.alipayobjects.com/os/rmsportal/NjNldKHIVQRozfbAOJUW.js"></script>

  <div class="chart-wrapper">
    <canvas id="mountNode"></canvas>
  </div>
  <script>
  var Shape = F2.Shape;
  var Util = F2.Util;
  Shape.registerShape('interval', 'text', {
    draw: function draw(cfg, container) {
      var points = this.parsePoints(cfg.points);
      // points 顶点的顺序
      // 1 ---- 2
      // |      |
      // 0 ---- 3
      var style = Util.mix({
        fill: cfg.color,
        z: true // 需要闭合
      }, cfg.style);
      var intervalShape = container.addShape('rect', {
        attrs: Util.mix({
          x: points[1].x,
          y: points[1].y,
         // width: points[2].x - points[1].x,
         // height: points[0].y - points[1].y
          width: points[1].y - points[2].y,
          height: points[1].x - points[0].x
          
        }, style)
      });

      var origin = cfg.origin._origin; // 获取对应的原始数据记录
      var textShape = container.addShape('text', {
        zIndex: 1,
        attrs: {
          x: (points[1].x + points[2].x) / 2,
          y: points[1].y - 5, // 往上偏移 5 像素
          text: origin['月均降雨量'],
          fill: '#808080',
          textAlign: 'center',
          textBaseline: 'bottom',
          fontSize: 10 // 字体大小
        }
      });
      container.sort();
      return [intervalShape, textShape];
    }
  });

  var data = [{
    name: 'London',
    月份: 'Jan.',
    月均降雨量: 18.9
  }, {
    name: 'London',
    月份: 'Feb.',
    月均降雨量: 28.8
  }, {
    name: 'London',
    月份: 'Mar.',
    月均降雨量: 39.3
  }, {
    name: 'London',
    月份: 'Apr.',
    月均降雨量: 81.4
  }, {
    name: 'London',
    月份: 'May.',
    月均降雨量: 47
  }, {
    name: 'London',
    月份: 'Jun.',
    月均降雨量: 20.3
  }, {
    name: 'London',
    月份: 'Jul.',
    月均降雨量: 24
  }, {
    name: 'London',
    月份: 'Aug.',
    月均降雨量: 35.6
  }, {
    name: 'Berlin',
    月份: 'Jan.',
    月均降雨量: 12.4
  }, {
    name: 'Berlin',
    月份: 'Feb.',
    月均降雨量: 23.2
  }, {
    name: 'Berlin',
    月份: 'Mar.',
    月均降雨量: 34.5
  }, {
    name: 'Berlin',
    月份: 'Apr.',
    月均降雨量: 99.7
  }, {
    name: 'Berlin',
    月份: 'May.',
    月均降雨量: 52.6
  }, {
    name: 'Berlin',
    月份: 'Jun.',
    月均降雨量: 35.5
  }, {
    name: 'Berlin',
    月份: 'Jul.',
    月均降雨量: 37.4
  }, {
    name: 'Berlin',
    月份: 'Aug.',
    月均降雨量: 42.4
  }];
  var chart = new F2.Chart({
    id: 'mountNode',
    pixelRatio: window.devicePixelRatio
  });
  chart.source(data);
  chart.legend(false);

  chart.interval().position('月份*月均降雨量').color('name').shape('text').adjust({
    type: 'dodge',
    marginRatio: 0.2
  }).style({
    radius: [4, 4, 0, 0]
  });
    
   chart.coord('rect', {
  transposed: true  // 坐标系进行转置
});

  chart.render();
</script>


</body>
</html>

**Comment by zengyue** [comment]
```
chart.interval().position('月份*月均降雨量').color('name').shape('text').adjust({
        type: 'dodge',
        marginRatio: 0.2
      }).style({
        radius: [0, 4, 4, 0]
      });
```

不是没画全，因为设置上下radius
