### ISSUE TITLE
为什么在我的电脑上图例为多出一项

### ISSUE THREAD

**Issue by cshenhb** [antvis/F2#931]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.antfin.com/zh-cn/f2/3.x/demo/line/stacked-line-point.html](https://antv.antfin.com/zh-cn/f2/3.x/demo/line/stacked-line-point.html)

### Steps to reproduce
和这个类似
![dsfs](https://user-images.githubusercontent.com/23427149/85986308-98966600-ba1e-11ea-8156-7b7f3c7c79c2.png)

### What is expected?
和官网demo一样

### What is actually happening?
在我的电脑上会重复一个图例

| Environment | Info |
|---|---|
| f2 | 3.5.0 |
| System | win10 |
| Browser | chrome |

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/examples/area/stacked

看看新版有没问题
