### ISSUE TITLE
支持把图头字段去掉吗？ 如图红框内

### ISSUE THREAD

**Issue by yanlee26** [antvis/F2#932]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。
![image](https://user-images.githubusercontent.com/20903311/86111955-f350c000-baf9-11ea-812c-1b5530c75452.png)

**Comment by cycgit** [comment]
chart.legend(false)
