### ISSUE TITLE
词云图的 tooltip 展示有问题

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/F2#934]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/other/other](https://f2.antv.vision/zh/examples/other/other)

### Steps to reproduce
对官网例子【词云图】设置了
```js
chart.tooltip({
                showTitle: true,
                triggerOn: 'touchstart'
            })
```

### What is expected?
展示 tooltip ，类似于 echarts 云图

### What is actually happening?
并不能正常展示词云图的tooltip

| Environment | Info |
|---|---|
| f2 | 3.6.3 |
| System | mac os |
| Browser | chrome 最新版本 |

**Comment by zengyue** [comment]
词云图暂时没有tooltip，需要自己实现
