### ISSUE TITLE
能提供一套f2自适应的代码么

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/F2#935]
在教程中找了，好像 F2 不可以自适应。请问一下有解决方案吗？或者折中方案，可以在模板提供一套自适应代码参考呀

**Comment by TheNovemberRain** [comment]
resize事件监听的实现挺常见的吧，重新渲染图表就可以了

**Comment by Rabbitzzc** [comment]
> resize事件监听的实现挺常见的吧，重新渲染图表就可以了

那确实是可以，主要是考虑在横屏下突然重新渲染不太友好，还是希望能够自适应一下嘛

**Comment by zengyue** [comment]
竖屏转横屏时的自适应？

**Comment by zengyue** [comment]
可以用 https://f2.antv.vision/zh/docs/api/chart/chart/#changesize 手动调整下大小
