### ISSUE TITLE
wx-f2的2.0版本怎么引入Interaction？

### ISSUE THREAD

**Issue by SimoralX** [antvis/F2#938]
1. 你们说的提交issue必须在那个指定页面打开，但是我真的打不开啊。

![2020-07-05_103747](https://user-images.githubusercontent.com/30761931/86524321-aed37480-beab-11ea-9f90-11c0e6e6150c.png)

2. wx-f2的如何注册 ScrollBar ，好吧这不是问题，可以用
```js
(F2, config) => {
          const chart = new F2.Chart({ ...config, plugins: ScrollBar });
          // ......
}
```
引入

3. wx-f2 的 Interaction 怎么引入总得说明一下吧，我照着文档API找到了一个方法再注册一下：

```js
self.dayChart = (F2, config) => {
          F2.Chart.registerInteraction('pan1', Pan);
          const chart = new F2.Chart({ ...config, plugins: ScrollBar });
          // ......
          chart.interaction('pan1');
}
```
虽然这样滑动可以滑动了，但是是x轴坐标还有文字标注滑动，柱状图并没有滑动啊

![z8xxq-vbf3o (1)](https://user-images.githubusercontent.com/30761931/86524609-222ab580-beaf-11ea-975e-a9523da3cf46.gif)

**Comment by JoeshuTT** [comment]
> 1. 你们说的提交issue必须在那个指定页面打开，但是我真的打不开啊。
> 
> ![2020-07-05_103747](https://user-images.githubusercontent.com/30761931/86524321-aed37480-beab-11ea-9f90-11c0e6e6150c.png)
> 
> 1. wx-f2的如何注册 ScrollBar ，好吧这不是问题，可以用
> 
> ```js
> (F2, config) => {
>           const chart = new F2.Chart({ ...config, plugins: ScrollBar });
>           // ......
> }
> ```
> 
> 引入
> 
> 1. wx-f2 的 Interaction 怎么引入总得说明一下吧，我照着文档API找到了一个方法再注册一下：
> 
> ```js
> self.dayChart = (F2, config) => {
>           F2.Chart.registerInteraction('pan1', Pan);
>           const chart = new F2.Chart({ ...config, plugins: ScrollBar });
>           // ......
>           chart.interaction('pan1');
> }
> ```
> 
> 虽然这样滑动可以滑动了，但是是x轴坐标还有文字标注滑动，柱状图并没有滑动啊
> 
> ![z8xxq-vbf3o (1)](https://user-images.githubusercontent.com/30761931/86524609-222ab580-beaf-11ea-975e-a9523da3cf46.gif)

老哥，你也是不容易，那么多条issues,都有你，看来F2的跟图表交互interaction有关的都有问题，搞死我了

**Comment by benvirus** [comment]
@SimoralX 测试数据提供一下

**Comment by panzhangguo** [comment]
哎，我钉钉小程序也无法实现平移滚动。按照这个重新注册的，直接Ctor is not a constructor的错误

**Comment by SimoralX** [comment]
> > 1. 你们说的提交issue必须在那个指定页面打开，但是我真的打不开啊。
> > 
> > ![2020-07-05_103747](https://user-images.githubusercontent.com/30761931/86524321-aed37480-beab-11ea-9f90-11c0e6e6150c.png)
> > 
> > 1. wx-f2的如何注册 ScrollBar ，好吧这不是问题，可以用
> > 
> > ```js
> > (F2, config) => {
> >           const chart = new F2.Chart({ ...config, plugins: ScrollBar });
> >           // ......
> > }
> > ```
> > 
> > 
> > 引入
> > 
> > 1. wx-f2 的 Interaction 怎么引入总得说明一下吧，我照着文档API找到了一个方法再注册一下：
> > 
> > ```js
> > self.dayChart = (F2, config) => {
> >           F2.Chart.registerInteraction('pan1', Pan);
> >           const chart = new F2.Chart({ ...config, plugins: ScrollBar });
> >           // ......
> >           chart.interaction('pan1');
> > }
> > ```
> > 
> > 
> > 虽然这样滑动可以滑动了，但是是x轴坐标还有文字标注滑动，柱状图并没有滑动啊
> > ![z8xxq-vbf3o (1)](https://user-images.githubusercontent.com/30761931/86524609-222ab580-beaf-11ea-975e-a9523da3cf46.gif)
> 
> 老哥，你也是不容易，那么多条issues,都有你，看来F2的跟图表交互interaction有关的都有问题，搞死我了

我放弃柱状图了，现在全部用折线图解决的。

**Comment by SimoralX** [comment]
> 哎，我钉钉小程序也无法实现平移滚动。按照这个重新注册的，直接Ctor is not a constructor的错误

我这边找到原因了：

### 依赖包
"@antv/wx-f2": "^2.1.0",
![image](https://user-images.githubusercontent.com/30761931/102953579-9b28d280-450c-11eb-9ab0-ec38f3bd00bd.png)

### 更改引入方法

交互引入方法，我之前写的重新注册的方法失效，请直接按照原文档写
![image](https://user-images.githubusercontent.com/30761931/102953647-c6132680-450c-11eb-8b54-c51c9a2366c1.png)

```js
/** 加载pan这个交互行为 */
require('@antv/f2/lib/interaction/pan');

// 直接定义动画，不需要再重新注册了
chartInstance.interaction('pan');
```
