### ISSUE TITLE
期望按住图表, 上下滑动时页面也会跟着上下滚动

### ISSUE THREAD

**Issue by XanderXueMingJi** [antvis/F2#945]
目前是按住图表时滑动时, 整个页面跟着滚动

**Comment by zengyue** [comment]
没看懂

**Comment by ZXHHHH123** [comment]
你好, 想借楼问一下:如果一个图表较高，希望在tooltip失效的前提下，可以拖动图表内容的时候实现页面的上下滑动。请问有提供对应的API吗？

**Comment by ZXHHHH123** [comment]
自己回复下 应该是钉钉小程序引擎从V1.0升级到V2.0之后出现的问题 我切换成V1.0后 报表展示可以正常带动页面上下滑动
