### ISSUE TITLE
f2 横坐标调整到顶部怎么处理呀，没找到对应的配置项

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/F2#947]
![image](https://user-images.githubusercontent.com/26913511/86910278-055ede00-c14c-11ea-8f1c-d18b31c1c70e.png)

f2 横坐标调整到顶部怎么处理呀，没找到对应的配置项。

**Comment by zengyue** [comment]
目前没有实现top， 只有 left, right, bottom 这3种

**Comment by Rabbitzzc** [comment]
> 目前没有实现top， 只有 left, right, bottom 这3种

了解，建议可以处理下，这块感觉还是又述求的
