### ISSUE TITLE
如何去除原本axis所占的空白位，占满整个canvas

### ISSUE THREAD

**Issue by TDiDa** [antvis/f2#95]
请问下如何去除原本axis所占的空白位，占满整个canvas，见下图

![image](https://user-images.githubusercontent.com/18672870/39300788-762ee8f6-497f-11e8-943b-043c1a770588.png)

**Comment by simaQ** [comment]
这是因为目前我们图表的 padding 内边距是自动计算的，如果没有坐标轴的话，你可以手动设置下 padding 属性，用法同 css 的 padding 属性相同，API 见: https://antv.alipay.com/zh-cn/f2/3.x/api/chart.html#_padding

```js
const chart = new F2.Chart({
  id: 'c1',
  width: 375,
  height: 260,
  padding: 30
});
```

**Comment by TDiDa** [comment]
@simaQ 是我封装错了，导致padding设置失效了，现在解决了

**Comment by simaQ** [comment]
👍  好的呢
