### ISSUE TITLE
官网上的这个柱状图的例子是不是有bug，只有设置的可见区域的柱子能出来，其他不可见的区域柱子都出不来

### ISSUE THREAD

**Issue by hellosanbao** [antvis/F2#954]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.
![image](https://user-images.githubusercontent.com/21216090/87111643-6bf31180-c29c-11ea-8b85-e86a6c5ac4fc.png)
---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by a766599438** [comment]
我跟你一样 把官网的例子拷下来 也出现了这样的问题  求赶紧解决

**Comment by zengyue** [comment]
是哪个demo?

**Comment by a766599438** [comment]
柱状图平移



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zengyue ye"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 下午3:21
收件人: "antvis/F2"<F2@noreply.github.com&gt;; 
抄送: "宠高"<243903166@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [antvis/F2] 官网上的这个柱状图的例子是不是有bug，只有设置的可见区域的柱子能出来，其他不可见的区域柱子都出不来 (#954)





 
是哪个demo?

**Comment by zengyue** [comment]
嗯，看到了

**Comment by a766599438** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zengyue ye"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 下午3:26
收件人: "antvis/F2"<F2@noreply.github.com&gt;; 
抄送: "宠高"<243903166@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [antvis/F2] 官网上的这个柱状图的例子是不是有bug，只有设置的可见区域的柱子能出来，其他不可见的区域柱子都出不来 (#954)





 
嗯，看到了

**Comment by OsbornWJ** [comment]
你好  问一下这个问题有解决吗

**Comment by ukhack** [comment]
KPI产物
