### ISSUE TITLE
F2 纵坐标最小刻度能够设置为整数么

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/F2#955]
在做折线图的时候，发现纵坐标如果数值过下，会导致出现小数，我想了解一下有相关的配置项么？能够以最小成本实现。而不是手动根据数值大小，如果小于1，则展示空字符串

**Comment by zengyue** [comment]
https://f2.antv.vision/zh/docs/api/chart/scale#%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7

通过formatter自己处理下就可以了

**Comment by Rabbitzzc** [comment]
> https://f2.antv.vision/zh/docs/api/chart/scale#%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7
> 
> 通过formatter自己处理下就可以了

`formatter`是可以处理，但是会和G2一样，如果1.1 和 1.2 同时 `formatter`为正数，意味着坐标轴上展示了两个相同的数据，这也是 `formatter`的不确定性
