### ISSUE TITLE
script标签引入的js，饼图提示找不到pieLabel方法，请问怎么解决？

### ISSUE THREAD

**Issue by m25910323** [antvis/F2#962]
script标签引入的js，饼图提示找不到pieLabel方法，请问怎么解决？

**Comment by missjing** [comment]
使用引入了全部 plugin 的版本，默认版本里没有 引入 pieLabel

https://gw.alipayobjects.com/os/antv/assets/f2/3.4.2/f2-all.min.js

**Comment by missjing** [comment]
> script标签引入的js，饼图提示找不到pieLabel方法，请问怎么解决？

使用引入了全部 plugin 的版本，默认版本里没有 引入 pieLabel

https://gw.alipayobjects.com/os/antv/assets/f2/3.4.2/f2-all.min.js

**Comment by m25910323** [comment]
问题已解决，谢谢

**Comment by zengyue** [comment]
https://gw.alipayobjects.com/os/lib/antv/f2/3.7.0/dist/f2-all.min.js

最新版的地址可以用这个
