### ISSUE TITLE
坐标轴(类目轴)数据过多导致重叠(即echarts中的axisLabel重叠问题)如何解决？

### ISSUE THREAD

**Issue by 654138926qq** [antvis/f2#97]
* **F2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
可以考虑通过设置 tickCount 来减少 label 的显示个数来解决：https://antv.alipay.com/zh-cn/f2/3.x/api/scale.html#_tickCount

```js
chart.source(data, {
  `x 轴字段名`: {
    tickCount: 4
  }
})
```
