### ISSUE TITLE
分组柱状图重叠

### ISSUE THREAD

**Issue by xmuSistone** [antvis/F2#975]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh/examples/column/dodge](https://f2.antv.vision/zh/examples/column/dodge)

### Steps to reproduce
第一次加载数据，重叠
![image](https://user-images.githubusercontent.com/12167762/88529089-15bef600-d032-11ea-8ecc-b3cd81000ed9.png)

| Environment | Info |
|---|---|
| f2 | 3.5.0 |
| System | - |
| Browser | - |

**Comment by xmuSistone** [comment]
![image](https://user-images.githubusercontent.com/12167762/88529128-22dbe500-d032-11ea-8c9d-3d4b4e4f43e6.png)

**Comment by cycgit** [comment]
第一次加载重叠？  

提供一下可复现的数据

**Comment by xmuSistone** [comment]
@cycgit 是的，第一次加载重叠；稍滑动一下，就恢复正常了。我是从antv官网摘出来的样例代码，用react，在componentDidMount里面创建chart及render。

**Comment by cycgit** [comment]
@xmuSistone 提供一下可复现的demo代码
