### ISSUE TITLE
alwaysShow 设置为true后，滑动图例区域也会导致定位数据左右移动

### ISSUE THREAD

**Issue by xiaoming0827** [antvis/F2#976]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tk3o7)

### Steps to reproduce
1、设置alwaysShow 为true，需要一直显示不消失
2、滑动图例部分，定位数据Crosshairs也会左右移动，希望和alwaysShow设置false一样，只有曲线图区域可以出发Crosshairs移动，图例区域不能
3、因为图例的点击事件很容易导致Crosshairs移动，这样的交互不是很友好，容易误操作

| Environment | Info |
|---|---|
| f2 | 3.7.1 |
| System | iPhonex |
| Browser | chrome |

**Comment by zengyue** [comment]
这个目前就是这么设计的
