### ISSUE TITLE
area 渐变问题，opacity怎么修改。

### ISSUE THREAD

**Issue by wzdwc** [antvis/f2#98]
增加了线条和区域的渐变属性
![image](https://user-images.githubusercontent.com/12741381/39511602-8cdb5db4-4e20-11e8-9f55-3959740e2b06.png)

![image](https://user-images.githubusercontent.com/12741381/39511590-83a9da04-4e20-11e8-86ea-f6469ef6f16e.png)
但是区域的渐变色值明显是有opacity的。
请问这个opacity在哪里可以修改，在F2的文档没有找到。或者怎么可以还原设置的色值。

**Comment by dxq613** [comment]
```js
area().style({
 opacity: 0.5
})
```

**Comment by wzdwc** [comment]
不行啊。没有效果。我试过了。

**Comment by simaQ** [comment]
```js
.style({
  fillOpacity: 1
});
```
用 fillOpacity 属性

**Comment by wzdwc** [comment]
nice，谢谢！
