### ISSUE TITLE
如何显示坐标轴的标题

### ISSUE THREAD

**Issue by kooriookami** [antvis/F2#988]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。
![image](https://user-images.githubusercontent.com/38392315/90107497-7876f800-dd7b-11ea-9905-742b34c6202e.png)
上图是G2显示效果，F2该如何实现显示坐标轴的标题呢

**Comment by cycgit** [comment]
F2 没有这个特性，可以业务代码实现
