### ISSUE TITLE
图表是否有类似pause 和 resume的方法？

### ISSUE THREAD

**Issue by liang3472** [antvis/F2#989]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ios app在切换到前台时，后台渲染会导致应用程序崩溃。是否有类似 pause 和 resume 的方法来控制渲染。

### What does the proposed API look like?
提供 pause 和 resume 方法

**Comment by zengyue** [comment]
这个没有，要自己判断实现
