### ISSUE TITLE
Tooltip don't displayed

### ISSUE THREAD

**Issue by legrandjeremy** [antvis/F2#996]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://quasar-f2-charts.surge.sh/#/dashboard](http://quasar-f2-charts.surge.sh/#/dashboard)

### Steps to reproduce
Hello !

I discovered F2 and I love the charts generated ! You did a great job.
I tried to use F2 on Quasar framework, it's worked well but tooltip doesn't displayed during mouse scroll on Chrome browser with Windows or Mac OS.
It worked well on Chrome mobile.

I find a public similar project to mine : http://quasar-f2-charts.surge.sh/#/dashboard
The second graph is a basic F2 Line Chart.

Link to the source : https://github.com/patrickmonteiro/quasar-f2-charts/blob/master/src/components/F2Line.vue

We can't "scroll" with our mouse to have tooltip displayed ;( It didn't work on Chrome browser with Windows or Mac OS.
It worked well on Chrome mobile.

The basic example on https://f2.antv.vision/en/examples/line/basic#with-point worked well.
I can't find the reason why it's blocked, I think it's related to Quasar but not sure.

MANY Thanks in advance,

Regards

| Environment | Info |
|---|---|
| f2 | 3.7.3 |
| System | Mac OS Catalina |
| Browser | Chrome 84 |

**Comment by zengyue** [comment]
F2 is designed for mobile, so chrome browser is not considered, you can try [G2 ](https://g2.antv.vision/en/), it can work on pc browser

**Comment by zengyue** [comment]
I am also considering making compatibility for desktop browsers，let F2 work on desktop

**Comment by legrandjeremy** [comment]
Thank you @zengyue for G2 proposal, I switched and it worked well ! Thanks
