### ISSUE TITLE
柱状图加入平移事件后左边两边柱子的宽度会消失一半

### ISSUE THREAD

**Issue by s769168112** [antvis/F2#997]
如图这样，最边上的柱状图的size只有其他的一半，怎么解决啊？
![QQ图片20200817163635](https://user-images.githubusercontent.com/38207533/90375691-e0914b00-e0a7-11ea-8dee-e312eb4930a3.png)

**Comment by s769168112** [comment]
![image](https://user-images.githubusercontent.com/38207533/90375853-19c9bb00-e0a8-11ea-92aa-55592323583f.png)

**Comment by s769168112** [comment]
![QQ图片20200817163635](https://user-images.githubusercontent.com/38207533/90375945-3f56c480-e0a8-11ea-8d64-39a21c42d05d.png)

**Comment by zengyue** [comment]
哪个版本出现的，复现demo 贴下

**Comment by s769168112** [comment]
> 哪个版本出现的，用codesandbox 弄个复现demo看看

3.7.3版本
![image](https://user-images.githubusercontent.com/38207533/90862162-97027200-e3bf-11ea-9767-a4922581817f.png)

**Comment by zengyue** [comment]
地址贴一些

**Comment by s769168112** [comment]
> 地址贴一下

https://codesandbox.io/s/unruffled-dawn-2donm?file=/index.js

**Comment by zengyue** [comment]
设置了max导致的

![image](https://user-images.githubusercontent.com/1478197/91317486-b0a31f80-e7ec-11ea-895e-b3f722e15d1e.png)

**Comment by s769168112** [comment]
> 设置了max导致的
> 
> ![image](https://user-images.githubusercontent.com/1478197/91317486-b0a31f80-e7ec-11ea-895e-b3f722e15d1e.png)

如果不设置max的话，柱状图就会把所有数据都挤在一屏里展示，就无法平移了。
