### ISSUE TITLE
饼图（环形图）中间的文字如何动态展示？

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/F2#998]
看了一下官网的例子，如果使用`pieLabel`，确实可以动态调整中间文字，但是很好奇为啥会出现这些横线呢？不太理解
![image](https://user-images.githubusercontent.com/26913511/90391019-fd854880-e0be-11ea-877b-e9b28dd587f8.png)

想了解一下还有其他办法点击饼图，动态展示中间文字或者样式么？
![up-9a3bf89c5d838dfb71b9b6c5afd2731e010](https://user-images.githubusercontent.com/26913511/90391721-2e19b200-e0c0-11ea-9a4b-ab90786d779f.gif)

**Comment by Rabbitzzc** [comment]
核心想实现的还是这个：https://antv-f2.gitee.io/zh/docs/api/chart/interaction/#%E9%A5%BC%E5%9B%BE%E9%80%89%E4%B8%AD

**Comment by zengyue** [comment]
https://codesandbox.io/s/fast-fog-thmhv?file=/index.js

```
const chart = new F2.Chart({
  id: "container",
  pixelRatio: window.devicePixelRatio
});
chart.source(data);
chart.coord("polar", {
  transposed: true,
  radius: 0.9,
  innerRadius: 0.5
});
chart.axis(false);
chart.legend(false);
chart.tooltip(false);
chart
  .interval()
  .position("const*money")
  .adjust("stack")
  .color("type", ["#1890FF", "#13C2C2", "#2FC25B", "#FACC14"]);
chart.interaction("pie-select");
chart.render();
```
