### ISSUE TITLE
浏览器引入 F2，会提示 pieLabel is not a function

### ISSUE THREAD

**Issue by tts-kk** [antvis/F2#999]
官网案例显示正常，但复制官网的案例到本地进行相应修改后提示 chart.pieLabel is not a function，而案例代码上的 ··到 CodeSandbox 打开·· 查看也是报的一样的错误。

查找解决方案时，在 API 文档看到 PieLabel 的说明：PieLabel 是一个用于绘制饼图文本的插件。
然后提供了 npm 环境安装的使用方法，没有 从浏览器引入 的解决方法。

请问如何解决从浏览器引入的 pieLabel is not a function ？

![image](https://user-images.githubusercontent.com/69715752/90481555-902bf300-e164-11ea-8c0f-0369e5606a1d.png)
![image](https://user-images.githubusercontent.com/69715752/90481599-9f12a580-e164-11ea-9e27-66dee6ac712e.png)

**Comment by zengyue** [comment]
https://codesandbox.io/s/fast-fog-thmhv?file=/index.js

或者 

```
import F2 from "@antv/f2/lib/index-all";
```

**Comment by tts-kk** [comment]
@zengyue 可能是我问题没有描述明白，您提供的解决方案仅限于使用了 npm install @antv/f2 --save 安装的环境下，而我现在遇到的问题是通过 cdn 引入的环境，由于引入 f2.js 的 html 需要被后端作为模板使用，所以这两种方法不适用

**Comment by zengyue** [comment]
cdn 也有对应的all 版本

https://gw.alipayobjects.com/os/lib/antv/f2/3.7.3/dist/f2-all.min.js

**Comment by tts-kk** [comment]
@zengyue 谢谢

**Comment by Leomemory** [comment]
import F2 from '@antv/f2';
const PieLabel = require('@antv/f2/lib/plugin/pie-label');
F2.Chart.plugins.register([PieLabel]);
